/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import TwoCommuting.Auto.Sec2ElementaryPreparation
public import TwoCommuting.Auto.Sec3MatrixInequalities
public import TwoCommuting.Auto.Sec4GaussianEnergies
public import TwoCommuting.Auto.Sec5OutputDependentIntervals
public import TwoCommuting.Auto.Sec6EuclideanCounting
public import TwoCommuting.Auto.Sec7FlowTransference
public import TwoCommuting.Auto.Sec8GaussianPrimitives
public import TwoCommuting.Auto.Sec9DiscreteTransformations
public import TwoCommuting.Auto.Sec10IntegrableExtension

/-!
# Pointwise convergence for two commuting transformations

This file was automatically generated by Claude.

Top-level import file of the library `TwoCommuting`, a formalization of
`blueprint/commuting_ergodic_blueprint.tex`.
-/
