/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib
public import TwoCommuting.Auto.Sec9DiscreteTransformations

/-!
# Extension to integrable functions

This file was automatically generated by Claude.

Formalization of §10 ("Extension to integrable functions", nodes T06–T08) of
`blueprint/commuting_ergodic_blueprint.tex`.

## Contents

* T06 (`one_sided_ergodic_weak_maximal`): the one-sided ergodic weak maximal estimate.
* T07 (`bilinear_ergodic_weak_maximal`): the bilinear weak maximal estimate.
* T08 (`commuting_ergodic_averages_converge_main`): **the main theorem**, almost everywhere and
  norm convergence of `N⁻¹ ∑_{n<N} f(Tⁿx) g(Sⁿx)` for `f ∈ L^p`, `g ∈ L^q`,
  `1/p + 1/q ≤ 1`.
-/

@[expose] public section

open scoped ENNReal NNReal
open MeasureTheory Filter Topology

namespace Auto

noncomputable section

section T06

/-- A forward average of length `N ≥ 1` is at most twice the centered maximal function. -/
lemma FinSupp.forward_avg_lt_two_maxZ {a : ℤ → ℝ} {S : Finset ℤ} (ha : FinSupp a S) (k : ℤ)
    {N : ℕ} (hN : 1 ≤ N) {t : ℝ} (ht : t < (N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, a (k + n)) :
    t / 2 < maxZ a k := by
  have hsub : (Finset.range N).image (fun n : ℕ => k + n) ⊆
      Finset.Icc (k - ((N - 1 : ℕ) : ℤ)) (k + ((N - 1 : ℕ) : ℤ)) := by
    intro j hj
    simp only [Finset.mem_image, Finset.mem_range] at hj
    obtain ⟨n, hn, rfl⟩ := hj
    simp only [Finset.mem_Icc]
    constructor <;> omega
  have hsum : ∑ n ∈ Finset.range N, a (k + n) ≤
      ∑ j ∈ Finset.Icc (k - ((N - 1 : ℕ) : ℤ)) (k + ((N - 1 : ℕ) : ℤ)), a j := by
    rw [← Finset.sum_image (f := a) (g := fun n : ℕ => k + n)
      (fun x _ y _ h => by simpa using h)]
    exact Finset.sum_le_sum_of_subset_of_nonneg hsub fun j _ _ => ha.nonneg j
  have h2 := ha.sum_Icc_le_maxZ k (N - 1)
  have hNpos : (0 : ℝ) < N := by exact_mod_cast hN
  have hcast : ((N - 1 : ℕ) : ℝ) = (N : ℝ) - 1 := by
    rw [Nat.cast_sub hN]; simp
  rw [hcast] at h2
  have hm := ha.maxZ_nonneg k
  rw [lt_inv_mul_iff₀ hNpos] at ht
  nlinarith

open Classical in
/-- One-sided weak type bound for finitely supported sequences, constant `10`. -/
lemma FinSupp.weak_forward {a : ℤ → ℝ} {S : Finset ℤ} (ha : FinSupp a S) {t : ℝ} (ht : 0 < t)
    (F : Finset ℤ) :
    t * (F.filter fun k => ∃ N : ℕ, 1 ≤ N ∧
      t < (N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, a (k + n)).card ≤ 10 * ∑ j ∈ S, a j := by
  classical
  have h := ha.weak_maxZ (t := t / 2) (by positivity) F
  have hc : (F.filter fun k => ∃ N : ℕ, 1 ≤ N ∧
      t < (N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, a (k + n)).card ≤
      (F.filter fun k => t / 2 < maxZ a k).card := by
    apply Finset.card_le_card
    intro k hk
    simp only [Finset.mem_filter] at hk ⊢
    obtain ⟨hkF, N, hN, hlt⟩ := hk
    exact ⟨hkF, ha.forward_avg_lt_two_maxZ k hN hlt⟩
  have hc' : ((F.filter fun k => ∃ N : ℕ, 1 ≤ N ∧
      t < (N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, a (k + n)).card : ℝ) ≤
      (F.filter fun k => t / 2 < maxZ a k).card := by exact_mod_cast hc
  nlinarith

variable {X : Type*} [MeasurableSpace X]

/-- The set where some forward orbit average of length `1 ≤ N ≤ K` exceeds `t`. -/
def fwdSetK (T : X → X) (h : X → ℝ) (t : ℝ) (K : ℕ) : Set X :=
  {x | ∃ N : ℕ, 1 ≤ N ∧ N ≤ K ∧ t < (N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, h (T^[n] x)}

/-- The finite-orbit-segment inequality: transference of `FinSupp.weak_forward`. -/
lemma orbit_segment_ineq (T : X → X) {h : X → ℝ} (h0 : ∀ x, 0 ≤ h x) {t : ℝ} (ht : 0 < t)
    (K L : ℕ) (x : X) :
    t * ∑ j ∈ Finset.range L, (fwdSetK T h t K).indicator 1 (T^[j] x) ≤
      10 * ∑ j ∈ Finset.range (L + K), h (T^[j] x) := by
  classical
  set Sset : Finset ℤ := (Finset.range (L + K)).image (Nat.cast : ℕ → ℤ) with hSset
  set a : ℤ → ℝ := fun j => if j ∈ Sset then h (T^[j.toNat] x) else 0 with ha_def
  have ha : FinSupp a Sset :=
    ⟨fun j => by simp only [ha_def]; split_ifs <;> simp [h0], fun j hj => by simp [ha_def, hj]⟩
  have hinj : Function.Injective (Nat.cast : ℕ → ℤ) := Nat.cast_injective
  have hsumS : ∑ j ∈ Sset, a j = ∑ j ∈ Finset.range (L + K), h (T^[j] x) := by
    rw [hSset, Finset.sum_image (fun x _ y _ hxy => hinj hxy)]
    refine Finset.sum_congr rfl fun j hj => ?_
    simp only [ha_def]
    rw [if_pos (Finset.mem_image_of_mem _ hj)]
    simp
  set F : Finset ℤ := (Finset.range L).image (Nat.cast : ℕ → ℤ)
  have hw := ha.weak_forward ht F
  rw [hsumS] at hw
  refine le_trans ?_ hw
  gcongr
  rw [Finset.sum_indicator_eq_sum_filter]
  simp only [Pi.one_apply, Finset.sum_const, nsmul_eq_mul, mul_one]
  have : (((Finset.range L).filter fun j => T^[j] x ∈ fwdSetK T h t K).image
      (Nat.cast : ℕ → ℤ)) ⊆ F.filter fun k => ∃ N : ℕ, 1 ≤ N ∧
        t < (N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, a (k + n) := by
    intro k hk
    simp only [Finset.mem_image, Finset.mem_filter, Finset.mem_range] at hk
    obtain ⟨j, ⟨hjL, N, hN1, hNK, hlt⟩, rfl⟩ := hk
    simp only [Finset.mem_filter]
    refine ⟨Finset.mem_image_of_mem _ (Finset.mem_range.2 hjL), N, hN1, ?_⟩
    convert hlt using 2
    refine Finset.sum_congr rfl fun n hn => ?_
    have hn' := Finset.mem_range.1 hn
    have hmem : ((j : ℤ) + n) ∈ Sset := by
      rw [hSset, Finset.mem_image]
      exact ⟨j + n, Finset.mem_range.2 (by omega), by push_cast; rfl⟩
    simp only [ha_def, if_pos hmem]
    have : ((j : ℤ) + n).toNat = n + j := by omega
    rw [this, Function.iterate_add_apply]
  have hc := Finset.card_le_card this
  rw [Finset.card_image_of_injective _ hinj] at hc
  exact_mod_cast hc

variable {μ : Measure X}

lemma integral_comp_iterate_eq {T : X → X} (hT : MeasurePreserving T μ μ) {g : X → ℝ}
    (hg : AEStronglyMeasurable g μ) (n : ℕ) : ∫ x, g (T^[n] x) ∂μ = ∫ x, g x ∂μ := by
  have hTn := hT.iterate n
  have := integral_map (μ := μ) hTn.aemeasurable (f := g) (by rwa [hTn.map_eq])
  rw [hTn.map_eq] at this
  exact this.symm

lemma integrable_comp_iterate {T : X → X} (hT : MeasurePreserving T μ μ) {g : X → ℝ}
    (hg : Integrable g μ) (n : ℕ) : Integrable (fun x => g (T^[n] x)) μ :=
  (hT.iterate n).integrable_comp_of_integrable hg

lemma measurableSet_fwdSetK {T : X → X} (hT : Measurable T) {h : X → ℝ} (hh : Measurable h)
    (t : ℝ) (K : ℕ) : MeasurableSet (fwdSetK T h t K) := by
  have : fwdSetK T h t K = ⋃ N ∈ Finset.Icc 1 K,
      {x | t < (N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, h (T^[n] x)} := by
    ext x; simp [fwdSetK, and_assoc]
  rw [this]
  exact Finset.measurableSet_biUnion _ fun N _ => measurableSet_lt measurable_const
    ((Finset.measurable_sum _ fun n _ => hh.comp (hT.iterate n)).const_mul _)

lemma measureReal_fwdSetK_le [IsProbabilityMeasure μ] {T : X → X}
    (hT : MeasurePreserving T μ μ) {h : X → ℝ} (hh : Measurable h) (h0 : ∀ x, 0 ≤ h x)
    (hi : Integrable h μ) {t : ℝ} (ht : 0 < t) (K : ℕ) :
    μ.real (fwdSetK T h t K) ≤ 10 * (∫ x, h x ∂μ) / t := by
  set E := fwdSetK T h t K
  have hE := measurableSet_fwdSetK hT.measurable hh t K
  set I := ∫ x, h x ∂μ
  have key : ∀ L : ℕ, t * (L * μ.real E) ≤ 10 * ((L + K) * I) := by
    intro L
    have hint := integral_mono (μ := μ)
      (f := fun x => t * ∑ j ∈ Finset.range L, E.indicator 1 (T^[j] x))
      (g := fun x => 10 * ∑ j ∈ Finset.range (L + K), h (T^[j] x)) ?_ ?_
      (fun x => orbit_segment_ineq T h0 ht K L x)
    · rw [integral_const_mul, integral_const_mul, integral_finsetSum, integral_finsetSum] at hint
      · have hj : ∀ j, ∫ x, E.indicator 1 (T^[j] x) ∂μ = μ.real E := fun j => by
          rw [integral_comp_iterate_eq hT
            ((measurable_one.indicator hE).aestronglyMeasurable (μ := μ)),
            integral_indicator_one hE]
        simp only [integral_comp_iterate_eq hT hi.aestronglyMeasurable, hj, Finset.sum_const,
          Finset.card_range, nsmul_eq_mul] at hint
        push_cast at hint
        exact hint
      · exact fun j _ => integrable_comp_iterate hT hi j
      · exact fun j _ => integrable_comp_iterate hT
          ((integrable_const (1 : ℝ)).indicator hE) j
    · exact (integrable_finsetSum _ fun j _ => integrable_comp_iterate hT
          ((integrable_const (1 : ℝ)).indicator hE) j).const_mul _
    · exact (integrable_finsetSum _ fun j _ => integrable_comp_iterate hT hi j).const_mul _
  have hI : 0 ≤ I := integral_nonneg h0
  have hlim : Tendsto (fun n : ℕ => 10 * I / t * (1 + (K : ℝ) / ((n + 1 : ℕ) : ℝ))) atTop
      (𝓝 (10 * I / t * (1 + 0))) := by
    refine tendsto_const_nhds.mul (tendsto_const_nhds.add ?_)
    exact (tendsto_const_div_atTop_nhds_zero_nat (K : ℝ)).comp (tendsto_add_atTop_nat 1)
  rw [add_zero, mul_one] at hlim
  refine ge_of_tendsto' hlim fun n => ?_
  have hk := key (n + 1)
  set L : ℝ := ((n + 1 : ℕ) : ℝ)
  have hn : (0 : ℝ) < L := by positivity
  have : 10 * I / t * (1 + (K : ℝ) / L) = 10 * ((L + K) * I) / (t * L) := by
    field_simp
  rw [this, le_div_iff₀ (by positivity)]
  linarith

lemma one_sided_weak_maximal_of_measurable [IsProbabilityMeasure μ] {T : X → X}
    (hT : MeasurePreserving T μ μ) {h : X → ℝ} (hh : Measurable h) (h0 : ∀ x, 0 ≤ h x)
    (hi : Integrable h μ) {t : ℝ} (ht : 0 < t) :
    μ {x | ∃ N : ℕ, 1 ≤ N ∧ t < (N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, h (T^[n] x)} ≤
      ENNReal.ofReal (10 * (∫ x, h x ∂μ) / t) := by
  have hU : {x | ∃ N : ℕ, 1 ≤ N ∧ t < (N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, h (T^[n] x)} =
      ⋃ K, fwdSetK T h t K := by
    ext x
    simp only [Set.mem_ofPred_eq, Set.mem_iUnion, fwdSetK]
    constructor
    · rintro ⟨N, hN, hlt⟩; exact ⟨N, N, hN, le_rfl, hlt⟩
    · rintro ⟨K, N, hN, -, hlt⟩; exact ⟨N, hN, hlt⟩
  have hmono : Monotone (fwdSetK T h t) := by
    intro K K' hKK' x hx
    obtain ⟨N, hN, hNK, hlt⟩ := hx
    exact ⟨N, hN, hNK.trans hKK', hlt⟩
  rw [hU, hmono.measure_iUnion]
  refine iSup_le fun K => ?_
  rw [← ofReal_measureReal]
  exact ENNReal.ofReal_le_ofReal (measureReal_fwdSetK_le hT hh h0 hi ht K)

/-- **Lemma 10.1 (node T06), weak maximal estimate.** For a measure-preserving map `T` of a
probability space, a nonnegative integrable `h` and `t > 0`, the one-sided ergodic maximal
function `M_T h = sup_{N ≥ 1} N⁻¹ ∑_{n<N} h ∘ Tⁿ` satisfies
`μ {M_T h > t} ≤ 10 ‖h‖₁ / t` (here `‖h‖₁ = ∫ h` since `h ≥ 0`).
The blueprint states the constant `6` (based on a Vitali constant `3`); our discrete maximal
estimate D01 has constant `5`, which yields the absolute constant `10`. No invertibility or
commutation is needed. -/
theorem one_sided_ergodic_weak_maximal [IsProbabilityMeasure μ] {T : X → X}
    (hT : MeasurePreserving T μ μ) {h : X → ℝ} (h0 : ∀ x, 0 ≤ h x)
    (hi : Integrable h μ) {t : ℝ} (ht : 0 < t) :
    μ {x | ∃ N : ℕ, 1 ≤ N ∧ t < (N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, h (T^[n] x)} ≤
      ENNReal.ofReal (10 * (∫ x, h x ∂μ) / t) := by
  set h' : X → ℝ := fun x => max (hi.aestronglyMeasurable.mk h x) 0 with hh'_def
  have hh' : Measurable h' :=
    hi.aestronglyMeasurable.stronglyMeasurable_mk.measurable.max measurable_const
  have heq : h =ᵐ[μ] h' := hi.aestronglyMeasurable.ae_eq_mk.mono fun x hx => by
    simp only [hh'_def, ← hx, max_eq_left (h0 x)]
  have hi' : Integrable h' μ := hi.congr heq
  have h0' : ∀ x, 0 ≤ h' x := fun x => le_max_right _ _
  have hall : ∀ᵐ x ∂μ, ∀ n : ℕ, h (T^[n] x) = h' (T^[n] x) :=
    ae_all_iff.2 fun n => (hT.iterate n).quasiMeasurePreserving.ae_eq_comp heq
  rw [integral_congr_ae heq]
  refine le_trans (measure_mono_ae ?_) (one_sided_weak_maximal_of_measurable hT hh' h0' hi' ht)
  filter_upwards [hall] with x hx
  intro hmem
  obtain ⟨N, hN, hlt⟩ := hmem
  refine ⟨N, hN, ?_⟩
  simpa only [hx] using hlt

end T06

/-! ### Node T07 -/

section T07

lemma avg_weights_sum {N : ℕ} (hN : 1 ≤ N) :
    ∑ _n ∈ Finset.range N, (N : ℝ)⁻¹ = 1 := by
  have : (N : ℝ) ≠ 0 := by positivity
  simp [this]

/-- Power-mean (Jensen) inequality for normalized finite averages. -/
lemma avg_le_rpow_avg {N : ℕ} (hN : 1 ≤ N) {b : ℕ → ℝ} (hb : ∀ n, 0 ≤ b n) {Q : ℝ}
    (hQ : 1 ≤ Q) :
    (N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, b n ≤
      ((N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, b n ^ Q) ^ (1 / Q) := by
  rw [Finset.mul_sum, Finset.mul_sum]
  exact Real.arith_mean_le_rpow_mean _ (fun _ => (N : ℝ)⁻¹) b (fun _ _ => by positivity)
    (avg_weights_sum hN) (fun n _ => hb n) hQ

/-- Hölder inequality for normalized finite averages, in `R`-th power form. -/
lemma holder_avg_rpow {N : ℕ} (hN : 1 ≤ N) {a b : ℕ → ℝ} (ha : ∀ n, 0 ≤ a n)
    (hb : ∀ n, 0 ≤ b n) {P Q R : ℝ} (hPQR : P.HolderTriple Q R) (hR : 1 ≤ R) :
    ((N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, a n * b n) ^ R ≤
      ((N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, a n ^ P) ^ (R / P) *
      ((N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, b n ^ Q) ^ (R / Q) := by
  have hNpos : (0 : ℝ) < (N : ℝ)⁻¹ := by
    have : (0 : ℝ) < N := by exact_mod_cast hN
    positivity
  have hP := hPQR.left_pos
  have hQ := hPQR.right_pos
  have hRpos : 0 < R := by linarith
  have hsum : R / P + R / Q = 1 := by
    have h := hPQR.inv_add_inv_eq_inv
    field_simp
    have : R * (P⁻¹ + Q⁻¹) = 1 := by rw [h, mul_inv_cancel₀ hRpos.ne']
    field_simp at this
    linarith
  have h1 : ((N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, a n * b n) ^ R ≤
      (N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, (a n * b n) ^ R := by
    rw [Finset.mul_sum, Finset.mul_sum]
    exact Real.rpow_arith_mean_le_arith_mean_rpow _ (fun _ => (N : ℝ)⁻¹) _
      (fun _ _ => hNpos.le) (avg_weights_sum hN) (fun n _ => mul_nonneg (ha n) (hb n)) hR
  have h2 := Real.Lr_rpow_le_Lp_mul_Lq_of_nonneg (Finset.range N) hPQR
    (fun n _ => ha n) (fun n _ => hb n)
  refine h1.trans ?_
  have hsplit : (N : ℝ)⁻¹ = (N : ℝ)⁻¹ ^ (R / P) * (N : ℝ)⁻¹ ^ (R / Q) := by
    rw [← Real.rpow_add hNpos, hsum, Real.rpow_one]
  have hA : 0 ≤ ∑ n ∈ Finset.range N, a n ^ P :=
    Finset.sum_nonneg fun n _ => Real.rpow_nonneg (ha n) _
  have hB : 0 ≤ ∑ n ∈ Finset.range N, b n ^ Q :=
    Finset.sum_nonneg fun n _ => Real.rpow_nonneg (hb n) _
  rw [Real.mul_rpow hNpos.le hA, Real.mul_rpow hNpos.le hB]
  calc (N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, (a n * b n) ^ R
      ≤ (N : ℝ)⁻¹ * ((∑ n ∈ Finset.range N, a n ^ P) ^ (R / P) *
          (∑ n ∈ Finset.range N, b n ^ Q) ^ (R / Q)) := by gcongr
    _ = _ := by conv_lhs => rw [hsplit]
                ring

lemma norm_bilinAvg_le_T08 {X : Type*} (T S : X → X) (f g : X → ℂ) (N : ℕ) (x : X) :
    ‖bilinAvg T S f g N x‖ ≤
      (N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, ‖f (T^[n] x)‖ * ‖g (S^[n] x)‖ := by
  unfold bilinAvg
  rw [norm_mul, norm_inv, Complex.norm_natCast]
  gcongr
  refine (norm_sum_le _ _).trans ?_
  simp only [norm_mul, le_refl]

lemma bilinAvg_comm {X : Type*} (T S : X → X) (f g : X → ℂ) :
    bilinAvg T S f g = bilinAvg S T g f := by
  ext N x
  simp only [bilinAvg, mul_comm (f _)]

variable {X : Type*} [MeasurableSpace X] {μ : Measure X}

lemma bilin_weak_core_finite [IsProbabilityMeasure μ] {T S : X → X}
    (hT : MeasurePreserving T μ μ) (hS : MeasurePreserving S μ μ)
    {P Q R : ℝ} (hPQR : P.HolderTriple Q R) (hR : 1 ≤ R) {f g : X → ℂ}
    (hfi : Integrable (fun x => ‖f x‖ ^ P) μ) (hgi : Integrable (fun x => ‖g x‖ ^ Q) μ)
    {A B : ℝ} (hA : 0 < A) (hB : 0 < B) (hAf : ∫ x, ‖f x‖ ^ P ∂μ = A ^ P)
    (hBg : ∫ x, ‖g x‖ ^ Q ∂μ = B ^ Q) {t : ℝ} (ht : 0 < t) :
    μ {x | ∃ N : ℕ, 1 ≤ N ∧ t < ‖bilinAvg T S f g N x‖} ≤
      ENNReal.ofReal (20 * (A * B / t) ^ R) := by
  have hP := hPQR.left_pos
  have hQ := hPQR.right_pos
  have hRpos : 0 < R := by linarith
  have hsum : R / P + R / Q = 1 := by
    have h := hPQR.inv_add_inv_eq_inv
    field_simp
    have : R * (P⁻¹ + Q⁻¹) = 1 := by rw [h, mul_inv_cancel₀ hRpos.ne']
    field_simp at this
    linarith
  set c := t / (A * B) with hc_def
  have hc : 0 < c := by positivity
  set α := A ^ P * c ^ R with hα
  set β := B ^ Q * c ^ R with hβ
  have hαpos : 0 < α := by positivity
  have hβpos : 0 < β := by positivity
  have key : α ^ (R / P) * β ^ (R / Q) = t ^ R := by
    rw [hα, hβ, Real.mul_rpow (by positivity) (by positivity),
      Real.mul_rpow (by positivity) (by positivity), ← Real.rpow_mul hA.le,
      ← Real.rpow_mul hc.le, ← Real.rpow_mul hB.le, ← Real.rpow_mul hc.le]
    have e1 : P * (R / P) = R := by field_simp
    have e2 : Q * (R / Q) = R := by field_simp
    have e3 : c ^ (R * (R / P)) * c ^ (R * (R / Q)) = c ^ R := by
      rw [← Real.rpow_add hc, ← mul_add, hsum, mul_one]
    have e4 : A * B * c = t := by rw [hc_def]; field_simp
    calc A ^ (P * (R / P)) * c ^ (R * (R / P)) * (B ^ (Q * (R / Q)) * c ^ (R * (R / Q)))
        = A ^ R * B ^ R * (c ^ (R * (R / P)) * c ^ (R * (R / Q))) := by
          rw [e1, e2]; ring
      _ = (A * B * c) ^ R := by
          rw [e3, Real.mul_rpow (by positivity) hc.le, Real.mul_rpow hA.le hB.le]
      _ = t ^ R := by rw [e4]
  have hsub : {x | ∃ N : ℕ, 1 ≤ N ∧ t < ‖bilinAvg T S f g N x‖} ⊆
      {x | ∃ N : ℕ, 1 ≤ N ∧ α < (N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, ‖f (T^[n] x)‖ ^ P} ∪
      {x | ∃ N : ℕ, 1 ≤ N ∧ β < (N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, ‖g (S^[n] x)‖ ^ Q} := by
    intro x hx
    obtain ⟨N, hN, hlt⟩ := hx
    by_contra hcon
    simp only [Set.mem_union, Set.mem_ofPred_eq, not_or, not_exists, not_and, not_lt] at hcon
    have hU := hcon.1 N hN
    have hV := hcon.2 N hN
    have hm := norm_bilinAvg_le_T08 T S f g N x
    set m := (N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, ‖f (T^[n] x)‖ * ‖g (S^[n] x)‖
    have hm0 : 0 ≤ m := (norm_nonneg _).trans hm
    have hH := holder_avg_rpow hN (a := fun n => ‖f (T^[n] x)‖) (b := fun n => ‖g (S^[n] x)‖)
      (fun n => norm_nonneg _) (fun n => norm_nonneg _) hPQR hR
    have hU0 : 0 ≤ (N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, ‖f (T^[n] x)‖ ^ P := by
      have : (0 : ℝ) ≤ (N : ℝ)⁻¹ := by positivity
      exact mul_nonneg this (Finset.sum_nonneg fun n _ => Real.rpow_nonneg (norm_nonneg _) _)
    have hV0 : 0 ≤ (N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, ‖g (S^[n] x)‖ ^ Q := by
      have : (0 : ℝ) ≤ (N : ℝ)⁻¹ := by positivity
      exact mul_nonneg this (Finset.sum_nonneg fun n _ => Real.rpow_nonneg (norm_nonneg _) _)
    have hmR : m ^ R ≤ t ^ R := by
      refine hH.trans ?_
      rw [← key]
      gcongr
    have : m ≤ t := (Real.rpow_le_rpow_iff hm0 ht.le hRpos).1 hmR
    linarith
  refine (measure_mono hsub).trans ((measure_union_le _ _).trans ?_)
  have h1 := one_sided_ergodic_weak_maximal hT (h := fun x => ‖f x‖ ^ P)
    (fun x => Real.rpow_nonneg (norm_nonneg _) _) hfi hαpos
  have h2 := one_sided_ergodic_weak_maximal hS (h := fun x => ‖g x‖ ^ Q)
    (fun x => Real.rpow_nonneg (norm_nonneg _) _) hgi hβpos
  refine (add_le_add h1 h2).trans ?_
  rw [hAf, hBg, ← ENNReal.ofReal_add (by positivity) (by positivity)]
  apply ENNReal.ofReal_le_ofReal
  have hinv : (A * B / t) ^ R = (c ^ R)⁻¹ := by
    rw [← Real.inv_rpow hc.le, hc_def, inv_div]
  rw [hinv, hα, hβ]
  have : 0 < A ^ P := by positivity
  have : 0 < B ^ Q := by positivity
  have : 0 < c ^ R := by positivity
  field_simp
  norm_num

/-- Changing `f, g` on null sets changes all averages only on a null set. -/
lemma bilinAvg_ae_congr {T S : X → X} (hT : MeasurePreserving T μ μ)
    (hS : MeasurePreserving S μ μ) {f f' g g' : X → ℂ} (hf : f =ᵐ[μ] f') (hg : g =ᵐ[μ] g') :
    ∀ᵐ x ∂μ, ∀ N, bilinAvg T S f g N x = bilinAvg T S f' g' N x := by
  have h1 : ∀ᵐ x ∂μ, ∀ n : ℕ, f (T^[n] x) = f' (T^[n] x) :=
    ae_all_iff.2 fun n => (hT.iterate n).quasiMeasurePreserving.ae_eq_comp hf
  have h2 : ∀ᵐ x ∂μ, ∀ n : ℕ, g (S^[n] x) = g' (S^[n] x) :=
    ae_all_iff.2 fun n => (hS.iterate n).quasiMeasurePreserving.ae_eq_comp hg
  filter_upwards [h1, h2] with x hx1 hx2 N
  simp only [bilinAvg, hx1, hx2]

lemma bilinAvg_zero_left {X : Type*} (T S : X → X) (g : X → ℂ) :
    bilinAvg T S 0 g = 0 := by
  ext N x; simp [bilinAvg]

lemma bilin_set_null_of_left {T S : X → X} (hT : MeasurePreserving T μ μ)
    (hS : MeasurePreserving S μ μ) {f g : X → ℂ} (hf : f =ᵐ[μ] 0) (t : ℝ) (ht : 0 < t) :
    μ {x | ∃ N : ℕ, 1 ≤ N ∧ t < ‖bilinAvg T S f g N x‖} = 0 := by
  refine measure_mono_null (t := {x | ¬ ∀ N, bilinAvg T S f g N x = bilinAvg T S 0 g N x})
    ?_ (ae_iff.1 (bilinAvg_ae_congr hT hS hf (EventuallyEq.refl _ g)))
  intro x hx hall
  obtain ⟨N, -, hlt⟩ := hx
  rw [hall N, bilinAvg_zero_left] at hlt
  simp at hlt
  linarith

lemma bilin_weak_core_top [IsProbabilityMeasure μ] {T S : X → X}
    (hT : MeasurePreserving T μ μ) (hS : MeasurePreserving S μ μ) {Q : ℝ} (hQ : 1 ≤ Q)
    {f g : X → ℂ} {K : ℝ} (hK : 0 < K) (hfK : ∀ᵐ x ∂μ, ‖f x‖ ≤ K)
    (hgi : Integrable (fun x => ‖g x‖ ^ Q) μ) {B : ℝ} (hB : 0 ≤ B)
    (hBg : ∫ x, ‖g x‖ ^ Q ∂μ = B ^ Q) {t : ℝ} (ht : 0 < t) :
    μ {x | ∃ N : ℕ, 1 ≤ N ∧ t < ‖bilinAvg T S f g N x‖} ≤
      ENNReal.ofReal (10 * (K * B / t) ^ Q) := by
  have hQpos : 0 < Q := by linarith
  have hall : ∀ᵐ x ∂μ, ∀ n : ℕ, ‖f (T^[n] x)‖ ≤ K :=
    ae_all_iff.2 fun n => (hT.iterate n).quasiMeasurePreserving.ae hfK
  have hsub : {x | ∃ N : ℕ, 1 ≤ N ∧ t < ‖bilinAvg T S f g N x‖} ≤ᵐ[μ]
      {x | ∃ N : ℕ, 1 ≤ N ∧
        (t / K) ^ Q < (N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, ‖g (S^[n] x)‖ ^ Q} := by
    filter_upwards [hall] with x hx
    intro hmem
    obtain ⟨N, hN, hlt⟩ := hmem
    by_contra hcon
    simp only [Set.mem_ofPred_eq, not_exists, not_and, not_lt] at hcon
    have hV := hcon N hN
    have hm := norm_bilinAvg_le_T08 T S f g N x
    have hJ := avg_le_rpow_avg hN (b := fun n => ‖g (S^[n] x)‖) (fun n => norm_nonneg _) hQ
    have hNinv : (0 : ℝ) ≤ (N : ℝ)⁻¹ := by positivity
    have h1 : (N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, ‖f (T^[n] x)‖ * ‖g (S^[n] x)‖ ≤
        K * ((N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, ‖g (S^[n] x)‖) := by
      rw [mul_left_comm, Finset.mul_sum _ _ K]
      gcongr with n hn
      exact hx n
    have h2 : ((N : ℝ)⁻¹ * ∑ n ∈ Finset.range N, ‖g (S^[n] x)‖ ^ Q) ^ (1 / Q) ≤ t / K := by
      calc _ ≤ ((t / K) ^ Q) ^ (1 / Q) := by
            gcongr
        _ = t / K := by
            rw [← Real.rpow_mul (by positivity), mul_one_div_cancel hQpos.ne', Real.rpow_one]
    have h3 : K * (t / K) = t := by field_simp
    have : ‖bilinAvg T S f g N x‖ ≤ t := by
      calc _ ≤ _ := hm
        _ ≤ _ := h1
        _ ≤ K * (t / K) := by gcongr; exact hJ.trans h2
        _ = t := h3
    linarith
  refine (measure_mono_ae hsub).trans ?_
  refine (one_sided_ergodic_weak_maximal hS (h := fun x => ‖g x‖ ^ Q)
    (fun x => Real.rpow_nonneg (norm_nonneg _) _) hgi (by positivity)).trans ?_
  apply ENNReal.ofReal_le_ofReal
  rw [hBg, mul_div_assoc, ← Real.div_rpow hB (by positivity)]
  have : B / (t / K) = K * B / t := by field_simp
  rw [this]

lemma ofReal_bound_eq {c A B t R : ℝ} (hc : 0 ≤ c) (hA : 0 ≤ A) (hB : 0 ≤ B) (ht : 0 < t)
    (hR : 0 ≤ R) :
    ENNReal.ofReal (c * (A * B / t) ^ R) =
      ENNReal.ofReal c * (ENNReal.ofReal A * ENNReal.ofReal B / ENNReal.ofReal t) ^ R := by
  rw [ENNReal.ofReal_mul hc, ← ENNReal.ofReal_rpow_of_nonneg (by positivity) hR,
    ENNReal.ofReal_div_of_pos ht, ENNReal.ofReal_mul hA]

lemma one_le_toReal_of_one_le {p : ℝ≥0∞} (hp : 1 ≤ p) (hpt : p ≠ ⊤) : 1 ≤ p.toReal := by
  have := ENNReal.toReal_mono hpt hp
  simpa using this

lemma eLpNorm_eq_ofReal_integral {f : X → ℂ} {p : ℝ≥0∞} (hp : 1 ≤ p) (hpt : p ≠ ⊤)
    (hf : MemLp f p μ) :
    eLpNorm f p μ = ENNReal.ofReal ((∫ x, ‖f x‖ ^ p.toReal ∂μ) ^ p.toReal⁻¹) ∧
      ((∫ x, ‖f x‖ ^ p.toReal ∂μ) ^ p.toReal⁻¹) ^ p.toReal = ∫ x, ‖f x‖ ^ p.toReal ∂μ ∧
      0 ≤ (∫ x, ‖f x‖ ^ p.toReal ∂μ) ^ p.toReal⁻¹ := by
  have hp0 : p ≠ 0 := (lt_of_lt_of_le zero_lt_one hp).ne'
  have hP := one_le_toReal_of_one_le hp hpt
  have hI : 0 ≤ ∫ x, ‖f x‖ ^ p.toReal ∂μ :=
    integral_nonneg fun x => Real.rpow_nonneg (norm_nonneg _) _
  refine ⟨hf.eLpNorm_eq_integral_rpow_norm hp0 hpt, Real.rpow_inv_rpow hI (by positivity),
    Real.rpow_nonneg hI _⟩

lemma bilin_weak_top_left [IsProbabilityMeasure μ] {T S : X → X}
    (hT : MeasurePreserving T μ μ) (hS : MeasurePreserving S μ μ) {q : ℝ≥0∞} (hq : 1 ≤ q)
    (hqt : q ≠ ⊤) {f g : X → ℂ} (hf : MemLp f ⊤ μ) (hg : MemLp g q μ) {t : ℝ} (ht : 0 < t) :
    μ {x | ∃ N : ℕ, 1 ≤ N ∧ t < ‖bilinAvg T S f g N x‖} ≤
      20 * (eLpNorm f ⊤ μ * eLpNorm g q μ / ENNReal.ofReal t) ^ q.toReal := by
  have hq0 : q ≠ 0 := (lt_of_lt_of_le zero_lt_one hq).ne'
  set K := (eLpNorm f ⊤ μ).toReal with hK_def
  have hKfin : eLpNorm f ⊤ μ ≠ ⊤ := hf.eLpNorm_lt_top.ne
  rcases (ENNReal.toReal_nonneg (a := eLpNorm f ⊤ μ)).eq_or_lt with hK0 | hKpos
  · have : eLpNorm f ⊤ μ = 0 := by
      rcases (ENNReal.toReal_eq_zero_iff _).1 hK0.symm with h | h
      · exact h
      · exact absurd h hKfin
    have hf0 : f =ᵐ[μ] 0 := (eLpNorm_eq_zero_iff ENNReal.top_ne_zero).1 this
    rw [bilin_set_null_of_left hT hS hf0 t ht]
    exact zero_le
  have hfK : ∀ᵐ x ∂μ, ‖f x‖ ≤ K := by
    filter_upwards [enorm_ae_le_eLpNormEssSup f μ] with x hx
    rw [← eLpNorm_exponent_top hf.aestronglyMeasurable] at hx
    have := ENNReal.toReal_mono hKfin hx
    simpa using this
  obtain ⟨hgB, hBQ, hB0⟩ := eLpNorm_eq_ofReal_integral hq hqt hg
  have hQ := one_le_toReal_of_one_le hq hqt
  refine (bilin_weak_core_top hT hS hQ hKpos hfK (hg.integrable_norm_rpow hq0 hqt) hB0
    hBQ.symm ht).trans ?_
  rw [ofReal_bound_eq (by norm_num) hKpos.le hB0 ht (by linarith), ← hgB,
    ENNReal.ofReal_toReal hKfin]
  gcongr
  norm_num

/-- **Lemma 10.2 (node T07), a bilinear weak bound.** Let `1 ≤ p, q ≤ ∞` with
`p⁻¹ + q⁻¹ ≤ 1` and `r⁻¹ = p⁻¹ + q⁻¹ > 0`. For measure-preserving `T, S` on a probability
space (no commutation needed), `f ∈ L^p`, `g ∈ L^q` and `t > 0`,
`μ {sup_{N ≥ 1} |A_N(f,g)| > t} ≤ 20 (‖f‖_p ‖g‖_q / t)^r`.
The absolute constant is `20` (twice the constant `10` of T06). -/
theorem bilinear_ergodic_weak_maximal [IsProbabilityMeasure μ] {T S : X → X}
    (hT : MeasurePreserving T μ μ) (hS : MeasurePreserving S μ μ) {p q r : ℝ≥0∞}
    (hp : 1 ≤ p) (hq : 1 ≤ q) (hpq : p⁻¹ + q⁻¹ ≤ 1) (hr : r⁻¹ = p⁻¹ + q⁻¹) (hr0 : 0 < r⁻¹)
    {f g : X → ℂ} (hf : MemLp f p μ) (hg : MemLp g q μ) {t : ℝ} (ht : 0 < t) :
    μ {x | ∃ N : ℕ, 1 ≤ N ∧ t < ‖bilinAvg T S f g N x‖} ≤
      20 * (eLpNorm f p μ * eLpNorm g q μ / ENNReal.ofReal t) ^ r.toReal := by
  by_cases hpt : p = ⊤
  · subst hpt
    by_cases hqt : q = ⊤
    · subst hqt; simp at hr; simp [hr] at hr0
    · have : r = q := by simpa using hr
      subst this
      exact bilin_weak_top_left hT hS hq hqt hf hg ht
  by_cases hqt : q = ⊤
  · subst hqt
    have : r = p := by simpa using hr
    subst this
    rw [bilinAvg_comm, mul_comm (eLpNorm f r μ)]
    exact bilin_weak_top_left hS hT hp hpt hg hf ht
  -- both exponents finite
  have hp0 : p ≠ 0 := (lt_of_lt_of_le zero_lt_one hp).ne'
  have hq0 : q ≠ 0 := (lt_of_lt_of_le zero_lt_one hq).ne'
  have hrt : r ≠ ⊤ := by
    intro h; rw [h] at hr0; simp at hr0
  have hr1 : 1 ≤ r := by
    rw [← ENNReal.inv_le_one, hr]; exact hpq
  have hP := one_le_toReal_of_one_le hp hpt
  have hQ := one_le_toReal_of_one_le hq hqt
  have hR := one_le_toReal_of_one_le hr1 hrt
  have hPQR : p.toReal.HolderTriple q.toReal r.toReal := by
    refine ⟨?_, by linarith, by linarith⟩
    have := congrArg ENNReal.toReal hr
    rw [ENNReal.toReal_add (by simpa using hp0) (by simpa using hq0)] at this
    simpa [ENNReal.toReal_inv] using this.symm
  obtain ⟨hfA, hAP, hA0⟩ := eLpNorm_eq_ofReal_integral hp hpt hf
  obtain ⟨hgB, hBQ, hB0⟩ := eLpNorm_eq_ofReal_integral hq hqt hg
  set A := (∫ x, ‖f x‖ ^ p.toReal ∂μ) ^ p.toReal⁻¹
  set B := (∫ x, ‖g x‖ ^ q.toReal ∂μ) ^ q.toReal⁻¹
  rcases hA0.eq_or_lt with hA | hApos
  · have hf0 : f =ᵐ[μ] 0 := (eLpNorm_eq_zero_iff hp0).1 (by rw [hfA, ← hA]; simp)
    rw [bilin_set_null_of_left hT hS hf0 t ht]
    exact zero_le
  rcases hB0.eq_or_lt with hB | hBpos
  · have hg0 : g =ᵐ[μ] 0 := (eLpNorm_eq_zero_iff hq0).1 (by rw [hgB, ← hB]; simp)
    rw [bilinAvg_comm, bilin_set_null_of_left hS hT hg0 t ht]
    exact zero_le
  refine (bilin_weak_core_finite hT hS hPQR hR (hf.integrable_norm_rpow hp0 hpt)
    (hg.integrable_norm_rpow hq0 hqt) hApos hBpos hAP.symm hBQ.symm ht).trans ?_
  rw [ofReal_bound_eq (by norm_num) hA0 hB0 ht (by linarith), ← hfA, ← hgB]
  norm_num

end T07

/-! ### Node T08 -/

section T08

variable {X : Type*} [MeasurableSpace X] {μ : Measure X}

/-- An essentially bounded function has a bounded measurable representative. -/
lemma exists_bdd_rep_of_memLp_top {f : X → ℂ} (hf : MemLp f ⊤ μ) :
    ∃ f' : X → ℂ, Measurable f' ∧ (∃ C, ∀ x, ‖f' x‖ ≤ C) ∧ f =ᵐ[μ] f' := by
  set K := (eLpNorm f ⊤ μ).toReal
  have hKfin : eLpNorm f ⊤ μ ≠ ⊤ := hf.eLpNorm_lt_top.ne
  have hfK : ∀ᵐ x ∂μ, ‖f x‖ ≤ K := by
    filter_upwards [enorm_ae_le_eLpNormEssSup f μ] with x hx
    rw [← eLpNorm_exponent_top hf.aestronglyMeasurable] at hx
    have := ENNReal.toReal_mono hKfin hx
    simpa using this
  set f₀ := hf.aestronglyMeasurable.mk f
  have hf₀ : Measurable f₀ := hf.aestronglyMeasurable.stronglyMeasurable_mk.measurable
  refine ⟨{x | ‖f₀ x‖ ≤ K}.indicator f₀, hf₀.indicator
    (measurableSet_le hf₀.norm measurable_const), ⟨K, fun x => ?_⟩, ?_⟩
  · by_cases hx : x ∈ {x | ‖f₀ x‖ ≤ K}
    · rw [Set.indicator_of_mem hx]; exact hx
    · rw [Set.indicator_of_notMem hx, norm_zero]; exact ENNReal.toReal_nonneg
  · filter_upwards [hf.aestronglyMeasurable.ae_eq_mk, hfK] with x hx hxK
    have hmem : x ∈ {x | ‖f₀ x‖ ≤ K} := by
      have h' : f₀ x = f x := hx.symm
      show ‖f₀ x‖ ≤ K
      rw [h']; exact hxK
    rw [Set.indicator_of_mem hmem]
    exact hx

/-- Approximation of an `L^p` function by bounded measurable functions. -/
lemma exists_bdd_approx_seq [IsFiniteMeasure μ] {p : ℝ≥0∞} (hp : 1 ≤ p) {f : X → ℂ}
    (hf : MemLp f p μ) :
    ∃ fs : ℕ → X → ℂ, (∀ k, Measurable (fs k)) ∧ (∀ k, ∃ C, ∀ x, ‖fs k x‖ ≤ C) ∧
      (∀ k, MemLp (fs k) p μ) ∧
      Tendsto (fun k => eLpNorm (f - fs k) p μ) atTop (𝓝 0) ∧
      ∀ k, eLpNorm (fs k) p μ ≤ eLpNorm f p μ + 1 := by
  have hbound : ∀ k, ∃ f' : X → ℂ, Measurable f' ∧ (∃ C, ∀ x, ‖f' x‖ ≤ C) ∧
      eLpNorm (f - f') p μ ≤ ((k + 1 : ℕ) : ℝ≥0∞)⁻¹ := by
    intro k
    by_cases hpt : p = ⊤
    · subst hpt
      obtain ⟨f', hm, hb, he⟩ := exists_bdd_rep_of_memLp_top hf
      refine ⟨f', hm, hb, ?_⟩
      have : f - f' =ᵐ[μ] 0 := he.mono fun x hx => by simp [hx]
      rw [eLpNorm_congr_ae this, eLpNorm_zero]
      exact zero_le
    · obtain ⟨g, hg, -⟩ := hf.exists_simpleFunc_eLpNorm_sub_lt hpt
        (ε := ((k + 1 : ℕ) : ℝ≥0∞)⁻¹) (by simp)
      exact ⟨g, g.measurable, g.exists_forall_norm_le, hg.le⟩
  choose fs hm hb hle using hbound
  have hmem : ∀ k, MemLp (fs k) p μ := fun k => by
    obtain ⟨C, hC⟩ := hb k
    exact MemLp.of_bound (hm k).aestronglyMeasurable C (Eventually.of_forall hC)
  refine ⟨fs, hm, hb, hmem, ?_, fun k => ?_⟩
  · have h0 : Tendsto (fun k : ℕ => ((k + 1 : ℕ) : ℝ≥0∞)⁻¹) atTop (𝓝 0) :=
      ENNReal.tendsto_inv_nat_nhds_zero.comp (tendsto_add_atTop_nat 1)
    exact tendsto_of_tendsto_of_tendsto_of_le_of_le tendsto_const_nhds h0
      (fun k => zero_le) hle
  · have : fs k = f - (f - fs k) := by abel
    rw [this]
    refine (eLpNorm_sub_le hp).trans ?_
    gcongr
    refine (hle k).trans ?_
    simp

lemma bilinAvg_sub_decomp (T S : X → X) (f f' g g' : X → ℂ) (N : ℕ) :
    bilinAvg T S f g N - bilinAvg T S f' g' N =
      bilinAvg T S (f - f') g N + bilinAvg T S f' (g - g') N := by
  ext x
  simp only [bilinAvg, Pi.sub_apply, Pi.add_apply, ← mul_sub, ← mul_add,
    ← Finset.sum_sub_distrib, ← Finset.sum_add_distrib]
  congr 1
  refine Finset.sum_congr rfl fun n _ => ?_
  ring

lemma bilinAvg_eq_smul_sum (T S : X → X) (f g : X → ℂ) (N : ℕ) :
    bilinAvg T S f g N = (N : ℂ)⁻¹ • ∑ n ∈ Finset.range N,
      (fun x => f (T^[n] x)) • (fun x => g (S^[n] x)) := by
  ext x
  simp [bilinAvg, Finset.sum_apply]

lemma aestronglyMeasurable_bilinAvg {T S : X → X} (hT : MeasurePreserving T μ μ)
    (hS : MeasurePreserving S μ μ) {f g : X → ℂ} (hf : AEStronglyMeasurable f μ)
    (hg : AEStronglyMeasurable g μ) (N : ℕ) :
    AEStronglyMeasurable (bilinAvg T S f g N) μ := by
  rw [bilinAvg_eq_smul_sum]
  refine AEStronglyMeasurable.const_smul ?_ _
  refine Finset.aestronglyMeasurable_sum _ fun n _ => ?_
  exact (hf.comp_measurePreserving (hT.iterate n)).smul (hg.comp_measurePreserving (hS.iterate n))

/-- Hölder, invariance and the triangle inequality: `‖A_N(f,g)‖_r ≤ ‖f‖_p ‖g‖_q`. -/
lemma eLpNorm_bilinAvg_le {T S : X → X} (hT : MeasurePreserving T μ μ)
    (hS : MeasurePreserving S μ μ) {p q r : ℝ≥0∞} [ENNReal.HolderTriple p q r] (hr : 1 ≤ r)
    {f g : X → ℂ} (hf : AEStronglyMeasurable f μ) (hg : AEStronglyMeasurable g μ) (N : ℕ) :
    eLpNorm (bilinAvg T S f g N) r μ ≤ eLpNorm f p μ * eLpNorm g q μ := by
  rcases Nat.eq_zero_or_pos N with rfl | hN
  · have : bilinAvg T S f g 0 = 0 := by ext x; simp [bilinAvg]
    rw [this, eLpNorm_zero]; exact zero_le
  rw [bilinAvg_eq_smul_sum, eLpNorm_const_smul]
  have hsum := eLpNorm_sum_le (μ := μ) (p := r)
    (f := fun n => (fun x => f (T^[n] x)) • (fun x => g (S^[n] x)))
    (s := Finset.range N) hr
  have hterm : ∀ n, eLpNorm ((fun x => f (T^[n] x)) • (fun x => g (S^[n] x))) r μ ≤
      eLpNorm f p μ * eLpNorm g q μ := by
    intro n
    refine (eLpNorm_smul_le_mul_eLpNorm (p := p) (q := q) (hf.comp_measurePreserving (hT.iterate n))
      (hg.comp_measurePreserving (hS.iterate n))).trans_eq ?_
    rw [eLpNorm_comp_measurePreserving hf (hT.iterate n),
      eLpNorm_comp_measurePreserving hg (hS.iterate n)]
  have h2 : eLpNorm (∑ n ∈ Finset.range N,
      (fun x => f (T^[n] x)) • (fun x => g (S^[n] x))) r μ ≤
      N * (eLpNorm f p μ * eLpNorm g q μ) := by
    refine hsum.trans ?_
    refine (Finset.sum_le_sum fun n _ => hterm n).trans ?_
    simp
  have hNe : ‖((N : ℂ))⁻¹‖ₑ = (N : ℝ≥0∞)⁻¹ := by
    rw [enorm_inv (by exact_mod_cast hN.ne'), ← ofReal_norm, Complex.norm_natCast,
      ENNReal.ofReal_natCast]
  rw [hNe]
  calc (N : ℝ≥0∞)⁻¹ * eLpNorm (∑ n ∈ Finset.range N,
        (fun x => f (T^[n] x)) • (fun x => g (S^[n] x))) r μ
      ≤ (N : ℝ≥0∞)⁻¹ * (N * (eLpNorm f p μ * eLpNorm g q μ)) := by gcongr
    _ = eLpNorm f p μ * eLpNorm g q μ := by
      rw [← mul_assoc, ENNReal.inv_mul_cancel (by exact_mod_cast hN.ne') (by simp), one_mul]

/-- Abstract almost-everywhere Cauchy criterion: a sequence that is uniformly (in `N`) close,
outside a set of small measure, to a.e. convergent sequences converges a.e. -/
lemma ae_tendsto_of_approx {a : ℕ → X → ℂ}
    (h : ∀ ε : ℝ, 0 < ε → ∀ δ : ℝ≥0∞, 0 < δ → ∃ b : ℕ → X → ℂ,
      (∀ᵐ x ∂μ, ∃ L, Tendsto (fun N => b N x) atTop (𝓝 L)) ∧
      μ {x | ∃ N, ε < ‖a N x - b N x‖} ≤ δ) :
    ∀ᵐ x ∂μ, ∃ L, Tendsto (fun N => a N x) atTop (𝓝 L) := by
  have hG : ∀ ε : ℝ, 0 < ε → ∀ᵐ x ∂μ, ∃ M, ∀ m ≥ M, ∀ n ≥ M, ‖a m x - a n x‖ < ε := by
    intro ε hε
    rw [ae_iff]
    refine le_antisymm (ENNReal.le_of_forall_pos_le_add fun δ hδ _ => ?_) zero_le
    obtain ⟨b, hb, hμ⟩ := h (ε / 4) (by positivity) δ (by exact_mod_cast hδ)
    rw [zero_add]
    have hsub : {x | ¬ ∃ M, ∀ m ≥ M, ∀ n ≥ M, ‖a m x - a n x‖ < ε} ⊆
        {x | ¬ ∃ L, Tendsto (fun N => b N x) atTop (𝓝 L)} ∪
          {x | ∃ N, ε / 4 < ‖a N x - b N x‖} := by
      intro x hx
      by_contra hc
      rw [Set.mem_union, not_or] at hc
      obtain ⟨hc1, hab⟩ := hc
      simp only [Set.mem_ofPred_eq, not_not] at hc1
      simp only [Set.mem_ofPred_eq, not_exists, not_lt] at hab
      obtain ⟨L, hL⟩ := hc1
      apply hx
      obtain ⟨M, hM⟩ := Metric.cauchySeq_iff.1 hL.cauchySeq (ε / 4) (by positivity)
      refine ⟨M, fun m hm n hn => ?_⟩
      have h1 := hM m hm n hn
      rw [dist_eq_norm] at h1
      have h2 := hab m
      have h3 := hab n
      rw [norm_sub_rev] at h3
      calc ‖a m x - a n x‖ = ‖(a m x - b m x) + (b m x - b n x) + (b n x - a n x)‖ := by
            ring_nf
        _ ≤ ‖a m x - b m x‖ + ‖b m x - b n x‖ + ‖b n x - a n x‖ := norm_add₃_le
        _ < ε := by linarith
    refine (measure_mono hsub).trans ((measure_union_le _ _).trans ?_)
    rw [ae_iff.1 hb, zero_add]
    exact hμ
  have hall : ∀ᵐ x ∂μ, ∀ k : ℕ, ∃ M, ∀ m ≥ M, ∀ n ≥ M,
      ‖a m x - a n x‖ < 1 / ((k : ℝ) + 1) :=
    ae_all_iff.2 fun k => hG _ (by positivity)
  filter_upwards [hall] with x hx
  have : CauchySeq (fun N => a N x) := Metric.cauchySeq_iff.2 fun ε hε => by
    obtain ⟨k, hk⟩ := exists_nat_one_div_lt hε
    obtain ⟨M, hM⟩ := hx k
    exact ⟨M, fun m hm n hn => by rw [dist_eq_norm]; exact (hM m hm n hn).trans hk⟩
  exact cauchySeq_tendsto_of_complete this

/-- Abstract `L^r` Cauchy criterion: a sequence uniformly approximable in `L^r` by
`L^r`-convergent sequences converges in `L^r`. -/
lemma Lr_tendsto_of_approx {r : ℝ≥0∞} [Fact (1 ≤ r)] {a : ℕ → X → ℂ}
    (ha : ∀ N, MemLp (a N) r μ)
    (h : ∀ ε : ℝ, 0 < ε → ∃ b : ℕ → X → ℂ, (∀ N, MemLp (b N) r μ) ∧
      (∃ G, MemLp G r μ ∧ Tendsto (fun N => eLpNorm (b N - G) r μ) atTop (𝓝 0)) ∧
      ∀ N, eLpNorm (a N - b N) r μ ≤ ENNReal.ofReal ε) :
    ∃ F, MemLp F r μ ∧ Tendsto (fun N => eLpNorm (a N - F) r μ) atTop (𝓝 0) := by
  set u : ℕ → Lp ℂ r μ := fun N => (ha N).toLp (a N)
  have hu : CauchySeq u := Metric.cauchySeq_iff.2 fun ε hε => by
    obtain ⟨b, hbm, ⟨G, hG, hbG⟩, hab⟩ := h (ε / 4) (by positivity)
    set v : ℕ → Lp ℂ r μ := fun N => (hbm N).toLp (b N)
    have hv : Tendsto v atTop (𝓝 (hG.toLp G)) :=
      (Lp.tendsto_Lp_iff_tendsto_eLpNorm'' b hbm G hG).2 hbG
    obtain ⟨M, hM⟩ := Metric.cauchySeq_iff.1 hv.cauchySeq (ε / 4) (by positivity)
    have hd : ∀ N, dist (u N) (v N) ≤ ε / 4 := fun N => by
      rw [dist_edist, Lp.edist_toLp_toLp]
      exact ENNReal.toReal_le_of_le_ofReal (by positivity) (hab N)
    refine ⟨M, fun m hm n hn => ?_⟩
    calc dist (u m) (u n) ≤ dist (u m) (v m) + dist (v m) (v n) + dist (v n) (u n) :=
          dist_triangle4 _ _ _ _
      _ < ε := by
          have := hd m; have := hd n; have := hM m hm n hn
          rw [dist_comm (v n)]
          linarith
  obtain ⟨w, hw⟩ := cauchySeq_tendsto_of_complete hu
  refine ⟨w, Lp.memLp w, ?_⟩
  rw [← Lp.toLp_coeFn w (Lp.memLp w)] at hw
  exact (Lp.tendsto_Lp_iff_tendsto_eLpNorm'' a ha _ _).1 hw

lemma tendsto_weak_bound {u : ℕ → ℝ≥0∞} (hu : Tendsto u atTop (𝓝 0)) {C e : ℝ≥0∞}
    (hC : C ≠ ⊤) (he : e ≠ 0) {R : ℝ} (hR : 0 < R) :
    Tendsto (fun k => 20 * (u k * C / e) ^ R) atTop (𝓝 0) := by
  have h1 : Tendsto (fun k => u k * C / e) atTop (𝓝 0) := by
    have := ENNReal.Tendsto.mul_const (b := e⁻¹) (ENNReal.Tendsto.mul_const hu (Or.inr hC))
      (Or.inr (ENNReal.inv_ne_top.2 he))
    simpa [div_eq_mul_inv] using this
  have h2 : Tendsto (fun k => (u k * C / e) ^ R) atTop (𝓝 0) := by
    have := ((ENNReal.continuous_rpow_const (y := R)).tendsto 0).comp h1
    rw [ENNReal.zero_rpow_of_pos hR] at this
    exact this
  have := ENNReal.Tendsto.const_mul h2 (Or.inr (by simp : (20 : ℝ≥0∞) ≠ ⊤))
  simpa using this

lemma memLp_bilinAvg {T S : X → X} (hT : MeasurePreserving T μ μ)
    (hS : MeasurePreserving S μ μ) {p q r : ℝ≥0∞} [ENNReal.HolderTriple p q r] (hr : 1 ≤ r)
    {f g : X → ℂ} (hf : MemLp f p μ) (hg : MemLp g q μ) (N : ℕ) :
    MemLp (bilinAvg T S f g N) r μ :=
  memLp_iff.2 ((eLpNorm_bilinAvg_le hT hS hr hf.aestronglyMeasurable hg.aestronglyMeasurable
    N).trans_lt (ENNReal.mul_lt_top hf.eLpNorm_lt_top hg.eLpNorm_lt_top))

/-- The hypothesis supplied by the bounded case (node T05). -/
def BoundedCaseConv {X : Type*} [MeasurableSpace X] (μ : Measure X) (T S : X → X) : Prop :=
  ∀ f g : X → ℂ, Measurable f → Measurable g → (∃ C, ∀ x, ‖f x‖ ≤ C) →
    (∃ C, ∀ x, ‖g x‖ ≤ C) →
    (∀ᵐ x ∂μ, ∃ L, Tendsto (fun N => bilinAvg T S f g N x) atTop (𝓝 L)) ∧
    ∀ r : ℝ, 1 ≤ r → ∃ F, MemLp F (ENNReal.ofReal r) μ ∧
      Tendsto (fun N => eLpNorm (bilinAvg T S f g N - F) (ENNReal.ofReal r) μ) atTop (𝓝 0)

lemma bilinAvg_zero_N (T S : X → X) (f g : X → ℂ) (x : X) : bilinAvg T S f g 0 x = 0 := by
  simp [bilinAvg]

/-- T08, almost-everywhere part, when `p⁻¹ + q⁻¹ > 0`. -/
lemma T08_ae_of_pos [IsProbabilityMeasure μ] {T S : X → X} (hT : MeasurePreserving T μ μ)
    (hS : MeasurePreserving S μ μ) (hbdd : BoundedCaseConv μ T S) {p q : ℝ≥0∞} (hp : 1 ≤ p)
    (hq : 1 ≤ q) (hpq : p⁻¹ + q⁻¹ ≤ 1) (hpos : 0 < p⁻¹ + q⁻¹) {f g : X → ℂ}
    (hf : MemLp f p μ) (hg : MemLp g q μ) :
    ∀ᵐ x ∂μ, ∃ L, Tendsto (fun N => bilinAvg T S f g N x) atTop (𝓝 L) := by
  set r := (p⁻¹ + q⁻¹)⁻¹
  have hr : r⁻¹ = p⁻¹ + q⁻¹ := inv_inv _
  have hr0 : 0 < r⁻¹ := by rw [hr]; exact hpos
  have hrt : r ≠ ⊤ := by intro h; rw [h] at hr0; simp at hr0
  have hr00 : r ≠ 0 := by
    intro h; rw [h, ENNReal.inv_zero] at hr; rw [← hr] at hpq; simp at hpq
  have hR : 0 < r.toReal := ENNReal.toReal_pos hr00 hrt
  obtain ⟨fs, hfm, hfb, hfmem, hft, hfn⟩ := exists_bdd_approx_seq hp hf
  obtain ⟨gs, hgm, hgb, hgmem, hgt, -⟩ := exists_bdd_approx_seq hq hg
  apply ae_tendsto_of_approx
  intro ε hε δ hδ
  set e := ENNReal.ofReal (ε / 2)
  have he : e ≠ 0 := (ENNReal.ofReal_pos.2 (by positivity)).ne'
  have hΦ : Tendsto (fun k => 20 * (eLpNorm (f - fs k) p μ * eLpNorm g q μ / e) ^ r.toReal +
      20 * (eLpNorm (g - gs k) q μ * (eLpNorm f p μ + 1) / e) ^ r.toReal) atTop (𝓝 0) := by
    have := (tendsto_weak_bound hft hg.eLpNorm_lt_top.ne he hR).add
      (tendsto_weak_bound hgt (ENNReal.add_ne_top.2 ⟨hf.eLpNorm_lt_top.ne, ENNReal.one_ne_top⟩)
        he hR)
    simpa using this
  obtain ⟨k, hk⟩ := ((tendsto_order.1 hΦ).2 δ hδ).exists
  refine ⟨bilinAvg T S (fs k) (gs k), (hbdd _ _ (hfm k) (hgm k) (hfb k) (hgb k)).1, ?_⟩
  have hsub : {x | ∃ N, ε < ‖bilinAvg T S f g N x - bilinAvg T S (fs k) (gs k) N x‖} ⊆
      {x | ∃ N : ℕ, 1 ≤ N ∧ ε / 2 < ‖bilinAvg T S (f - fs k) g N x‖} ∪
      {x | ∃ N : ℕ, 1 ≤ N ∧ ε / 2 < ‖bilinAvg T S (fs k) (g - gs k) N x‖} := by
    intro x hx
    obtain ⟨N, hN⟩ := hx
    rcases Nat.eq_zero_or_pos N with rfl | hNpos
    · simp [bilinAvg_zero_N] at hN; linarith
    have hdec := congrFun (bilinAvg_sub_decomp T S f (fs k) g (gs k) N) x
    simp only [Pi.sub_apply, Pi.add_apply] at hdec
    rw [hdec] at hN
    have := norm_add_le (bilinAvg T S (f - fs k) g N x) (bilinAvg T S (fs k) (g - gs k) N x)
    by_contra hc
    simp only [Set.mem_union, Set.mem_ofPred_eq, not_or, not_exists, not_and, not_lt] at hc
    have h1 := hc.1 N hNpos
    have h2 := hc.2 N hNpos
    linarith
  refine (measure_mono hsub).trans ((measure_union_le _ _).trans ?_)
  have hb1 := bilinear_ergodic_weak_maximal hT hS hp hq hpq hr hr0 (hf.sub (hfmem k)) hg
    (t := ε / 2) (by positivity)
  have hb2 := bilinear_ergodic_weak_maximal hT hS hp hq hpq hr hr0 (hfmem k) (hg.sub (hgmem k))
    (t := ε / 2) (by positivity)
  have hb2' : μ {x | ∃ N : ℕ, 1 ≤ N ∧ ε / 2 < ‖bilinAvg T S (fs k) (g - gs k) N x‖} ≤
      20 * (eLpNorm (g - gs k) q μ * (eLpNorm f p μ + 1) / e) ^ r.toReal := by
    refine hb2.trans ?_
    rw [mul_comm (eLpNorm (fs k) p μ)]
    gcongr
    exact hfn k
  exact (add_le_add hb1 hb2').trans hk.le

/-- T08, `L^r` part, when `r⁻¹ = p⁻¹ + q⁻¹ > 0`. -/
lemma T08_Lr_of_pos [IsProbabilityMeasure μ] {T S : X → X} (hT : MeasurePreserving T μ μ)
    (hS : MeasurePreserving S μ μ) (hbdd : BoundedCaseConv μ T S) {p q : ℝ≥0∞} (hp : 1 ≤ p)
    (hq : 1 ≤ q) (hpq : p⁻¹ + q⁻¹ ≤ 1) (hpos : 0 < p⁻¹ + q⁻¹) {f g : X → ℂ}
    (hf : MemLp f p μ) (hg : MemLp g q μ) :
    ∃ F, MemLp F (p⁻¹ + q⁻¹)⁻¹ μ ∧
      Tendsto (fun N => eLpNorm (bilinAvg T S f g N - F) (p⁻¹ + q⁻¹)⁻¹ μ) atTop (𝓝 0) := by
  set r := (p⁻¹ + q⁻¹)⁻¹
  have hr : r⁻¹ = p⁻¹ + q⁻¹ := inv_inv _
  have hr0 : 0 < r⁻¹ := by rw [hr]; exact hpos
  have hrt : r ≠ ⊤ := by intro h; rw [h] at hr0; simp at hr0
  have hr1 : 1 ≤ r := by rw [← ENNReal.inv_le_one, hr]; exact hpq
  have hR1 : 1 ≤ r.toReal := one_le_toReal_of_one_le hr1 hrt
  haveI : Fact (1 ≤ r) := ⟨hr1⟩
  haveI : ENNReal.HolderTriple p q r := ⟨hr.symm⟩
  obtain ⟨fs, hfm, hfb, hfmem, hft, hfn⟩ := exists_bdd_approx_seq hp hf
  obtain ⟨gs, hgm, hgb, hgmem, hgt, -⟩ := exists_bdd_approx_seq hq hg
  apply Lr_tendsto_of_approx (memLp_bilinAvg hT hS hr1 hf hg)
  intro ε hε
  have hΨ : Tendsto (fun k => eLpNorm (f - fs k) p μ * eLpNorm g q μ +
      (eLpNorm f p μ + 1) * eLpNorm (g - gs k) q μ) atTop (𝓝 0) := by
    have := (ENNReal.Tendsto.mul_const hft (Or.inr hg.eLpNorm_lt_top.ne)).add
      (ENNReal.Tendsto.const_mul hgt
        (Or.inr (ENNReal.add_ne_top.2 ⟨hf.eLpNorm_lt_top.ne, ENNReal.one_ne_top⟩)))
    simpa using this
  obtain ⟨k, hk⟩ := ((tendsto_order.1 hΨ).2 (ENNReal.ofReal ε) (ENNReal.ofReal_pos.2 hε)).exists
  refine ⟨fun N => bilinAvg T S (fs k) (gs k) N,
    memLp_bilinAvg hT hS hr1 (hfmem k) (hgmem k), ?_, fun N => ?_⟩
  · obtain ⟨F, hF, hFt⟩ := (hbdd _ _ (hfm k) (hgm k) (hfb k) (hgb k)).2 r.toReal hR1
    rw [ENNReal.ofReal_toReal hrt] at hF hFt
    exact ⟨F, hF, hFt⟩
  · rw [bilinAvg_sub_decomp]
    refine (eLpNorm_add_le hr1).trans (le_trans ?_ hk.le)
    refine add_le_add (eLpNorm_bilinAvg_le (p := p) (q := q) hT hS hr1
      (hf.sub (hfmem k)).aestronglyMeasurable hg.aestronglyMeasurable N)
      ((eLpNorm_bilinAvg_le (p := p) (q := q) hT hS hr1 (hfmem k).aestronglyMeasurable
        (hg.sub (hgmem k)).aestronglyMeasurable N).trans ?_)
    gcongr
    exact hfn k

/-- T08 for `p = q = ∞`: pass to bounded measurable representatives. -/
lemma T08_top_top {T S : X → X} (hT : MeasurePreserving T μ μ)
    (hS : MeasurePreserving S μ μ) (hbdd : BoundedCaseConv μ T S) {f g : X → ℂ}
    (hf : MemLp f ⊤ μ) (hg : MemLp g ⊤ μ) :
    (∀ᵐ x ∂μ, ∃ L, Tendsto (fun N => bilinAvg T S f g N x) atTop (𝓝 L)) ∧
    ∀ r : ℝ, 1 ≤ r → ∃ F, MemLp F (ENNReal.ofReal r) μ ∧
      Tendsto (fun N => eLpNorm (bilinAvg T S f g N - F) (ENNReal.ofReal r) μ) atTop (𝓝 0) := by
  obtain ⟨f', hf'm, hf'b, hff'⟩ := exists_bdd_rep_of_memLp_top hf
  obtain ⟨g', hg'm, hg'b, hgg'⟩ := exists_bdd_rep_of_memLp_top hg
  have hae := bilinAvg_ae_congr hT hS hff' hgg'
  obtain ⟨h1, h2⟩ := hbdd f' g' hf'm hg'm hf'b hg'b
  refine ⟨?_, fun r hr => ?_⟩
  · filter_upwards [hae, h1] with x hx hL
    obtain ⟨L, hL⟩ := hL
    refine ⟨L, ?_⟩
    have : (fun N => bilinAvg T S f g N x) = fun N => bilinAvg T S f' g' N x := funext hx
    rw [this]; exact hL
  · obtain ⟨F, hF, hFt⟩ := h2 r hr
    refine ⟨F, hF, hFt.congr fun N => ?_⟩
    refine eLpNorm_congr_ae ?_
    filter_upwards [hae] with x hx
    simp [hx N]

end T08

section T08Final

universe u

/-- **Theorem 10.3 (node T08), reduction to bounded inputs.** Let `T, S` be commuting
measurable probability-preserving maps of a probability space, and assume the bounded-input
statement (node T05) `hbdd` for this pair. Then for `1 ≤ p, q ≤ ∞` with `p⁻¹ + q⁻¹ ≤ 1`,
`f ∈ L^p`, `g ∈ L^q`:
(a) the averages `A_N(f,g)` converge almost everywhere;
(b) if `r⁻¹ = p⁻¹ + q⁻¹ > 0`, they converge in `L^r`;
(c) if `p = q = ∞`, they converge in every finite `L^r`, `1 ≤ r < ∞`.
The commutation hypothesis is only used through `hbdd`. -/
theorem commuting_ergodic_averages_converge_of_bounded {X : Type u} [MeasurableSpace X]
    {μ : Measure X} [IsProbabilityMeasure μ] {T S : X → X} (hT : MeasurePreserving T μ μ)
    (hS : MeasurePreserving S μ μ) (_hTS : T ∘ S = S ∘ T)
    (hbdd : ∀ f g : X → ℂ, Measurable f → Measurable g → (∃ C, ∀ x, ‖f x‖ ≤ C) →
      (∃ C, ∀ x, ‖g x‖ ≤ C) →
      (∀ᵐ x ∂μ, ∃ L, Tendsto (fun N => bilinAvg T S f g N x) atTop (𝓝 L)) ∧
      ∀ r : ℝ, 1 ≤ r → ∃ F, MemLp F (ENNReal.ofReal r) μ ∧
        Tendsto (fun N => eLpNorm (bilinAvg T S f g N - F) (ENNReal.ofReal r) μ) atTop (𝓝 0))
    {p q : ℝ≥0∞} (hp : 1 ≤ p) (hq : 1 ≤ q) (hpq : p⁻¹ + q⁻¹ ≤ 1) {f g : X → ℂ}
    (hf : MemLp f p μ) (hg : MemLp g q μ) :
    (∀ᵐ x ∂μ, ∃ L, Tendsto (fun N => bilinAvg T S f g N x) atTop (𝓝 L)) ∧
    (0 < p⁻¹ + q⁻¹ → ∃ F, MemLp F (p⁻¹ + q⁻¹)⁻¹ μ ∧
      Tendsto (fun N => eLpNorm (bilinAvg T S f g N - F) (p⁻¹ + q⁻¹)⁻¹ μ) atTop (𝓝 0)) ∧
    (p = ⊤ → q = ⊤ → ∀ r : ℝ, 1 ≤ r → ∃ F, MemLp F (ENNReal.ofReal r) μ ∧
      Tendsto (fun N => eLpNorm (bilinAvg T S f g N - F) (ENNReal.ofReal r) μ) atTop (𝓝 0)) := by
  have hB : BoundedCaseConv μ T S := hbdd
  refine ⟨?_, fun hpos => T08_Lr_of_pos hT hS hB hp hq hpq hpos hf hg, ?_⟩
  · by_cases hpos : 0 < p⁻¹ + q⁻¹
    · exact T08_ae_of_pos hT hS hB hp hq hpq hpos hf hg
    · have h0 : p⁻¹ + q⁻¹ = 0 := by simpa using hpos
      rw [add_eq_zero, ENNReal.inv_eq_zero, ENNReal.inv_eq_zero] at h0
      obtain ⟨rfl, rfl⟩ := h0
      exact (T08_top_top hT hS hB hf hg).1
  · rintro rfl rfl
    exact (T08_top_top hT hS hB hf hg).2

/-- The statement of the bounded-input theorem (node T05) for all probability spaces in
`Type u`: commuting measurable probability-preserving maps and bounded measurable inputs have
averages converging almost everywhere and in every finite `L^r`. -/
def BoundedCaseTheorem : Prop :=
  ∀ (X : Type u) [MeasurableSpace X] (μ : Measure X) [IsProbabilityMeasure μ] (T S : X → X),
    MeasurePreserving T μ μ → MeasurePreserving S μ μ → T ∘ S = S ∘ T →
    BoundedCaseConv μ T S

/-- **Theorem 10.3 (node T08), final convergence theorem**, packaged: given the bounded-input
theorem (node T05) `H`, for commuting measurable probability-preserving `T, S` on an arbitrary
probability space and `f ∈ L^p`, `g ∈ L^q` with `1 ≤ p, q ≤ ∞`, `p⁻¹ + q⁻¹ ≤ 1`, the averages
converge almost everywhere, in `L^r` for `r⁻¹ = p⁻¹ + q⁻¹ > 0`, and in every finite `L^r` when
`p = q = ∞`. No ergodicity or invertibility is assumed. -/
theorem commuting_ergodic_averages_converge (H : BoundedCaseTheorem.{u}) {X : Type u}
    [MeasurableSpace X] {μ : Measure X} [IsProbabilityMeasure μ] {T S : X → X}
    (hT : MeasurePreserving T μ μ) (hS : MeasurePreserving S μ μ) (hTS : T ∘ S = S ∘ T)
    {p q : ℝ≥0∞} (hp : 1 ≤ p) (hq : 1 ≤ q) (hpq : p⁻¹ + q⁻¹ ≤ 1) {f g : X → ℂ}
    (hf : MemLp f p μ) (hg : MemLp g q μ) :
    (∀ᵐ x ∂μ, ∃ L, Tendsto (fun N => bilinAvg T S f g N x) atTop (𝓝 L)) ∧
    (0 < p⁻¹ + q⁻¹ → ∃ F, MemLp F (p⁻¹ + q⁻¹)⁻¹ μ ∧
      Tendsto (fun N => eLpNorm (bilinAvg T S f g N - F) (p⁻¹ + q⁻¹)⁻¹ μ) atTop (𝓝 0)) ∧
    (p = ⊤ → q = ⊤ → ∀ r : ℝ, 1 ≤ r → ∃ F, MemLp F (ENNReal.ofReal r) μ ∧
      Tendsto (fun N => eLpNorm (bilinAvg T S f g N - F) (ENNReal.ofReal r) μ) atTop (𝓝 0)) :=
  commuting_ergodic_averages_converge_of_bounded hT hS hTS (H X μ T S hT hS hTS) hp hq hpq hf hg

end T08Final


section MainTheorem

universe u

/-- Theorem 9.4 (node T05) in the packaged form `BoundedCaseTheorem`. -/
theorem bounded_case_theorem : BoundedCaseTheorem.{u} :=
  fun X _ μ _ T S hT hS hTS f g hf hg hfb hgb => by
    obtain ⟨h1, F, -, h3⟩ := bounded_commuting_averages_ae μ T S hT hS hTS f g hf hg hfb hgb
    exact ⟨h1, fun r hr => ⟨F, h3 r hr⟩⟩

/-- **Theorem 10.3 (node T08), final convergence theorem.** Let `T, S` be commuting measurable
probability-preserving transformations of an arbitrary probability space `(X, μ)`. For every
`f ∈ L^p`, `g ∈ L^q` with `1 ≤ p, q ≤ ∞` and `1/p + 1/q ≤ 1`, the averages
`A_N(f,g)(x) = N⁻¹ ∑_{n<N} f(Tⁿx) g(Sⁿx)` converge to a finite limit almost everywhere. If
`1/r = 1/p + 1/q > 0`, convergence also holds in `L^r`; for `p = q = ∞`, convergence holds in
every finite `L^r`. Neither ergodicity nor invertibility is assumed. -/
theorem commuting_ergodic_averages_converge_main {X : Type u} [MeasurableSpace X]
    {μ : Measure X} [IsProbabilityMeasure μ] {T S : X → X}
    (hT : MeasurePreserving T μ μ) (hS : MeasurePreserving S μ μ) (hTS : T ∘ S = S ∘ T)
    {p q : ℝ≥0∞} (hp : 1 ≤ p) (hq : 1 ≤ q) (hpq : p⁻¹ + q⁻¹ ≤ 1) {f g : X → ℂ}
    (hf : MemLp f p μ) (hg : MemLp g q μ) :
    (∀ᵐ x ∂μ, ∃ L, Tendsto (fun N => bilinAvg T S f g N x) atTop (𝓝 L)) ∧
    (0 < p⁻¹ + q⁻¹ → ∃ F, MemLp F (p⁻¹ + q⁻¹)⁻¹ μ ∧
      Tendsto (fun N => eLpNorm (bilinAvg T S f g N - F) (p⁻¹ + q⁻¹)⁻¹ μ) atTop (𝓝 0)) ∧
    (p = ⊤ → q = ⊤ → ∀ r : ℝ, 1 ≤ r → ∃ F, MemLp F (ENNReal.ofReal r) μ ∧
      Tendsto (fun N => eLpNorm (bilinAvg T S f g N - F) (ENNReal.ofReal r) μ) atTop (𝓝 0)) :=
  commuting_ergodic_averages_converge bounded_case_theorem hT hS hTS hp hq hpq hf hg

end MainTheorem


end

end Auto
