/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib

/-!
# Elementary analytic preparation

This file was automatically generated by Claude.

Formalization of §2 ("Elementary analytic preparation", nodes A01–A07) of
`blueprint/commuting_ergodic_blueprint.tex`: differentiation under the integral,
Gaussian calculus, finite measurable choices, lattice sampling, norming tests,
the integrable-kernel bilinear bound, and uniqueness of compact Borel measures.
-/

@[expose] public section

namespace Auto

end Auto
