/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib
public import TwoCommuting.Auto.Sec2ElementaryPreparation
public import TwoCommuting.Auto.Sec3MatrixInequalities
public import TwoCommuting.Auto.Sec4GaussianEnergies
public import TwoCommuting.Auto.Sec5OutputDependentIntervals

/-!
# Euclidean counting and a Cauchy criterion

This file was automatically generated by Claude.

Formalization of §6 ("Euclidean counting and a Cauchy criterion", nodes E01–E02) of
`blueprint/commuting_ergodic_blueprint.tex`.

## Contents

* §6 setup: the interval kernels `K^{(m)}_{u,v}` (`Kern`) are continuous, bounded and
  integrable with `‖K^{(m)}_{u,v}‖₁ ≤ ‖g_c^{(m)}‖₁ log(v/u)` (`integrable_Kern`).
* E01 (`Euclidean_counting_bound`): the counting estimate
  `‖S_n^{(m)}(F,G)‖_{3/2} ≤ C √n ‖F‖₃ ‖G‖₃`. The proof passes Lemma 5.3 (node D03) to the
  continuum on sampled arrays (`tri_lattice_bound`, `tri_rect_bound`, node A04), extends to
  measurable finite-menu choices (`tri_meas_bound`, node A03), rewrites the trilinear form as a
  pairing with the bilinear outputs (`integral_triInt_eq`), selects phases and maximizing lists
  measurably (`Sfin_pairing`), applies the norming test A05 (`Sfin_Cc_bound`), passes to `L³`
  inputs by density (`Sfin_bound`, node A06) and to all rational interval lists by monotone
  convergence.
* E02 (`square_root_counting_implies_ae_Cauchy`): square-root counting implies almost
  everywhere convergence.
-/

@[expose] public section

open scoped ENNReal NNReal
open MeasureTheory Filter Topology Real

namespace Auto

noncomputable section

/-! ### The interval kernels -/

section Kernels

/-- The scale integrand `s^{m/2} g_{cs}^{(m)}(t) / s` of the interval kernels. -/
def kernIntegrand (m : ℕ) (s t : ℝ) : ℝ := √s ^ m * gaussianD m (63 / 20 * s) t / s

lemma Kern_eq (m : ℕ) (a b t : ℝ) : Kern m a b t = ∫ s in a..b, kernIntegrand m s t := rfl

lemma continuousOn_kernIntegrand_joint (m : ℕ) :
    ContinuousOn (fun z : ℝ × ℝ => kernIntegrand m z.1 z.2) {z | 0 < z.1} := by
  have hg : ContinuousOn (fun z : ℝ × ℝ => gaussianD m (63 / 20 * z.1) z.2) {z | 0 < z.1} :=
    (continuousOn_gaussianD_joint m).comp ((continuous_const.mul continuous_fst).prodMk
      continuous_snd).continuousOn fun z hz => by
        simp only [Set.mem_ofPred_eq] at hz ⊢; exact mul_pos (by norm_num) hz
  exact (((Real.continuous_sqrt.comp continuous_fst).pow m).continuousOn.mul hg).div
    continuous_fst.continuousOn fun z hz => ne_of_gt hz

/-- The interval kernels are continuous in the spatial variable. -/
lemma continuous_Kern (m : ℕ) {a b : ℝ} (ha : 0 < a) (hab : a ≤ b) : Continuous (Kern m a b) := by
  have e : Kern m a b = fun t => ∫ s in a..b, kernIntegrand m (max a s) t := by
    funext t
    rw [Kern_eq]
    refine intervalIntegral.integral_congr fun s hs => ?_
    rw [Set.uIcc_of_le hab] at hs
    simp [max_eq_right hs.1]
  rw [e]
  have hc : Continuous fun z : ℝ × ℝ => kernIntegrand m (max a z.2) z.1 :=
    (continuousOn_kernIntegrand_joint m).comp_continuous
      ((continuous_const.max continuous_snd).prodMk continuous_fst)
      fun z => lt_of_lt_of_le ha (le_max_left _ _)
  exact intervalIntegral.continuous_parametric_intervalIntegral_of_continuous' (μ := volume)
    (f := fun t s => kernIntegrand m (max a s) t) hc a b

/-- A uniform bound for the scale integrand: `|s^{m/2} g_{cs}^{(m)}(t)/s| ≤ C s^{-3/2}`. -/
lemma abs_kernIntegrand_le (m : ℕ) : ∃ C : ℝ, 0 ≤ C ∧ ∀ s, 0 < s → ∀ t,
    |kernIntegrand m s t| ≤ C / (s * √s) := by
  obtain ⟨M, hM⟩ := abs_gaussianD_le_const m (σ := 63 / 20) (by norm_num)
  have hM0 : 0 ≤ M := (abs_nonneg _).trans (hM 0)
  refine ⟨M, hM0, fun s hs t => ?_⟩
  have hss : 0 < √s := Real.sqrt_pos.2 hs
  unfold kernIntegrand
  rw [gaussianD_scale m (by norm_num) hs]
  rw [abs_div, abs_mul, abs_mul, abs_of_pos hs, abs_of_pos (by positivity : (0 : ℝ) < √s ^ m),
    abs_of_pos (by positivity : (0 : ℝ) < (√s)⁻¹ ^ (m + 1))]
  have h1 := hM ((√s)⁻¹ * t)
  have e : √s ^ m * ((√s)⁻¹ ^ (m + 1) * |gaussianD m (63 / 20) ((√s)⁻¹ * t)|) / s =
      |gaussianD m (63 / 20) ((√s)⁻¹ * t)| / (s * √s) := by
    rw [inv_pow, pow_succ]
    field_simp
  rw [e]
  gcongr

/-- The interval kernels are bounded. -/
lemma abs_Kern_le (m : ℕ) {a b : ℝ} (ha : 0 < a) (hab : a ≤ b) :
    ∃ C : ℝ, ∀ t, |Kern m a b t| ≤ C := by
  obtain ⟨C, hC, h⟩ := abs_kernIntegrand_le m
  refine ⟨C / (a * √a) * (b - a), fun t => ?_⟩
  rw [Kern_eq]
  have := intervalIntegral.norm_integral_le_of_norm_le_const (a := a) (b := b)
    (f := fun s => kernIntegrand m s t) (C := C / (a * √a)) ?_
  · rw [Real.norm_eq_abs, abs_of_nonneg (sub_nonneg.2 hab)] at this
    exact this
  intro s hs
  rw [Set.uIoc_of_le hab] at hs
  have hs0 : 0 < s := ha.trans hs.1
  rw [Real.norm_eq_abs]
  refine (h s hs0 t).trans ?_
  have : a * √a ≤ s * √s := mul_le_mul hs.1.le (Real.sqrt_le_sqrt hs.1.le) (Real.sqrt_nonneg _)
    hs0.le
  exact div_le_div_of_nonneg_left hC (by positivity) this

/-- The `L¹` mass of the scale integrand at scale `s`: `∫ |κ_s(t)/s| dt = ‖g_c^{(m)}‖₁ / s`. -/
lemma integral_abs_kernIntegrand (m : ℕ) {s : ℝ} (hs : 0 < s) :
    ∫ t, |kernIntegrand m s t| = (∫ t, |gaussianD m (63 / 20) t|) / s := by
  have e : (fun t => |kernIntegrand m s t|) =
      fun t => s⁻¹ * |(√s) ^ m * gaussianD m (63 / 20 * s) t| := by
    funext t
    unfold kernIntegrand
    rw [abs_div, abs_of_pos hs, div_eq_inv_mul]
  rw [e, integral_const_mul, integral_abs_gaussianD_scale m (by norm_num) hs]
  field_simp

lemma integrable_kernIntegrand (m : ℕ) {s : ℝ} (hs : 0 < s) :
    Integrable (kernIntegrand m s) := by
  have : kernIntegrand m s = fun t => (√s ^ m / s) * gaussianD m (63 / 20 * s) t := by
    funext t; unfold kernIntegrand; ring
  rw [this]
  exact (integrable_gaussianD m (by positivity)).const_mul _

/-- **§6 setup:** the interval kernels are integrable, with
`‖K^{(m)}_{a,b}‖₁ ≤ ‖g_c^{(m)}‖₁ log(b/a)`. -/
theorem integrable_Kern (m : ℕ) {a b : ℝ} (ha : 0 < a) (hab : a ≤ b) :
    Integrable (Kern m a b) ∧
      ∫ t, |Kern m a b t| ≤ (∫ t, |gaussianD m (63 / 20) t|) * Real.log (b / a) := by
  set μ : Measure ℝ := volume.restrict (Set.Ioc a b)
  set f : ℝ × ℝ → ℝ := fun z => kernIntegrand m z.1 z.2
  have hcont : ContinuousOn f (Set.Ioc a b ×ˢ Set.univ) :=
    (continuousOn_kernIntegrand_joint m).mono fun z hz => ha.trans hz.1.1
  have hmeas : AEStronglyMeasurable f (μ.prod volume) := by
    have hμ : μ.prod (volume : Measure ℝ) =
        ((volume : Measure ℝ).prod volume).restrict (Set.Ioc a b ×ˢ Set.univ) := by
      rw [← Measure.prod_restrict, Measure.restrict_univ]
    rw [hμ]
    exact hcont.aestronglyMeasurable (measurableSet_Ioc.prod MeasurableSet.univ)
  set c := ∫ t, |gaussianD m (63 / 20) t|
  have hinner : ∀ s ∈ Set.Ioc a b, ∫ t, ‖f (s, t)‖ = c / s := fun s hs => by
    simp only [f, Real.norm_eq_abs]
    exact integral_abs_kernIntegrand m (ha.trans hs.1)
  have hint : Integrable f (μ.prod volume) := by
    rw [integrable_prod_iff hmeas]
    refine ⟨?_, ?_⟩
    · refine (ae_restrict_iff' measurableSet_Ioc).2 (Eventually.of_forall fun s hs => ?_)
      exact integrable_kernIntegrand m (ha.trans hs.1)
    · refine (integrableOn_congr_fun (fun s hs => (hinner s hs).symm) measurableSet_Ioc).1 ?_
      refine ContinuousOn.integrableOn_Icc (f := fun s => c / s) ?_ |>.mono_set
        Set.Ioc_subset_Icc_self
      exact continuousOn_const.div continuousOn_id fun s hs => (ha.trans_le hs.1).ne'
  have hK : Kern m a b = fun t => ∫ s, f (s, t) ∂μ := by
    funext t
    rw [Kern_eq, intervalIntegral.integral_of_le hab]
  refine ⟨hK ▸ hint.integral_prod_right, ?_⟩
  -- the norm bound
  have h1 : ∀ t, |Kern m a b t| ≤ ∫ s, |f (s, t)| ∂μ := fun t => by
    rw [hK]; exact abs_integral_le_integral_abs
  have hswap : Integrable (fun t => ∫ s, |f (s, t)| ∂μ) := hint.norm.integral_prod_right
  have hswap' : ∫ t, ∫ s, |f (s, t)| ∂μ = ∫ s, (∫ t, |f (s, t)|) ∂μ := by
    have h1 := integral_prod (fun z => ‖f z‖) hint.norm
    have h2 := integral_prod_symm (fun z => ‖f z‖) hint.norm
    simp only [Real.norm_eq_abs] at h1 h2
    rw [← h1, h2]
  calc ∫ t, |Kern m a b t| ≤ ∫ t, ∫ s, |f (s, t)| ∂μ :=
        integral_mono (hK ▸ hint.integral_prod_right).abs hswap h1
    _ = ∫ s, (∫ t, |f (s, t)|) ∂μ := hswap'
    _ = ∫ s in Set.Ioc a b, c / s := by
        refine setIntegral_congr_fun measurableSet_Ioc fun s hs => ?_
        simpa [Real.norm_eq_abs] using hinner s hs
    _ = c * Real.log (b / a) := by
        rw [← intervalIntegral.integral_of_le hab]
        simp only [div_eq_mul_inv c]
        rw [intervalIntegral.integral_const_mul, integral_inv_of_pos ha (ha.trans_le hab)]

end Kernels

/-! ### The trilinear form on the mesh -/

section Lattice

variable {n : ℕ} {sm sp : ℝ}

/-- The kernel `∑_ℓ η_ℓ K^{(m)}_{a_ℓ,b_ℓ}` of an interval list with coefficients. -/
def ilKern (m : ℕ) (L : IntervalList n sm sp) (t : ℝ) : ℂ :=
  ∑ ℓ ∈ Finset.range L.len, L.c ℓ * (Kern m (L.a ℓ) (L.b ℓ) t : ℂ)

lemma continuous_ilKern (m : ℕ) (hsm : 0 < sm) (L : IntervalList n sm sp) :
    Continuous (ilKern m L) := by
  refine continuous_finsetSum _ fun ℓ hℓ => continuous_const.mul ?_
  have hℓ' := Finset.mem_range.1 hℓ
  exact Complex.continuous_ofReal.comp (continuous_Kern m (hsm.trans_le (L.range ℓ hℓ').1)
    (L.lt ℓ hℓ').le)

lemma ilKern_bdd (m : ℕ) (hsm : 0 < sm) (L : IntervalList n sm sp) :
    ∃ C, ∀ t, ‖ilKern m L t‖ ≤ C := by
  have : ∀ ℓ ∈ Finset.range L.len, ∃ C, ∀ t, ‖L.c ℓ * (Kern m (L.a ℓ) (L.b ℓ) t : ℂ)‖ ≤ C := by
    intro ℓ hℓ
    have hℓ' := Finset.mem_range.1 hℓ
    obtain ⟨C, hC⟩ := abs_Kern_le m (hsm.trans_le (L.range ℓ hℓ').1) (L.lt ℓ hℓ').le
    refine ⟨C, fun t => ?_⟩
    rw [norm_mul, Complex.norm_real, Real.norm_eq_abs]
    calc ‖L.c ℓ‖ * |Kern m (L.a ℓ) (L.b ℓ) t| ≤ 1 * |Kern m (L.a ℓ) (L.b ℓ) t| :=
          mul_le_mul_of_nonneg_right (L.norm_c ℓ) (abs_nonneg _)
      _ ≤ C := by rw [one_mul]; exact hC t
  choose! C hC using this
  exact ⟨∑ ℓ ∈ Finset.range L.len, C ℓ, fun t =>
    (norm_sum_le _ _).trans (Finset.sum_le_sum fun ℓ hℓ => hC ℓ hℓ t)⟩

lemma integrable_ilKern (m : ℕ) (hsm : 0 < sm) (L : IntervalList n sm sp) :
    Integrable (ilKern m L) := by
  refine integrable_finsetSum _ fun ℓ hℓ => Integrable.const_mul ?_ _
  have hℓ' := Finset.mem_range.1 hℓ
  exact (integrable_Kern m (hsm.trans_le (L.range ℓ hℓ').1) (L.lt ℓ hℓ').le).1.ofReal

/-- The integrand of the continuum trilinear form, in the coordinates `x = (x, y, t)`:
`H(x,y) F(x+t,y) G(x,y+t) ∑_ℓ η_ℓ K_ℓ(t)` with the interval list chosen at `(x,y)`. -/
def triInt (m : ℕ) {κ : Type*} (L : κ → IntervalList n sm sp) (c : ℝ × ℝ → κ)
    (H F G : ℝ × ℝ → ℂ) (x : Fin 3 → ℝ) : ℂ :=
  H (x 0, x 1) * F (x 0 + x 2, x 1) * G (x 0, x 1 + x 2) * ilKern m (L (c (x 0, x 1))) (x 2)

lemma exists_fin_shift {R : ℕ} {w : ℤ} (h : |w| ≤ R) : ∃ i : Fin (2 * R + 1), (i : ℤ) - R = w := by
  have h1 := neg_abs_le w
  have h2 := le_abs_self w
  refine ⟨⟨(w + R).toNat, by omega⟩, ?_⟩
  show (((w + R).toNat : ℕ) : ℤ) - R = w
  omega

/-- A finite sum over an injective parametrization of the support is the lattice sum. -/
lemma sum_eq_tsum_of_injective {T E : Type*} [Fintype T] [NormedAddCommGroup E] {d : ℕ}
    (e : T → (Fin d → ℤ)) (he : Function.Injective e) (f : (Fin d → ℤ) → E)
    (hs : ∀ z, f z ≠ 0 → z ∈ Set.range e) : ∑ t, f (e t) = ∑' z, f z := by
  rw [← he.tsum_eq (fun z hz => hs z hz), tsum_fintype]

lemma abs_le_of_norm_le {p : ℝ × ℝ} {ρ : ℝ} (h : ‖p‖ ≤ ρ) : |p.1| ≤ ρ ∧ |p.2| ≤ ρ := by
  rw [Prod.norm_def, max_le_iff] at h
  exact ⟨h.1, h.2⟩

lemma int_abs_le_of {N : ℕ} (hN : 0 < N) {w : ℤ} {r : ℝ} (h : |(w : ℝ) / N| ≤ r) :
    (|w| : ℝ) ≤ r * N := by
  have hN' : (0 : ℝ) < N := by exact_mod_cast hN
  rw [abs_div, abs_of_pos hN', div_le_iff₀ hN'] at h
  exact_mod_cast h

end Lattice

section LatticeBound

variable {n : ℕ} {sm sp : ℝ}

lemma norm_le_of_ne_zero {Φ : ℝ × ℝ → ℂ} {ρ : ℝ} (hΦ : ∀ p, ρ < ‖p‖ → Φ p = 0) {p : ℝ × ℝ}
    (hp : Φ p ≠ 0) : ‖p‖ ≤ ρ :=
  not_lt.1 fun h => hp (hΦ p h)

lemma int_bounds_of_ne_zero {Φ : ℝ × ℝ → ℂ} {ρ : ℝ} (hΦ : ∀ p, ρ < ‖p‖ → Φ p = 0) {N : ℕ}
    (hN : 0 < N) {a b : ℤ} (hp : Φ ((a : ℝ) / N, (b : ℝ) / N) ≠ 0) :
    (|a| : ℝ) ≤ ρ * N ∧ (|b| : ℝ) ≤ ρ * N := by
  have h := abs_le_of_norm_le (norm_le_of_ne_zero hΦ hp)
  exact ⟨int_abs_le_of hN h.1, int_abs_le_of hN h.2⟩

/-- The discrete form of the trilinear bound: Lemma 5.3 (node D03) applied to sampled arrays. -/
theorem tri_lattice_bound {m : ℕ} (hm : m = 3 ∨ m = 4) (hn : 1 ≤ n) (hlt : sm < sp)
    {κ : Type*} (L : κ → IntervalList n sm sp) (c : ℝ × ℝ → κ) (H F G : ℝ × ℝ → ℂ)
    {ρ : ℝ} (hρ : 0 ≤ ρ) (hH : ∀ p, ρ < ‖p‖ → H p = 0) (hF : ∀ p, ρ < ‖p‖ → F p = 0)
    (hG : ∀ p, ρ < ‖p‖ → G p = 0) {N : ℕ} (hN : 0 < N) (hNs : ((N : ℝ)⁻¹) ^ 2 ≤ sm) :
    ‖((N : ℝ)⁻¹) ^ 3 • ∑' z : Fin 3 → ℤ, triInt m L c H F G (fun i => (z i : ℝ) / N)‖ ≤
      7 * constD03 * √n *
      (((N : ℝ)⁻¹) ^ 2 * ∑' z : Fin 2 → ℤ, ‖H ((z 0 : ℝ) / N, (z 1 : ℝ) / N)‖ ^ 3) ^ (1 / 3 : ℝ) *
      (((N : ℝ)⁻¹) ^ 2 * ∑' z : Fin 2 → ℤ, ‖F ((z 0 : ℝ) / N, (z 1 : ℝ) / N)‖ ^ 3) ^ (1 / 3 : ℝ) *
      (((N : ℝ)⁻¹) ^ 2 * ∑' z : Fin 2 → ℤ, ‖G ((z 0 : ℝ) / N, (z 1 : ℝ) / N)‖ ^ 3) ^
        (1 / 3 : ℝ) := by
  classical
  have hN' : (0 : ℝ) < N := by exact_mod_cast hN
  set h : ℝ := (N : ℝ)⁻¹ with hh_def
  have hh : 0 < h := inv_pos.2 hN'
  have hz : ∀ w : ℤ, (w : ℝ) / N = h * w := fun w => by rw [div_eq_inv_mul]
  set R : ℕ := ⌈4 * ρ * N⌉₊ with hR
  have hRge : 4 * ρ * N ≤ R := Nat.le_ceil _
  set kk : Fin (2 * R + 1) → ℤ := fun i => (i : ℤ) - R with hkk
  have hk : Function.Injective kk := fun i j hij => by
    simp only [kk, sub_left_inj] at hij; exact Fin.ext (by exact_mod_cast hij)
  have hfind : ∀ w : ℤ, (|w| : ℝ) ≤ 4 * ρ * N → ∃ i, kk i = w := fun w hw =>
    exists_fin_shift (by exact_mod_cast hw.trans hRge)
  have hρN : 0 ≤ ρ * N := by positivity
  set u : Fin (2 * R + 1) → ℝ := fun i => h * kk i with hu
  set Hd : HeatData (Fin (2 * R + 1)) := ⟨u, h, ![fun i j => H (-u i, -u j),
    fun j k => F (u j + u k, -u j), fun k i => G (-u i, u k + u i)]⟩ with hHd
  set M : Fin (2 * R + 1) → Fin (2 * R + 1) → IntervalList n sm sp :=
    fun i j => L (c (-u i, -u j))
  have key := Hd.Gaussian_derivative_grid_count hk (fun i => rfl) hh hm hn hNs hlt M
  -- the trilinear sum
  have hD : Hd.D03sum M m =
      (h ^ 3 : ℝ) • ∑' z : Fin 3 → ℤ, triInt m L c H F G (fun i => (z i : ℝ) / N) := by
    set e : Fin (2 * R + 1) × Fin (2 * R + 1) × Fin (2 * R + 1) → (Fin 3 → ℤ) :=
      fun t => ![-kk t.1, -kk t.2.1, kk t.1 + kk t.2.1 + kk t.2.2]
    have he : Function.Injective e := by
      rintro ⟨i, j, k⟩ ⟨i', j', k'⟩ hij
      have h0 := congrFun hij 0
      have h1 := congrFun hij 1
      have h2 := congrFun hij 2
      simp only [e, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_two,
        Matrix.head_cons, Matrix.tail_cons, neg_inj] at h0 h1 h2
      have := hk h0
      have := hk h1
      subst i' j'
      have := hk (by linarith : kk k = kk k')
      subst k'; rfl
    have hs : ∀ z : Fin 3 → ℤ, triInt m L c H F G (fun i => (z i : ℝ) / N) ≠ 0 →
        z ∈ Set.range e := by
      intro z hz0
      simp only [triInt] at hz0
      have hH0 : H ((z 0 : ℝ) / N, (z 1 : ℝ) / N) ≠ 0 := fun h0 => hz0 (by simp [h0])
      have hF0 : F (((z 0 + z 2 : ℤ) : ℝ) / N, (z 1 : ℝ) / N) ≠ 0 := fun h0 => hz0 (by
        have h0' : F ((z 0 : ℝ) / N + (z 2 : ℝ) / N, (z 1 : ℝ) / N) = 0 := by
          rw [show (z 0 : ℝ) / N + (z 2 : ℝ) / N = ((z 0 + z 2 : ℤ) : ℝ) / N by push_cast; ring]
          exact h0
        rw [h0']; ring)
      obtain ⟨b0, b1⟩ := int_bounds_of_ne_zero hH hN hH0
      obtain ⟨b02, -⟩ := int_bounds_of_ne_zero hF hN hF0
      obtain ⟨i, hi⟩ := hfind (-z 0) (by
        rw [Int.cast_neg, abs_neg]; nlinarith)
      obtain ⟨j, hj⟩ := hfind (-z 1) (by
        rw [Int.cast_neg, abs_neg]; nlinarith)
      obtain ⟨k, hk'⟩ := hfind (z 0 + z 1 + z 2) (by
        have : |((z 0 + z 1 + z 2 : ℤ) : ℝ)| ≤ |((z 0 + z 2 : ℤ) : ℝ)| + |(z 1 : ℝ)| := by
          push_cast
          rw [show (z 0 : ℝ) + z 1 + z 2 = (z 0 + z 2) + z 1 by ring]
          exact abs_add_le _ _
        nlinarith)
      refine ⟨(i, j, k), ?_⟩
      funext l
      fin_cases l <;> simp [e, hi, hj, hk'] <;> ring
    rw [HeatData.D03sum, Complex.real_smul, ← sum_eq_tsum_of_injective e he _ hs,
      Fintype.sum_prod_type, Fintype.sum_congr _ _ fun i => Fintype.sum_prod_type _]
    congr 1
    refine Finset.sum_congr rfl fun i _ => Finset.sum_congr rfl fun j _ =>
      Finset.sum_congr rfl fun k _ => ?_
    simp only [e, triInt, hHd, M, ilKern, Matrix.cons_val_zero, Matrix.cons_val_one,
      Matrix.cons_val_two, Matrix.head_cons, Matrix.tail_cons, hz, u]
    push_cast
    ring_nf
  -- the array norms
  have hn0 : nNorm Hd.h (Hd.A 0) =
      (h ^ 2 * ∑' z : Fin 2 → ℤ, ‖H ((z 0 : ℝ) / N, (z 1 : ℝ) / N)‖ ^ 3) ^ (1 / 3 : ℝ) := by
    set e : Fin (2 * R + 1) × Fin (2 * R + 1) → (Fin 2 → ℤ) := fun t => ![-kk t.1, -kk t.2]
    have he : Function.Injective e := by
      rintro ⟨i, j⟩ ⟨i', j'⟩ hij
      have h0 := congrFun hij 0
      have h1 := congrFun hij 1
      simp only [e, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, neg_inj] at h0 h1
      rw [hk h0, hk h1]
    have hs : ∀ z : Fin 2 → ℤ, ‖H ((z 0 : ℝ) / N, (z 1 : ℝ) / N)‖ ^ 3 ≠ 0 → z ∈ Set.range e := by
      intro z hz0
      have hH0 : H ((z 0 : ℝ) / N, (z 1 : ℝ) / N) ≠ 0 := fun h0 => hz0 (by simp [h0])
      obtain ⟨b0, b1⟩ := int_bounds_of_ne_zero hH hN hH0
      obtain ⟨i, hi⟩ := hfind (-z 0) (by rw [Int.cast_neg, abs_neg]; nlinarith)
      obtain ⟨j, hj⟩ := hfind (-z 1) (by rw [Int.cast_neg, abs_neg]; nlinarith)
      refine ⟨(i, j), ?_⟩
      funext l
      fin_cases l <;> simp [e, hi, hj]
    unfold nNorm
    rw [← sum_eq_tsum_of_injective e he _ hs, Fintype.sum_prod_type]
    congr 2
    refine Finset.sum_congr rfl fun i _ => Finset.sum_congr rfl fun j _ => ?_
    simp only [e, hHd, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, hz, u]
    push_cast
    ring_nf
  have hn1 : nNorm Hd.h (Hd.A 1) =
      (h ^ 2 * ∑' z : Fin 2 → ℤ, ‖F ((z 0 : ℝ) / N, (z 1 : ℝ) / N)‖ ^ 3) ^ (1 / 3 : ℝ) := by
    set e : Fin (2 * R + 1) × Fin (2 * R + 1) → (Fin 2 → ℤ) :=
      fun t => ![kk t.1 + kk t.2, -kk t.1]
    have he : Function.Injective e := by
      rintro ⟨i, j⟩ ⟨i', j'⟩ hij
      have h0 := congrFun hij 0
      have h1 := congrFun hij 1
      simp only [e, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, neg_inj] at h0 h1
      have := hk h1
      subst i'
      rw [hk (by linarith : kk j = kk j')]
    have hs : ∀ z : Fin 2 → ℤ, ‖F ((z 0 : ℝ) / N, (z 1 : ℝ) / N)‖ ^ 3 ≠ 0 → z ∈ Set.range e := by
      intro z hz0
      have hF0 : F ((z 0 : ℝ) / N, (z 1 : ℝ) / N) ≠ 0 := fun h0 => hz0 (by simp [h0])
      obtain ⟨b0, b1⟩ := int_bounds_of_ne_zero hF hN hF0
      obtain ⟨j, hj⟩ := hfind (-z 1) (by rw [Int.cast_neg, abs_neg]; nlinarith)
      obtain ⟨k, hk'⟩ := hfind (z 0 + z 1) (by
        have := abs_add_le (z 0 : ℝ) (z 1)
        push_cast; nlinarith)
      refine ⟨(j, k), ?_⟩
      funext l
      fin_cases l <;> simp [e, hj, hk']
    unfold nNorm
    rw [← sum_eq_tsum_of_injective e he _ hs, Fintype.sum_prod_type]
    congr 2
    refine Finset.sum_congr rfl fun i _ => Finset.sum_congr rfl fun j _ => ?_
    simp only [e, hHd, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, hz, u]
    push_cast
    ring_nf
  have hn2 : nNorm Hd.h (Hd.A 2) =
      (h ^ 2 * ∑' z : Fin 2 → ℤ, ‖G ((z 0 : ℝ) / N, (z 1 : ℝ) / N)‖ ^ 3) ^ (1 / 3 : ℝ) := by
    set e : Fin (2 * R + 1) × Fin (2 * R + 1) → (Fin 2 → ℤ) :=
      fun t => ![-kk t.2, kk t.1 + kk t.2]
    have he : Function.Injective e := by
      rintro ⟨i, j⟩ ⟨i', j'⟩ hij
      have h0 := congrFun hij 0
      have h1 := congrFun hij 1
      simp only [e, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, neg_inj] at h0 h1
      have := hk h0
      subst j'
      rw [hk (by linarith : kk i = kk i')]
    have hs : ∀ z : Fin 2 → ℤ, ‖G ((z 0 : ℝ) / N, (z 1 : ℝ) / N)‖ ^ 3 ≠ 0 → z ∈ Set.range e := by
      intro z hz0
      have hG0 : G ((z 0 : ℝ) / N, (z 1 : ℝ) / N) ≠ 0 := fun h0 => hz0 (by simp [h0])
      obtain ⟨b0, b1⟩ := int_bounds_of_ne_zero hG hN hG0
      obtain ⟨i, hi⟩ := hfind (-z 0) (by rw [Int.cast_neg, abs_neg]; nlinarith)
      obtain ⟨k, hk'⟩ := hfind (z 1 + z 0) (by
        have := abs_add_le (z 1 : ℝ) (z 0)
        push_cast; nlinarith)
      refine ⟨(k, i), ?_⟩
      funext l
      fin_cases l <;> simp [e, hi, hk']
    unfold nNorm
    rw [← sum_eq_tsum_of_injective e he _ hs, Fintype.sum_prod_type]
    congr 2
    refine Finset.sum_congr rfl fun i _ => Finset.sum_congr rfl fun j _ => ?_
    simp only [e, hHd, Matrix.cons_val_two, Matrix.tail_cons, Matrix.cons_val_zero,
      Matrix.cons_val_one, Matrix.head_cons, hz, u]
    push_cast
    ring_nf
  rw [hD, hn0, hn1, hn2] at key
  exact key

end LatticeBound

section RectBound

variable {n : ℕ} {sm sp : ℝ}

lemma exists_support_bound {f : ℝ × ℝ → ℂ} (hf : HasCompactSupport f) :
    ∃ ρ, 0 ≤ ρ ∧ ∀ p, ρ < ‖p‖ → f p = 0 := by
  obtain ⟨r, hr⟩ := hf.isCompact.isBounded.subset_closedBall 0
  refine ⟨max r 0, le_max_right _ _, fun p hp => image_eq_zero_of_notMem_tsupport fun h => ?_⟩
  have := hr h
  rw [Metric.mem_closedBall, dist_zero_right] at this
  linarith [le_max_left r 0]

/-- `∫_{ℝ²} f(x₀, x₁) dx = ∫_{ℝ×ℝ} f`. -/
lemma integral_fin2_eq {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] (f : ℝ × ℝ → E) :
    ∫ x : Fin 2 → ℝ, f (x 0, x 1) = ∫ p, f p :=
  (volume_preserving_finTwoArrow ℝ).integral_comp' (g := f)

lemma ilKern_family_bdd (m : ℕ) (hsm : 0 < sm) {κ : Type*} [Finite κ]
    (L : κ → IntervalList n sm sp) : ∃ C, ∀ k t, ‖ilKern m (L k) t‖ ≤ C := by
  have := Fintype.ofFinite κ
  choose C hC using fun k => ilKern_bdd m hsm (L k)
  refine ⟨∑ k, |C k|, fun k t => (hC k t).trans ((le_abs_self _).trans ?_)⟩
  exact Finset.single_le_sum (f := fun k => |C k|) (fun _ _ => abs_nonneg _) (Finset.mem_univ k)

/-- Bound and support of the trilinear integrand. -/
lemma triInt_bdd_supp (m : ℕ) (hsm : 0 < sm) {κ : Type*} [Finite κ]
    (L : κ → IntervalList n sm sp) {H F G : ℝ × ℝ → ℂ}
    (hHc : Continuous H) (hHs : HasCompactSupport H) (hFc : Continuous F)
    (hFs : HasCompactSupport F) (hGc : Continuous G) (hGs : HasCompactSupport G) :
    ∃ M, ∃ ρ, 0 ≤ ρ ∧ (∀ p, ρ < ‖p‖ → H p = 0) ∧ (∀ p, ρ < ‖p‖ → F p = 0) ∧
      (∀ p, ρ < ‖p‖ → G p = 0) ∧ (∀ c' : ℝ × ℝ → κ, ∀ x, ‖triInt m L c' H F G x‖ ≤ M) ∧
      ∀ c' : ℝ × ℝ → κ, ∀ x : Fin 3 → ℝ, 3 * ρ < ‖x‖ → triInt m L c' H F G x = 0 := by
  obtain ⟨CH, hCH⟩ := hHc.bounded_above_of_compact_support hHs
  obtain ⟨CF, hCF⟩ := hFc.bounded_above_of_compact_support hFs
  obtain ⟨CG, hCG⟩ := hGc.bounded_above_of_compact_support hGs
  obtain ⟨CK, hCK⟩ := ilKern_family_bdd m hsm L
  obtain ⟨ρ1, hρ1, h1⟩ := exists_support_bound hHs
  obtain ⟨ρ2, hρ2, h2⟩ := exists_support_bound hFs
  obtain ⟨ρ3, hρ3, h3⟩ := exists_support_bound hGs
  set ρ := max ρ1 (max ρ2 ρ3)
  have hH : ∀ p, ρ < ‖p‖ → H p = 0 := fun p hp => h1 p (lt_of_le_of_lt (le_max_left _ _) hp)
  have hF : ∀ p, ρ < ‖p‖ → F p = 0 := fun p hp =>
    h2 p (lt_of_le_of_lt ((le_max_left _ _).trans (le_max_right _ _)) hp)
  have hG : ∀ p, ρ < ‖p‖ → G p = 0 := fun p hp =>
    h3 p (lt_of_le_of_lt ((le_max_right _ _).trans (le_max_right _ _)) hp)
  have hρ : 0 ≤ ρ := hρ1.trans (le_max_left _ _)
  refine ⟨CH * CF * CG * CK, ρ, hρ, hH, hF, hG, fun c' x => ?_, fun c' x hx => ?_⟩
  · simp only [triInt, norm_mul]
    have h0 := (norm_nonneg _).trans (hCH (x 0, x 1))
    have h1 := (norm_nonneg _).trans (hCF (x 0 + x 2, x 1))
    have h2 := (norm_nonneg _).trans (hCG (x 0, x 1 + x 2))
    gcongr
    · exact hCH _
    · exact hCF _
    · exact hCG _
    · exact hCK _ _
  · simp only [triInt]
    by_cases hp : ρ < ‖(x 0, x 1)‖
    · rw [hH _ hp]; ring
    push Not at hp
    rw [Prod.norm_def, max_le_iff] at hp
    have h2 : 2 * ρ < |x 2| := by
      by_contra hcon
      push Not at hcon
      have : ‖x‖ ≤ 3 * ρ := by
        refine (pi_norm_le_iff_of_nonneg (by linarith)).2 fun i => ?_
        fin_cases i
        · show ‖x 0‖ ≤ 3 * ρ
          simp only [Real.norm_eq_abs] at hp ⊢; linarith [hp.1]
        · show ‖x 1‖ ≤ 3 * ρ
          simp only [Real.norm_eq_abs] at hp ⊢; linarith [hp.2]
        · show ‖x 2‖ ≤ 3 * ρ
          rw [Real.norm_eq_abs]; linarith
      linarith
    have : ρ < ‖(x 0 + x 2, x 1)‖ := by
      rw [Prod.norm_def]
      refine lt_of_lt_of_le ?_ (le_max_left _ _)
      have h0 : |x 0| ≤ ρ := by simpa using hp.1
      have := abs_sub_abs_le_abs_sub (x 2) (-(x 0))
      simp only [abs_neg, sub_neg_eq_add] at this
      show ρ < ‖x 0 + x 2‖
      rw [Real.norm_eq_abs, add_comm]; linarith
    rw [hF _ this]; ring

/-- Continuity of the trilinear integrand off the grid hyperplanes. -/
lemma triInt_continuousAt (m : ℕ) (hsm : 0 < sm) {κ : Type*} (L : κ → IntervalList n sm sp)
    {c : ℝ × ℝ → κ} {Xs Ys : Finset ℝ} (hc : GridConst Xs Ys c) {H F G : ℝ × ℝ → ℂ}
    (hHc : Continuous H) (hFc : Continuous F) (hGc : Continuous G) (x : Fin 3 → ℝ)
    (hx : ∀ p ∈ Xs.image (fun a => ((0 : Fin 3), a)) ∪ Ys.image (fun b => ((1 : Fin 3), b)),
      x p.1 ≠ p.2) :
    ContinuousAt (triInt m L c H F G) x := by
  set k0 := c (x 0, x 1)
  have hΨ : Continuous fun y : Fin 3 → ℝ => H (y 0, y 1) * F (y 0 + y 2, y 1) *
      G (y 0, y 1 + y 2) * ilKern m (L k0) (y 2) := by
    have := continuous_ilKern m hsm (L k0)
    fun_prop
  refine hΨ.continuousAt.congr ?_
  have hX : ∀ a ∈ Xs, ∀ᶠ y : Fin 3 → ℝ in 𝓝 x, (y 0 < a ↔ x 0 < a) := by
    intro a ha
    have hne : x 0 ≠ a := hx (0, a) (Finset.mem_union_left _ (Finset.mem_image_of_mem _ ha))
    rcases lt_or_gt_of_ne hne with h | h
    · filter_upwards [(continuous_apply 0).continuousAt.eventually (gt_mem_nhds h)] with y hy
      exact ⟨fun _ => h, fun _ => hy⟩
    · filter_upwards [(continuous_apply 0).continuousAt.eventually (lt_mem_nhds h)] with y hy
      exact ⟨fun h' => absurd h' (not_lt.2 hy.le), fun h' => absurd h' (not_lt.2 h.le)⟩
  have hY : ∀ b ∈ Ys, ∀ᶠ y : Fin 3 → ℝ in 𝓝 x, (y 1 < b ↔ x 1 < b) := by
    intro b hb
    have hne : x 1 ≠ b := hx (1, b) (Finset.mem_union_right _ (Finset.mem_image_of_mem _ hb))
    rcases lt_or_gt_of_ne hne with h | h
    · filter_upwards [(continuous_apply 1).continuousAt.eventually (gt_mem_nhds h)] with y hy
      exact ⟨fun _ => h, fun _ => hy⟩
    · filter_upwards [(continuous_apply 1).continuousAt.eventually (lt_mem_nhds h)] with y hy
      exact ⟨fun h' => absurd h' (not_lt.2 hy.le), fun h' => absurd h' (not_lt.2 h.le)⟩
  filter_upwards [(eventually_all_finset Xs).2 hX, (eventually_all_finset Ys).2 hY] with y hy1 hy2
  simp only [triInt]
  rw [hc (y 0, y 1) (x 0, x 1) hy1 hy2]

/-- Lattice sampling (node A04, `d = 2`) of `‖Φ‖³` for continuous compactly supported `Φ`. -/
lemma tendsto_lattice_norm_cube {Φ : ℝ × ℝ → ℂ} (hc : Continuous Φ) (hs : HasCompactSupport Φ) :
    Tendsto (fun N : ℕ => ((N : ℝ)⁻¹) ^ 2 *
      ∑' z : Fin 2 → ℤ, ‖Φ ((z 0 : ℝ) / N, (z 1 : ℝ) / N)‖ ^ 3) atTop
      (𝓝 (∫ p, ‖Φ p‖ ^ 3)) := by
  obtain ⟨C, hC⟩ := hc.bounded_above_of_compact_support hs
  obtain ⟨ρ, hρ, hΦ⟩ := exists_support_bound hs
  have hC0 : 0 ≤ C := (norm_nonneg _).trans (hC 0)
  have h := lattice_sampling_dominated_convergence (d := 2)
    (fun x : Fin 2 → ℝ => ‖Φ (x 0, x 1)‖ ^ 3) ⟨C ^ 3, fun x => by
      rw [Real.norm_eq_abs, abs_of_nonneg (by positivity)]
      exact pow_le_pow_left₀ (norm_nonneg _) (hC _) 3⟩
    ⟨ρ, fun x hx => by
      have : ρ < ‖(x 0, x 1)‖ := by
        by_contra hcon
        push Not at hcon
        rw [Prod.norm_def, max_le_iff] at hcon
        refine absurd hx (not_lt.2 ((pi_norm_le_iff_of_nonneg hρ).2 fun i => ?_))
        fin_cases i
        · exact hcon.1
        · exact hcon.2
      simp [hΦ _ this]⟩ ∅ (fun x _ => by fun_prop)
  rw [integral_fin2_eq (fun p => ‖Φ p‖ ^ 3)] at h
  simpa only [smul_eq_mul] using h

/-- **The continuum trilinear bound for rectangular choices** (first step of Theorem 6.1,
node E01): the limit `h = 1/N → 0` of Lemma 5.3 (node D03) on sampled arrays, via node A04. -/
theorem tri_rect_bound {m : ℕ} (hm : m = 3 ∨ m = 4) (hn : 1 ≤ n) (hsm : 0 < sm) (hlt : sm < sp)
    {κ : Type*} [Finite κ] (L : κ → IntervalList n sm sp) {c : ℝ × ℝ → κ} {Xs Ys : Finset ℝ}
    (hc : GridConst Xs Ys c) {H F G : ℝ × ℝ → ℂ}
    (hHc : Continuous H) (hHs : HasCompactSupport H) (hFc : Continuous F)
    (hFs : HasCompactSupport F) (hGc : Continuous G) (hGs : HasCompactSupport G) :
    ‖∫ x, triInt m L c H F G x‖ ≤ 7 * constD03 * √n * (∫ p, ‖H p‖ ^ 3) ^ (1 / 3 : ℝ) *
      (∫ p, ‖F p‖ ^ 3) ^ (1 / 3 : ℝ) * (∫ p, ‖G p‖ ^ 3) ^ (1 / 3 : ℝ) := by
  obtain ⟨M, ρ, hρ, hH, hF, hG, hM, hsupp⟩ :=
    triInt_bdd_supp m hsm L hHc hHs hFc hFs hGc hGs
  have hA := lattice_sampling_dominated_convergence (d := 3) (triInt m L c H F G) ⟨M, hM c⟩
    ⟨3 * ρ, hsupp c⟩ _ (fun x hx => triInt_continuousAt m hsm L hc hHc hFc hGc x hx)
  have hL : Tendsto (fun N : ℕ =>
      ‖((N : ℝ)⁻¹) ^ 3 • ∑' z : Fin 3 → ℤ, triInt m L c H F G (fun i => (z i : ℝ) / N)‖) atTop
      (𝓝 ‖∫ x, triInt m L c H F G x‖) := (continuous_norm.tendsto _).comp hA
  have hR := ((((tendsto_lattice_norm_cube hHc hHs).rpow_const (p := 1 / 3) (Or.inr (by norm_num))).const_mul
    (7 * constD03 * √n)).mul ((tendsto_lattice_norm_cube hFc hFs).rpow_const
      (p := 1 / 3) (Or.inr (by norm_num)))).mul ((tendsto_lattice_norm_cube hGc hGs).rpow_const
      (p := 1 / 3) (Or.inr (by norm_num)))
  refine le_of_tendsto_of_tendsto hL hR ?_
  have h0 : Tendsto (fun N : ℕ => ((N : ℝ)⁻¹) ^ 2) atTop (𝓝 0) := by
    have h0' : Tendsto (fun N : ℕ => (N : ℝ)⁻¹) atTop (𝓝 0) :=
      tendsto_inv_atTop_zero.comp tendsto_natCast_atTop_atTop
    simpa using h0'.pow 2
  filter_upwards [eventually_gt_atTop 0, h0.eventually (ge_mem_nhds hsm)] with N hN hNs
  have := tri_lattice_bound hm hn hlt L c H F G hρ hH hF hG hN hNs
  simpa only [mul_assoc] using this

/-- Selecting a measurable function by a choice with measurable fibers is measurable. -/
lemma measurable_select {X : Type*} [MeasurableSpace X] {κ : Type*} [Finite κ] {c : X → κ}
    (hc : ∀ k, MeasurableSet (c ⁻¹' {k})) (g : κ → X → ℂ) (hg : ∀ k, Measurable (g k)) :
    Measurable fun x => g (c x) x := by
  classical
  have := Fintype.ofFinite κ
  have e : (fun x => g (c x) x) = fun x => ∑ k, (c ⁻¹' {k}).indicator (g k) x := by
    funext x
    rw [Finset.sum_eq_single (c x)]
    · simp [Set.indicator]
    · intro b _ hb
      simp [Set.indicator, Ne.symm hb]
    · simp
  rw [e]
  exact Finset.measurable_sum _ fun k _ => (hg k).indicator (hc k)

lemma measurable_triInt (m : ℕ) (hsm : 0 < sm) {κ : Type*} [Finite κ]
    (L : κ → IntervalList n sm sp) {c : ℝ × ℝ → κ} (hc : ∀ k, MeasurableSet (c ⁻¹' {k}))
    {H F G : ℝ × ℝ → ℂ} (hH : Measurable H) (hF : Measurable F) (hG : Measurable G) :
    Measurable (triInt m L c H F G) := by
  have hp : Measurable fun x : Fin 3 → ℝ => (x 0, x 1) := by fun_prop
  have hK : Measurable fun x : Fin 3 → ℝ => ilKern m (L (c (x 0, x 1))) (x 2) :=
    measurable_select (c := fun x : Fin 3 → ℝ => c (x 0, x 1)) (fun k => hp (hc k))
      (fun k x => ilKern m (L k) (x 2))
      (fun k => (continuous_ilKern m hsm (L k)).measurable.comp (measurable_pi_apply 2))
  unfold triInt
  refine ((hH.comp hp).mul ?_).mul ?_ |>.mul hK
  · exact hF.comp (by fun_prop)
  · exact hG.comp (by fun_prop)

/-- The projection `x ↦ (x₀, x₁)` of `ℝ³` to `ℝ²` pulls null sets back to null sets. -/
lemma qmp_proj01 : QuasiMeasurePreserving (fun x : Fin 3 → ℝ => (x 0, x 1)) := by
  have h := (volume_preserving_finTwoArrow ℝ).quasiMeasurePreserving.comp
    (Measure.quasiMeasurePreserving_snd.comp
      (volume_preserving_piFinSuccAbove (fun _ : Fin 3 => ℝ) 2).quasiMeasurePreserving)
  exact h

/-- **The continuum trilinear bound for measurable finite-menu choices** (Theorem 6.1, node
E01, second step): approximate the choice by rectangular choices (node A03) and pass to the limit
by dominated convergence. -/
theorem tri_meas_bound {m : ℕ} (hm : m = 3 ∨ m = 4) (hn : 1 ≤ n) (hsm : 0 < sm) (hlt : sm < sp)
    {κ : Type*} [Finite κ] [Nonempty κ] (L : κ → IntervalList n sm sp) {c : ℝ × ℝ → κ}
    (hc : ∀ k, MeasurableSet (c ⁻¹' {k})) {H F G : ℝ × ℝ → ℂ}
    (hHc : Continuous H) (hHs : HasCompactSupport H) (hFc : Continuous F)
    (hFs : HasCompactSupport F) (hGc : Continuous G) (hGs : HasCompactSupport G) :
    ‖∫ x, triInt m L c H F G x‖ ≤ 7 * constD03 * √n * (∫ p, ‖H p‖ ^ 3) ^ (1 / 3 : ℝ) *
      (∫ p, ‖F p‖ ^ 3) ^ (1 / 3 : ℝ) * (∫ p, ‖G p‖ ^ 3) ^ (1 / 3 : ℝ) := by
  obtain ⟨M, ρ, hρ, hH, hF, hG, hM, hsupp⟩ :=
    triInt_bdd_supp m hsm L hHc hHs hFc hFs hGc hGs
  set Q : Set (ℝ × ℝ) := Metric.closedBall 0 ρ
  have hQ : volume Q ≠ ⊤ := measure_closedBall_lt_top.ne
  obtain ⟨cs, hcs, hae⟩ := finite_measurable_menu_rectangular_approximation c hc hQ
  have hmeas : ∀ k, ∀ j, MeasurableSet (cs k ⁻¹' {j}) := by
    intro k j
    obtain ⟨Xs, Ys, hg⟩ := hcs k
    exact measurableSet_of_mem_gridSets ⟨Xs, Ys, fun p q hx hy => by
      simp only [Set.mem_preimage, Set.mem_singleton_iff, eq_iff_iff]
      rw [hg p q hx hy]⟩
  set B := 7 * constD03 * √n * (∫ p, ‖H p‖ ^ 3) ^ (1 / 3 : ℝ) *
      (∫ p, ‖F p‖ ^ 3) ^ (1 / 3 : ℝ) * (∫ p, ‖G p‖ ^ 3) ^ (1 / 3 : ℝ)
  have hk : ∀ k, ‖∫ x, triInt m L (cs k) H F G x‖ ≤ B := fun k => by
    obtain ⟨Xs, Ys, hg⟩ := hcs k
    exact tri_rect_bound hm hn hsm hlt L hg hHc hHs hFc hFs hGc hGs
  -- dominated convergence
  set bound : (Fin 3 → ℝ) → ℝ := (Metric.closedBall 0 (3 * ρ)).indicator fun _ => M
  have hbound : Integrable bound :=
    (integrableOn_const measure_closedBall_lt_top.ne).integrable_indicator
      Metric.isClosed_closedBall.measurableSet
  have hlim : Tendsto (fun k => ∫ x, triInt m L (cs k) H F G x) atTop
      (𝓝 (∫ x, triInt m L c H F G x)) := by
    refine tendsto_integral_of_dominated_convergence bound (fun k =>
      (measurable_triInt m hsm L (hmeas k) hHc.measurable hFc.measurable
        hGc.measurable).aestronglyMeasurable) hbound (fun k => Eventually.of_forall fun x => ?_) ?_
    · by_cases hx : ‖x‖ ≤ 3 * ρ
      · have : x ∈ Metric.closedBall (0 : Fin 3 → ℝ) (3 * ρ) := by
          rw [Metric.mem_closedBall, dist_zero_right]; exact hx
        simp only [bound, Set.indicator_of_mem this]
        exact hM _ x
      · rw [hsupp _ x (not_le.1 hx), norm_zero]
        exact Set.indicator_nonneg (fun _ _ => (norm_nonneg _).trans (hM c x)) x
    · have h2 : ∀ᵐ p : ℝ × ℝ, p ∈ Q → ∀ᶠ k in atTop, cs k p = c p :=
        (ae_restrict_iff' Metric.isClosed_closedBall.measurableSet).1 hae
      filter_upwards [qmp_proj01.ae h2] with x hx
      by_cases hxQ : (x 0, x 1) ∈ Q
      · refine tendsto_const_nhds.congr' ?_
        filter_upwards [hx hxQ] with k hk
        simp only [triInt, hk]
      · have hH0 : H (x 0, x 1) = 0 := hH _ (by
          simp only [Q, Metric.mem_closedBall, dist_zero_right, not_le] at hxQ; exact hxQ)
        have e : ∀ c' : ℝ × ℝ → κ, triInt m L c' H F G x = 0 := fun c' => by
          simp [triInt, hH0]
        simp only [e]
        exact tendsto_const_nhds
  exact le_of_tendsto' ((continuous_norm.tendsto _).comp hlim) hk

/-- The coordinates `x ↦ ((x₀, x₁), x₂)` of `ℝ³`, as a measurable equivalence. -/
def fin3Equiv : (Fin 3 → ℝ) ≃ᵐ (ℝ × ℝ) × ℝ :=
  (MeasurableEquiv.piFinSuccAbove (fun _ : Fin 3 => ℝ) 2).trans
    ((MeasurableEquiv.prodCongr (MeasurableEquiv.refl ℝ) MeasurableEquiv.finTwoArrow).trans
      MeasurableEquiv.prodComm)

lemma fin3Equiv_apply (x : Fin 3 → ℝ) : fin3Equiv x = ((x 0, x 1), x 2) := rfl

lemma measurePreserving_fin3Equiv :
    MeasurePreserving fin3Equiv volume ((volume : Measure (ℝ × ℝ)).prod (volume : Measure ℝ)) := by
  have h1 := volume_preserving_piFinSuccAbove (fun _ : Fin 3 => ℝ) 2
  have h2 := (MeasurePreserving.id (volume : Measure ℝ)).prod (volume_preserving_finTwoArrow ℝ)
  have h3 := Measure.measurePreserving_swap (μ := (volume : Measure ℝ))
    (ν := (volume : Measure (ℝ × ℝ)))
  exact h3.comp (h2.comp h1)

/-- **Fubini for the trilinear form**: `∫_{ℝ³} triInt = ∫_{ℝ²} H · B_{K_{c(p)}}(F, G)`. -/
theorem integral_triInt_eq (m : ℕ) (hsm : 0 < sm) {κ : Type*} [Finite κ]
    (L : κ → IntervalList n sm sp) {c : ℝ × ℝ → κ} (hc : ∀ k, MeasurableSet (c ⁻¹' {k}))
    {H F G : ℝ × ℝ → ℂ} (hHc : Continuous H) (hHs : HasCompactSupport H) (hFc : Continuous F)
    (hFs : HasCompactSupport F) (hGc : Continuous G) (hGs : HasCompactSupport G) :
    Integrable (triInt m L c H F G) ∧
    Integrable (fun p => H p * bilinKernel (ilKern m (L (c p))) F G p) ∧
    ∫ x, triInt m L c H F G x = ∫ p, H p * bilinKernel (ilKern m (L (c p))) F G p := by
  obtain ⟨M, ρ, hρ, -, -, -, hM, hsupp⟩ :=
    triInt_bdd_supp m hsm L hHc hHs hFc hFs hGc hGs
  have hmeas := measurable_triInt m hsm L hc hHc.measurable hFc.measurable hGc.measurable
  have hint : Integrable (triInt m L c H F G) := by
    have hb : Integrable ((Metric.closedBall (0 : Fin 3 → ℝ) (3 * ρ)).indicator fun _ => M) :=
      (integrableOn_const measure_closedBall_lt_top.ne).integrable_indicator
        Metric.isClosed_closedBall.measurableSet
    refine Integrable.mono' hb hmeas.aestronglyMeasurable (Eventually.of_forall fun x => ?_)
    by_cases hx : ‖x‖ ≤ 3 * ρ
    · have : x ∈ Metric.closedBall (0 : Fin 3 → ℝ) (3 * ρ) := by
        rw [Metric.mem_closedBall, dist_zero_right]; exact hx
      rw [Set.indicator_of_mem this]
      exact hM _ x
    · rw [hsupp _ x (not_le.1 hx), norm_zero]
      exact Set.indicator_nonneg (fun _ _ => (norm_nonneg _).trans (hM c x)) x
  set Ψ : (ℝ × ℝ) × ℝ → ℂ := fun z => H z.1 * (F (z.1.1 + z.2, z.1.2) * G (z.1.1, z.1.2 + z.2) *
    ilKern m (L (c z.1)) z.2)
  have hT : triInt m L c H F G = Ψ ∘ fin3Equiv := by
    funext x; simp only [triInt, Ψ, Function.comp, fin3Equiv_apply]; ring
  have hΨ : Integrable Ψ ((volume : Measure (ℝ × ℝ)).prod (volume : Measure ℝ)) := by
    rw [hT] at hint
    exact (measurePreserving_fin3Equiv.integrable_comp_emb
      fin3Equiv.measurableEmbedding).1 hint
  have hmarg : (fun p => H p * bilinKernel (ilKern m (L (c p))) F G p) =
      fun p => ∫ t, Ψ (p, t) := by
    funext p
    simp only [Ψ, bilinKernel]
    rw [integral_const_mul]
  refine ⟨hint, hmarg ▸ hΨ.integral_prod_left, ?_⟩
  rw [hT, Function.comp_def, measurePreserving_fin3Equiv.integral_comp' (g := Ψ),
    integral_prod _ hΨ, hmarg]

end RectBound

/-! ### Finite families of rational interval lists -/

/-- Lists of at most `n` pairwise disjoint open intervals `(u, v)` with positive rational
endpoints (the index set of the counting functions `S_n` of §6). -/
structure RatIntervalList (n : ℕ) where
  /-- the endpoints `(u, v)` of the intervals -/
  l : List (ℚ × ℚ)
  len_le : l.length ≤ n
  pos : ∀ p ∈ l, 0 < p.1
  lt : ∀ p ∈ l, p.1 < p.2
  disj : l.Pairwise fun p q => Disjoint (Set.Ioo (p.1 : ℝ) p.2) (Set.Ioo (q.1 : ℝ) q.2)

lemma RatIntervalList.l_injective (n : ℕ) :
    Function.Injective (RatIntervalList.l : RatIntervalList n → List (ℚ × ℚ)) := by
  rintro ⟨l, _, _, _, _⟩ ⟨l', _, _, _, _⟩ h
  cases h; rfl

instance (n : ℕ) : Countable (RatIntervalList n) :=
  (RatIntervalList.l_injective n).countable

/-- The counting function `sup_I ∑_{(u,v) ∈ I} Δ(u,v)` over lists `I` of at most `n` disjoint
rational intervals, for an increment functional `Δ` (with values in `[0, ∞]`). -/
def countingSup (n : ℕ) (Δ : ℝ → ℝ → ℝ≥0∞) : ℝ≥0∞ :=
  ⨆ I : RatIntervalList n, (I.l.map fun p => Δ p.1 p.2).sum

section Menu

variable {n : ℕ}

/-- The `ℓ`-th interval of a list (a dummy interval past the end). -/
def RatIntervalList.ival (I : RatIntervalList n) (ℓ : ℕ) : ℚ × ℚ :=
  if h : ℓ < I.l.length then I.l[ℓ] else (1, 2)

lemma RatIntervalList.ival_mem (I : RatIntervalList n) {ℓ : ℕ} (h : ℓ < I.l.length) :
    I.ival ℓ ∈ I.l := by
  simp only [RatIntervalList.ival, h, dite_true]; exact List.getElem_mem h

lemma list_sum_map_eq_sum_range {α M : Type*} [AddCommMonoid M] (l : List α) (f : α → M)
    (d : α) : (l.map f).sum = ∑ ℓ ∈ Finset.range l.length,
      f (if h : ℓ < l.length then l[ℓ] else d) := by
  induction l with
  | nil => simp
  | cons a l ih =>
    rw [List.map_cons, List.sum_cons, ih]
    show _ = ∑ ℓ ∈ Finset.range (l.length + 1), _
    rw [Finset.sum_range_succ', add_comm]
    simp

lemma RatIntervalList.sum_map_eq (I : RatIntervalList n) {M : Type*} [AddCommMonoid M]
    (f : ℚ × ℚ → M) : (I.l.map f).sum = ∑ ℓ ∈ Finset.range I.l.length, f (I.ival ℓ) :=
  list_sum_map_eq_sum_range _ _ _

/-- The four phases `iʲ`. -/
def phase (j : Fin 4) : ℂ := Complex.I ^ (j : ℕ)

lemma norm_phase (j : Fin 4) : ‖phase j‖ = 1 := by
  simp [phase]

/-- For every complex number some phase gives `|z| ≤ 2 Re(iʲ z)`. -/
lemma exists_phase (z : ℂ) : ∃ j : Fin 4, ‖z‖ ≤ 2 * (phase j * z).re := by
  have h := Complex.norm_le_abs_re_add_abs_im z
  have e0 : (phase 0 * z).re = z.re := by simp [phase]
  have e1 : (phase 1 * z).re = -z.im := by simp [phase]
  have e2 : (phase 2 * z).re = -z.re := by simp [phase, pow_two]
  have e3 : (phase 3 * z).re = z.im := by simp [phase, pow_succ, pow_two]
  rcases le_total |z.im| |z.re| with hc | hc
  · rcases le_total 0 z.re with hr | hr
    · exact ⟨0, by rw [e0]; rw [abs_of_nonneg hr] at hc h; linarith⟩
    · exact ⟨2, by rw [e2]; rw [abs_of_nonpos hr] at hc h; linarith⟩
  · rcases le_total 0 z.im with hr | hr
    · exact ⟨3, by rw [e3]; rw [abs_of_nonneg hr] at hc h; linarith⟩
    · exact ⟨1, by rw [e1]; rw [abs_of_nonpos hr] at hc h; linarith⟩

/-- The interval list (with phases `φ`) attached to a rational interval list. -/
def RatIntervalList.toIL (I : RatIntervalList n) (φ : Fin n → Fin 4) {sm sp : ℝ}
    (hbd : ∀ q ∈ I.l, sm ≤ (q.1 : ℝ) ∧ (q.2 : ℝ) ≤ sp) : IntervalList n sm sp where
  len := I.l.length
  a ℓ := (I.ival ℓ).1
  b ℓ := (I.ival ℓ).2
  c ℓ := if h : ℓ < n then phase (φ ⟨ℓ, h⟩) else 0
  len_le := I.len_le
  lt ℓ hℓ := by exact_mod_cast I.lt _ (I.ival_mem hℓ)
  disj ℓ hℓ ℓ' hℓ' hne := by
    have hp := List.pairwise_iff_getElem.1 I.disj
    simp only [RatIntervalList.ival, hℓ, hℓ', dite_true]
    rcases lt_or_gt_of_ne hne with h | h
    · exact hp ℓ ℓ' hℓ hℓ' h
    · exact (hp ℓ' ℓ hℓ' hℓ h).symm
  norm_c ℓ := by
    split_ifs
    · rw [norm_phase]
    · simp
  range ℓ hℓ := hbd _ (I.ival_mem hℓ)

/-- A finite family of rational interval lists lies in a compact positive scale range. -/
lemma exists_scale_range (𝓕 : Finset (RatIntervalList n)) :
    ∃ sm sp : ℝ, 0 < sm ∧ sm < sp ∧ ∀ I ∈ 𝓕, ∀ q ∈ I.l, sm ≤ (q.1 : ℝ) ∧ (q.2 : ℝ) ≤ sp := by
  classical
  set T : Finset (ℚ × ℚ) := 𝓕.biUnion fun I => I.l.toFinset
  have hT : ∀ q ∈ T, 0 < q.1 := by
    intro q hq
    obtain ⟨I, -, hq⟩ := Finset.mem_biUnion.1 hq
    exact I.pos q (List.mem_toFinset.1 hq)
  obtain ⟨ε, hε, hεT⟩ : ∃ ε : ℚ, 0 < ε ∧ ∀ q ∈ T, ε ≤ q.1 := by
    rcases T.eq_empty_or_nonempty with h | h
    · exact ⟨1, one_pos, by simp [h]⟩
    · refine ⟨(T.image Prod.fst).min' (h.image _), ?_, fun q hq =>
        Finset.min'_le _ _ (Finset.mem_image_of_mem _ hq)⟩
      obtain ⟨q, hq, hmin⟩ := Finset.mem_image.1 ((T.image Prod.fst).min'_mem (h.image _))
      rw [← hmin]; exact hT q hq
  obtain ⟨Λ, hΛT⟩ : ∃ Λ : ℚ, ∀ q ∈ T, q.2 ≤ Λ :=
    ⟨∑ q ∈ T, |q.2|, fun q hq => (le_abs_self _).trans
      (Finset.single_le_sum (f := fun q : ℚ × ℚ => |q.2|) (fun _ _ => abs_nonneg _) hq)⟩
  refine ⟨ε, max Λ ε + 1, by exact_mod_cast hε, ?_, fun I hI q hq => ?_⟩
  · have : (ε : ℝ) ≤ max (Λ : ℝ) ε := le_max_right _ _
    push_cast; linarith
  · have hqT : q ∈ T := Finset.mem_biUnion.2 ⟨I, hI, List.mem_toFinset.2 hq⟩
    refine ⟨by exact_mod_cast hεT q hqT, ?_⟩
    have : (q.2 : ℝ) ≤ Λ := by exact_mod_cast hΛT q hqT
    push_cast
    linarith [le_max_left (Λ : ℝ) ε]

end Menu

section Selection

/-- A measurable maximizing selector among finitely many measurable real functions (least
maximizing index in an enumeration). -/
lemma exists_measurable_argmax {X : Type*} [MeasurableSpace X] {κ : Type*} [Fintype κ]
    [Nonempty κ] (f : κ → X → ℝ) (hf : ∀ k, Measurable (f k)) :
    ∃ c : X → κ, (∀ k, MeasurableSet (c ⁻¹' {k})) ∧ ∀ x k, f k x ≤ f (c x) x := by
  classical
  set K := Fintype.card κ
  set e : κ ≃ Fin K := Fintype.equivFin κ
  set M : X → ℝ := fun x => Finset.univ.sup' Finset.univ_nonempty fun k => f k x
  have hM : Measurable M := by
    have := Finset.measurable_sup' (s := Finset.univ) Finset.univ_nonempty (f := f)
      fun k _ => hf k
    convert this using 1
    funext x
    simp [M, Finset.sup'_apply]
  set P : X → ℕ → Prop := fun x j => ∃ h : j < K, f (e.symm ⟨j, h⟩) x = M x
  have hex : ∀ x, ∃ j, P x j := by
    intro x
    obtain ⟨k, -, hk⟩ := Finset.exists_mem_eq_sup' Finset.univ_nonempty fun k => f k x
    exact ⟨e k, (e k).2, by simp [M, hk]⟩
  set c : X → κ := fun x => e.symm ⟨Nat.find (hex x), (Nat.find_spec (hex x)).1⟩
  have hPm : ∀ j, MeasurableSet {x | P x j} := by
    intro j
    by_cases hj : j < K
    · have : {x | P x j} = {x | f (e.symm ⟨j, hj⟩) x = M x} := by
        ext x; simp [P, hj]
      rw [this]; exact measurableSet_eq_fun (hf _) hM
    · have : {x | P x j} = ∅ := by ext x; simp [P, hj]
      rw [this]; exact MeasurableSet.empty
  refine ⟨c, fun k => ?_, fun x k => ?_⟩
  · have : c ⁻¹' {k} = {x | P x (e k)} ∩ ⋂ i ∈ Finset.range (e k), {x | ¬ P x i} := by
      ext x
      simp only [Set.mem_preimage, Set.mem_singleton_iff, Set.mem_inter_iff, Set.mem_iInter,
        Finset.mem_range, Set.mem_ofPred_eq, c]
      rw [Equiv.symm_apply_eq]
      constructor
      · intro h
        have h' : Nat.find (hex x) = e k := by rw [← h]
        rw [← h']
        exact ⟨Nat.find_spec (hex x), fun i hi => Nat.find_min (hex x) hi⟩
      · rintro ⟨h1, h2⟩
        apply Fin.ext
        simp only
        rw [Nat.find_eq_iff]
        exact ⟨h1, fun i hi => h2 i hi⟩
    rw [this]
    exact (hPm _).inter (MeasurableSet.biInter (Finset.range _).countable_toSet
      fun i _ => (hPm i).compl)
  · obtain ⟨hlt, hc⟩ := Nat.find_spec (hex x)
    show f k x ≤ f (e.symm ⟨Nat.find (hex x), _⟩) x
    rw [hc]
    exact Finset.le_sup' (fun k => f k x) (Finset.mem_univ k)

end Selection

section Counting

variable {n : ℕ}

/-- The output `B_{K_{u,v}}(F,G)` of the interval kernel `K^{(m)}_{u,v}`, `q = (u, v)`. -/
def bilinTerm (m : ℕ) (F G : ℝ × ℝ → ℂ) (q : ℚ × ℚ) (p : ℝ × ℝ) : ℂ :=
  bilinKernel (fun t => (Kern m q.1 q.2 t : ℂ)) F G p

/-- `∑_{(u,v) ∈ I} |B_{K_{u,v}}(F,G)|`. -/
def listSum (m : ℕ) (F G : ℝ × ℝ → ℂ) (I : RatIntervalList n) (p : ℝ × ℝ) : ℝ≥0 :=
  (I.l.map fun q => ‖bilinTerm m F G q p‖₊).sum

/-- The counting function restricted to a finite family `𝓕` of interval lists. -/
def Sfin (m : ℕ) (F G : ℝ × ℝ → ℂ) (𝓕 : Finset (RatIntervalList n)) (p : ℝ × ℝ) : ℝ≥0 :=
  𝓕.sup fun I => listSum m F G I p

lemma measurable_bilinKernel {K : ℝ → ℂ} {F G : ℝ × ℝ → ℂ} (hK : Measurable K)
    (hF : Measurable F) (hG : Measurable G) : Measurable (bilinKernel K F G) := by
  have hjoint : Measurable fun q : (ℝ × ℝ) × ℝ =>
      F (q.1.1 + q.2, q.1.2) * G (q.1.1, q.1.2 + q.2) * K q.2 := by
    refine (Measurable.mul ?_ ?_).mul (hK.comp measurable_snd)
    · exact hF.comp (by fun_prop)
    · exact hG.comp (by fun_prop)
  exact (hjoint.stronglyMeasurable.integral_prod_right' (ν := volume)).measurable

lemma norm_bilinKernel_le {K : ℝ → ℂ} {F G : ℝ × ℝ → ℂ} (hK : Integrable K) {CF CG : ℝ}
    (hF : ∀ x, ‖F x‖ ≤ CF) (hG : ∀ x, ‖G x‖ ≤ CG) (p : ℝ × ℝ) :
    ‖bilinKernel K F G p‖ ≤ CF * CG * ∫ t, ‖K t‖ := by
  have hCF : 0 ≤ CF := (norm_nonneg _).trans (hF 0)
  rw [bilinKernel, ← integral_const_mul]
  refine norm_integral_le_of_norm_le (hK.norm.const_mul _) (Eventually.of_forall fun t => ?_)
  rw [norm_mul, norm_mul]
  gcongr
  · exact hF _
  · exact hG _

lemma measurable_bilinTerm (m : ℕ) {F G : ℝ × ℝ → ℂ} (hF : Measurable F) (hG : Measurable G)
    {q : ℚ × ℚ} (hq : 0 < q.1) (hlt : q.1 < q.2) : Measurable (bilinTerm m F G q) :=
  measurable_bilinKernel (Complex.continuous_ofReal.comp (continuous_Kern m
    (by exact_mod_cast hq) (by exact_mod_cast hlt.le))).measurable hF hG

lemma measurable_listSum (m : ℕ) {F G : ℝ × ℝ → ℂ} (hF : Measurable F) (hG : Measurable G)
    (I : RatIntervalList n) : Measurable (listSum m F G I) := by
  unfold listSum
  have e : (fun p => (I.l.map fun q => ‖bilinTerm m F G q p‖₊).sum) = fun p =>
      ∑ ℓ ∈ Finset.range I.l.length, ‖bilinTerm m F G (I.ival ℓ) p‖₊ := by
    funext p; exact I.sum_map_eq _
  rw [e]
  exact Finset.measurable_sum _ fun ℓ hℓ =>
    (measurable_bilinTerm m hF hG (I.pos _ (I.ival_mem (Finset.mem_range.1 hℓ)))
      (I.lt _ (I.ival_mem (Finset.mem_range.1 hℓ)))).nnnorm

lemma measurable_Sfin (m : ℕ) {F G : ℝ × ℝ → ℂ} (hF : Measurable F) (hG : Measurable G)
    (𝓕 : Finset (RatIntervalList n)) : Measurable (Sfin m F G 𝓕) := by
  classical
  induction 𝓕 using Finset.induction_on with
  | empty =>
    have e : Sfin m F G (∅ : Finset (RatIntervalList n)) = fun _ => 0 := by
      funext p; simp [Sfin]
    rw [e]; exact measurable_const
  | insert a s _ ih =>
    have e : Sfin m F G (insert a s) = fun p => listSum m F G a p ⊔ Sfin m F G s p := by
      funext p; simp [Sfin, Finset.sup_insert]
    rw [e]
    exact (measurable_listSum m hF hG a).sup ih

lemma constD03_nonneg : 0 ≤ constD03 := by
  unfold constD03
  have := constD_spec.1
  have := constA_spec.1
  have := HeatData.jumpConst_nonneg
  positivity

/-- Expansion of the output of a phased interval list into the outputs of its intervals. -/
lemma bilinKernel_toIL (m : ℕ) {F G : ℝ × ℝ → ℂ} (hFc : Continuous F)
    (hFs : HasCompactSupport F) (hGc : Continuous G) (hGs : HasCompactSupport G)
    (I : RatIntervalList n) (φ : Fin n → Fin 4) {sm sp : ℝ} (hsm : 0 < sm)
    (hbd : ∀ q ∈ I.l, sm ≤ (q.1 : ℝ) ∧ (q.2 : ℝ) ≤ sp) (p : ℝ × ℝ) :
    bilinKernel (ilKern m (I.toIL φ hbd)) F G p = ∑ ℓ ∈ Finset.range I.l.length,
      (I.toIL φ hbd).c ℓ * bilinTerm m F G (I.ival ℓ) p := by
  obtain ⟨CF, hCF⟩ := hFc.bounded_above_of_compact_support hFs
  obtain ⟨CG, hCG⟩ := hGc.bounded_above_of_compact_support hGs
  have hint : ∀ ℓ ∈ Finset.range I.l.length, Integrable fun t =>
      F (p.1 + t, p.2) * G (p.1, p.2 + t) * (Kern m (I.ival ℓ).1 (I.ival ℓ).2 t : ℂ) := by
    intro ℓ hℓ
    have hℓ' := Finset.mem_range.1 hℓ
    have hK : Integrable fun t => (Kern m (I.ival ℓ).1 (I.ival ℓ).2 t : ℂ) :=
      (integrable_Kern m (hsm.trans_le ((I.toIL φ hbd).range ℓ hℓ').1)
        ((I.toIL φ hbd).lt ℓ hℓ').le).1.ofReal
    have hm : AEStronglyMeasurable (fun t => F (p.1 + t, p.2) * G (p.1, p.2 + t)) :=
      (Continuous.mul (hFc.comp (by fun_prop)) (hGc.comp (by fun_prop))).aestronglyMeasurable
    refine hK.bdd_mul (c := CF * CG) hm (Eventually.of_forall fun t => ?_)
    rw [norm_mul]
    exact mul_le_mul (hCF _) (hCG _) (norm_nonneg _) ((norm_nonneg _).trans (hCF 0))
  have e : (fun t => F (p.1 + t, p.2) * G (p.1, p.2 + t) * ilKern m (I.toIL φ hbd) t) =
      fun t => ∑ ℓ ∈ Finset.range I.l.length, (I.toIL φ hbd).c ℓ *
        (F (p.1 + t, p.2) * G (p.1, p.2 + t) * (Kern m (I.ival ℓ).1 (I.ival ℓ).2 t : ℂ)) := by
    funext t
    simp only [ilKern, Finset.mul_sum]
    refine Finset.sum_congr rfl fun ℓ _ => ?_
    simp only [RatIntervalList.toIL]; ring
  rw [bilinKernel, e, integral_finsetSum _ fun ℓ hℓ => (hint ℓ hℓ).const_mul _]
  refine Finset.sum_congr rfl fun ℓ _ => ?_
  rw [integral_const_mul]
  rfl

/-- **Pairing estimate for a finite family** (Theorem 6.1, node E01): for continuous compactly
supported `F, G` and nonnegative continuous compactly supported `H`,
`∫ H S_𝓕(F,G) ≤ 2 C √n ‖H‖₃ ‖F‖₃ ‖G‖₃`. Phases from the four units `iʲ` and a measurable
maximizing choice reduce this to the trilinear bound. -/
theorem Sfin_pairing {m : ℕ} (hm : m = 3 ∨ m = 4) (hn : 1 ≤ n) (𝓕 : Finset (RatIntervalList n))
    {F G : ℝ × ℝ → ℂ} (hFc : Continuous F) (hFs : HasCompactSupport F) (hGc : Continuous G)
    (hGs : HasCompactSupport G) (H : ℝ × ℝ → ℝ) (hHc : Continuous H) (hHs : HasCompactSupport H)
    (hH0 : 0 ≤ H) :
    ∫ p, H p * (Sfin m F G 𝓕 p : ℝ) ≤ 2 * (7 * constD03 * √n) *
      (∫ p, ‖F p‖ ^ 3) ^ (1 / 3 : ℝ) * (∫ p, ‖G p‖ ^ 3) ^ (1 / 3 : ℝ) *
        (∫ p, |H p| ^ (3 : ℝ)) ^ (1 / 3 : ℝ) := by
  classical
  have hRHS : 0 ≤ 2 * (7 * constD03 * √n) * (∫ p, ‖F p‖ ^ 3) ^ (1 / 3 : ℝ) *
      (∫ p, ‖G p‖ ^ 3) ^ (1 / 3 : ℝ) * (∫ p, |H p| ^ (3 : ℝ)) ^ (1 / 3 : ℝ) := by
    have := constD03_nonneg
    have h1 : 0 ≤ ∫ p, ‖F p‖ ^ 3 := integral_nonneg fun _ => by positivity
    have h2 : 0 ≤ ∫ p, ‖G p‖ ^ 3 := integral_nonneg fun _ => by positivity
    have h3 : 0 ≤ ∫ p, |H p| ^ (3 : ℝ) := integral_nonneg fun _ => by positivity
    positivity
  rcases 𝓕.eq_empty_or_nonempty with hE | hne
  · subst hE
    simpa [Sfin] using hRHS
  obtain ⟨sm, sp, hsm, hlt, hbd⟩ := exists_scale_range 𝓕
  -- the menu
  set κ := {I // I ∈ 𝓕} × (Fin n → Fin 4)
  have : Nonempty κ := ⟨(⟨hne.choose, hne.choose_spec⟩, fun _ => 0)⟩
  set L : κ → IntervalList n sm sp := fun k => k.1.1.toIL k.2 (hbd k.1.1 k.1.2)
  set Φ : κ → ℝ × ℝ → ℂ := fun k p => bilinKernel (ilKern m (L k)) F G p
  have hΦm : ∀ k, Measurable (Φ k) := fun k =>
    measurable_bilinKernel (continuous_ilKern m hsm (L k)).measurable hFc.measurable
      hGc.measurable
  obtain ⟨c, hc, hcmax⟩ := exists_measurable_argmax (fun k p => (Φ k p).re)
    fun k => Complex.measurable_re.comp (hΦm k)
  -- pointwise bound
  have hpt : ∀ p, (Sfin m F G 𝓕 p : ℝ) ≤ 2 * (Φ (c p) p).re := by
    intro p
    obtain ⟨I, hI, hIeq⟩ := Finset.exists_mem_eq_sup 𝓕 hne fun I => listSum m F G I p
    choose φ hφ using fun ℓ : Fin n => exists_phase (bilinTerm m F G (I.ival ℓ) p)
    refine le_trans ?_ (mul_le_mul_of_nonneg_left (hcmax p (⟨I, hI⟩, φ)) zero_le_two)
    rw [Sfin, hIeq, listSum, I.sum_map_eq, NNReal.coe_sum]
    simp only [Φ, L]
    rw [bilinKernel_toIL m hFc hFs hGc hGs I φ hsm, Complex.re_sum, Finset.mul_sum]
    refine Finset.sum_le_sum fun ℓ hℓ => ?_
    have hℓn : ℓ < n := (Finset.mem_range.1 hℓ).trans_le I.len_le
    have := hφ ⟨ℓ, hℓn⟩
    simp only [coe_nnnorm, RatIntervalList.toIL, hℓn, dite_true]
    exact this
  -- the trilinear form
  set Hc : ℝ × ℝ → ℂ := fun p => (H p : ℂ)
  have hHcc : Continuous Hc := Complex.continuous_ofReal.comp hHc
  have hHcs : HasCompactSupport Hc := hHs.comp_left Complex.ofReal_zero
  obtain ⟨-, hint, heq⟩ := integral_triInt_eq m hsm L hc hHcc hHcs hFc hFs hGc hGs
  have hbound := tri_meas_bound hm hn hsm hlt L hc hHcc hHcs hFc hFs hGc hGs
  have hS : Measurable fun p => H p * (Sfin m F G 𝓕 p : ℝ) :=
    hHc.measurable.mul (measurable_coe_nnreal_real.comp (measurable_Sfin m hFc.measurable
      hGc.measurable 𝓕))
  have hpt2 : ∀ p, H p * (Sfin m F G 𝓕 p : ℝ) ≤ 2 * (Hc p * Φ (c p) p).re := by
    intro p
    have : (Hc p * Φ (c p) p).re = H p * (Φ (c p) p).re := by simp [Hc]
    rw [this]
    calc H p * (Sfin m F G 𝓕 p : ℝ) ≤ H p * (2 * (Φ (c p) p).re) :=
          mul_le_mul_of_nonneg_left (hpt p) (hH0 p)
      _ = _ := by ring
  have hint2 : Integrable fun p => 2 * (Hc p * Φ (c p) p).re :=
    (hint.re).const_mul 2
  calc ∫ p, H p * (Sfin m F G 𝓕 p : ℝ)
      ≤ ∫ p, 2 * (Hc p * Φ (c p) p).re := by
        refine integral_mono_of_nonneg (Eventually.of_forall fun p => ?_) hint2
          (Eventually.of_forall hpt2)
        exact mul_nonneg (hH0 p) (NNReal.coe_nonneg _)
    _ = 2 * (∫ p, Hc p * Φ (c p) p).re := by
        rw [integral_const_mul]
        congr 1
        exact integral_re hint
    _ ≤ 2 * ‖∫ x, triInt m L c Hc F G x‖ := by
        rw [heq]
        exact mul_le_mul_of_nonneg_left (Complex.re_le_norm _) zero_le_two
    _ ≤ 2 * (7 * constD03 * √n * (∫ p, ‖Hc p‖ ^ 3) ^ (1 / 3 : ℝ) *
          (∫ p, ‖F p‖ ^ 3) ^ (1 / 3 : ℝ) * (∫ p, ‖G p‖ ^ 3) ^ (1 / 3 : ℝ)) :=
        mul_le_mul_of_nonneg_left hbound zero_le_two
    _ = _ := by
        have e : (∫ p, ‖Hc p‖ ^ 3) = ∫ p, |H p| ^ (3 : ℝ) := by
          refine integral_congr_ae (Eventually.of_forall fun p => ?_)
          simp only [Hc, Complex.norm_real, Real.norm_eq_abs]
          exact_mod_cast (Real.rpow_natCast |H p| 3).symm
        rw [e]; ring

lemma RatIntervalList.ival_valid (I : RatIntervalList n) {ℓ : ℕ} (h : ℓ < I.l.length) :
    (0 : ℝ) < (I.ival ℓ).1 ∧ ((I.ival ℓ).1 : ℝ) < (I.ival ℓ).2 :=
  ⟨by exact_mod_cast I.pos _ (I.ival_mem h), by exact_mod_cast I.lt _ (I.ival_mem h)⟩

lemma integrable_KernC (m : ℕ) {q : ℚ × ℚ} (hq : (0 : ℝ) < q.1 ∧ (q.1 : ℝ) < q.2) :
    Integrable fun t => (Kern m q.1 q.2 t : ℂ) :=
  (integrable_Kern m hq.1 hq.2.le).1.ofReal

lemma measurable_KernC (m : ℕ) {q : ℚ × ℚ} (hq : (0 : ℝ) < q.1 ∧ (q.1 : ℝ) < q.2) :
    Measurable fun t => (Kern m q.1 q.2 t : ℂ) :=
  (Complex.continuous_ofReal.comp (continuous_Kern m hq.1 hq.2.le)).measurable

/-- Each interval output lies in `L^{3/2}` (node A06). -/
lemma memLp_bilinTerm (m : ℕ) {F G : ℝ × ℝ → ℂ} (hF : Measurable F) (hG : Measurable G)
    (hF3 : MemLp F 3) (hG3 : MemLp G 3) {q : ℚ × ℚ} (hq : (0 : ℝ) < q.1 ∧ (q.1 : ℝ) < q.2) :
    MemLp (bilinTerm m F G q) (3 / 2) :=
  (L1_kernel_bilinear_bound hF hG (measurable_KernC m hq) hF3 hG3 (integrable_KernC m hq)).2.1

/-- The majorant `∑_{I ∈ 𝓕} ∑_{(u,v) ∈ I} |B_{u,v}(F,G)|`. -/
def Wsum (m : ℕ) (F G : ℝ × ℝ → ℂ) (𝓕 : Finset (RatIntervalList n)) (p : ℝ × ℝ) : ℝ :=
  ∑ I ∈ 𝓕, ∑ ℓ ∈ Finset.range I.l.length, ‖bilinTerm m F G (I.ival ℓ) p‖

lemma listSum_coe (m : ℕ) (F G : ℝ × ℝ → ℂ) (I : RatIntervalList n) (p : ℝ × ℝ) :
    (listSum m F G I p : ℝ) = ∑ ℓ ∈ Finset.range I.l.length, ‖bilinTerm m F G (I.ival ℓ) p‖ := by
  rw [listSum, I.sum_map_eq, NNReal.coe_sum]; rfl

lemma Sfin_le_Wsum (m : ℕ) (F G : ℝ × ℝ → ℂ) (𝓕 : Finset (RatIntervalList n)) (p : ℝ × ℝ) :
    (Sfin m F G 𝓕 p : ℝ) ≤ Wsum m F G 𝓕 p := by
  classical
  rcases 𝓕.eq_empty_or_nonempty with hE | hne
  · subst hE; simp [Sfin, Wsum]
  obtain ⟨I, hI, hIeq⟩ := Finset.exists_mem_eq_sup 𝓕 hne fun I => listSum m F G I p
  rw [Sfin, hIeq, listSum_coe, Wsum]
  exact Finset.single_le_sum (f := fun I : RatIntervalList n => ∑ ℓ ∈ Finset.range I.l.length,
    ‖bilinTerm m F G (I.ival ℓ) p‖) (fun I _ => Finset.sum_nonneg fun _ _ => norm_nonneg _) hI

lemma Sfin_le_add (m : ℕ) (F G F' G' : ℝ × ℝ → ℂ) (𝓕 : Finset (RatIntervalList n))
    (p : ℝ × ℝ) : (Sfin m F G 𝓕 p : ℝ) ≤ Sfin m F' G' 𝓕 p + ∑ I ∈ 𝓕,
      ∑ ℓ ∈ Finset.range I.l.length, ‖bilinTerm m F G (I.ival ℓ) p -
        bilinTerm m F' G' (I.ival ℓ) p‖ := by
  classical
  rcases 𝓕.eq_empty_or_nonempty with hE | hne
  · subst hE; simp [Sfin]
  obtain ⟨I, hI, hIeq⟩ := Finset.exists_mem_eq_sup 𝓕 hne fun I => listSum m F G I p
  rw [Sfin, hIeq, listSum_coe]
  have h1 : (listSum m F' G' I p : ℝ) ≤ Sfin m F' G' 𝓕 p := by
    exact_mod_cast Finset.le_sup (f := fun I => listSum m F' G' I p) hI
  have h2 : ∑ ℓ ∈ Finset.range I.l.length, ‖bilinTerm m F G (I.ival ℓ) p‖ ≤
      (listSum m F' G' I p : ℝ) + ∑ ℓ ∈ Finset.range I.l.length,
        ‖bilinTerm m F G (I.ival ℓ) p - bilinTerm m F' G' (I.ival ℓ) p‖ := by
    rw [listSum_coe, ← Finset.sum_add_distrib]
    refine Finset.sum_le_sum fun ℓ _ => ?_
    have := norm_sub_norm_le (bilinTerm m F G (I.ival ℓ) p) (bilinTerm m F' G' (I.ival ℓ) p)
    linarith
  have h3 : ∑ ℓ ∈ Finset.range I.l.length,
        ‖bilinTerm m F G (I.ival ℓ) p - bilinTerm m F' G' (I.ival ℓ) p‖ ≤ ∑ I ∈ 𝓕,
      ∑ ℓ ∈ Finset.range I.l.length, ‖bilinTerm m F G (I.ival ℓ) p -
        bilinTerm m F' G' (I.ival ℓ) p‖ :=
    Finset.single_le_sum (f := fun I : RatIntervalList n => ∑ ℓ ∈ Finset.range I.l.length,
      ‖bilinTerm m F G (I.ival ℓ) p - bilinTerm m F' G' (I.ival ℓ) p‖)
      (fun I _ => Finset.sum_nonneg fun _ _ => norm_nonneg _) hI
  linarith

lemma memLp_Sfin (m : ℕ) {F G : ℝ × ℝ → ℂ} (hF : Measurable F) (hG : Measurable G)
    (hF3 : MemLp F 3) (hG3 : MemLp G 3) (𝓕 : Finset (RatIntervalList n)) :
    MemLp (fun p => (Sfin m F G 𝓕 p : ℝ)) (3 / 2) := by
  have hW : MemLp (Wsum m F G 𝓕) (3 / 2) := by
    unfold Wsum
    refine memLp_finsetSum _ fun I _ => memLp_finsetSum _ fun ℓ hℓ => ?_
    exact (memLp_bilinTerm m hF hG hF3 hG3 (I.ival_valid (Finset.mem_range.1 hℓ))).norm
  refine hW.mono' (measurable_coe_nnreal_real.comp
    (measurable_Sfin m hF hG 𝓕)).aestronglyMeasurable (Eventually.of_forall fun p => ?_)
  rw [Real.norm_eq_abs, abs_of_nonneg (NNReal.coe_nonneg _)]
  exact Sfin_le_Wsum m F G 𝓕 p

lemma toReal_eLpNorm_three {F : ℝ × ℝ → ℂ} (hF : MemLp F 3) :
    (eLpNorm F 3).toReal = (∫ p, ‖F p‖ ^ 3) ^ (1 / 3 : ℝ) := by
  rw [hF.eLpNorm_eq_integral_rpow_norm (by norm_num) (by norm_num),
    ENNReal.toReal_ofReal (by positivity)]
  have : ((3 : ℝ≥0∞)).toReal = 3 := by norm_num
  rw [this]
  norm_num

/-- **The finite counting estimate for continuous compactly supported inputs** (node E01, via the
norming test A05). -/
theorem Sfin_Cc_bound {m : ℕ} (hm : m = 3 ∨ m = 4) (hn : 1 ≤ n) (𝓕 : Finset (RatIntervalList n))
    {F G : ℝ × ℝ → ℂ} (hFc : Continuous F) (hFs : HasCompactSupport F) (hGc : Continuous G)
    (hGs : HasCompactSupport G) :
    (eLpNorm (fun p => (Sfin m F G 𝓕 p : ℝ)) (3 / 2)).toReal ≤
      14 * constD03 * √n * (eLpNorm F 3).toReal * (eLpNorm G 3).toReal := by
  have hF3 : MemLp F 3 := hFc.memLp_of_hasCompactSupport hFs
  have hG3 : MemLp G 3 := hGc.memLp_of_hasCompactSupport hGs
  have hU := memLp_Sfin m hFc.measurable hGc.measurable hF3 hG3 𝓕
  have hU' : MemLp (fun p => (Sfin m F G 𝓕 p : ℝ)) (ENNReal.ofReal (3 / 2)) := by
    rw [ofReal_three_halves]; exact hU
  have key := nonnegative_Lp_norm_test (fun p => NNReal.coe_nonneg _) hU'
    (B := 2 * (7 * constD03 * √n) * (∫ p, ‖F p‖ ^ 3) ^ (1 / 3 : ℝ) *
      (∫ p, ‖G p‖ ^ 3) ^ (1 / 3 : ℝ))
    (fun H hHc hHs hH0 => Sfin_pairing hm hn 𝓕 hFc hFs hGc hGs H hHc hHs hH0)
  have e := toReal_eLpNorm_eq_integral (p := 3 / 2) (by norm_num) hU'
  rw [ofReal_three_halves] at e
  rw [e, toReal_eLpNorm_three hF3, toReal_eLpNorm_three hG3]
  have e2 : (∫ p, |(Sfin m F G 𝓕 p : ℝ)| ^ (3 / 2 : ℝ)) =
      ∫ p, (Sfin m F G 𝓕 p : ℝ) ^ (3 / 2 : ℝ) := by
    simp only [abs_of_nonneg (NNReal.coe_nonneg _)]
  rw [e2, show (1 : ℝ) / (3 / 2) = 2 / 3 by norm_num]
  refine key.trans (le_of_eq ?_)
  ring

lemma eLpNorm_le_add_of_sub_le {F F' : ℝ × ℝ → ℂ} (hF : MemLp F 3) {δ : ℝ}
    (hδ : 0 ≤ δ) (h : eLpNorm (F - F') 3 ≤ ENNReal.ofReal δ) :
    eLpNorm F' 3 ≤ ENNReal.ofReal ((eLpNorm F 3).toReal + δ) := by
  have h1 := eLpNorm_add_le (p := 3) (μ := volume) (f := F) (g := F' - F) (by norm_num)
  rw [show F + (F' - F) = F' by abel, eLpNorm_sub_comm] at h1
  refine h1.trans ((add_le_add le_rfl h).trans (le_of_eq ?_))
  rw [ENNReal.ofReal_add ENNReal.toReal_nonneg hδ, ENNReal.ofReal_toReal hF.eLpNorm_ne_top]

/-- **The finite counting estimate for general `L³` inputs** (node E01): density of continuous
compactly supported functions and the bilinear continuity of node A06. -/
theorem Sfin_bound {m : ℕ} (hm : m = 3 ∨ m = 4) (hn : 1 ≤ n) (𝓕 : Finset (RatIntervalList n))
    {F G : ℝ × ℝ → ℂ} (hF : Measurable F) (hG : Measurable G) (hF3 : MemLp F 3)
    (hG3 : MemLp G 3) :
    (eLpNorm (fun p => (Sfin m F G 𝓕 p : ℝ)) (3 / 2)).toReal ≤
      14 * constD03 * √n * (eLpNorm F 3).toReal * (eLpNorm G 3).toReal := by
  set f := (eLpNorm F 3).toReal
  set g := (eLpNorm G 3).toReal
  set K := 14 * constD03 * √n
  set a := (eLpNorm (fun p => (Sfin m F G 𝓕 p : ℝ)) (3 / 2)).toReal
  set k : ℚ × ℚ → ℝ := fun q => (eLpNorm (fun t => (Kern m q.1 q.2 t : ℂ)) 1).toReal
  set S := ∑ I ∈ 𝓕, ∑ ℓ ∈ Finset.range I.l.length, k (I.ival ℓ)
  have hk0 : ∀ q, 0 ≤ k q := fun q => ENNReal.toReal_nonneg
  have hK0 : 0 ≤ K := by have := constD03_nonneg; positivity
  have hf0 : 0 ≤ f := ENNReal.toReal_nonneg
  have hg0 : 0 ≤ g := ENNReal.toReal_nonneg
  have hU := memLp_Sfin m hF hG hF3 hG3 𝓕
  have h32 : (1 : ℝ≥0∞) ≤ 3 / 2 := by
    rw [← ofReal_three_halves]; exact ENNReal.one_le_ofReal.2 (by norm_num)
  -- the estimate at precision `δ`
  have hδ : ∀ δ : ℝ, 0 < δ → a ≤ K * (f + δ) * (g + δ) + S * (δ * g + (f + δ) * δ) := by
    intro δ hδ
    have hε : ENNReal.ofReal δ ≠ 0 := (ENNReal.ofReal_pos.2 hδ).ne'
    obtain ⟨F', hF's, hF'd, hF'c, hF'3⟩ :=
      hF3.exists_hasCompactSupport_eLpNorm_sub_le (by norm_num) hε
    obtain ⟨G', hG's, hG'd, hG'c, hG'3⟩ :=
      hG3.exists_hasCompactSupport_eLpNorm_sub_le (by norm_num) hε
    have hF'n := eLpNorm_le_add_of_sub_le (F' := F') hF3 hδ.le hF'd
    have hG'n := eLpNorm_le_add_of_sub_le (F' := G') hG3 hδ.le hG'd
    have hU' := memLp_Sfin m hF'c.measurable hG'c.measurable hF'3 hG'3 𝓕
    -- comparison of the two counting functions
    have h1 := toReal_eLpNorm_le_add h32 hU hU'
    have h2 := Sfin_Cc_bound hm hn 𝓕 hF'c hF's hG'c hG's
    have hf' : (eLpNorm F' 3).toReal ≤ f + δ :=
      ENNReal.toReal_le_of_le_ofReal (by positivity) hF'n
    have hg' : (eLpNorm G' 3).toReal ≤ g + δ :=
      ENNReal.toReal_le_of_le_ofReal (by positivity) hG'n
    -- the error term
    set D : ℝ × ℝ → ℝ := fun p => ∑ I ∈ 𝓕, ∑ ℓ ∈ Finset.range I.l.length,
      ‖bilinTerm m F G (I.ival ℓ) p - bilinTerm m F' G' (I.ival ℓ) p‖
    have hD : ∀ p, ‖(fun p => (Sfin m F G 𝓕 p : ℝ)) p - (fun p => (Sfin m F' G' 𝓕 p : ℝ)) p‖ ≤
        D p := by
      intro p
      rw [Real.norm_eq_abs, abs_le]
      have e1 := Sfin_le_add m F G F' G' 𝓕 p
      have e2 := Sfin_le_add m F' G' F G 𝓕 p
      have e3 : ∑ I ∈ 𝓕, ∑ ℓ ∈ Finset.range I.l.length, ‖bilinTerm m F' G' (I.ival ℓ) p -
          bilinTerm m F G (I.ival ℓ) p‖ = D p := by
        simp only [D, norm_sub_rev]
      constructor <;> linarith
    have hterm : ∀ I ∈ 𝓕, ∀ ℓ ∈ Finset.range I.l.length,
        eLpNorm (fun p => ‖bilinTerm m F G (I.ival ℓ) p - bilinTerm m F' G' (I.ival ℓ) p‖)
          (3 / 2) volume ≤ ENNReal.ofReal (k (I.ival ℓ) * (δ * g + (f + δ) * δ)) := by
      intro I _ ℓ hℓ
      have hq := I.ival_valid (Finset.mem_range.1 hℓ)
      have hc := L1_kernel_bilinear_continuity hF hG hF'c.measurable hG'c.measurable
        (measurable_KernC m hq) hF3 hG3 hF'3 hG'3 (integrable_KernC m hq)
      have hmeas : AEStronglyMeasurable (fun p => bilinTerm m F G (I.ival ℓ) p -
          bilinTerm m F' G' (I.ival ℓ) p) volume :=
        ((memLp_bilinTerm m hF hG hF3 hG3 hq).sub
          (memLp_bilinTerm m hF'c.measurable hG'c.measurable hF'3 hG'3 hq)).aestronglyMeasurable
      rw [eLpNorm_norm _ hmeas]
      refine hc.trans ?_
      have hK1 : eLpNorm (fun t => (Kern m (I.ival ℓ).1 (I.ival ℓ).2 t : ℂ)) 1 volume =
          ENNReal.ofReal (k (I.ival ℓ)) :=
        (ENNReal.ofReal_toReal (memLp_one_iff_integrable.2 (integrable_KernC m hq)).eLpNorm_ne_top).symm
      have hG1 : eLpNorm G 3 volume = ENNReal.ofReal g :=
        (ENNReal.ofReal_toReal hG3.eLpNorm_ne_top).symm
      rw [hK1, hG1]
      calc ENNReal.ofReal (k (I.ival ℓ)) * (eLpNorm (F - F') 3 volume * ENNReal.ofReal g +
            eLpNorm F' 3 volume * eLpNorm (G - G') 3 volume)
          ≤ ENNReal.ofReal (k (I.ival ℓ)) * (ENNReal.ofReal δ * ENNReal.ofReal g +
            ENNReal.ofReal (f + δ) * ENNReal.ofReal δ) := by gcongr
        _ = ENNReal.ofReal (k (I.ival ℓ) * (δ * g + (f + δ) * δ)) := by
            rw [← ENNReal.ofReal_mul hδ.le, ← ENNReal.ofReal_mul (by positivity),
              ← ENNReal.ofReal_add (by positivity) (by positivity),
              ← ENNReal.ofReal_mul (hk0 _)]
    have hdiff : eLpNorm ((fun p => (Sfin m F G 𝓕 p : ℝ)) - fun p => (Sfin m F' G' 𝓕 p : ℝ))
        (3 / 2) volume ≤ ENNReal.ofReal (S * (δ * g + (f + δ) * δ)) := by
      refine (eLpNorm_mono_real (hU.sub hU').aestronglyMeasurable hD).trans ?_
      have eD : D = ∑ I ∈ 𝓕, ∑ ℓ ∈ Finset.range I.l.length, fun p =>
          ‖bilinTerm m F G (I.ival ℓ) p - bilinTerm m F' G' (I.ival ℓ) p‖ := by
        funext p; simp [D, Finset.sum_apply]
      rw [eD]
      refine (eLpNorm_sum_le h32).trans ?_
      refine (Finset.sum_le_sum fun I _ => eLpNorm_sum_le h32).trans ?_
      refine (Finset.sum_le_sum fun I hI => Finset.sum_le_sum fun ℓ hℓ =>
        hterm I hI ℓ hℓ).trans (le_of_eq ?_)
      have eS : S * (δ * g + (f + δ) * δ) = ∑ I ∈ 𝓕, ∑ ℓ ∈ Finset.range I.l.length,
          k (I.ival ℓ) * (δ * g + (f + δ) * δ) := by simp only [S, Finset.sum_mul]
      rw [eS, ENNReal.ofReal_sum_of_nonneg fun I _ => Finset.sum_nonneg fun ℓ _ => by
        have := hk0 (I.ival ℓ); positivity]
      refine Finset.sum_congr rfl fun I _ => ?_
      rw [ENNReal.ofReal_sum_of_nonneg fun ℓ _ => by have := hk0 (I.ival ℓ); positivity]
    have h3 : (eLpNorm ((fun p => (Sfin m F G 𝓕 p : ℝ)) - fun p => (Sfin m F' G' 𝓕 p : ℝ))
        (3 / 2) volume).toReal ≤ S * (δ * g + (f + δ) * δ) :=
      ENNReal.toReal_le_of_le_ofReal (by
        have : 0 ≤ S := Finset.sum_nonneg fun I _ => Finset.sum_nonneg fun ℓ _ => hk0 _
        positivity) hdiff
    have h4 : a ≤ K * (eLpNorm F' 3).toReal * (eLpNorm G' 3).toReal +
        S * (δ * g + (f + δ) * δ) := by
      have := add_le_add h2 h3
      exact h1.trans this
    have h5 : K * (eLpNorm F' 3).toReal * (eLpNorm G' 3).toReal ≤ K * (f + δ) * (g + δ) :=
      mul_le_mul (mul_le_mul_of_nonneg_left hf' hK0) hg' ENNReal.toReal_nonneg (by positivity)
    linarith
  -- let `δ → 0`
  have hlim : Tendsto (fun j : ℕ => K * (f + 1 / ((j : ℝ) + 1)) * (g + 1 / ((j : ℝ) + 1)) +
      S * (1 / ((j : ℝ) + 1) * g + (f + 1 / ((j : ℝ) + 1)) * (1 / ((j : ℝ) + 1)))) atTop
      (𝓝 (K * f * g)) := by
    have h0 : Tendsto (fun j : ℕ => 1 / ((j : ℝ) + 1)) atTop (𝓝 0) :=
      tendsto_one_div_add_atTop_nhds_zero_nat
    have hc : Continuous fun δ : ℝ => K * (f + δ) * (g + δ) + S * (δ * g + (f + δ) * δ) := by
      fun_prop
    have := (hc.tendsto 0).comp h0
    simpa [Function.comp_def] using this
  exact ge_of_tendsto' hlim fun j => hδ _ Nat.one_div_pos_of_nat

/-- The interval kernel `K^{(m)}_{u,v}` as a complex function. -/
def KernC (m : ℕ) (u v t : ℝ) : ℂ := (Kern m u v t : ℂ)

lemma listSum_enorm (m : ℕ) (F G : ℝ × ℝ → ℂ) (I : RatIntervalList n) (p : ℝ × ℝ) :
    (I.l.map fun q => ‖bilinKernel (KernC m q.1 q.2) F G p‖ₑ).sum =
      ((listSum m F G I p : ℝ≥0) : ℝ≥0∞) := by
  rw [listSum, I.sum_map_eq, I.sum_map_eq, ENNReal.ofNNReal_finsetSum]
  rfl

lemma Sfin_enorm_eLpNorm (m : ℕ) {F G : ℝ × ℝ → ℂ} (hF : Measurable F) (hG : Measurable G)
    (𝓕 : Finset (RatIntervalList n)) :
    eLpNorm (fun p => (Sfin m F G 𝓕 p : ℝ)) (3 / 2) =
      (∫⁻ p, ((Sfin m F G 𝓕 p : ℝ≥0) : ℝ≥0∞) ^ (3 / 2 : ℝ)) ^ (2 / 3 : ℝ) := by
  have h32 : (3 / 2 : ℝ≥0∞).toReal = 3 / 2 := toReal_three_halves
  rw [eLpNorm_eq_lintegral_rpow_enorm_toReal (by norm_num)
    (by rw [← ofReal_three_halves]; exact ENNReal.ofReal_ne_top)
    (measurable_Sfin m hF hG 𝓕).coe_nnreal_real.aestronglyMeasurable, h32]
  norm_num

/-- **Theorem 6.1 (node E01), counting estimate.** For `m = 3, 4` and every `n ≥ 1`,
`‖S_n^{(m)}(F,G)‖_{L^{3/2}(ℝ²)} ≤ C √n ‖F‖_{L³} ‖G‖_{L³}`, where
`S_n^{(m)}(F,G)(x,y) = sup_I ∑_{(u,v) ∈ I} |B_{K^{(m)}_{u,v}}(F,G)(x,y)|` over lists `I` of at
most `n` disjoint open intervals with positive rational endpoints. The constant `C` is absolute
(quantified before `m`, `n`, `F`, `G`). -/
theorem Euclidean_counting_bound :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ m : ℕ, (m = 3 ∨ m = 4) → ∀ n : ℕ, 1 ≤ n →
      ∀ F G : ℝ × ℝ → ℂ, Measurable F → Measurable G → MemLp F 3 → MemLp G 3 →
        (∫⁻ p, countingSup n (fun u v => ‖bilinKernel (KernC m u v) F G p‖ₑ) ^ (3 / 2 : ℝ)) ^
          (2 / 3 : ℝ) ≤ ENNReal.ofReal (C * √n) * eLpNorm F 3 * eLpNorm G 3 := by
  classical
  refine ⟨14 * constD03, by have := constD03_nonneg; positivity, fun m hm n hn F G hF hG hF3 hG3 => ?_⟩
  set X : ℝ≥0∞ := ENNReal.ofReal (14 * constD03 * √n) * eLpNorm F 3 * eLpNorm G 3
  -- enumerate the interval lists
  have : Nonempty (RatIntervalList n) :=
    ⟨⟨[], by simp, by simp, by simp, List.Pairwise.nil⟩⟩
  obtain ⟨e, he⟩ := exists_surjective_nat (RatIntervalList n)
  set 𝓕 : ℕ → Finset (RatIntervalList n) := fun N => (Finset.range N).image e
  set s : ℕ → ℝ × ℝ → ℝ≥0∞ := fun N p => ((Sfin m F G (𝓕 N) p : ℝ≥0) : ℝ≥0∞)
  have hs_mono : ∀ p, Monotone fun N => s N p := by
    intro p N N' hNN'
    simp only [s, ENNReal.coe_le_coe]
    exact Finset.sup_mono (Finset.image_subset_image (Finset.range_subset_range.2 hNN'))
  have hsup : ∀ p, countingSup n (fun u v => ‖bilinKernel (KernC m u v) F G p‖ₑ) ≤
      ⨆ N, s N p := by
    intro p
    refine iSup_le fun I => ?_
    obtain ⟨N, hN⟩ := he I
    rw [listSum_enorm]
    refine le_iSup_of_le (N + 1) ?_
    simp only [s, ENNReal.coe_le_coe]
    exact Finset.le_sup (f := fun I => listSum m F G I p)
      (Finset.mem_image.2 ⟨N, Finset.mem_range.2 (Nat.lt_succ_self N), hN⟩)
  -- each finite family obeys the bound
  have hN : ∀ N, ∫⁻ p, s N p ^ (3 / 2 : ℝ) ≤ X ^ (3 / 2 : ℝ) := by
    intro N
    have hb := Sfin_bound hm hn (𝓕 N) hF hG hF3 hG3
    have hU := memLp_Sfin m hF hG hF3 hG3 (𝓕 N)
    have hle : eLpNorm (fun p => (Sfin m F G (𝓕 N) p : ℝ)) (3 / 2) ≤ X := by
      rw [← ENNReal.ofReal_toReal hU.eLpNorm_ne_top]
      refine (ENNReal.ofReal_le_ofReal hb).trans (le_of_eq ?_)
      have hc : 0 ≤ 14 * constD03 * √n := by have := constD03_nonneg; positivity
      rw [ENNReal.ofReal_mul (mul_nonneg hc ENNReal.toReal_nonneg), ENNReal.ofReal_mul hc,
        ENNReal.ofReal_toReal hF3.eLpNorm_ne_top, ENNReal.ofReal_toReal hG3.eLpNorm_ne_top]
    rw [Sfin_enorm_eLpNorm m hF hG] at hle
    have := ENNReal.rpow_le_rpow hle (by norm_num : (0 : ℝ) ≤ 3 / 2)
    rwa [← ENNReal.rpow_mul, show (2 / 3 : ℝ) * (3 / 2) = 1 by norm_num, ENNReal.rpow_one] at this
  -- monotone convergence
  have hmeas : ∀ N, Measurable fun p => s N p ^ (3 / 2 : ℝ) := fun N =>
    (measurable_Sfin m hF hG (𝓕 N)).coe_nnreal_ennreal.pow_const _
  have hint : ∫⁻ p, countingSup n (fun u v => ‖bilinKernel (KernC m u v) F G p‖ₑ) ^ (3 / 2 : ℝ) ≤
      X ^ (3 / 2 : ℝ) := by
    calc _ ≤ ∫⁻ p, ⨆ N, s N p ^ (3 / 2 : ℝ) := by
          refine lintegral_mono fun p => ?_
          -- `(sup s)^{3/2} ≤ sup s^{3/2}`
          set Y := ⨆ N, s N p ^ (3 / 2 : ℝ)
          have h1 : ⨆ N, s N p ≤ Y ^ (2 / 3 : ℝ) := by
            refine iSup_le fun N => ?_
            have := ENNReal.rpow_le_rpow (le_iSup (fun N => s N p ^ (3 / 2 : ℝ)) N)
              (by norm_num : (0 : ℝ) ≤ 2 / 3)
            rwa [← ENNReal.rpow_mul, show (3 / 2 : ℝ) * (2 / 3) = 1 by norm_num,
              ENNReal.rpow_one] at this
          have h2 := ENNReal.rpow_le_rpow ((hsup p).trans h1) (by norm_num : (0 : ℝ) ≤ 3 / 2)
          rwa [← ENNReal.rpow_mul, show (2 / 3 : ℝ) * (3 / 2) = 1 by norm_num,
            ENNReal.rpow_one] at h2
      _ = ⨆ N, ∫⁻ p, s N p ^ (3 / 2 : ℝ) := by
          refine lintegral_iSup hmeas fun N N' hNN' p => ?_
          exact ENNReal.rpow_le_rpow (hs_mono p hNN') (by norm_num)
      _ ≤ X ^ (3 / 2 : ℝ) := iSup_le hN
  have := ENNReal.rpow_le_rpow hint (by norm_num : (0 : ℝ) ≤ 2 / 3)
  rwa [← ENNReal.rpow_mul, show (3 / 2 : ℝ) * (2 / 3) = 1 by norm_num, ENNReal.rpow_one] at this

end Counting

/-! ### Node E02: counting gives a limit -/

section E02

/-- Helper for node E02: the sum over a list of positive rational intervals is measurable. -/
lemma measurable_countingSum_list {Ω : Type*} [MeasurableSpace Ω] (H : Ω → ℝ → ℂ)
    (hmeas : ∀ s : ℚ, 0 < s → Measurable fun ω => H ω s) (l : List (ℚ × ℚ))
    (hl : ∀ p ∈ l, 0 < p.1 ∧ 0 < p.2) :
    Measurable fun ω => (l.map fun p : ℚ × ℚ => ‖H ω p.2 - H ω p.1‖ₑ).sum := by
  induction l with
  | nil => simp
  | cons p l ih =>
    simp only [List.map_cons, List.sum_cons]
    have hp := hl p (by simp)
    refine Measurable.add ?_ (ih fun q hq => hl q (by simp [hq]))
    exact ((hmeas _ hp.2).sub (hmeas _ hp.1)).enorm

/-- **Node E02, measurability.** The counting function `S_n(ω)` is measurable. -/
lemma measurable_countingSup_increments {Ω : Type*} [MeasurableSpace Ω] (H : Ω → ℝ → ℂ)
    (hmeas : ∀ s : ℚ, 0 < s → Measurable fun ω => H ω s) (n : ℕ) :
    Measurable fun ω => countingSup n (fun u v => ‖H ω v - H ω u‖ₑ) := by
  unfold countingSup
  refine Measurable.iSup fun I => ?_
  exact measurable_countingSum_list H hmeas I.l fun p hp =>
    ⟨I.pos p hp, (I.pos p hp).trans (I.lt p hp)⟩

/-- Helper for node E02: if a path has increments larger than `ε` on rational intervals
arbitrarily far out, one can find `n` disjoint such intervals beyond any `K ≥ 0`. -/
lemma exists_list_large_increments (H0 : ℝ → ℂ) {ε : ℝ}
    (hE : ∀ K : ℝ, ∃ u v : ℚ, K < u ∧ u < v ∧ ε < ‖H0 v - H0 u‖) :
    ∀ n : ℕ, ∀ K : ℝ, 0 ≤ K → ∃ l : List (ℚ × ℚ), l.length = n ∧
      (∀ p ∈ l, K < p.1 ∧ p.1 < p.2) ∧
      l.Pairwise (fun p q => Disjoint (Set.Ioo (p.1 : ℝ) p.2) (Set.Ioo (q.1 : ℝ) q.2)) ∧
      (n : ℝ≥0∞) * ENNReal.ofReal ε ≤ (l.map fun p : ℚ × ℚ => ‖H0 p.2 - H0 p.1‖ₑ).sum := by
  intro n
  induction n with
  | zero => intro K _; exact ⟨[], by simp, by simp, by simp, by simp⟩
  | succ n ih =>
    intro K hK
    obtain ⟨u, v, hKu, huv, hε⟩ := hE K
    have huv' : (u : ℝ) < v := by exact_mod_cast huv
    obtain ⟨l, hlen, hl, hdisj, hsum⟩ := ih v (by linarith)
    refine ⟨(u, v) :: l, by simp [hlen], ?_, ?_, ?_⟩
    · intro p hp
      rcases List.mem_cons.1 hp with rfl | hp
      · exact ⟨hKu, huv⟩
      · have := hl p hp
        refine ⟨by linarith [this.1], this.2⟩
    · refine List.pairwise_cons.2 ⟨fun q hq => ?_, hdisj⟩
      have := (hl q hq).1
      refine Set.disjoint_left.2 fun x hx hx' => ?_
      simp only [Set.mem_Ioo] at hx hx'
      linarith [hx.2, hx'.1]
    · simp only [List.map_cons, List.sum_cons, Nat.cast_succ, add_mul, one_mul]
      rw [add_comm]
      gcongr
      rw [← ofReal_norm]
      exact ENNReal.ofReal_le_ofReal hε.le

/-- Helper for node E02: lower bound `S_n ≥ n ε` on the bad set. -/
lemma le_countingSup_of_large_increments (H0 : ℝ → ℂ) {ε : ℝ}
    (hE : ∀ K : ℝ, ∃ u v : ℚ, K < u ∧ u < v ∧ ε < ‖H0 v - H0 u‖) (n : ℕ) :
    (n : ℝ≥0∞) * ENNReal.ofReal ε ≤ countingSup n (fun u v => ‖H0 v - H0 u‖ₑ) := by
  obtain ⟨l, hlen, hl, hdisj, hsum⟩ := exists_list_large_increments H0 hE n 0 le_rfl
  let I : RatIntervalList n :=
    ⟨l, hlen.le, fun p hp => by exact_mod_cast (hl p hp).1, fun p hp => by
      exact_mod_cast (hl p hp).2, hdisj⟩
  exact hsum.trans (le_iSup (fun I : RatIntervalList n =>
    (I.l.map fun p => ‖H0 (p.2 : ℝ) - H0 (p.1 : ℝ)‖ₑ).sum) I)

/-- Helper for node E02: a path, continuous on `(0, ∞)`, whose increments between rationals
are eventually small, converges at infinity. -/
lemma exists_tendsto_of_rat_cauchy (H0 : ℝ → ℂ) (hcont : ContinuousOn H0 (Set.Ioi 0))
    (hC : ∀ ε > 0, ∃ K : ℝ, ∀ u v : ℚ, K < u → u < v → ‖H0 v - H0 u‖ ≤ ε) :
    ∃ L, Tendsto H0 atTop (𝓝 L) := by
  -- real Cauchy property
  have hR : ∀ ε > 0, ∃ K : ℝ, 0 ≤ K ∧ ∀ x y : ℝ, K < x → K < y → ‖H0 x - H0 y‖ ≤ ε := by
    intro ε hε
    obtain ⟨K, hK⟩ := hC ε hε
    refine ⟨max K 0, le_max_right _ _, fun x y hx hy => ?_⟩
    have hsym : ∀ u v : ℚ, max K 0 < u → max K 0 < v → ‖H0 u - H0 v‖ ≤ ε := by
      intro u v hu hv
      have hu' : K < u := lt_of_le_of_lt (le_max_left _ _) hu
      have hv' : K < v := lt_of_le_of_lt (le_max_left _ _) hv
      rcases lt_trichotomy u v with h | h | h
      · rw [norm_sub_rev]; exact hK u v hu' h
      · subst h; simp [hε.le]
      · exact hK v u hv' h
    -- rational sequences approaching from above
    have hseq : ∀ z : ℝ, ∃ q : ℕ → ℚ, (∀ k, z < q k) ∧
        Tendsto (fun k => (q k : ℝ)) atTop (𝓝 z) := by
      intro z
      have : ∀ k : ℕ, ∃ r : ℚ, z < r ∧ (r : ℝ) < z + 1 / ((k : ℝ) + 1) := fun k => by
        have : (0:ℝ) < 1 / ((k : ℝ) + 1) := by positivity
        exact exists_rat_btwn (by linarith)
      choose q hq using this
      refine ⟨q, fun k => (hq k).1, ?_⟩
      have h0 := tendsto_one_div_add_atTop_nhds_zero_nat (𝕜 := ℝ)
      have h1 : Tendsto (fun k : ℕ => z + 1 / ((k : ℝ) + 1)) atTop (𝓝 z) := by
        simpa using h0.const_add z
      exact tendsto_of_tendsto_of_tendsto_of_le_of_le tendsto_const_nhds h1
        (fun k => (hq k).1.le) (fun k => (hq k).2.le)
    obtain ⟨q, hq, hqt⟩ := hseq x
    obtain ⟨r, hr, hrt⟩ := hseq y
    have hx0 : (0 : ℝ) < x := lt_of_le_of_lt (le_max_right _ _) hx
    have hy0 : (0 : ℝ) < y := lt_of_le_of_lt (le_max_right _ _) hy
    have hcx : ContinuousAt H0 x := hcont.continuousAt (Ioi_mem_nhds hx0)
    have hcy : ContinuousAt H0 y := hcont.continuousAt (Ioi_mem_nhds hy0)
    have ht : Tendsto (fun k => ‖H0 (q k) - H0 (r k)‖) atTop (𝓝 ‖H0 x - H0 y‖) :=
      ((hcx.tendsto.comp hqt).sub (hcy.tendsto.comp hrt)).norm
    exact le_of_tendsto' ht fun k => hsym (q k) (r k) (hx.trans (hq k)) (hy.trans (hr k))
  have hcauchy : Cauchy (map H0 atTop) := by
    rw [Metric.cauchy_iff]
    refine ⟨inferInstance, fun ε hε => ?_⟩
    obtain ⟨K, -, hK⟩ := hR (ε / 2) (by positivity)
    refine ⟨H0 '' Set.Ioi K, image_mem_map (Ioi_mem_atTop K), ?_⟩
    rintro _ ⟨x, hx, rfl⟩ _ ⟨y, hy, rfl⟩
    rw [dist_eq_norm]
    exact (hK x y hx hy).trans_lt (by linarith)
  exact cauchy_map_iff_exists_tendsto.1 hcauchy

/-- Helper for node E02: the set where increments larger than `ε` occur arbitrarily far out
is null. -/
lemma measure_bad_set_eq_zero {Ω : Type*} [MeasurableSpace Ω] {ν : Measure Ω}
    [IsProbabilityMeasure ν] (H : Ω → ℝ → ℂ)
    (hmeas : ∀ s : ℚ, 0 < s → Measurable fun ω => H ω s) {B : ℝ}
    (hB : ∀ n : ℕ, 1 ≤ n → (∫⁻ ω, countingSup n (fun u v => ‖H ω v - H ω u‖ₑ) ^ (3 / 2 : ℝ)
      ∂ν) ^ (2 / 3 : ℝ) ≤ ENNReal.ofReal (B * √n)) {ε : ℝ} (hε : 0 < ε) :
    ν {ω | ∀ K : ℝ, ∃ u v : ℚ, K < u ∧ u < v ∧ ε < ‖H ω v - H ω u‖} = 0 := by
  set E := {ω | ∀ K : ℝ, ∃ u v : ℚ, K < u ∧ u < v ∧ ε < ‖H ω v - H ω u‖}
  set m : ℝ := ((ν E) ^ (2 / 3 : ℝ)).toReal
  have hm0 : 0 ≤ m := ENNReal.toReal_nonneg
  have key : ∀ n : ℕ, 1 ≤ n → m * n * ε ≤ max B 0 * √n := by
    intro n hn
    set S := fun ω => countingSup n (fun u v => ‖H ω v - H ω u‖ₑ)
    set c : ℝ≥0∞ := (n : ℝ≥0∞) * ENNReal.ofReal ε
    have hSm : Measurable S := measurable_countingSup_increments H hmeas n
    have hsub : E ⊆ {ω | c ^ (3 / 2 : ℝ) ≤ S ω ^ (3 / 2 : ℝ)} := by
      intro ω hω
      exact ENNReal.rpow_le_rpow (le_countingSup_of_large_increments (H ω) hω n) (by norm_num)
    have hmark := mul_meas_ge_le_lintegral₀ (μ := ν) (hSm.pow_const (3 / 2 : ℝ)).aemeasurable
      (c ^ (3 / 2 : ℝ))
    have h1 : c ^ (3 / 2 : ℝ) * ν E ≤ ∫⁻ ω, S ω ^ (3 / 2 : ℝ) ∂ν :=
      (mul_le_mul_right (measure_mono hsub) _).trans hmark
    have h2 : (c ^ (3 / 2 : ℝ) * ν E) ^ (2 / 3 : ℝ) ≤ ENNReal.ofReal (B * √n) :=
      (ENNReal.rpow_le_rpow h1 (by norm_num)).trans (hB n hn)
    rw [ENNReal.mul_rpow_of_nonneg _ _ (by norm_num), ← ENNReal.rpow_mul] at h2
    norm_num at h2
    have hcfin : c ≠ ⊤ := ENNReal.mul_ne_top (by simp) ENNReal.ofReal_ne_top
    have hEfin : ν E ^ (2 / 3 : ℝ) ≠ ⊤ :=
      ENNReal.rpow_ne_top_of_nonneg (by norm_num) (measure_ne_top ν E)
    have h3 := ENNReal.toReal_mono ENNReal.ofReal_ne_top h2
    rw [ENNReal.toReal_mul, ENNReal.toReal_ofReal', ENNReal.toReal_mul,
      ENNReal.toReal_ofReal hε.le] at h3
    simp only [ENNReal.toReal_natCast] at h3
    have : max (B * √n) 0 ≤ max B 0 * √n := by
      rcases le_total 0 B with hB0 | hB0
      · rw [max_eq_left hB0, max_eq_left (by positivity)]
      · rw [max_eq_right hB0, max_eq_right (mul_nonpos_of_nonpos_of_nonneg hB0 (by positivity))]
        simp
    nlinarith
  -- conclude `m = 0`
  have hmz : m = 0 := by
    by_contra hne
    have hmpos : 0 < m := lt_of_le_of_ne hm0 (Ne.symm hne)
    obtain ⟨n, hn⟩ := exists_nat_gt ((max B 0 / (m * ε)) ^ 2 + 1)
    have hn1 : 1 ≤ n := by
      have : (1 : ℝ) < n := by nlinarith [sq_nonneg (max B 0 / (m * ε))]
      exact_mod_cast this.le
    have hk := key n hn1
    have hsq : √(n : ℝ) * √n = n := Real.mul_self_sqrt (by positivity)
    have hsn : max B 0 / (m * ε) < √n := by
      rw [Real.lt_sqrt (by positivity)]; linarith
    have hpos : 0 < √(n : ℝ) := Real.sqrt_pos.2 (by exact_mod_cast hn1)
    rw [div_lt_iff₀ (by positivity)] at hsn
    have : m * n * ε = (√n * (m * ε)) * √n := by
      calc m * n * ε = m * (√n * √n) * ε := by rw [hsq]
        _ = _ := by ring
    rw [this] at hk
    have := (mul_le_mul_iff_left₀ hpos).1 hk
    linarith
  have : ν E ^ (2 / 3 : ℝ) = 0 := by
    rcases (ENNReal.toReal_eq_zero_iff _).1 hmz with h | h
    · exact h
    · exact absurd h (ENNReal.rpow_ne_top_of_nonneg (by norm_num) (measure_ne_top ν E))
  rcases ENNReal.rpow_eq_zero_iff.1 this with h | h
  · exact h.1
  · exact absurd h.1 (measure_ne_top ν E)

/-- **Lemma "Counting gives a limit" (node E02).** Let `(Ω, ν)` be a probability space and
`H_ω : (0, ∞) → ℂ` continuous for each `ω`, with `ω ↦ H_ω(s)` measurable for positive rational
`s`. If the counting functions `S_n(ω) = sup_I ∑_{(u,v) ∈ I} |H_ω(v) - H_ω(u)|` (over lists
of at most `n` disjoint rational intervals) satisfy `‖S_n‖_{3/2} ≤ B √n` for all `n ≥ 1`, then
`H_ω(s)` has a finite limit as `s → ∞` for almost every `ω`. -/
theorem square_root_counting_implies_ae_Cauchy {Ω : Type*} [MeasurableSpace Ω] {ν : Measure Ω}
    [IsProbabilityMeasure ν] (H : Ω → ℝ → ℂ) (hcont : ∀ ω, ContinuousOn (H ω) (Set.Ioi 0))
    (hmeas : ∀ s : ℚ, 0 < s → Measurable fun ω => H ω s) {B : ℝ}
    (hB : ∀ n : ℕ, 1 ≤ n → (∫⁻ ω, countingSup n (fun u v => ‖H ω v - H ω u‖ₑ) ^ (3 / 2 : ℝ)
      ∂ν) ^ (2 / 3 : ℝ) ≤ ENNReal.ofReal (B * √n)) :
    ∀ᵐ ω ∂ν, ∃ L, Tendsto (H ω) atTop (𝓝 L) := by
  have hnull : ∀ j : ℕ, ∀ᵐ ω ∂ν, ¬ ∀ K : ℝ, ∃ u v : ℚ, K < u ∧ u < v ∧
      1 / ((j : ℝ) + 1) < ‖H ω v - H ω u‖ := fun j =>
    measure_eq_zero_iff_ae_notMem.1 (measure_bad_set_eq_zero H hmeas hB (by positivity))
  filter_upwards [ae_all_iff.2 hnull] with ω hω
  refine exists_tendsto_of_rat_cauchy (H ω) (hcont ω) fun ε hε => ?_
  obtain ⟨j, hj⟩ := exists_nat_one_div_lt hε
  have := hω j
  push Not at this
  obtain ⟨K, hK⟩ := this
  exact ⟨K, fun u v hu huv => (hK u v hu huv).trans hj.le⟩

end E02

end

end Auto
