/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib
public import TwoCommuting.Auto.Sec6EuclideanCounting

/-!
# Transference to commuting real flows

This file was automatically generated by Claude.

Formalization of §7 ("Transference to commuting real flows", node F01) of
`blueprint/commuting_ergodic_blueprint.tex`.

## Contents

* `CommutingFlows`: commuting, jointly measurable, measure-preserving real flows.
* `flowBilin`: the flow bilinear operator `B^Ω_K(f,g)(ω) = ∫ f(U^t ω) g(V^t ω) K(t) dt`.
* F01 (`flow_counting_bound`): the counting estimate for commuting flows, transferred from the
  Euclidean estimate E01.
-/

@[expose] public section

open scoped ENNReal NNReal
open MeasureTheory Filter Topology

namespace Auto

noncomputable section

/-- The statement of Theorem 6.1 (node E01). -/
def E01Statement : Prop :=
  ∃ C : ℝ, 0 ≤ C ∧ ∀ m : ℕ, (m = 3 ∨ m = 4) → ∀ n : ℕ, 1 ≤ n →
    ∀ F G : ℝ × ℝ → ℂ, Measurable F → Measurable G → MemLp F 3 → MemLp G 3 →
      (∫⁻ p, countingSup n (fun u v => ‖bilinKernel (KernC m u v) F G p‖ₑ) ^ (3 / 2 : ℝ)) ^
        (2 / 3 : ℝ) ≤ ENNReal.ofReal (C * √n) * eLpNorm F 3 * eLpNorm G 3

/-- Commuting jointly measurable measure-preserving real flows (setting of §7). The identity
`U⁰ = id` is not required (in the suspension of node T01 it holds only almost everywhere). -/
structure CommutingFlows {Ω : Type*} [MeasurableSpace Ω] (ν : Measure Ω) (U V : ℝ → Ω → Ω) :
    Prop where
  measU : Measurable fun p : ℝ × Ω => U p.1 p.2
  measV : Measurable fun p : ℝ × Ω => V p.1 p.2
  mpU : ∀ t, MeasurePreserving (U t) ν ν
  mpV : ∀ t, MeasurePreserving (V t) ν ν
  addU : ∀ s t ω, U (s + t) ω = U s (U t ω)
  addV : ∀ s t ω, V (s + t) ω = V s (V t ω)
  comm : ∀ s t ω, U s (V t ω) = V t (U s ω)

/-- The flow bilinear operator `B^Ω_K(f,g)(ω) = ∫ f(U^t ω) g(V^t ω) K(t) dt`. -/
def flowBilin {Ω : Type*} (U V : ℝ → Ω → Ω) (K : ℝ → ℂ) (f g : Ω → ℂ) (ω : Ω) : ℂ :=
  ∫ t, f (U t ω) * g (V t ω) * K t

/-- The statement of Proposition 7.1 (node F01). -/
def F01Statement : Prop :=
  ∃ C : ℝ, 0 ≤ C ∧ ∀ (Ω : Type) [MeasurableSpace Ω] (ν : Measure Ω) [IsProbabilityMeasure ν]
    (U V : ℝ → Ω → Ω), CommutingFlows ν U V → ∀ m : ℕ, (m = 3 ∨ m = 4) → ∀ n : ℕ, 1 ≤ n →
    ∀ f g : Ω → ℂ, Measurable f → Measurable g → (∃ B, ∀ ω, ‖f ω‖ ≤ B) → (∃ B, ∀ ω, ‖g ω‖ ≤ B) →
      (∫⁻ ω, countingSup n (fun u v => ‖flowBilin U V (KernC m u v) f g ω‖ₑ) ^ (3 / 2 : ℝ) ∂ν) ^
        (2 / 3 : ℝ) ≤ ENNReal.ofReal (C * √n) * eLpNorm f 3 ν * eLpNorm g 3 ν


/-- Theorem 6.1 (node E01) in the packaged form `E01Statement`. -/
theorem E01_holds : E01Statement := Euclidean_counting_bound

section FlowTransfer

/-- The interval kernels `K^{(m)}_{u,v}` with `0 < u ≤ v` are measurable and integrable. -/
lemma KernC_measurable_integrable (m : ℕ) {u v : ℝ} (hu : 0 < u) (huv : u ≤ v) :
    Measurable (KernC m u v) ∧ Integrable (KernC m u v) :=
  ⟨Complex.measurable_ofReal.comp (continuous_Kern m hu huv).measurable,
    (integrable_Kern m hu huv).1.ofReal⟩

/-- The square `Q_R = [-R, R]²`. -/
def flowSq (R : ℝ) : Set (ℝ × ℝ) := Set.Icc (-R) R ×ˢ Set.Icc (-R) R

lemma measurableSet_flowSq (R : ℝ) : MeasurableSet (flowSq R) :=
  measurableSet_Icc.prod measurableSet_Icc

lemma volume_flowSq (R : ℝ) :
    volume (flowSq R) = ENNReal.ofReal (2 * R) * ENNReal.ofReal (2 * R) := by
  rw [flowSq, Measure.volume_eq_prod, Measure.prod_prod, Real.volume_Icc]
  ring_nf

lemma volume_flowSq_ne_top (R : ℝ) : volume (flowSq R) ≠ ∞ := by
  rw [volume_flowSq]; exact ENNReal.mul_ne_top ENNReal.ofReal_ne_top ENNReal.ofReal_ne_top

lemma volume_flowSq_ne_zero {R : ℝ} (hR : 0 < R) : volume (flowSq R) ≠ 0 := by
  rw [volume_flowSq]
  have : ENNReal.ofReal (2 * R) ≠ 0 := by
    rw [Ne, ENNReal.ofReal_eq_zero]; push Not; linarith
  exact mul_ne_zero this this

lemma volume_flowSq_add {M L : ℝ} (hM : 0 < M) (hL : 0 ≤ L) :
    volume (flowSq (M + L)) = ENNReal.ofReal ((1 + L / M) ^ 2) * volume (flowSq M) := by
  have h1 : 0 ≤ 1 + L / M := by positivity
  have e : 2 * (M + L) = (1 + L / M) * (2 * M) := by field_simp
  rw [volume_flowSq, volume_flowSq, e, ENNReal.ofReal_mul h1, sq, ENNReal.ofReal_mul h1]
  ring

lemma add_mem_flowSq {M L : ℝ} {p : ℝ × ℝ} (hp : p ∈ flowSq M) {t : ℝ}
    (ht : t ∈ Set.Icc (-L) L) :
    (p.1 + t, p.2) ∈ flowSq (M + L) ∧ (p.1, p.2 + t) ∈ flowSq (M + L) := by
  simp only [flowSq, Set.mem_prod, Set.mem_Icc] at hp ht ⊢
  refine ⟨⟨⟨?_, ?_⟩, ?_, ?_⟩, ⟨?_, ?_⟩, ?_, ?_⟩ <;> linarith

variable {Ω : Type*} [MeasurableSpace Ω] {ν : Measure Ω} {U V : ℝ → Ω → Ω}

open Classical in
/-- The orbit function `F_ω(u, v) = f(U^u V^v ω) 1_{Q_R}(u, v)`. -/
def orbitFun (U V : ℝ → Ω → Ω) (f : Ω → ℂ) (R : ℝ) (ω : Ω) (x : ℝ × ℝ) : ℂ :=
  if x ∈ flowSq R then f (U x.1 (V x.2 ω)) else 0

lemma measurable_flowPhi (hC : CommutingFlows ν U V) :
    Measurable fun z : Ω × (ℝ × ℝ) => U z.2.1 (V z.2.2 z.1) :=
  hC.measU.comp (measurable_snd.fst.prodMk
    (hC.measV.comp (measurable_snd.snd.prodMk measurable_fst)))

lemma measurable_orbitFun_joint (hC : CommutingFlows ν U V) {f : Ω → ℂ} (hf : Measurable f)
    (R : ℝ) : Measurable fun z : Ω × (ℝ × ℝ) => orbitFun U V f R z.1 z.2 := by
  unfold orbitFun
  exact Measurable.ite (measurable_snd (measurableSet_flowSq R)) (hf.comp (measurable_flowPhi hC))
    measurable_const

lemma measurable_orbitFun (hC : CommutingFlows ν U V) {f : Ω → ℂ} (hf : Measurable f)
    (R : ℝ) (ω : Ω) : Measurable (orbitFun U V f R ω) :=
  (measurable_orbitFun_joint hC hf R).comp
    (measurable_const.prodMk measurable_id : Measurable fun x : ℝ × ℝ => (ω, x))

omit [MeasurableSpace Ω] in
lemma norm_orbitFun_le {f : Ω → ℂ} {B : ℝ} (hB : ∀ ω, ‖f ω‖ ≤ B) (R : ℝ) (ω : Ω)
    (x : ℝ × ℝ) : ‖orbitFun U V f R ω x‖ ≤ B := by
  have hB0 : 0 ≤ B := (norm_nonneg _).trans (hB ω)
  unfold orbitFun; split_ifs
  · exact hB _
  · simpa using hB0

lemma memLp_orbitFun (hC : CommutingFlows ν U V) {f : Ω → ℂ} (hf : Measurable f) {B : ℝ}
    (hB : ∀ ω, ‖f ω‖ ≤ B) (R : ℝ) (ω : Ω) : MemLp (orbitFun U V f R ω) 3 := by
  have hB0 : 0 ≤ B := (norm_nonneg _).trans (hB ω)
  refine MemLp.of_le (memLp_indicator_const 3 (measurableSet_flowSq R).nullMeasurableSet B
    (Or.inr (volume_flowSq_ne_top R))) (measurable_orbitFun hC hf R ω).aestronglyMeasurable
    (Eventually.of_forall fun x => ?_)
  by_cases hx : x ∈ flowSq R
  · simp only [orbitFun, hx, ↓reduceIte, Set.indicator_of_mem hx, Real.norm_eq_abs, abs_of_nonneg hB0]
    exact hB _
  · simp [orbitFun, hx]

lemma measurable_flowBilin (hC : CommutingFlows ν U V) {K : ℝ → ℂ} (hK : Measurable K)
    {f g : Ω → ℂ} (hf : Measurable f) (hg : Measurable g) :
    Measurable (flowBilin U V K f g) := by
  have hj : Measurable fun z : Ω × ℝ => f (U z.2 z.1) * g (V z.2 z.1) * K z.2 :=
    ((hf.comp (hC.measU.comp (measurable_snd.prodMk measurable_fst))).mul
      (hg.comp (hC.measV.comp (measurable_snd.prodMk measurable_fst)))).mul
      (hK.comp measurable_snd)
  exact (hj.stronglyMeasurable.integral_prod_right' (ν := volume)).measurable

lemma measurable_bilinKernel_orbit (hC : CommutingFlows ν U V) {K : ℝ → ℂ} (hK : Measurable K)
    {f g : Ω → ℂ} (hf : Measurable f) (hg : Measurable g) (R : ℝ) :
    Measurable fun z : Ω × (ℝ × ℝ) =>
      bilinKernel K (orbitFun U V f R z.1) (orbitFun U V g R z.1) z.2 := by
  have hF := measurable_orbitFun_joint hC hf R
  have hG := measurable_orbitFun_joint hC hg R
  have hj : Measurable fun w : (Ω × (ℝ × ℝ)) × ℝ =>
      orbitFun U V f R w.1.1 (w.1.2.1 + w.2, w.1.2.2) *
        orbitFun U V g R w.1.1 (w.1.2.1, w.1.2.2 + w.2) * K w.2 := by
    refine (Measurable.mul ?_ ?_).mul (hK.comp measurable_snd)
    · exact hF.comp (f := fun w : (Ω × (ℝ × ℝ)) × ℝ => (w.1.1, (w.1.2.1 + w.2, w.1.2.2)))
        (by fun_prop)
    · exact hG.comp (f := fun w : (Ω × (ℝ × ℝ)) × ℝ => (w.1.1, (w.1.2.1, w.1.2.2 + w.2)))
        (by fun_prop)
  exact (hj.stronglyMeasurable.integral_prod_right' (ν := volume)).measurable

/-- The list sums of the flow counting function. -/
def flowList (m : ℕ) (U V : ℝ → Ω → Ω) (f g : Ω → ℂ) {n : ℕ} (I : RatIntervalList n)
    (ω : Ω) : ℝ≥0∞ :=
  (I.l.map fun q => ‖flowBilin U V (KernC m q.1 q.2) f g ω‖ₑ).sum

/-- The list sums of the Euclidean counting function. -/
def euclList (m : ℕ) (F G : ℝ × ℝ → ℂ) {n : ℕ} (I : RatIntervalList n) (x : ℝ × ℝ) : ℝ≥0∞ :=
  (I.l.map fun q => ‖bilinKernel (KernC m q.1 q.2) F G x‖ₑ).sum

lemma list_sum_map_le_add {α : Type*} (l : List α) (a b : α → ℝ≥0∞) (δ : ℝ≥0∞)
    (h : ∀ q ∈ l, a q ≤ b q + δ) : (l.map a).sum ≤ (l.map b).sum + l.length * δ := by
  induction l with
  | nil => simp
  | cons q l ih =>
    simp only [List.map_cons, List.sum_cons, List.length_cons, Nat.cast_succ]
    have h1 := h q List.mem_cons_self
    have h2 := ih fun r hr => h r (List.mem_cons_of_mem _ hr)
    calc a q + (l.map a).sum ≤ (b q + δ) + ((l.map b).sum + l.length * δ) := add_le_add h1 h2
      _ = _ := by ring

lemma measurable_list_sum_map {X : Type*} [MeasurableSpace X] {α : Type*} (l : List α)
    (h : α → X → ℝ≥0∞) (hm : ∀ q ∈ l, Measurable (h q)) :
    Measurable fun x => (l.map fun q => h q x).sum := by
  induction l with
  | nil => simp
  | cons q l ih =>
    simp only [List.map_cons, List.sum_cons]
    exact (hm q List.mem_cons_self).add (ih fun r hr => hm r (List.mem_cons_of_mem _ hr))

lemma measurable_finset_sup_enn {X : Type*} [MeasurableSpace X] {ι : Type*} (s : Finset ι)
    (h : ι → X → ℝ≥0∞) (hm : ∀ i ∈ s, Measurable (h i)) :
    Measurable fun x => s.sup fun i => h i x := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | insert i s hi ih =>
    simp only [Finset.sup_insert]
    exact (hm i (Finset.mem_insert_self _ _)).sup
      (ih fun j hj => hm j (Finset.mem_insert_of_mem hj))

lemma measurable_flowList (hC : CommutingFlows ν U V) (m : ℕ) {f g : Ω → ℂ}
    (hf : Measurable f) (hg : Measurable g) {n : ℕ} (I : RatIntervalList n) :
    Measurable (flowList m U V f g I) := by
  unfold flowList
  refine measurable_list_sum_map I.l (fun q ω => ‖flowBilin U V (KernC m q.1 q.2) f g ω‖ₑ)
    fun q hq => ?_
  have hq1 : (0 : ℝ) < q.1 := by exact_mod_cast I.pos q hq
  have hq2 : (q.1 : ℝ) ≤ q.2 := by exact_mod_cast (I.lt q hq).le
  exact (measurable_flowBilin hC (KernC_measurable_integrable m hq1 hq2).1 hf hg).enorm

lemma integrable_bdd_kernel_mul {φ : ℝ → ℂ} (hφ : Measurable φ) {B : ℝ}
    (hB : ∀ t, ‖φ t‖ ≤ B) {K : ℝ → ℂ} (hK : Integrable K) :
    Integrable fun t => φ t * K t :=
  hK.bdd_mul (c := B) hφ.aestronglyMeasurable (Eventually.of_forall hB)

lemma norm_mul_le_of_le {a b : ℂ} {A B : ℝ} (ha : ‖a‖ ≤ A) (hb : ‖b‖ ≤ B) :
    ‖a * b‖ ≤ A * B := by
  rw [norm_mul]; exact mul_le_mul ha hb (norm_nonneg _) ((norm_nonneg _).trans ha)

/-- **Comparison of the flow and Euclidean outputs** (proof of node F01): on `Q_M`, the
Euclidean operator applied to the orbit functions on `Q_{M+L}` differs from the flow operator
at `U^u V^v ω` by at most `‖f‖_∞ ‖g‖_∞` times the `L¹` tail of the kernel outside `[-L, L]`. -/
lemma flow_eucl_diff (hC : CommutingFlows ν U V) {f g : Ω → ℂ} (hf : Measurable f)
    (hg : Measurable g) {Bf Bg : ℝ} (hBf : ∀ ω, ‖f ω‖ ≤ Bf) (hBg : ∀ ω, ‖g ω‖ ≤ Bg)
    {K : ℝ → ℂ} (hK : Integrable K) {M L : ℝ} (ω : Ω) {p : ℝ × ℝ} (hp : p ∈ flowSq M) :
    ‖flowBilin U V K f g (U p.1 (V p.2 ω)) -
        bilinKernel K (orbitFun U V f (M + L) ω) (orbitFun U V g (M + L) ω) p‖ₑ ≤
      ENNReal.ofReal (Bf * Bg) * ∫⁻ t in (Set.Icc (-L) L)ᶜ, ‖K t‖ₑ := by
  set x := U p.1 (V p.2 ω)
  have hmU : Measurable fun t : ℝ => U t x := hC.measU.comp (measurable_id.prodMk measurable_const)
  have hmV : Measurable fun t : ℝ => V t x := hC.measV.comp (measurable_id.prodMk measurable_const)
  have hint1 : Integrable fun t => f (U t x) * g (V t x) * K t :=
    integrable_bdd_kernel_mul ((hf.comp hmU).mul (hg.comp hmV))
      (fun t => norm_mul_le_of_le (hBf _) (hBg _)) hK
  have hint2 : Integrable fun t => orbitFun U V f (M + L) ω (p.1 + t, p.2) *
      orbitFun U V g (M + L) ω (p.1, p.2 + t) * K t :=
    integrable_bdd_kernel_mul
      (((measurable_orbitFun hC hf (M + L) ω).comp (by fun_prop)).mul
        ((measurable_orbitFun hC hg (M + L) ω).comp (by fun_prop)))
      (fun t => norm_mul_le_of_le (norm_orbitFun_le hBf _ _ _) (norm_orbitFun_le hBg _ _ _)) hK
  rw [flowBilin, bilinKernel, ← integral_sub hint1 hint2,
    ← lintegral_const_mul' _ _ ENNReal.ofReal_ne_top,
    ← lintegral_indicator measurableSet_Icc.compl]
  refine (enorm_integral_le_lintegral_enorm _).trans (lintegral_mono fun t => ?_)
  by_cases h : (p.1 + t, p.2) ∈ flowSq (M + L) ∧ (p.1, p.2 + t) ∈ flowSq (M + L)
  · have e : orbitFun U V f (M + L) ω (p.1 + t, p.2) * orbitFun U V g (M + L) ω (p.1, p.2 + t) *
        K t = f (U t x) * g (V t x) * K t := by
      simp only [orbitFun, h.1, h.2, ↓reduceIte, x]
      rw [add_comm p.1 t, hC.addU t p.1, add_comm p.2 t, hC.addV t p.2, hC.comm p.1 t]
    rw [e, sub_self, enorm_zero]; exact zero_le
  · have ht : t ∈ (Set.Icc (-L) L)ᶜ := fun ht => h (add_mem_flowSq hp ht)
    have e : orbitFun U V f (M + L) ω (p.1 + t, p.2) * orbitFun U V g (M + L) ω (p.1, p.2 + t) *
        K t = 0 := by
      rw [not_and_or] at h
      rcases h with h | h <;> simp [orbitFun, h]
    rw [e, sub_zero, Set.indicator_of_mem ht, enorm_mul]
    gcongr
    rw [← ofReal_norm]
    exact ENNReal.ofReal_le_ofReal (norm_mul_le_of_le (hBf _) (hBg _))

/-- `L¹` tails of an integrable kernel tend to zero. -/
lemma tendsto_tail_lintegral {K : ℝ → ℂ} (hKm : Measurable K) (hK : Integrable K) :
    Tendsto (fun L : ℝ => ∫⁻ t in (Set.Icc (-L) L)ᶜ, ‖K t‖ₑ) atTop (𝓝 0) := by
  have h := tendsto_lintegral_filter_of_dominated_convergence (μ := volume) (l := atTop)
    (F := fun L t => (Set.Icc (-L) L)ᶜ.indicator (fun t => ‖K t‖ₑ) t) (f := fun _ => 0)
    (fun t => ‖K t‖ₑ) (Eventually.of_forall fun L => hKm.enorm.indicator measurableSet_Icc.compl)
    (Eventually.of_forall fun L => Eventually.of_forall fun t => Set.indicator_le_self _ _ t)
    hK.2.ne (Eventually.of_forall fun t => tendsto_const_nhds.congr' ?_)
  · simpa [lintegral_indicator measurableSet_Icc.compl] using h
  · filter_upwards [eventually_ge_atTop |t|] with L hL
    rw [Set.indicator_of_notMem]
    simp only [Set.mem_compl_iff, not_not, Set.mem_Icc]
    exact abs_le.mp hL

/-- Choice of `L` for a finite family of interval lists. -/
lemma exists_tail_bound (m : ℕ) {n : ℕ} (𝓕 : Finset (RatIntervalList n)) {δ : ℝ≥0∞}
    (hδ : 0 < δ) : ∃ L : ℝ, 0 ≤ L ∧
      ∀ I ∈ 𝓕, ∀ q ∈ I.l, ∫⁻ t in (Set.Icc (-L) L)ᶜ, ‖KernC m q.1 q.2 t‖ₑ ≤ δ := by
  classical
  set P := 𝓕.biUnion fun I => I.l.toFinset
  have hP : ∀ q ∈ P, ∀ᶠ L in atTop, ∫⁻ t in (Set.Icc (-L) L)ᶜ, ‖KernC m q.1 q.2 t‖ₑ ≤ δ := by
    intro q hq
    obtain ⟨I, -, hqI⟩ := Finset.mem_biUnion.1 hq
    have hq' := List.mem_toFinset.1 hqI
    have hq1 : (0 : ℝ) < q.1 := by exact_mod_cast I.pos q hq'
    have hq2 : (q.1 : ℝ) ≤ q.2 := by exact_mod_cast (I.lt q hq').le
    obtain ⟨hm, hi⟩ := KernC_measurable_integrable m hq1 hq2
    exact ((tendsto_order.1 (tendsto_tail_lintegral hm hi)).2 δ hδ).mono fun L hL => hL.le
  obtain ⟨L, hL1, hL2⟩ := (((Filter.eventually_all_finset P).2 hP).and
    (eventually_ge_atTop 0)).exists
  exact ⟨L, hL2, fun I hI q hq => hL1 q (Finset.mem_biUnion.2 ⟨I, hI, List.mem_toFinset.2 hq⟩)⟩

lemma eLpNorm_three_rpow {X : Type*} [MeasurableSpace X] {F : X → ℂ} {μ : Measure X}
    (hF : AEStronglyMeasurable F μ) :
    eLpNorm F 3 μ ^ (3 : ℝ) = ∫⁻ x, ‖F x‖ₑ ^ (3 : ℝ) ∂μ := by
  rw [eLpNorm_eq_lintegral_rpow_enorm_toReal (by norm_num) (by norm_num) hF, ← ENNReal.rpow_mul]
  norm_num

lemma measurable_eLpNorm_orbitFun (hC : CommutingFlows ν U V) {f : Ω → ℂ}
    (hf : Measurable f) (R : ℝ) :
    Measurable fun ω => eLpNorm (orbitFun U V f R ω) 3 volume := by
  have e : (fun ω => eLpNorm (orbitFun U V f R ω) 3 volume) =
      fun ω => (∫⁻ x, ‖orbitFun U V f R ω x‖ₑ ^ (3 : ℝ)) ^ (1 / (3 : ℝ)) := by
    funext ω
    rw [eLpNorm_eq_lintegral_rpow_enorm_toReal (by norm_num) (by norm_num)
      (measurable_orbitFun hC hf R ω).aestronglyMeasurable]
    norm_num
  rw [e]
  exact (((measurable_orbitFun_joint hC hf R).enorm.pow_const _).lintegral_prod_right').pow_const _

/-- Tonelli and invariance: `∫ ‖F_ω‖₃³ dν = |Q_R| ‖f‖₃³`. -/
lemma lintegral_eLpNorm_orbitFun [SFinite ν] (hC : CommutingFlows ν U V) {f : Ω → ℂ}
    (hf : Measurable f) (R : ℝ) :
    ∫⁻ ω, eLpNorm (orbitFun U V f R ω) 3 volume ^ (3 : ℝ) ∂ν =
      volume (flowSq R) * eLpNorm f 3 ν ^ (3 : ℝ) := by
  have h3 : ∀ ω, eLpNorm (orbitFun U V f R ω) 3 volume ^ (3 : ℝ) =
      ∫⁻ x, ‖orbitFun U V f R ω x‖ₑ ^ (3 : ℝ) := fun ω =>
    eLpNorm_three_rpow (measurable_orbitFun hC hf R ω).aestronglyMeasurable
  simp_rw [h3, eLpNorm_three_rpow hf.aestronglyMeasurable]
  have hj : Measurable fun z : Ω × (ℝ × ℝ) => ‖orbitFun U V f R z.1 z.2‖ₑ ^ (3 : ℝ) :=
    (measurable_orbitFun_joint hC hf R).enorm.pow_const _
  rw [lintegral_lintegral_swap (f := fun ω x => ‖orbitFun U V f R ω x‖ₑ ^ (3 : ℝ))
    hj.aemeasurable]
  have h : ∀ x, ∫⁻ ω, ‖orbitFun U V f R ω x‖ₑ ^ (3 : ℝ) ∂ν =
      (flowSq R).indicator (fun _ => ∫⁻ ω, ‖f ω‖ₑ ^ (3 : ℝ) ∂ν) x := by
    intro x
    by_cases hx : x ∈ flowSq R
    · simp only [orbitFun, hx, ↓reduceIte, Set.indicator_of_mem]
      exact ((hC.mpU x.1).comp (hC.mpV x.2)).lintegral_comp (hf.enorm.pow_const _)
    · simp [orbitFun, hx]
  simp_rw [h]
  rw [lintegral_indicator_const (measurableSet_flowSq R), mul_comm]

/-- Cauchy–Schwarz in `ω` for the products of the orbit norms. -/
lemma lintegral_cs_three_halves {X : Type*} [MeasurableSpace X] {μ : Measure X}
    {a b : X → ℝ≥0∞} (ha : AEMeasurable a μ) (hb : AEMeasurable b μ) (A V na nb : ℝ≥0∞)
    (hA : ∫⁻ x, a x ^ (3 : ℝ) ∂μ = V * na ^ (3 : ℝ))
    (hB : ∫⁻ x, b x ^ (3 : ℝ) ∂μ = V * nb ^ (3 : ℝ)) :
    ∫⁻ x, (A * a x * b x) ^ (3 / 2 : ℝ) ∂μ ≤ (A * na * nb) ^ (3 / 2 : ℝ) * V := by
  have e1 : ∀ x, (A * a x * b x) ^ (3 / 2 : ℝ) =
      A ^ (3 / 2 : ℝ) * (a x ^ (3 / 2 : ℝ) * b x ^ (3 / 2 : ℝ)) := by
    intro x
    rw [ENNReal.mul_rpow_of_nonneg _ _ (by norm_num), ENNReal.mul_rpow_of_nonneg _ _ (by norm_num),
      mul_assoc]
  simp_rw [e1]
  rw [lintegral_const_mul'' (f := fun x => a x ^ (3 / 2 : ℝ) * b x ^ (3 / 2 : ℝ)) _
    ((ha.pow_const _).mul (hb.pow_const _))]
  have hcs := ENNReal.lintegral_mul_le_Lp_mul_Lq μ Real.HolderConjugate.two_two
    (ha.pow_const (3 / 2 : ℝ)) (hb.pow_const (3 / 2 : ℝ))
  have e2 : ∀ y : ℝ≥0∞, (y ^ (3 / 2 : ℝ)) ^ (2 : ℝ) = y ^ (3 : ℝ) := fun y => by
    rw [← ENNReal.rpow_mul]; norm_num
  simp only [Pi.mul_apply, e2, hA, hB] at hcs
  have hV : V ^ (1 / 2 : ℝ) * V ^ (1 / 2 : ℝ) = V := by
    rw [← ENNReal.rpow_add_of_nonneg _ _ (by norm_num) (by norm_num)]; norm_num
  have hsq : ∀ c : ℝ≥0∞, (V * c ^ (3 : ℝ)) ^ (1 / 2 : ℝ) = V ^ (1 / 2 : ℝ) * c ^ (3 / 2 : ℝ) := by
    intro c; rw [ENNReal.mul_rpow_of_nonneg _ _ (by norm_num), ← ENNReal.rpow_mul]; norm_num
  calc A ^ (3 / 2 : ℝ) * ∫⁻ x, a x ^ (3 / 2 : ℝ) * b x ^ (3 / 2 : ℝ) ∂μ
      ≤ A ^ (3 / 2 : ℝ) * ((V * na ^ (3 : ℝ)) ^ (1 / 2 : ℝ) * (V * nb ^ (3 : ℝ)) ^ (1 / 2 : ℝ)) := by
        gcongr
    _ = A ^ (3 / 2 : ℝ) * na ^ (3 / 2 : ℝ) * nb ^ (3 / 2 : ℝ) *
          (V ^ (1 / 2 : ℝ) * V ^ (1 / 2 : ℝ)) := by rw [hsq, hsq]; ring
    _ = (A * na * nb) ^ (3 / 2 : ℝ) * V := by
        rw [hV, ENNReal.mul_rpow_of_nonneg _ _ (by norm_num),
          ENNReal.mul_rpow_of_nonneg _ _ (by norm_num)]

/-- The Euclidean counting estimate (node E01) applied on one orbit, restricted to a finite
family of interval lists and to a set `S`. -/
lemma orbit_E01 {m n : ℕ} {A : ℝ≥0∞}
    (hE : ∀ F G : ℝ × ℝ → ℂ, Measurable F → Measurable G → MemLp F 3 → MemLp G 3 →
      (∫⁻ p, countingSup n (fun u v => ‖bilinKernel (KernC m u v) F G p‖ₑ) ^ (3 / 2 : ℝ)) ^
        (2 / 3 : ℝ) ≤ A * eLpNorm F 3 * eLpNorm G 3)
    {F G : ℝ × ℝ → ℂ} (hF : Measurable F) (hG : Measurable G) (hF3 : MemLp F 3)
    (hG3 : MemLp G 3) (𝓕 : Finset (RatIntervalList n)) (S : Set (ℝ × ℝ)) :
    ∫⁻ x in S, (𝓕.sup fun I => euclList m F G I x) ^ (3 / 2 : ℝ) ≤
      (A * eLpNorm F 3 * eLpNorm G 3) ^ (3 / 2 : ℝ) := by
  calc ∫⁻ x in S, (𝓕.sup fun I => euclList m F G I x) ^ (3 / 2 : ℝ)
      ≤ ∫⁻ x, countingSup n (fun u v => ‖bilinKernel (KernC m u v) F G x‖ₑ) ^ (3 / 2 : ℝ) := by
        refine (setLIntegral_le_lintegral _ _).trans (lintegral_mono fun x => ?_)
        refine ENNReal.rpow_le_rpow (Finset.sup_le fun I _ => ?_) (by norm_num)
        exact le_iSup (fun I : RatIntervalList n => euclList m F G I x) I
    _ = ((∫⁻ x, countingSup n (fun u v => ‖bilinKernel (KernC m u v) F G x‖ₑ) ^ (3 / 2 : ℝ)) ^
          (2 / 3 : ℝ)) ^ (3 / 2 : ℝ) := by
        rw [← ENNReal.rpow_mul]; norm_num
    _ ≤ _ := ENNReal.rpow_le_rpow (hE F G hF hG hF3 hG3) (by norm_num)

lemma measurable_euclList_orbit (hC : CommutingFlows ν U V) (m : ℕ) {f g : Ω → ℂ}
    (hf : Measurable f) (hg : Measurable g) (R : ℝ) {n : ℕ} (I : RatIntervalList n) :
    Measurable fun z : Ω × (ℝ × ℝ) =>
      euclList m (orbitFun U V f R z.1) (orbitFun U V g R z.1) I z.2 := by
  unfold euclList
  refine measurable_list_sum_map (X := Ω × (ℝ × ℝ)) I.l _ fun q hq => ?_
  have hq1 : (0 : ℝ) < q.1 := by exact_mod_cast I.pos q hq
  have hq2 : (q.1 : ℝ) ≤ q.2 := by exact_mod_cast (I.lt q hq).le
  exact (measurable_bilinKernel_orbit hC (KernC_measurable_integrable m hq1 hq2).1 hf hg R).enorm

lemma enorm_le_add_enorm_sub (a b : ℂ) : ‖a‖ₑ ≤ ‖b‖ₑ + ‖a - b‖ₑ := by
  calc ‖a‖ₑ = ‖b + (a - b)‖ₑ := by rw [add_sub_cancel]
    _ ≤ ‖b‖ₑ + ‖a - b‖ₑ := enorm_add_le _ _

/-- **Proof of node F01, main step**: the transference inequality for a finite family of
interval lists, with fixed truncation parameters `L` (tails) and `M` (size of the square):
`‖S_{n,𝓕}^Ω‖_{3/2} ≤ C √n (|Q_{M+L}|/|Q_M|)^{2/3} ‖f‖₃ ‖g‖₃ + n ‖f‖_∞ ‖g‖_∞ δ`. -/
lemma flow_core_ML [IsProbabilityMeasure ν] (hC : CommutingFlows ν U V) {m n : ℕ} {A : ℝ≥0∞}
    (hE : ∀ F G : ℝ × ℝ → ℂ, Measurable F → Measurable G → MemLp F 3 → MemLp G 3 →
      (∫⁻ p, countingSup n (fun u v => ‖bilinKernel (KernC m u v) F G p‖ₑ) ^ (3 / 2 : ℝ)) ^
        (2 / 3 : ℝ) ≤ A * eLpNorm F 3 * eLpNorm G 3)
    {f g : Ω → ℂ} (hf : Measurable f) (hg : Measurable g) {Bf Bg : ℝ}
    (hBf : ∀ ω, ‖f ω‖ ≤ Bf) (hBg : ∀ ω, ‖g ω‖ ≤ Bg) (𝓕 : Finset (RatIntervalList n))
    {M L : ℝ} (hM : 0 < M) (hL : 0 ≤ L) {δ : ℝ≥0∞}
    (htail : ∀ I ∈ 𝓕, ∀ q ∈ I.l, ∫⁻ t in (Set.Icc (-L) L)ᶜ, ‖KernC m q.1 q.2 t‖ₑ ≤ δ) :
    (∫⁻ ω, (𝓕.sup fun I => flowList m U V f g I ω) ^ (3 / 2 : ℝ) ∂ν) ^ (2 / 3 : ℝ) ≤
      A * eLpNorm f 3 ν * eLpNorm g 3 ν * ENNReal.ofReal ((1 + L / M) ^ 2) +
        n * (ENNReal.ofReal (Bf * Bg) * δ) := by
  set s : Ω → ℝ≥0∞ := fun ω => 𝓕.sup fun I => flowList m U V f g I ω with hs_def
  have hs : Measurable s :=
    measurable_finset_sup_enn 𝓕 _ fun I _ => measurable_flowList hC m hf hg I
  set X := ∫⁻ ω, s ω ^ (3 / 2 : ℝ) ∂ν with hX_def
  set Q := flowSq M with hQ_def
  set V0 := volume Q with hV0_def
  set D := A * eLpNorm f 3 ν * eLpNorm g 3 ν with hD_def
  set E : Ω × (ℝ × ℝ) → ℝ≥0∞ := fun z => 𝓕.sup fun I =>
    euclList m (orbitFun U V f (M + L) z.1) (orbitFun U V g (M + L) z.1) I z.2 with hE_def
  have hEm : Measurable E :=
    measurable_finset_sup_enn 𝓕 _ fun I _ => measurable_euclList_orbit hC m hf hg (M + L) I
  set c : ℝ≥0∞ := n * (ENNReal.ofReal (Bf * Bg) * δ) with hc_def
  set μ : Measure (Ω × (ℝ × ℝ)) := ν.prod (volume.restrict Q) with hμ_def
  have hΦ : Measurable fun z : Ω × (ℝ × ℝ) => U z.2.1 (V z.2.2 z.1) := measurable_flowPhi hC
  -- invariance: the flow expression on `Ω × Q_M`
  have h1 : ∫⁻ z, s (U z.2.1 (V z.2.2 z.1)) ^ (3 / 2 : ℝ) ∂μ = V0 * X := by
    rw [lintegral_prod_symm (fun z : Ω × (ℝ × ℝ) => s (U z.2.1 (V z.2.2 z.1)) ^ (3 / 2 : ℝ))
      ((hs.comp hΦ).pow_const _).aemeasurable]
    have h : ∀ x : ℝ × ℝ, ∫⁻ ω, s (U x.1 (V x.2 ω)) ^ (3 / 2 : ℝ) ∂ν = X := fun x =>
      ((hC.mpU x.1).comp (hC.mpV x.2)).lintegral_comp (hs.pow_const _)
    simp only [h, lintegral_const, Measure.restrict_apply_univ]
    rw [mul_comm]
  -- pointwise comparison of the flow and Euclidean expressions
  have hμ : μ = (ν.prod volume).restrict (Set.univ ×ˢ Q) := by
    rw [hμ_def, ← Measure.prod_restrict, Measure.restrict_univ]
  have h2 : ∀ᵐ z ∂μ, s (U z.2.1 (V z.2.2 z.1)) ≤ E z + c := by
    rw [hμ]
    filter_upwards [ae_restrict_mem (MeasurableSet.univ.prod (measurableSet_flowSq M))] with z hz
    refine Finset.sup_le fun I hI => ?_
    have hle : euclList m (orbitFun U V f (M + L) z.1) (orbitFun U V g (M + L) z.1) I z.2 ≤
        E z :=
      Finset.le_sup (f := fun I => euclList m (orbitFun U V f (M + L) z.1)
        (orbitFun U V g (M + L) z.1) I z.2) hI
    refine le_trans ?_ (add_le_add hle le_rfl)
    unfold flowList euclList
    refine (list_sum_map_le_add I.l _ (fun q : ℚ × ℚ => ‖bilinKernel (KernC m q.1 q.2)
      (orbitFun U V f (M + L) z.1) (orbitFun U V g (M + L) z.1) z.2‖ₑ)
      (ENNReal.ofReal (Bf * Bg) * δ) fun q hq => ?_).trans ?_
    · have hq1 : (0 : ℝ) < q.1 := by exact_mod_cast I.pos q hq
      have hq2 : (q.1 : ℝ) ≤ q.2 := by exact_mod_cast (I.lt q hq).le
      have hd := flow_eucl_diff hC hf hg hBf hBg (KernC_measurable_integrable m hq1 hq2).2
        (L := L) z.1 hz.2
      refine (enorm_le_add_enorm_sub _ (bilinKernel (KernC m q.1 q.2)
        (orbitFun U V f (M + L) z.1) (orbitFun U V g (M + L) z.1) z.2)).trans ?_
      gcongr
      exact hd.trans (by gcongr; exact htail I hI q hq)
    · rw [hc_def]
      gcongr
      exact_mod_cast I.len_le
  -- the Euclidean expression: node E01 on each orbit, then Cauchy–Schwarz
  have h3 : ∫⁻ z, E z ^ (3 / 2 : ℝ) ∂μ ≤ D ^ (3 / 2 : ℝ) * volume (flowSq (M + L)) := by
    rw [lintegral_prod _ (hEm.pow_const _).aemeasurable]
    calc ∫⁻ ω, ∫⁻ x, E (ω, x) ^ (3 / 2 : ℝ) ∂(volume.restrict Q) ∂ν
        ≤ ∫⁻ ω, (A * eLpNorm (orbitFun U V f (M + L) ω) 3 volume *
            eLpNorm (orbitFun U V g (M + L) ω) 3 volume) ^ (3 / 2 : ℝ) ∂ν :=
          lintegral_mono fun ω => orbit_E01 hE (measurable_orbitFun hC hf (M + L) ω)
            (measurable_orbitFun hC hg (M + L) ω) (memLp_orbitFun hC hf hBf (M + L) ω)
            (memLp_orbitFun hC hg hBg (M + L) ω) 𝓕 Q
      _ ≤ _ := lintegral_cs_three_halves (measurable_eLpNorm_orbitFun hC hf (M + L)).aemeasurable
          (measurable_eLpNorm_orbitFun hC hg (M + L)).aemeasurable _ _ _ _
          (lintegral_eLpNorm_orbitFun hC hf (M + L)) (lintegral_eLpNorm_orbitFun hC hg (M + L))
  -- the error term
  have h4 : ∫⁻ _z, c ^ (3 / 2 : ℝ) ∂μ = c ^ (3 / 2 : ℝ) * V0 := by
    rw [lintegral_const, hμ_def, ← Set.univ_prod_univ, Measure.prod_prod, measure_univ, one_mul,
      Measure.restrict_apply_univ]
  have hmink := ENNReal.lintegral_Lp_add_le (μ := μ) (f := E) (g := fun _ => c)
    hEm.aemeasurable aemeasurable_const (p := 3 / 2) (by norm_num)
  rw [show (1 : ℝ) / (3 / 2) = 2 / 3 by norm_num] at hmink
  have hV0 : V0 ≠ 0 := volume_flowSq_ne_zero hM
  have hV0' : V0 ≠ ∞ := volume_flowSq_ne_top M
  have hr : 1 ≤ ENNReal.ofReal ((1 + L / M) ^ 2) := by
    rw [ENNReal.one_le_ofReal]
    exact one_le_pow₀ (by linarith [div_nonneg hL hM.le])
  have key : V0 ^ (2 / 3 : ℝ) * X ^ (2 / 3 : ℝ) ≤
      V0 ^ (2 / 3 : ℝ) * (D * ENNReal.ofReal ((1 + L / M) ^ 2) + c) := by
    calc V0 ^ (2 / 3 : ℝ) * X ^ (2 / 3 : ℝ) = (V0 * X) ^ (2 / 3 : ℝ) :=
          (ENNReal.mul_rpow_of_nonneg _ _ (by norm_num)).symm
      _ = (∫⁻ z, s (U z.2.1 (V z.2.2 z.1)) ^ (3 / 2 : ℝ) ∂μ) ^ (2 / 3 : ℝ) := by rw [h1]
      _ ≤ (∫⁻ z, (E z + c) ^ (3 / 2 : ℝ) ∂μ) ^ (2 / 3 : ℝ) :=
          ENNReal.rpow_le_rpow (lintegral_mono_ae (h2.mono fun z hz =>
            ENNReal.rpow_le_rpow hz (by norm_num))) (by norm_num)
      _ ≤ (∫⁻ z, E z ^ (3 / 2 : ℝ) ∂μ) ^ (2 / 3 : ℝ) +
          (∫⁻ _z, c ^ (3 / 2 : ℝ) ∂μ) ^ (2 / 3 : ℝ) := hmink
      _ ≤ (D ^ (3 / 2 : ℝ) * volume (flowSq (M + L))) ^ (2 / 3 : ℝ) +
          (c ^ (3 / 2 : ℝ) * V0) ^ (2 / 3 : ℝ) := by
          rw [h4]; gcongr
      _ = D * volume (flowSq (M + L)) ^ (2 / 3 : ℝ) + c * V0 ^ (2 / 3 : ℝ) := by
          rw [ENNReal.mul_rpow_of_nonneg (D ^ (3 / 2 : ℝ)) _ (by norm_num),
            ENNReal.mul_rpow_of_nonneg (c ^ (3 / 2 : ℝ)) _ (by norm_num), ← ENNReal.rpow_mul D,
            ← ENNReal.rpow_mul c]
          norm_num
      _ ≤ D * (ENNReal.ofReal ((1 + L / M) ^ 2) * V0 ^ (2 / 3 : ℝ)) + c * V0 ^ (2 / 3 : ℝ) := by
          gcongr
          rw [volume_flowSq_add hM hL, ENNReal.mul_rpow_of_nonneg _ _ (by norm_num)]
          gcongr
          calc ENNReal.ofReal ((1 + L / M) ^ 2) ^ (2 / 3 : ℝ)
              ≤ ENNReal.ofReal ((1 + L / M) ^ 2) ^ (1 : ℝ) :=
                ENNReal.rpow_le_rpow_of_exponent_le hr (by norm_num)
            _ = _ := ENNReal.rpow_one _
      _ = V0 ^ (2 / 3 : ℝ) * (D * ENNReal.ofReal ((1 + L / M) ^ 2) + c) := by ring
  exact (ENNReal.mul_le_mul_iff_right
    (ENNReal.rpow_pos (pos_iff_ne_zero.2 hV0) hV0').ne'
    (ENNReal.rpow_ne_top_of_nonneg (by norm_num) hV0')).mp key

/-- The transference bound for a finite family of interval lists: let `M → ∞` and then the
tail parameter tend to zero in `flow_core_ML`. -/
lemma flow_core_fin [IsProbabilityMeasure ν] (hC : CommutingFlows ν U V) {m n : ℕ}
    {A : ℝ≥0∞}
    (hE : ∀ F G : ℝ × ℝ → ℂ, Measurable F → Measurable G → MemLp F 3 → MemLp G 3 →
      (∫⁻ p, countingSup n (fun u v => ‖bilinKernel (KernC m u v) F G p‖ₑ) ^ (3 / 2 : ℝ)) ^
        (2 / 3 : ℝ) ≤ A * eLpNorm F 3 * eLpNorm G 3)
    {f g : Ω → ℂ} (hf : Measurable f) (hg : Measurable g) {Bf Bg : ℝ}
    (hBf : ∀ ω, ‖f ω‖ ≤ Bf) (hBg : ∀ ω, ‖g ω‖ ≤ Bg) (𝓕 : Finset (RatIntervalList n)) :
    (∫⁻ ω, (𝓕.sup fun I => flowList m U V f g I ω) ^ (3 / 2 : ℝ) ∂ν) ^ (2 / 3 : ℝ) ≤
      A * eLpNorm f 3 ν * eLpNorm g 3 ν := by
  set X := (∫⁻ ω, (𝓕.sup fun I => flowList m U V f g I ω) ^ (3 / 2 : ℝ) ∂ν) ^ (2 / 3 : ℝ)
  set D := A * eLpNorm f 3 ν * eLpNorm g 3 ν
  have key : ∀ ε : ℝ, 0 < ε →
      X ≤ D + n * (ENNReal.ofReal (Bf * Bg) * ENNReal.ofReal ε) := by
    intro ε hε
    obtain ⟨L, hL, ht⟩ := exists_tail_bound m 𝓕 (ENNReal.ofReal_pos.2 hε)
    have hlim : Tendsto (fun M : ℝ => D * ENNReal.ofReal ((1 + L / M) ^ 2) +
        n * (ENNReal.ofReal (Bf * Bg) * ENNReal.ofReal ε)) atTop
        (𝓝 (D + n * (ENNReal.ofReal (Bf * Bg) * ENNReal.ofReal ε))) := by
      have h0 : Tendsto (fun M : ℝ => (1 + L / M) ^ 2) atTop (𝓝 1) := by
        have : Tendsto (fun M : ℝ => L / M) atTop (𝓝 0) :=
          tendsto_const_nhds.div_atTop tendsto_id
        simpa using (this.const_add 1).pow 2
      have h1 : Tendsto (fun M : ℝ => ENNReal.ofReal ((1 + L / M) ^ 2)) atTop (𝓝 1) := by
        simpa using ENNReal.tendsto_ofReal h0
      simpa using (ENNReal.Tendsto.const_mul (a := D) h1 (Or.inl one_ne_zero)).add_const
        (n * (ENNReal.ofReal (Bf * Bg) * ENNReal.ofReal ε))
    exact ge_of_tendsto hlim ((eventually_gt_atTop 0).mono fun M hM =>
      flow_core_ML hC hE hf hg hBf hBg 𝓕 hM hL ht)
  have hlim : Tendsto (fun ε : ℝ => D + n * (ENNReal.ofReal (Bf * Bg) * ENNReal.ofReal ε))
      (𝓝[>] 0) (𝓝 D) := by
    have h1 : Tendsto (fun ε : ℝ => ENNReal.ofReal ε) (𝓝[>] 0) (𝓝 0) := by
      simpa using ENNReal.tendsto_ofReal
        (tendsto_nhdsWithin_of_tendsto_nhds (tendsto_id (x := 𝓝 (0 : ℝ))))
    have h2 := ENNReal.Tendsto.const_mul (ENNReal.Tendsto.const_mul h1
      (Or.inr (ENNReal.ofReal_ne_top (r := Bf * Bg)))) (Or.inr (ENNReal.natCast_ne_top n))
    simpa using h2.const_add D
  exact ge_of_tendsto hlim (eventually_nhdsWithin_of_forall fun ε hε => key ε hε)

lemma iSup_eq_iSup_finset_sup {ι : Type*} (a : ι → ℝ≥0∞) :
    (⨆ i, a i) = ⨆ 𝓕 : Finset ι, 𝓕.sup a := by
  classical
  apply le_antisymm
  · exact iSup_le fun i => le_iSup_of_le {i} (by simp)
  · exact iSup_le fun 𝓕 => Finset.sup_le fun i _ => le_iSup a i

lemma rpow_iSup_enn {ι : Type*} (x : ι → ℝ≥0∞) {y : ℝ} (hy : 0 < y) :
    (⨆ i, x i) ^ y = ⨆ i, x i ^ y := by
  exact (ENNReal.orderIsoRpow y hy).map_iSup x

end FlowTransfer

/-- **Proposition 7.1 (node F01): transference to commuting real flows.** Let `(Ω, ν)` be a
probability space carrying commuting, jointly measurable, measure-preserving real flows
`U, V`. For bounded measurable `f, g`, `m ∈ {3, 4}` and `n ≥ 1`,
`‖S_n^{(m),Ω}(f, g)‖_{L^{3/2}(ν)} ≤ C √n ‖f‖_{L³(ν)} ‖g‖_{L³(ν)}`,
with the constant `C` of the Euclidean counting estimate (node E01). -/
theorem flow_counting_transference (hE : E01Statement) : F01Statement := by
  obtain ⟨C, hC0, hE⟩ := hE
  refine ⟨C, hC0, ?_⟩
  intro Ω _ ν _ U V hC m hm n hn f g hf hg hfb hgb
  obtain ⟨Bf, hBf⟩ := hfb
  obtain ⟨Bg, hBg⟩ := hgb
  set B := ENNReal.ofReal (C * √n) * eLpNorm f 3 ν * eLpNorm g 3 ν
  have hfin : ∀ 𝓕 : Finset (RatIntervalList n),
      ∫⁻ ω, (𝓕.sup fun I => flowList m U V f g I ω) ^ (3 / 2 : ℝ) ∂ν ≤ B ^ (3 / 2 : ℝ) := by
    intro 𝓕
    have h := flow_core_fin hC (hE m hm n hn) hf hg hBf hBg 𝓕
    calc ∫⁻ ω, (𝓕.sup fun I => flowList m U V f g I ω) ^ (3 / 2 : ℝ) ∂ν
        = ((∫⁻ ω, (𝓕.sup fun I => flowList m U V f g I ω) ^ (3 / 2 : ℝ) ∂ν) ^ (2 / 3 : ℝ)) ^
            (3 / 2 : ℝ) := by rw [← ENNReal.rpow_mul]; norm_num
      _ ≤ _ := ENNReal.rpow_le_rpow h (by norm_num)
  have hrepr : ∀ ω, countingSup n (fun u v => ‖flowBilin U V (KernC m u v) f g ω‖ₑ) ^ (3 / 2 : ℝ)
      = ⨆ 𝓕 : Finset (RatIntervalList n),
          (𝓕.sup fun I => flowList m U V f g I ω) ^ (3 / 2 : ℝ) := by
    intro ω
    rw [← rpow_iSup_enn _ (by norm_num)]
    exact congrArg (· ^ (3 / 2 : ℝ)) (iSup_eq_iSup_finset_sup (fun I => flowList m U V f g I ω))
  rw [lintegral_congr fun ω => hrepr ω, lintegral_iSup_directed (fun 𝓕 =>
    ((measurable_finset_sup_enn 𝓕 _ fun I _ =>
      measurable_flowList hC m hf hg I).pow_const _).aemeasurable)]
  · calc (⨆ 𝓕 : Finset (RatIntervalList n),
          ∫⁻ ω, (𝓕.sup fun I => flowList m U V f g I ω) ^ (3 / 2 : ℝ) ∂ν) ^ (2 / 3 : ℝ)
        ≤ (B ^ (3 / 2 : ℝ)) ^ (2 / 3 : ℝ) := ENNReal.rpow_le_rpow (iSup_le hfin) (by norm_num)
      _ = B := by rw [← ENNReal.rpow_mul]; norm_num
  · classical
    intro 𝓕₁ 𝓕₂
    refine ⟨𝓕₁ ∪ 𝓕₂, fun ω => ?_, fun ω => ?_⟩
    · exact ENNReal.rpow_le_rpow (Finset.sup_mono Finset.subset_union_left) (by norm_num)
    · exact ENNReal.rpow_le_rpow (Finset.sup_mono Finset.subset_union_right) (by norm_num)


/-- **Proposition 7.1 (node F01)**, unconditionally: for commuting jointly measurable
probability-preserving flows and bounded measurable `f, g`,
`‖S_n^{(m),Ω}(f,g)‖_{3/2} ≤ C √n ‖f‖₃ ‖g‖₃`. -/
theorem flow_counting_bound : F01Statement := flow_counting_transference E01_holds


end

end Auto
