/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib
public import TwoCommuting.Auto.Sec7FlowTransference

/-!
# From Gaussian primitives to one-sided averages

This file was automatically generated by Claude.

Formalization of §8 ("From Gaussian primitives to one-sided averages", nodes S01–S02) of
`blueprint/commuting_ergodic_blueprint.tex`.

## Contents

* S01 (`Gaussian_primitives_to_all_L1_kernels`): if the third- and fourth-derivative Gaussian
  primitives of a bounded function converge, all `L¹`-kernel averages converge (scalar
  Tauberian argument; even kernels `ρ_s`, odd kernels `Q`, density of Gaussian kernels).
* S02 (`S02_holds`): convergence of `R⁻¹ ∫_0^R f(U^t ω) g(V^t ω) dt` for commuting flows.
-/

@[expose] public section

open scoped ENNReal NNReal
open MeasureTheory Filter Topology

namespace Auto

noncomputable section

section S01Sec

open Set
open scoped Real

section S01

variable {a : ℝ → ℂ} {M : ℝ}

/-- Helper for node S01: a bounded measurable function times an integrable function is
integrable. -/
lemma s01_integrable_mul (ha : Measurable a) (hM : ∀ t, ‖a t‖ ≤ M) {ψ : ℝ → ℂ}
    (hψ : Integrable ψ) : Integrable (fun t => a t * ψ t) :=
  hψ.bdd_mul ha.aestronglyMeasurable (Eventually.of_forall hM)

/-- Helper for node S01: `|∫ a ψ| ≤ M ‖ψ‖₁`. -/
lemma s01_norm_integral_mul_le (hM : ∀ t, ‖a t‖ ≤ M) {ψ : ℝ → ℂ} (hψ : Integrable ψ) :
    ‖∫ t, a t * ψ t‖ ≤ M * ∫ t, ‖ψ t‖ := by
  rw [← integral_const_mul]
  refine norm_integral_le_of_norm_le (hψ.norm.const_mul M) (Eventually.of_forall fun t => ?_)
  rw [norm_mul]
  exact mul_le_mul_of_nonneg_right (hM t) (norm_nonneg _)

/-- The pairing `I_j(σ) = ∫ a(t) g_σ^{(j)}(t) dt` (helper for node S01). -/
def s01I (a : ℝ → ℂ) (j : ℕ) (σ : ℝ) : ℂ := ∫ t, a t * (gaussianD j σ t : ℂ)

/-- Helper for node S01: the heat equation for the pairings, `∂_σ I_j = I_{j+2} / 2`. -/
lemma s01_hasDerivAt_I (ha : Measurable a) (hM : ∀ t, ‖a t‖ ≤ M) (j : ℕ) {σ : ℝ}
    (hσ : 0 < σ) : HasDerivAt (s01I a j) (s01I a (j + 2) σ / 2) σ := by
  obtain ⟨C, hC, hCb⟩ := abs_pow_mul_gaussianD_le (j + 2) 0
  have hM0 : 0 ≤ M := (norm_nonneg _).trans (hM 0)
  have hs : Ioo (σ / 2) (2 * σ) ∈ 𝓝 σ := Ioo_mem_nhds (by linarith) (by linarith)
  have hmeasg : ∀ k τ, AEStronglyMeasurable (fun t => a t * (gaussianD k τ t : ℂ)) :=
    fun k τ => ha.aestronglyMeasurable.mul
      (Complex.continuous_ofReal.comp (continuous_gaussianD k τ)).aestronglyMeasurable
  have key := hasDerivAt_integral_of_dominated_loc_of_deriv_le (μ := volume)
    (F := fun τ t => a t * (gaussianD j τ t : ℂ))
    (F' := fun τ t => a t * ((gaussianD (j + 2) τ t / 2 : ℝ) : ℂ)) (x₀ := σ)
    (bound := fun t => M * (C * (√(σ / 2))⁻¹ ^ (j + 3) *
      Real.exp (-(t ^ 2) / (4 * (2 * σ))))) hs ?_ ?_ ?_ ?_ ?_ ?_
  · have : (∫ t, a t * ((gaussianD (j + 2) σ t / 2 : ℝ) : ℂ)) = s01I a (j + 2) σ / 2 := by
      unfold s01I; rw [← integral_div]; congr 1; funext t; push_cast; ring
    rw [← this]; exact key.2
  · exact Eventually.of_forall fun τ => hmeasg j τ
  · exact s01_integrable_mul ha hM (integrable_gaussianD j hσ).ofReal
  · have : (fun t => a t * ((gaussianD (j + 2) σ t / 2 : ℝ) : ℂ)) =
        fun t => (1 / 2 : ℂ) * (a t * (gaussianD (j + 2) σ t : ℂ)) := by
      funext t; push_cast; ring
    rw [this]; exact (hmeasg (j + 2) σ).const_mul _
  · refine Eventually.of_forall fun t τ hτ => ?_
    have hτ0 : 0 < τ := by linarith [hτ.1]
    have hb := hCb τ hτ0 t
    simp only [pow_zero, one_mul, mul_one] at hb
    rw [norm_mul, Complex.norm_real, Real.norm_eq_abs]
    have h1 : (√τ)⁻¹ ≤ (√(σ / 2))⁻¹ :=
      inv_anti₀ (Real.sqrt_pos.2 (by linarith)) (Real.sqrt_le_sqrt hτ.1.le)
    have h2 : Real.exp (-(t ^ 2) / (4 * τ)) ≤ Real.exp (-(t ^ 2) / (4 * (2 * σ))) := by
      refine Real.exp_le_exp.2 ?_
      rw [neg_div, neg_div, neg_le_neg_iff]
      exact div_le_div_of_nonneg_left (sq_nonneg t) (by linarith) (by linarith [hτ.2])
    have h3 : |gaussianD (j + 2) τ t / 2| ≤ C * (√(σ / 2))⁻¹ ^ (j + 3) *
        Real.exp (-(t ^ 2) / (4 * (2 * σ))) := by
      rw [abs_div, abs_two]
      calc |gaussianD (j + 2) τ t| / 2 ≤ |gaussianD (j + 2) τ t| := by
            linarith [abs_nonneg (gaussianD (j + 2) τ t)]
        _ ≤ C * (√τ)⁻¹ ^ (j + 2 + 1) * Real.exp (-(t ^ 2) / (4 * τ)) := hb
        _ ≤ C * (√(σ / 2))⁻¹ ^ (j + 3) * Real.exp (-(t ^ 2) / (4 * (2 * σ))) := by
            gcongr
    exact mul_le_mul (hM t) h3 (abs_nonneg _) hM0
  · exact ((integrable_exp_neg_sq_div (by positivity : (0:ℝ) < 2 * σ)).const_mul _).const_mul _
  · refine Eventually.of_forall fun t τ hτ => ?_
    have hτ0 : 0 < τ := by linarith [hτ.1]
    exact (hasDerivAt_gaussianD_variance j hτ0 t).ofReal_comp.const_mul (a t)

/-- Helper for node S01: a bounded solution of `u F'(u) = p F(u) + e(u)` with `e → 0` and
`p > 0` tends to zero (integrate `(u^{-p} F)' = u^{-p-1} e` from `s` to infinity). -/
lemma s01_tendsto_zero_of_euler {F e : ℝ → ℂ} {p : ℝ} (hp : 0 < p) {K : ℝ}
    (hF : ∀ᶠ u in atTop, ‖F u‖ ≤ K) (he : Tendsto e atTop (𝓝 0))
    (hd : ∀ u, 0 < u → HasDerivAt F (((p : ℂ) * F u + e u) / u) u) :
    Tendsto F atTop (𝓝 0) := by
  rw [Metric.tendsto_nhds]
  intro ε hε
  have he' := Metric.tendsto_nhds.1 he (ε * p / 2) (by positivity)
  obtain ⟨s1, hs1⟩ := eventually_atTop.1 (hF.and he')
  filter_upwards [eventually_ge_atTop (max s1 1)] with s hs
  have hs0 : 0 < s := lt_of_lt_of_le one_pos (le_trans (le_max_right _ _) hs)
  rw [dist_zero_right]
  set G : ℝ → ℂ := fun u => ((u ^ (-p) : ℝ) : ℂ) * F u with hG
  have hGd : ∀ u, 0 < u → HasDerivAt G (((u ^ (-p - 1) : ℝ) : ℂ) * e u) u := by
    intro u hu
    have h1 := (Real.hasDerivAt_rpow_const (p := -p) (Or.inl hu.ne')).ofReal_comp
    have h2 := h1.mul (hd u hu)
    convert h2 using 1
    have hw : u ^ (-p) = u ^ (-p - 1) * u := by
      rw [Real.rpow_sub_one hu.ne']; field_simp
    rw [hw]
    have hu' : (u : ℂ) ≠ 0 := by exact_mod_cast hu.ne'
    push_cast
    field_simp
    ring
  -- bound on `[s, T]`
  have hbd : ∀ T, s ≤ T → ‖G T - G s‖ ≤ ε / 2 * (s ^ (-p) - T ^ (-p)) := by
    intro T hT
    have hpos : ∀ x ∈ Icc s T, 0 < x := fun x hx => lt_of_lt_of_le hs0 hx.1
    have := image_norm_le_of_norm_deriv_right_le_deriv_boundary' (a := s) (b := T)
      (f := fun u => G u - G s) (f' := fun u => ((u ^ (-p - 1) : ℝ) : ℂ) * e u)
      (B := fun u => ε / 2 * (s ^ (-p) - u ^ (-p)))
      (B' := fun u => ε / 2 * (p * u ^ (-p - 1))) ?_ ?_ ?_ ?_ ?_ ?_ (x := T) ⟨hT, le_rfl⟩
    · exact this
    · intro x hx
      exact ((hGd x (hpos x hx)).sub_const (G s)).continuousAt.continuousWithinAt
    · intro x hx
      exact ((hGd x (hpos x (Ico_subset_Icc_self hx))).sub_const (G s)).hasDerivWithinAt
    · simp
    · intro x hx
      have hx0 := hpos x hx
      exact (((Real.hasDerivAt_rpow_const (p := -p) (Or.inl hx0.ne')).const_sub
        (s ^ (-p))).const_mul (ε / 2)).continuousAt.continuousWithinAt
    · intro x hx
      have hx0 := hpos x (Ico_subset_Icc_self hx)
      have h1 := Real.hasDerivAt_rpow_const (p := -p) (Or.inl hx0.ne')
      have h2 := (h1.const_sub (s ^ (-p))).const_mul (ε / 2)
      convert h2.hasDerivWithinAt using 1
      ring_nf
    · intro x hx
      have hx0 := hpos x (Ico_subset_Icc_self hx)
      have hxs : s1 ≤ x := le_trans (le_max_left _ _) (hs.trans hx.1)
      have hex := (hs1 x hxs).2
      rw [dist_zero_right] at hex
      rw [norm_mul, Complex.norm_real, Real.norm_eq_abs,
        abs_of_pos (Real.rpow_pos_of_pos hx0 _)]
      have : 0 < x ^ (-p - 1) := Real.rpow_pos_of_pos hx0 _
      nlinarith
  -- let `T → ∞`
  have hlim : ‖G s‖ ≤ ε / 2 * s ^ (-p) := by
    have ht : Tendsto (fun T : ℝ => T ^ (-p) * K + ε / 2 * s ^ (-p)) atTop
        (𝓝 (0 * K + ε / 2 * s ^ (-p))) :=
      ((tendsto_rpow_neg_atTop hp).mul_const K).add_const _
    rw [zero_mul, zero_add] at ht
    refine ge_of_tendsto ht ?_
    filter_upwards [eventually_ge_atTop s, eventually_ge_atTop s1] with T hT hT1
    have h1 := hbd T hT
    have h2 : ‖G T‖ ≤ T ^ (-p) * K := by
      have hT0 : 0 < T := lt_of_lt_of_le hs0 hT
      simp only [hG, norm_mul, Complex.norm_real, Real.norm_eq_abs,
        abs_of_pos (Real.rpow_pos_of_pos hT0 _)]
      exact mul_le_mul_of_nonneg_left (hs1 T hT1).1 (Real.rpow_pos_of_pos hT0 _).le
    have h3 : ‖G s‖ ≤ ‖G T‖ + ‖G T - G s‖ := by
      have := norm_sub_le (G T) (G T - G s)
      simpa using this
    have h4 : 0 ≤ T ^ (-p) := (Real.rpow_pos_of_pos (lt_of_lt_of_le hs0 hT) _).le
    nlinarith
  have hsp : 0 < s ^ (-p) := Real.rpow_pos_of_pos hs0 _
  have : ‖G s‖ = s ^ (-p) * ‖F s‖ := by
    simp only [hG, norm_mul, Complex.norm_real, Real.norm_eq_abs, abs_of_pos hsp]
  rw [this] at hlim
  have : ‖F s‖ ≤ ε / 2 := by
    by_contra hcon
    push Not at hcon
    nlinarith
  linarith

/-- The Gaussian pairing `C_m(u) = ∫ a(t) u^{m/2} g_{cu}^{(m)}(t) dt` (helper for node S01). -/
def s01C (a : ℝ → ℂ) (c : ℝ) (m : ℕ) (u : ℝ) : ℂ :=
  ∫ t, a t * ((√u ^ m * gaussianD m (c * u) t : ℝ) : ℂ)

/-- The primitive `H_m(s) = ∫_1^s C_m(u) du / u` (helper for node S01). -/
def s01H (a : ℝ → ℂ) (c : ℝ) (m : ℕ) (s : ℝ) : ℂ := ∫ u in (1 : ℝ)..s, s01C a c m u / u

lemma s01C_eq (c : ℝ) (m : ℕ) (u : ℝ) :
    s01C a c m u = ((√u ^ m : ℝ) : ℂ) * s01I a m (c * u) := by
  unfold s01C s01I
  rw [← integral_const_mul]
  congr 1; funext t; push_cast; ring

lemma s01_hasDerivAt_I_comp (ha : Measurable a) (hM : ∀ t, ‖a t‖ ≤ M) (j : ℕ) {c s : ℝ}
    (hc : 0 < c) (hs : 0 < s) :
    HasDerivAt (fun s => s01I a j (c * s)) ((c : ℂ) * s01I a (j + 2) (c * s) / 2) s := by
  have h1 := s01_hasDerivAt_I ha hM j (mul_pos hc hs)
  have h2 : HasDerivAt (fun s : ℝ => c * s) c s := by
    simpa using (hasDerivAt_id s).const_mul c
  convert (h1.scomp s h2) using 1
  · rfl
  · rw [Complex.real_smul]; ring

lemma s01_continuousOn_C_div (ha : Measurable a) (hM : ∀ t, ‖a t‖ ≤ M) {c : ℝ} (hc : 0 < c)
    (m : ℕ) : ContinuousOn (fun u => s01C a c m u / u) (Ioi 0) := by
  intro u hu
  have hu0 : (0 : ℝ) < u := hu
  refine ContinuousAt.continuousWithinAt ?_
  have he : (fun u => s01C a c m u / u) =
      fun u => ((√u ^ m : ℝ) : ℂ) * s01I a m (c * u) / u := by
    funext u; rw [s01C_eq]
  rw [he]
  refine ContinuousAt.div (ContinuousAt.mul ?_ ?_) ?_ ?_
  · exact (Complex.continuous_ofReal.comp (Real.continuous_sqrt.pow m)).continuousAt
  · exact (s01_hasDerivAt_I_comp ha hM m hc hu0).continuousAt
  · exact Complex.continuous_ofReal.continuousAt
  · exact_mod_cast hu0.ne'

lemma s01_hasDerivAt_H (ha : Measurable a) (hM : ∀ t, ‖a t‖ ≤ M) {c : ℝ} (hc : 0 < c)
    (m : ℕ) {s : ℝ} (hs : 0 < s) : HasDerivAt (s01H a c m) (s01C a c m s / s) s := by
  have hcont := s01_continuousOn_C_div ha hM hc m
  have hsub : uIcc 1 s ⊆ Ioi 0 := by
    intro x hx
    rcases le_total 1 s with h | h
    · rw [uIcc_of_le h] at hx; exact lt_of_lt_of_le one_pos hx.1
    · rw [uIcc_of_ge h] at hx; exact lt_of_lt_of_le hs hx.1
  exact intervalIntegral.integral_hasDerivAt_right ((hcont.mono hsub).intervalIntegrable)
    (hcont.stronglyMeasurableAtFilter isOpen_Ioi s hs) (hcont.continuousAt (Ioi_mem_nhds hs))

lemma s01_norm_I_zero_le (hM : ∀ t, ‖a t‖ ≤ M) {σ : ℝ} (hσ : 0 < σ) :
    ‖s01I a 0 σ‖ ≤ M := by
  unfold s01I
  have h := s01_norm_integral_mul_le hM (integrable_gaussianD 0 hσ).ofReal
  simp only [RCLike.norm_ofReal] at h
  have hg : ∫ t, |gaussianD 0 σ t| = 1 := by
    rw [gaussianD_zero, ← integral_gaussian_eq_one hσ]
    congr 1; funext t
    rw [abs_of_nonneg]
    unfold gaussian; positivity
  rw [hg, mul_one] at h
  exact h

lemma s01_norm_Q_le (hM : ∀ t, ‖a t‖ ≤ M) {c s : ℝ} (hc : 0 < c) (hs : 0 < s) :
    ‖((√s : ℝ) : ℂ) * s01I a 1 (c * s)‖ ≤ M * ∫ t, |gaussianD 1 c t| := by
  have e : ((√s : ℝ) : ℂ) * s01I a 1 (c * s) = s01C a c 1 s := by rw [s01C_eq, pow_one]
  rw [e]
  unfold s01C
  have hint : Integrable (fun t => ((√s ^ 1 * gaussianD 1 (c * s) t : ℝ) : ℂ)) :=
    ((integrable_gaussianD 1 (mul_pos hc hs)).const_mul _).ofReal
  have h := s01_norm_integral_mul_le hM hint
  simp only [Complex.norm_real, Real.norm_eq_abs] at h
  rwa [integral_abs_gaussianD_scale 1 hc hs] at h

/-- Helper for node S01 (even kernels): if `H_4` converges then `A(s) = ∫ a g_{cs}` converges. -/
lemma s01_even_limit (ha : Measurable a) (hM : ∀ t, ‖a t‖ ≤ M) {c : ℝ} (hc : 0 < c)
    {L4 : ℂ} (h4 : Tendsto (s01H a c 4) atTop (𝓝 L4)) :
    ∃ L : ℂ, Tendsto (fun s => s01I a 0 (c * s)) atTop (𝓝 L) := by
  set P : ℝ → ℂ := fun s => s01I a 0 (c * s) - (c : ℂ) * s / 2 * s01I a 2 (c * s) with hP
  set D : ℝ → ℂ := fun s => P s + (c : ℂ) ^ 2 / 4 * s01H a c 4 s with hD
  have hPd : ∀ s, 0 < s → HasDerivAt P (-((c : ℂ) ^ 2 * s / 4) * s01I a 4 (c * s)) s := by
    intro s hs
    have h0 := s01_hasDerivAt_I_comp ha hM 0 hc hs
    have h2 := s01_hasDerivAt_I_comp ha hM 2 hc hs
    have hl : HasDerivAt (fun s : ℝ => (c : ℂ) * s / 2) ((c : ℂ) / 2) s := by
      have := ((hasDerivAt_id s).ofReal_comp.const_mul (c : ℂ)).div_const 2
      simpa using this
    convert h0.sub (hl.mul h2) using 1
    simp only [zero_add]
    ring
  have hDd : ∀ s, 0 < s → HasDerivAt D 0 s := by
    intro s hs
    have := (hPd s hs).add ((s01_hasDerivAt_H ha hM hc 4 hs).const_mul ((c : ℂ) ^ 2 / 4))
    convert this using 1
    rw [s01C_eq]
    have hsq : ((√s ^ 4 : ℝ) : ℂ) = (s : ℂ) ^ 2 := by
      have : √s ^ 4 = s ^ 2 := by
        rw [show (4 : ℕ) = 2 * 2 from rfl, pow_mul, Real.sq_sqrt hs.le]
      exact_mod_cast this
    have hs' : (s : ℂ) ≠ 0 := by exact_mod_cast hs.ne'
    rw [hsq]
    field_simp
    ring
  have hDc : ∀ s, 1 ≤ s → D s = D 1 := by
    intro s hs
    have := norm_image_sub_le_of_norm_deriv_le_segment' (f := D) (f' := fun _ => (0 : ℂ))
      (C := 0) (a := 1) (b := s)
      (fun x hx => (hDd x (lt_of_lt_of_le one_pos hx.1)).hasDerivWithinAt)
      (fun x _ => by simp) s ⟨hs, le_rfl⟩
    simp only [zero_mul, norm_le_zero_iff, sub_eq_zero] at this
    exact this
  have hH1 : s01H a c 4 1 = 0 := by simp [s01H]
  set L : ℂ := P 1 - (c : ℂ) ^ 2 / 4 * L4
  have hPL : Tendsto P atTop (𝓝 L) := by
    have : Tendsto (fun s => P 1 - (c : ℂ) ^ 2 / 4 * s01H a c 4 s) atTop (𝓝 L) :=
      tendsto_const_nhds.sub (h4.const_mul _)
    refine this.congr' ?_
    filter_upwards [eventually_ge_atTop 1] with s hs
    have := hDc s hs
    simp only [hD, hH1, mul_zero, add_zero] at this
    rw [← this]; ring
  refine ⟨L, ?_⟩
  -- `B = A - L` solves the Euler equation `s B' = B + (L - P)`
  have hB := s01_tendsto_zero_of_euler (F := fun s => s01I a 0 (c * s) - L)
    (e := fun s => L - P s) (p := 1) one_pos (K := M + ‖L‖)
    ((eventually_gt_atTop 0).mono fun s hs => ?_) ?_ ?_
  · have := hB.add_const L
    simpa using this
  · exact (norm_sub_le _ _).trans (by linarith [s01_norm_I_zero_le hM (mul_pos hc hs)])
  · simpa using (tendsto_const_nhds (x := L)).sub hPL
  · intro s hs
    have h0 := s01_hasDerivAt_I_comp ha hM 0 hc hs
    convert h0.sub_const L using 1
    have hs' : (s : ℂ) ≠ 0 := by exact_mod_cast hs.ne'
    simp only [hP]
    push_cast
    field_simp
    ring

/-- Helper for node S01 (odd kernels): if `H_3` converges then
`Q(s) = ∫ a √s g'_{cs}` tends to zero. -/
lemma s01_odd_limit (ha : Measurable a) (hM : ∀ t, ‖a t‖ ≤ M) {c : ℝ} (hc : 0 < c)
    {L3 : ℂ} (h3 : Tendsto (s01H a c 3) atTop (𝓝 L3)) :
    Tendsto (fun s => ((√s : ℝ) : ℂ) * s01I a 1 (c * s)) atTop (𝓝 0) := by
  set Q : ℝ → ℂ := fun s => ((√s : ℝ) : ℂ) * s01I a 1 (c * s) with hQ
  set V : ℝ → ℂ := fun s => Q s - (c : ℂ) / 2 * (s01H a c 3 s - L3) with hV
  have hQd : ∀ s, 0 < s → HasDerivAt Q
      (((1 / (2 * √s) : ℝ) : ℂ) * s01I a 1 (c * s) +
        ((√s : ℝ) : ℂ) * ((c : ℂ) * s01I a 3 (c * s) / 2)) s := by
    intro s hs
    have h1 := (Real.hasDerivAt_sqrt hs.ne').ofReal_comp
    exact h1.mul (s01_hasDerivAt_I_comp ha hM 1 hc hs)
  have hHL : Tendsto (fun s => s01H a c 3 s - L3) atTop (𝓝 0) := by
    simpa using h3.sub_const L3
  have hVt := s01_tendsto_zero_of_euler (F := V)
    (e := fun s => (c : ℂ) / 4 * (s01H a c 3 s - L3)) (p := 1 / 2) (by norm_num)
    (K := M * (∫ t, |gaussianD 1 c t|) + ‖(c : ℂ) / 2‖ * 1) ?_ ?_ ?_
  · have := hVt.add (hHL.const_mul ((c : ℂ) / 2))
    simp only [mul_zero, add_zero] at this
    refine this.congr fun s => ?_
    simp only [hV]; ring
  · have hev := (Metric.tendsto_nhds.1 hHL) 1 one_pos
    filter_upwards [hev, eventually_gt_atTop 0] with s hs hs0
    rw [dist_zero_right] at hs
    refine (norm_sub_le _ _).trans (add_le_add (s01_norm_Q_le hM hc hs0) ?_)
    rw [norm_mul]
    exact mul_le_mul_of_nonneg_left hs.le (norm_nonneg _)
  · simpa using hHL.const_mul ((c : ℂ) / 4)
  · intro s hs
    have := (hQd s hs).sub ((s01_hasDerivAt_H ha hM hc 3 hs).const_mul ((c : ℂ) / 2))
    convert this.add_const ((c : ℂ) / 2 * L3) using 1
    · funext u; simp only [hV, Pi.sub_apply]; ring
    rw [s01C_eq]
    set r := √s with hr
    have hr0 : 0 < r := Real.sqrt_pos.2 hs
    have hsr : (s : ℂ) = (r : ℂ) ^ 2 := by
      have : r ^ 2 = s := Real.sq_sqrt hs.le
      exact_mod_cast this.symm
    have hr' : (r : ℂ) ≠ 0 := by exact_mod_cast hr0.ne'
    simp only [hV, hQ]
    rw [hsr]
    push_cast
    field_simp
    ring

/-! ### Kernel averages -/

/-- The property that the dilated pairings with an `L¹` kernel `φ` converge to `L ∫ φ`
(helper for node S01). -/
def S01Good (a : ℝ → ℂ) (L : ℂ) (φ : ℝ → ℂ) : Prop :=
  Integrable φ ∧
    Tendsto (fun R : ℝ => ∫ t, a t * ((R⁻¹ : ℂ) * φ (t / R))) atTop (𝓝 (L * ∫ t, φ t))

lemma s01_integrable_dilate {φ : ℝ → ℂ} (hφ : Integrable φ) {R : ℝ} (hR : R ≠ 0) :
    Integrable (fun t => (R⁻¹ : ℂ) * φ (t / R)) :=
  (hφ.comp_div hR).const_mul _

lemma s01_integral_norm_dilate (φ : ℝ → ℂ) {R : ℝ} (hR : 0 < R) :
    ∫ t, ‖(R⁻¹ : ℂ) * φ (t / R)‖ = ∫ t, ‖φ t‖ := by
  have : (fun t => ‖(R⁻¹ : ℂ) * φ (t / R)‖) = fun t => R⁻¹ * ‖φ (t / R)‖ := by
    funext t
    rw [norm_mul, norm_inv, Complex.norm_real, Real.norm_eq_abs, abs_of_pos hR]
  rw [this, integral_const_mul, Measure.integral_comp_div (fun x => ‖φ x‖) R, abs_of_pos hR,
    smul_eq_mul, ← mul_assoc, inv_mul_cancel₀ hR.ne', one_mul]

lemma s01_good_add {L : ℂ} {φ ψ : ℝ → ℂ} (hφ : S01Good a L φ) (hψ : S01Good a L ψ)
    (ha : Measurable a) (hM : ∀ t, ‖a t‖ ≤ M) : S01Good a L (fun t => φ t + ψ t) := by
  refine ⟨hφ.1.add hψ.1, ?_⟩
  rw [integral_add hφ.1 hψ.1, mul_add]
  refine (hφ.2.add hψ.2).congr' ?_
  filter_upwards [eventually_gt_atTop 0] with R hR
  rw [← integral_add (s01_integrable_mul ha hM (s01_integrable_dilate hφ.1 hR.ne'))
    (s01_integrable_mul ha hM (s01_integrable_dilate hψ.1 hR.ne'))]
  congr 1; funext t; ring

lemma s01_good_const_mul {L : ℂ} {φ : ℝ → ℂ} (hφ : S01Good a L φ) (b : ℂ) :
    S01Good a L (fun t => b * φ t) := by
  refine ⟨hφ.1.const_mul b, ?_⟩
  rw [integral_const_mul]
  have := hφ.2.const_mul b
  rw [show b * (L * ∫ t, φ t) = L * (b * ∫ t, φ t) by ring] at this
  refine this.congr fun R => ?_
  rw [← integral_const_mul]
  congr 1; funext t; ring

lemma s01_good_zero {L : ℂ} : S01Good a L (fun _ => 0) :=
  ⟨integrable_zero _ _ _, by simp⟩

lemma s01_good_sum {L : ℂ} (ha : Measurable a) (hM : ∀ t, ‖a t‖ ≤ M) (s : Finset ℕ)
    (φ : ℕ → ℝ → ℂ) (hφ : ∀ i ∈ s, S01Good a L (φ i)) :
    S01Good a L (fun t => ∑ i ∈ s, φ i t) := by
  induction s using Finset.induction_on with
  | empty => simpa using (s01_good_zero (a := a) (L := L))
  | insert i s hi ih =>
    have h1 := hφ i (Finset.mem_insert_self i s)
    have h2 := ih fun j hj => hφ j (Finset.mem_insert_of_mem hj)
    have := s01_good_add h1 h2 ha hM
    simpa [Finset.sum_insert hi] using this

/-- Helper for node S01: the good kernels are closed in `L¹`, using the uniform bound
`|∫ a(t) R⁻¹ φ(t/R) dt| ≤ M ‖φ‖₁`. -/
lemma s01_good_of_approx {L : ℂ} (ha : Measurable a) (hM : ∀ t, ‖a t‖ ≤ M) {φ : ℝ → ℂ}
    (hφ : Integrable φ)
    (happrox : ∀ η > 0, ∃ ψ, S01Good a L ψ ∧ ∫ t, ‖φ t - ψ t‖ ≤ η) : S01Good a L φ := by
  refine ⟨hφ, ?_⟩
  have hM0 : 0 ≤ M := (norm_nonneg _).trans (hM 0)
  rw [Metric.tendsto_nhds]
  intro ε hε
  set η := ε / (3 * (M + ‖L‖ + 1)) with hη
  have hη0 : 0 < η := by positivity
  obtain ⟨ψ, hψ, hψη⟩ := happrox η hη0
  filter_upwards [Metric.tendsto_nhds.1 hψ.2 (ε / 3) (by positivity),
    eventually_gt_atTop 0] with R hR hR0
  rw [dist_eq_norm] at hR ⊢
  have hdiff : (∫ t, a t * ((R⁻¹ : ℂ) * φ (t / R))) - ∫ t, a t * ((R⁻¹ : ℂ) * ψ (t / R)) =
      ∫ t, a t * ((R⁻¹ : ℂ) * (φ - ψ) (t / R)) := by
    rw [← integral_sub (s01_integrable_mul ha hM (s01_integrable_dilate hφ hR0.ne'))
      (s01_integrable_mul ha hM (s01_integrable_dilate hψ.1 hR0.ne'))]
    congr 1; funext t; simp only [Pi.sub_apply]; ring
  have h1 : ‖(∫ t, a t * ((R⁻¹ : ℂ) * φ (t / R))) - ∫ t, a t * ((R⁻¹ : ℂ) * ψ (t / R))‖
      ≤ M * η := by
    rw [hdiff]
    refine (s01_norm_integral_mul_le hM
      (s01_integrable_dilate (hφ.sub hψ.1) hR0.ne')).trans ?_
    rw [s01_integral_norm_dilate _ hR0]
    exact mul_le_mul_of_nonneg_left hψη hM0
  have h2 : ‖L * (∫ t, ψ t) - L * ∫ t, φ t‖ ≤ ‖L‖ * η := by
    rw [← mul_sub, norm_mul, ← integral_sub hψ.1 hφ]
    refine mul_le_mul_of_nonneg_left ((norm_integral_le_integral_norm _).trans ?_)
      (norm_nonneg _)
    refine le_trans (le_of_eq ?_) hψη
    congr 1; funext t; exact norm_sub_rev _ _
  have h3 : M * η + ‖L‖ * η < 2 * ε / 3 := by
    have : (M + ‖L‖) * η < ε / 3 := by
      rw [hη]
      have hpos : 0 < M + ‖L‖ + 1 := by positivity
      rw [mul_div_assoc', div_lt_div_iff₀ (by positivity) (by norm_num)]
      nlinarith
    nlinarith
  set X := ∫ t, a t * ((R⁻¹ : ℂ) * φ (t / R))
  set Y := ∫ t, a t * ((R⁻¹ : ℂ) * ψ (t / R))
  calc ‖X - L * ∫ t, φ t‖
      = ‖(X - Y) + (Y - L * ∫ t, ψ t) + (L * (∫ t, ψ t) - L * ∫ t, φ t)‖ := by
        congr 1; ring
    _ ≤ ‖X - Y‖ + ‖Y - L * ∫ t, ψ t‖ + ‖L * (∫ t, ψ t) - L * ∫ t, φ t‖ := norm_add₃_le
    _ < ε := by linarith

/-! ### The Gaussian kernels -/

lemma s01_gaussianD_one {σ : ℝ} (hσ : 0 < σ) (t : ℝ) :
    gaussianD 1 σ t = -(t / σ) * gaussian σ t := by
  have h1 := hasDerivAt_gaussianD 0 σ t
  rw [gaussianD_zero] at h1
  have h2 : HasDerivAt (gaussian σ) (-(t / σ) * gaussian σ t) t := by
    unfold gaussian
    have hq : HasDerivAt (fun y : ℝ => -(y ^ 2) / (2 * σ)) (-(2 * t) / (2 * σ)) t := by
      have := ((hasDerivAt_pow 2 t).neg.div_const (2 * σ))
      convert this using 1
      simp
    have := (hq.exp).const_mul (√(2 * π * σ))⁻¹
    convert this using 1
    field_simp
  exact h1.unique h2

lemma s01_tendsto_sq_div {k : ℝ} (hk : 0 < k) :
    Tendsto (fun R : ℝ => R ^ 2 / (2 * k)) atTop atTop :=
  (tendsto_pow_atTop two_ne_zero).atTop_div_const (by positivity)

/-- Helper for node S01: the even Gaussian kernels `e^{-k t²}` are good. -/
lemma s01_good_gauss {L : ℂ} (hA : Tendsto (s01I a 0) atTop (𝓝 L)) {k : ℝ} (hk : 0 < k) :
    S01Good a L (fun t => ((Real.exp (-k * t ^ 2) : ℝ) : ℂ)) := by
  refine ⟨(integrable_exp_neg_mul_sq hk).ofReal, ?_⟩
  have hint : ∫ t, ((Real.exp (-k * t ^ 2) : ℝ) : ℂ) = ((√(π / k) : ℝ) : ℂ) := by
    rw [← integral_gaussian k]; exact integral_ofReal
  rw [hint]
  have hlim := ((hA.comp (s01_tendsto_sq_div hk)).const_mul ((√(π / k) : ℝ) : ℂ))
  rw [mul_comm L]
  refine hlim.congr' ?_
  filter_upwards [eventually_gt_atTop 0] with R hR
  simp only [Function.comp_apply]
  unfold s01I
  rw [← integral_const_mul]
  congr 1; funext t
  have hpk : 0 < π / k := by positivity
  have hreal : R⁻¹ * Real.exp (-k * (t / R) ^ 2) =
      √(π / k) * gaussianD 0 (R ^ 2 / (2 * k)) t := by
    rw [gaussianD_zero]
    unfold gaussian
    have e1 : 2 * π * (R ^ 2 / (2 * k)) = π / k * R ^ 2 := by field_simp
    have e2 : -(t ^ 2) / (2 * (R ^ 2 / (2 * k))) = -k * (t / R) ^ 2 := by
      field_simp
    rw [e1, e2, Real.sqrt_mul hpk.le, Real.sqrt_sq hR.le]
    have : 0 < √(π / k) := Real.sqrt_pos.2 hpk
    field_simp
  have hc : ((R⁻¹ : ℂ)) * ((Real.exp (-k * (t / R) ^ 2) : ℝ) : ℂ) =
      ((√(π / k) : ℝ) : ℂ) * ((gaussianD 0 (R ^ 2 / (2 * k)) t : ℝ) : ℂ) := by
    exact_mod_cast congrArg (fun x : ℝ => (x : ℂ)) hreal
  rw [hc]; ring

/-- Helper for node S01: the odd Gaussian kernels `t e^{-k t²}` are good. -/
lemma s01_good_odd {L : ℂ}
    (hQ : Tendsto (fun σ => ((√σ : ℝ) : ℂ) * s01I a 1 σ) atTop (𝓝 0)) {k : ℝ} (hk : 0 < k) :
    S01Good a L (fun t => ((t * Real.exp (-k * t ^ 2) : ℝ) : ℂ)) := by
  refine ⟨(integrable_mul_exp_neg_mul_sq hk).ofReal, ?_⟩
  have hint : ∫ t, ((t * Real.exp (-k * t ^ 2) : ℝ) : ℂ) = 0 := by
    have h := integral_neg_eq_self (fun t : ℝ => ((t * Real.exp (-k * t ^ 2) : ℝ) : ℂ)) volume
    have h' : (fun t : ℝ => (((-t) * Real.exp (-k * (-t) ^ 2) : ℝ) : ℂ)) =
        fun t => -((t * Real.exp (-k * t ^ 2) : ℝ) : ℂ) := by
      funext t; push_cast; ring_nf
    simp only [h', integral_neg] at h
    have : (2 : ℂ) * ∫ t, ((t * Real.exp (-k * t ^ 2) : ℝ) : ℂ) = 0 := by
      linear_combination -h
    simpa using this
  rw [hint, mul_zero]
  set κ : ℝ := -(√(2 * π) / (2 * k))
  have hlim := ((hQ.comp (s01_tendsto_sq_div hk)).const_mul (κ : ℂ))
  rw [mul_zero] at hlim
  refine hlim.congr' ?_
  filter_upwards [eventually_gt_atTop 0] with R hR
  simp only [Function.comp_apply]
  unfold s01I
  rw [← integral_const_mul, ← integral_const_mul]
  congr 1; funext t
  set σ := R ^ 2 / (2 * k) with hσ
  have hσ0 : 0 < σ := by positivity
  have hreal : R⁻¹ * ((t / R) * Real.exp (-k * (t / R) ^ 2)) =
      κ * (√σ * gaussianD 1 σ t) := by
    rw [s01_gaussianD_one hσ0]
    unfold gaussian
    have e2 : -(t ^ 2) / (2 * σ) = -k * (t / R) ^ 2 := by
      rw [hσ]; field_simp
    rw [e2, show 2 * π * σ = (2 * π) * σ by ring, Real.sqrt_mul (by positivity) σ]
    have h1 : 0 < √σ := Real.sqrt_pos.2 hσ0
    have h2 : 0 < √(2 * π) := Real.sqrt_pos.2 (by positivity)
    simp only [κ]
    rw [hσ]
    field_simp
  have hc : ((R⁻¹ : ℂ)) * (((t / R) * Real.exp (-k * (t / R) ^ 2) : ℝ) : ℂ) =
      (κ : ℂ) * (((√σ : ℝ) : ℂ) * ((gaussianD 1 σ t : ℝ) : ℂ)) := by
    exact_mod_cast congrArg (fun x : ℝ => (x : ℂ)) hreal
  rw [hc]; ring

/-! ### Density of the Gaussian kernels -/

/-- Helper for node S01: the substitution `z = e^{-t²}` and Weierstrass approximation. A
continuous function vanishing near `0` and near infinity is approximated by
`e^{-t²} p(e^{-t²}) + t e^{-t²} q(e^{-t²})` with a pointwise error `η (1 + |t|) e^{-t²}`. -/
lemma s01_poly_approx {f : ℝ → ℝ} (hf : Continuous f) {δ R0 : ℝ} (hδ : 0 < δ)
    (hz : ∀ t, |t| ≤ δ ∨ R0 ≤ |t| → f t = 0) {η : ℝ} (hη : 0 < η) :
    ∃ p q : Polynomial ℝ, ∀ t, |f t - (Real.exp (-t ^ 2) * p.eval (Real.exp (-t ^ 2)) +
      t * Real.exp (-t ^ 2) * q.eval (Real.exp (-t ^ 2)))| ≤
        η * ((1 + |t|) * Real.exp (-t ^ 2)) := by
  set g : ℝ → ℝ := fun t => f t * Real.exp (t ^ 2) with hg
  have hgc : Continuous g := by fun_prop
  have hgz : ∀ t, |t| ≤ δ ∨ R0 ≤ |t| → g t = 0 := fun t ht => by simp [hg, hz t ht]
  set sq : ℝ → ℝ := fun z => √(-Real.log z) with hsq
  set F : ℝ → ℝ := fun z => (g (sq z) + g (-sq z)) / 2 with hF
  set G : ℝ → ℝ := fun z => (g (sq z) - g (-sq z)) / (2 * sq z) with hG
  have hsq_nonneg : ∀ z, 0 ≤ sq z := fun z => Real.sqrt_nonneg _
  -- vanishing of `F, G` where `sq z` is small or large
  have hFG0 : ∀ y, (sq y ≤ δ ∨ R0 ≤ sq y) → F y = 0 ∧ G y = 0 := by
    intro y hy
    have h1 : g (sq y) = 0 := hgz _ (by rw [abs_of_nonneg (hsq_nonneg y)]; exact hy)
    have h2 : g (-sq y) = 0 := hgz _ (by rw [abs_neg, abs_of_nonneg (hsq_nonneg y)]; exact hy)
    simp [hF, hG, h1, h2]
  -- continuity on `[0, 1]`
  set R1 := max R0 δ
  have hR1 : δ ≤ R1 := le_max_right _ _
  have hcont : ∀ z ∈ Icc (0 : ℝ) 1, ContinuousAt F z ∧ ContinuousAt G z := by
    intro z hz01
    by_cases hlow : z < Real.exp (-R1 ^ 2)
    · have hev : ∀ᶠ y in 𝓝 z, F y = 0 ∧ G y = 0 := by
        have hz0 : -Real.exp (-R1 ^ 2) < z := by linarith [hz01.1, Real.exp_pos (-R1 ^ 2)]
        filter_upwards [Ioo_mem_nhds hz0 hlow] with y hy
        rcases eq_or_ne y 0 with rfl | hy0
        · have h0 : sq 0 = 0 := by simp [hsq]
          exact hFG0 0 (Or.inl (by rw [h0]; exact hδ.le))
        · refine hFG0 y (Or.inr ?_)
          have hay : |y| < Real.exp (-R1 ^ 2) := abs_lt.2 ⟨hy.1, hy.2⟩
          have hlog : Real.log y < -R1 ^ 2 := by
            rw [← Real.log_abs]
            calc Real.log |y| < Real.log (Real.exp (-R1 ^ 2)) :=
                  Real.log_lt_log (abs_pos.2 hy0) hay
              _ = -R1 ^ 2 := Real.log_exp _
          have hR1' : 0 ≤ R1 := hδ.le.trans hR1
          have : R1 < sq y := by
            rw [hsq]; simp only
            rw [Real.lt_sqrt hR1']; linarith
          linarith [le_max_left R0 δ]
      exact ⟨continuousAt_const.congr (hev.mono fun y hy => hy.1.symm),
        continuousAt_const.congr (hev.mono fun y hy => hy.2.symm)⟩
    by_cases hhigh : Real.exp (-δ ^ 2) < z
    · have hev : ∀ᶠ y in 𝓝 z, F y = 0 ∧ G y = 0 := by
        filter_upwards [Ioi_mem_nhds hhigh] with y hy
        refine hFG0 y (Or.inl ?_)
        have hy0 : 0 < y := lt_trans (Real.exp_pos _) hy
        have hlog : -δ ^ 2 < Real.log y := by
          rw [← Real.log_exp (-δ ^ 2)]; exact Real.log_lt_log (Real.exp_pos _) hy
        calc sq y = √(-Real.log y) := rfl
          _ ≤ √(δ ^ 2) := Real.sqrt_le_sqrt (by linarith)
          _ = δ := Real.sqrt_sq hδ.le
      exact ⟨continuousAt_const.congr (hev.mono fun y hy => hy.1.symm),
        continuousAt_const.congr (hev.mono fun y hy => hy.2.symm)⟩
    push Not at hlow hhigh
    have hz0 : 0 < z := lt_of_lt_of_le (Real.exp_pos _) hlow
    have hz1 : z < 1 := lt_of_le_of_lt hhigh (Real.exp_lt_one_iff.2 (by nlinarith))
    have hsqc : ContinuousAt sq z :=
      Real.continuous_sqrt.continuousAt.comp (Real.continuousAt_log hz0.ne').neg
    have hsq0 : sq z ≠ 0 := by
      have : 0 < -Real.log z := neg_pos.2 (Real.log_neg hz0 hz1)
      exact (Real.sqrt_pos.2 this).ne'
    have hg1 : ContinuousAt (fun y => g (sq y)) z := hgc.continuousAt.comp hsqc
    have hg2 : ContinuousAt (fun y => g (-sq y)) z := hgc.continuousAt.comp hsqc.neg
    exact ⟨(hg1.add hg2).div_const 2,
      (hg1.sub hg2).div (continuousAt_const.mul hsqc) (mul_ne_zero two_ne_zero hsq0)⟩
  have hFc : ContinuousOn F (Icc 0 1) := fun z hz => (hcont z hz).1.continuousWithinAt
  have hGc : ContinuousOn G (Icc 0 1) := fun z hz => (hcont z hz).2.continuousWithinAt
  obtain ⟨p, hp⟩ := exists_polynomial_near_of_continuousOn 0 1 F hFc η hη
  obtain ⟨q, hq⟩ := exists_polynomial_near_of_continuousOn 0 1 G hGc η hη
  refine ⟨p, q, fun t => ?_⟩
  set z := Real.exp (-t ^ 2) with hzdef
  have hz0 : 0 < z := Real.exp_pos _
  have hzI : z ∈ Icc (0 : ℝ) 1 := ⟨hz0.le, Real.exp_le_one_iff.2 (by nlinarith)⟩
  have hsqz : sq z = |t| := by
    simp only [hsq, hzdef, Real.log_exp, neg_neg]
    exact Real.sqrt_sq_eq_abs t
  -- the key identity `g t = F z + t G z`
  have hid : g t = F z + t * G z := by
    simp only [hF, hG, hsqz]
    rcases lt_trichotomy t 0 with ht | ht | ht
    · rw [abs_of_neg ht, neg_neg]
      have := ht.ne
      field_simp
      ring
    · subst ht; simp
    · rw [abs_of_pos ht]
      have := ht.ne'
      field_simp
      ring
  have hft : f t = z * (F z + t * G z) := by
    rw [← hid, hg]; simp only [hzdef]
    have he : Real.exp (-t ^ 2) * Real.exp (t ^ 2) = 1 := by rw [← Real.exp_add]; simp
    linear_combination (-(f t)) * he
  rw [hft]
  have e : z * (F z + t * G z) - (z * p.eval z + t * z * q.eval z) =
      z * ((F z - p.eval z) + t * (G z - q.eval z)) := by ring
  rw [e, abs_mul, abs_of_pos hz0]
  have h1 := hp z hzI
  have h2 := hq z hzI
  rw [abs_sub_comm] at h1 h2
  have : |(F z - p.eval z) + t * (G z - q.eval z)| ≤ η * (1 + |t|) := by
    calc |(F z - p.eval z) + t * (G z - q.eval z)|
        ≤ |F z - p.eval z| + |t| * |G z - q.eval z| := by
          refine (abs_add_le _ _).trans ?_; rw [abs_mul]
      _ ≤ η + |t| * η := by gcongr
      _ = η * (1 + |t|) := by ring
  calc z * |(F z - p.eval z) + t * (G z - q.eval z)| ≤ z * (η * (1 + |t|)) :=
        mul_le_mul_of_nonneg_left this hz0.le
    _ = η * ((1 + |t|) * z) := by ring

/-- Helper for node S01: the polynomial Gaussian approximants are good. -/
lemma s01_good_poly {L : ℂ} (ha : Measurable a) (hM : ∀ t, ‖a t‖ ≤ M)
    (hA : Tendsto (s01I a 0) atTop (𝓝 L))
    (hQ : Tendsto (fun σ => ((√σ : ℝ) : ℂ) * s01I a 1 σ) atTop (𝓝 0)) (p q : Polynomial ℝ) :
    S01Good a L (fun t => ((Real.exp (-t ^ 2) * p.eval (Real.exp (-t ^ 2)) +
      t * Real.exp (-t ^ 2) * q.eval (Real.exp (-t ^ 2)) : ℝ) : ℂ)) := by
  have hreal : ∀ t : ℝ, Real.exp (-t ^ 2) * p.eval (Real.exp (-t ^ 2)) +
      t * Real.exp (-t ^ 2) * q.eval (Real.exp (-t ^ 2)) =
      (∑ i ∈ Finset.range (p.natDegree + 1),
          p.coeff i * Real.exp (-((i : ℝ) + 1) * t ^ 2)) +
        ∑ i ∈ Finset.range (q.natDegree + 1),
          q.coeff i * (t * Real.exp (-((i : ℝ) + 1) * t ^ 2)) := by
    intro t
    have hexp : ∀ i : ℕ, Real.exp (-((i : ℝ) + 1) * t ^ 2) =
        Real.exp (-t ^ 2) * Real.exp (-t ^ 2) ^ i := by
      intro i
      rw [← Real.exp_nat_mul, ← Real.exp_add]; congr 1; ring
    rw [Polynomial.eval_eq_sum_range, Polynomial.eval_eq_sum_range, Finset.mul_sum,
      Finset.mul_sum]
    congr 1
    · refine Finset.sum_congr rfl fun i _ => ?_
      rw [hexp]; ring
    · refine Finset.sum_congr rfl fun i _ => ?_
      rw [hexp]; ring
  have hfun : (fun t => ((Real.exp (-t ^ 2) * p.eval (Real.exp (-t ^ 2)) +
      t * Real.exp (-t ^ 2) * q.eval (Real.exp (-t ^ 2)) : ℝ) : ℂ)) =
      fun t => (∑ i ∈ Finset.range (p.natDegree + 1),
          (p.coeff i : ℂ) * ((Real.exp (-((i : ℝ) + 1) * t ^ 2) : ℝ) : ℂ)) +
        ∑ i ∈ Finset.range (q.natDegree + 1),
          (q.coeff i : ℂ) * ((t * Real.exp (-((i : ℝ) + 1) * t ^ 2) : ℝ) : ℂ) := by
    funext t
    rw [hreal t]
    simp only [Complex.ofReal_add, Complex.ofReal_sum, Complex.ofReal_mul]
  rw [hfun]
  refine s01_good_add ?_ ?_ ha hM
  · refine s01_good_sum ha hM _ (fun i t => (p.coeff i : ℂ) *
      ((Real.exp (-((i : ℝ) + 1) * t ^ 2) : ℝ) : ℂ)) fun i _ => ?_
    exact s01_good_const_mul (s01_good_gauss hA (by positivity)) _
  · refine s01_good_sum ha hM _ (fun i t => (q.coeff i : ℂ) *
      ((t * Real.exp (-((i : ℝ) + 1) * t ^ 2) : ℝ) : ℂ)) fun i _ => ?_
    exact s01_good_const_mul (s01_good_odd hQ (by positivity)) _

lemma s01_integrable_weight :
    Integrable (fun t : ℝ => (1 + |t|) * Real.exp (-t ^ 2)) := by
  have h1 : Integrable (fun t : ℝ => Real.exp (-1 * t ^ 2)) := integrable_exp_neg_mul_sq one_pos
  have h2 := (integrable_mul_exp_neg_mul_sq (b := 1) one_pos).norm
  refine (h1.add h2).congr (Eventually.of_forall fun t => ?_)
  simp only [Pi.add_apply, Real.norm_eq_abs, abs_mul, abs_of_pos (Real.exp_pos _), neg_one_mul]
  ring

/-- Helper for node S01: continuous real functions vanishing near `0` and near infinity are
good. -/
lemma s01_good_cont_real {L : ℂ} (ha : Measurable a) (hM : ∀ t, ‖a t‖ ≤ M)
    (hA : Tendsto (s01I a 0) atTop (𝓝 L))
    (hQ : Tendsto (fun σ => ((√σ : ℝ) : ℂ) * s01I a 1 σ) atTop (𝓝 0))
    {f : ℝ → ℝ} (hf : Continuous f) {δ R0 : ℝ} (hδ : 0 < δ)
    (hz : ∀ t, |t| ≤ δ ∨ R0 ≤ |t| → f t = 0) : S01Good a L (fun t => (f t : ℂ)) := by
  have hcs : HasCompactSupport f := by
    refine HasCompactSupport.intro (isCompact_Icc (a := -R0) (b := R0)) fun x hx => hz x ?_
    right
    simp only [mem_Icc, not_and_or, not_le] at hx
    rcases hx with hx | hx
    · linarith [neg_le_abs x]
    · linarith [le_abs_self x]
  have hfi : Integrable (fun t => (f t : ℂ)) := (hf.integrable_of_hasCompactSupport hcs).ofReal
  refine s01_good_of_approx ha hM hfi fun η hη => ?_
  set K0 := ∫ t : ℝ, (1 + |t|) * Real.exp (-t ^ 2)
  have hK0 : 0 ≤ K0 := integral_nonneg fun t => by positivity
  obtain ⟨p, q, hpq⟩ := s01_poly_approx hf hδ hz (η := η / (K0 + 1)) (by positivity)
  have hgood := s01_good_poly ha hM hA hQ p q
  refine ⟨_, hgood, ?_⟩
  calc ∫ t, ‖(f t : ℂ) - ((Real.exp (-t ^ 2) * p.eval (Real.exp (-t ^ 2)) +
        t * Real.exp (-t ^ 2) * q.eval (Real.exp (-t ^ 2)) : ℝ) : ℂ)‖
      ≤ ∫ t, η / (K0 + 1) * ((1 + |t|) * Real.exp (-t ^ 2)) := by
        refine integral_mono (hfi.sub hgood.1).norm (s01_integrable_weight.const_mul _)
          fun t => ?_
        simp only
        rw [← Complex.ofReal_sub, Complex.norm_real, Real.norm_eq_abs]
        exact hpq t
    _ = η / (K0 + 1) * K0 := integral_const_mul _ _
    _ ≤ η := by
        rw [div_mul_eq_mul_div, div_le_iff₀ (by positivity)]
        nlinarith

/-- Helper for node S01: continuous complex functions vanishing near `0` and near infinity are
good. -/
lemma s01_good_cont_complex {L : ℂ} (ha : Measurable a) (hM : ∀ t, ‖a t‖ ≤ M)
    (hA : Tendsto (s01I a 0) atTop (𝓝 L))
    (hQ : Tendsto (fun σ => ((√σ : ℝ) : ℂ) * s01I a 1 σ) atTop (𝓝 0))
    {g : ℝ → ℂ} (hg : Continuous g) {δ R0 : ℝ} (hδ : 0 < δ)
    (hz : ∀ t, |t| ≤ δ ∨ R0 ≤ |t| → g t = 0) : S01Good a L g := by
  have h1 := s01_good_cont_real ha hM hA hQ (Complex.continuous_re.comp hg) hδ (R0 := R0)
    (fun t ht => by simp [hz t ht])
  have h2 := s01_good_cont_real ha hM hA hQ (Complex.continuous_im.comp hg) hδ (R0 := R0)
    (fun t ht => by simp [hz t ht])
  have := s01_good_add h1 (s01_good_const_mul h2 Complex.I) ha hM
  convert this using 1
  funext t
  simp only [Function.comp_apply]
  rw [mul_comm, Complex.re_add_im]

/-- Helper for node S01: continuous compactly supported kernels are good (cut off near `0`). -/
lemma s01_good_cc {L : ℂ} (ha : Measurable a) (hM : ∀ t, ‖a t‖ ≤ M)
    (hA : Tendsto (s01I a 0) atTop (𝓝 L))
    (hQ : Tendsto (fun σ => ((√σ : ℝ) : ℂ) * s01I a 1 σ) atTop (𝓝 0))
    {h : ℝ → ℂ} (hh : Continuous h) (hcs : HasCompactSupport h) : S01Good a L h := by
  obtain ⟨Mh, hMh⟩ := hh.bounded_above_of_compact_support hcs
  have hMh0 : 0 ≤ Mh := (norm_nonneg _).trans (hMh 0)
  obtain ⟨r, hr⟩ := hcs.isCompact.isBounded.subset_closedBall 0
  have hhz : ∀ t, r + 1 ≤ |t| → h t = 0 := by
    intro t ht
    refine image_eq_zero_of_notMem_tsupport fun hmem => ?_
    have := hr hmem
    rw [Metric.mem_closedBall, dist_zero_right, Real.norm_eq_abs] at this
    linarith
  refine s01_good_of_approx ha hM (hh.integrable_of_hasCompactSupport hcs) fun η hη => ?_
  set δ := η / (4 * (Mh + 1)) with hδ
  have hδ0 : 0 < δ := by positivity
  set χ : ℝ → ℝ := fun t => min 1 (max 0 (|t| / δ - 1)) with hχ
  have hχc : Continuous χ := by fun_prop
  have hχ01 : ∀ t, 0 ≤ χ t ∧ χ t ≤ 1 := fun t =>
    ⟨le_min zero_le_one (le_max_left _ _), min_le_left _ _⟩
  set ψ : ℝ → ℂ := fun t => (χ t : ℂ) * h t with hψ
  have hψgood : S01Good a L ψ := by
    refine s01_good_cont_complex ha hM hA hQ (by fun_prop) hδ0 (R0 := r + 1) fun t ht => ?_
    rcases ht with ht | ht
    · have : χ t = 0 := by
        have h1 : |t| / δ - 1 ≤ 0 := by
          rw [sub_nonpos, div_le_one hδ0]; exact ht
        simp only [hχ, max_eq_left h1, min_eq_right zero_le_one]
      simp [hψ, this]
    · simp [hψ, hhz t ht]
  refine ⟨ψ, hψgood, ?_⟩
  have hbound : ∀ t, ‖h t - ψ t‖ ≤ (Icc (-(2 * δ)) (2 * δ)).indicator (fun _ => Mh) t := by
    intro t
    have e : h t - ψ t = ((1 - χ t : ℝ) : ℂ) * h t := by simp [hψ]; ring
    rw [e, norm_mul, Complex.norm_real, Real.norm_eq_abs]
    by_cases ht : t ∈ Icc (-(2 * δ)) (2 * δ)
    · rw [indicator_of_mem ht]
      have : |1 - χ t| ≤ 1 := by
        rw [abs_le]; constructor <;> linarith [hχ01 t]
      calc |1 - χ t| * ‖h t‖ ≤ 1 * Mh := mul_le_mul this (hMh t) (norm_nonneg _) zero_le_one
        _ = Mh := one_mul _
    · rw [indicator_of_notMem ht]
      have ht' : 2 * δ < |t| := by
        simp only [mem_Icc, not_and_or, not_le] at ht
        rcases ht with ht | ht
        · linarith [neg_abs_le t]
        · linarith [le_abs_self t]
      have : χ t = 1 := by
        have h1 : 1 ≤ |t| / δ - 1 := by
          rw [le_sub_iff_add_le, le_div_iff₀ hδ0]; linarith
        simp only [hχ, max_eq_right (by linarith : (0 : ℝ) ≤ |t| / δ - 1),
          min_eq_left h1]
      simp [this]
  calc ∫ t, ‖h t - ψ t‖ ≤ ∫ t, (Icc (-(2 * δ)) (2 * δ)).indicator (fun _ => Mh) t := by
        refine integral_mono ((hh.integrable_of_hasCompactSupport hcs).sub hψgood.1).norm
          ?_ hbound
        exact (integrableOn_const measure_Icc_lt_top.ne).integrable_indicator measurableSet_Icc
    _ = 4 * δ * Mh := by
        rw [integral_indicator_const _ measurableSet_Icc]
        simp only [Measure.real, Real.volume_Icc, smul_eq_mul]
        rw [ENNReal.toReal_ofReal (by linarith)]
        ring
    _ ≤ η := by
        rw [hδ]
        rw [show 4 * (η / (4 * (Mh + 1))) * Mh = η * (Mh / (Mh + 1)) by field_simp]
        have : Mh / (Mh + 1) ≤ 1 := by rw [div_le_one (by linarith)]; linarith
        nlinarith

/-- Helper for node S01: every integrable kernel is good. -/
lemma s01_good_all {L : ℂ} (ha : Measurable a) (hM : ∀ t, ‖a t‖ ≤ M)
    (hA : Tendsto (s01I a 0) atTop (𝓝 L))
    (hQ : Tendsto (fun σ => ((√σ : ℝ) : ℂ) * s01I a 1 σ) atTop (𝓝 0))
    {φ : ℝ → ℂ} (hφ : Integrable φ) : S01Good a L φ := by
  refine s01_good_of_approx ha hM hφ fun η hη => ?_
  obtain ⟨g, hgcs, hgη, hgc, -⟩ := hφ.exists_hasCompactSupport_integral_sub_le hη
  exact ⟨g, s01_good_cc ha hM hA hQ hgc hgcs, hgη⟩

/-- **Lemma "Scalar implication" (node S01).** Let `a : ℝ → ℂ` be bounded and measurable,
`c = 63/20`, `C_m(s) = ∫ a(t) s^{m/2} g_{cs}^{(m)}(t) dt` and `H_m(s) = ∫_1^s C_m(u) du/u`.
If `H_3(s)` and `H_4(s)` converge as `s → ∞`, then there is `L ∈ ℂ` such that
`∫ a(t) R⁻¹ φ(t/R) dt → L ∫ φ` for every `φ ∈ L¹(ℝ)`; in particular
`R⁻¹ ∫_0^R a(t) dt → L`. -/
theorem Gaussian_primitives_to_all_L1_kernels {a : ℝ → ℂ} (ha : Measurable a) {M : ℝ}
    (hM : ∀ t, ‖a t‖ ≤ M)
    (h3 : ∃ L3 : ℂ, Tendsto (fun s => ∫ u in (1 : ℝ)..s,
      (∫ t, a t * ((√u ^ 3 * gaussianD 3 (63 / 20 * u) t : ℝ) : ℂ)) / u) atTop (𝓝 L3))
    (h4 : ∃ L4 : ℂ, Tendsto (fun s => ∫ u in (1 : ℝ)..s,
      (∫ t, a t * ((√u ^ 4 * gaussianD 4 (63 / 20 * u) t : ℝ) : ℂ)) / u) atTop (𝓝 L4)) :
    ∃ L : ℂ, (∀ φ : ℝ → ℂ, Integrable φ →
      Tendsto (fun R : ℝ => ∫ t, a t * ((R⁻¹ : ℂ) * φ (t / R))) atTop (𝓝 (L * ∫ t, φ t))) ∧
      Tendsto (fun R : ℝ => (R⁻¹ : ℂ) * ∫ t in (0 : ℝ)..R, a t) atTop (𝓝 L) := by
  set c : ℝ := 63 / 20 with hcdef
  have hc : 0 < c := by norm_num
  obtain ⟨L3, hL3⟩ := h3
  obtain ⟨L4, hL4⟩ := h4
  obtain ⟨L, hE⟩ := s01_even_limit ha hM hc (L4 := L4) hL4
  have hO := s01_odd_limit ha hM hc (L3 := L3) hL3
  have hdiv : Tendsto (fun σ : ℝ => σ / c) atTop atTop := tendsto_id.atTop_div_const hc
  have hA : Tendsto (s01I a 0) atTop (𝓝 L) := by
    refine (hE.comp hdiv).congr fun σ => ?_
    simp only [Function.comp_apply]
    rw [mul_div_cancel₀ σ hc.ne']
  have hQ : Tendsto (fun σ => ((√σ : ℝ) : ℂ) * s01I a 1 σ) atTop (𝓝 0) := by
    have := (hO.comp hdiv).const_mul ((√c : ℝ) : ℂ)
    rw [mul_zero] at this
    refine this.congr' ?_
    filter_upwards [eventually_gt_atTop 0] with σ hσ
    simp only [Function.comp_apply]
    rw [mul_div_cancel₀ σ hc.ne', ← mul_assoc, ← Complex.ofReal_mul, ← Real.sqrt_mul hc.le,
      mul_div_cancel₀ σ hc.ne']
  have hall : ∀ φ : ℝ → ℂ, Integrable φ →
      Tendsto (fun R : ℝ => ∫ t, a t * ((R⁻¹ : ℂ) * φ (t / R))) atTop
        (𝓝 (L * ∫ t, φ t)) := fun φ hφ => (s01_good_all ha hM hA hQ hφ).2
  refine ⟨L, hall, ?_⟩
  -- the one-sided averages: `φ = 𝟙_{(0,1]}`
  set φ0 : ℝ → ℂ := (Ioc (0 : ℝ) 1).indicator fun _ => (1 : ℂ)
  have hφ0 : Integrable φ0 :=
    (integrableOn_const measure_Ioc_lt_top.ne).integrable_indicator measurableSet_Ioc
  have hint : ∫ t, φ0 t = 1 := by
    rw [integral_indicator_const _ measurableSet_Ioc]
    simp [Measure.real, Real.volume_Ioc]
  have := hall φ0 hφ0
  rw [hint, mul_one] at this
  refine this.congr' ?_
  filter_upwards [eventually_gt_atTop 0] with R hR
  rw [intervalIntegral.integral_of_le hR.le, ← integral_indicator measurableSet_Ioc,
    ← integral_const_mul]
  congr 1; funext t
  by_cases ht : t ∈ Ioc 0 R
  · have ht' : t / R ∈ Ioc (0 : ℝ) 1 :=
      ⟨div_pos ht.1 hR, (div_le_one hR).2 ht.2⟩
    simp only [φ0, indicator_of_mem ht, indicator_of_mem ht']
    ring
  · have ht' : t / R ∉ Ioc (0 : ℝ) 1 := fun h =>
      ht ⟨(div_pos_iff_of_pos_right hR).1 h.1, (div_le_one hR).1 h.2⟩
    simp only [φ0, indicator_of_notMem ht, indicator_of_notMem ht']
    ring

end S01

end S01Sec

/-- The statement of Theorem 8.2 (node S02). -/
def S02Statement : Prop :=
  ∀ (Ω : Type) [MeasurableSpace Ω] (ν : Measure Ω) [IsProbabilityMeasure ν]
    (U V : ℝ → Ω → Ω), CommutingFlows ν U V →
    ∀ f g : Ω → ℂ, Measurable f → Measurable g → (∃ B, ∀ ω, ‖f ω‖ ≤ B) → (∃ B, ∀ ω, ‖g ω‖ ≤ B) →
      ∀ᵐ ω ∂ν, ∃ L : ℂ, Tendsto (fun R : ℝ => (R⁻¹ : ℂ) * ∫ t in (0 : ℝ)..R, f (U t ω) * g (V t ω))
        atTop (𝓝 L)

/-- The statement of Lemma 6.2 (node E02): square-root counting bounds imply almost-everywhere
convergence. -/
def E02Statement : Prop := ∀ (Ω : Type) [MeasurableSpace Ω] (ν : Measure Ω) [IsProbabilityMeasure ν]
    (H : Ω → ℝ → ℂ), (∀ ω, ContinuousOn (H ω) (Set.Ioi 0)) →
    (∀ s : ℚ, 0 < s → Measurable fun ω => H ω s) →
    ∀ B : ℝ, (∀ n : ℕ, 1 ≤ n → (∫⁻ ω, countingSup n (fun u v => ‖H ω v - H ω u‖ₑ) ^ (3 / 2 : ℝ) ∂ν)
      ^ (2 / 3 : ℝ) ≤ ENNReal.ofReal (B * √n)) →
    ∀ᵐ ω ∂ν, ∃ L, Tendsto (H ω) atTop (𝓝 L)

/-- The statement of Lemma 8.1 (node S01): convergence of the Gaussian primitives implies
convergence of all `L¹`-kernel averages. -/
def S01Statement : Prop := ∀ (a : ℝ → ℂ), Measurable a → ∀ M : ℝ, (∀ t, ‖a t‖ ≤ M) →
    (∃ L3 : ℂ, Tendsto (fun s => ∫ u in (1 : ℝ)..s,
      (∫ t, a t * ((√u ^ 3 * gaussianD 3 (63 / 20 * u) t : ℝ) : ℂ)) / u) atTop (𝓝 L3)) →
    (∃ L4 : ℂ, Tendsto (fun s => ∫ u in (1 : ℝ)..s,
      (∫ t, a t * ((√u ^ 4 * gaussianD 4 (63 / 20 * u) t : ℝ) : ℂ)) / u) atTop (𝓝 L4)) →
    ∃ L : ℂ, (∀ φ : ℝ → ℂ, Integrable φ →
        Tendsto (fun R : ℝ => ∫ t, a t * ((R⁻¹ : ℂ) * φ (t / R))) atTop (𝓝 (L * ∫ t, φ t))) ∧
      Tendsto (fun R : ℝ => (R⁻¹ : ℂ) * ∫ t in (0 : ℝ)..R, a t) atTop (𝓝 L)

/-! ### Node S02: the scalar primitives -/

section S02Scalar

/-- The scale integrand `(u, t) ↦ u^{m/2} g_{cu}^{(m)}(t)/u` is integrable on `(α, β] × ℝ`. -/
lemma integrable_prod_kernIntegrand_S02 (m : ℕ) {α β : ℝ} (hα : 0 < α) :
    Integrable (fun z : ℝ × ℝ => kernIntegrand m z.1 z.2)
      ((volume.restrict (Set.Ioc α β)).prod volume) := by
  set μ : Measure ℝ := volume.restrict (Set.Ioc α β)
  set f : ℝ × ℝ → ℝ := fun z => kernIntegrand m z.1 z.2
  have hcont : ContinuousOn f (Set.Ioc α β ×ˢ Set.univ) :=
    (continuousOn_kernIntegrand_joint m).mono fun z hz => hα.trans hz.1.1
  have hmeas : AEStronglyMeasurable f (μ.prod volume) := by
    have hμ : μ.prod (volume : Measure ℝ) =
        ((volume : Measure ℝ).prod volume).restrict (Set.Ioc α β ×ˢ Set.univ) := by
      rw [← Measure.prod_restrict, Measure.restrict_univ]
    rw [hμ]
    exact hcont.aestronglyMeasurable (measurableSet_Ioc.prod MeasurableSet.univ)
  set c := ∫ t, |gaussianD m (63 / 20) t|
  have hinner : ∀ s ∈ Set.Ioc α β, ∫ t, ‖f (s, t)‖ = c / s := fun s hs => by
    simp only [f, Real.norm_eq_abs]
    exact integral_abs_kernIntegrand m (hα.trans hs.1)
  rw [integrable_prod_iff hmeas]
  refine ⟨?_, ?_⟩
  · refine (ae_restrict_iff' measurableSet_Ioc).2 (Eventually.of_forall fun s hs => ?_)
    exact integrable_kernIntegrand m (hα.trans hs.1)
  · refine (integrableOn_congr_fun (fun s hs => (hinner s hs).symm) measurableSet_Ioc).1 ?_
    refine ContinuousOn.integrableOn_Icc (f := fun s => c / s) ?_ |>.mono_set
      Set.Ioc_subset_Icc_self
    exact continuousOn_const.div continuousOn_id fun s hs => (hα.trans_le hs.1).ne'

/-- The scale average `ψ(u) = ∫ a(t) κ_{m,u}(t) dt / u`. -/
def scaleAvgS02 (m : ℕ) (a : ℝ → ℂ) (u : ℝ) : ℂ := ∫ t, a t * (kernIntegrand m u t : ℂ)

variable {a : ℝ → ℂ} {M : ℝ}

lemma integrable_prod_scaleAvgS02 (m : ℕ) (ha : Measurable a) (hM : ∀ t, ‖a t‖ ≤ M)
    {α β : ℝ} (hα : 0 < α) :
    Integrable (Function.uncurry fun u t => a t * (kernIntegrand m u t : ℂ))
      ((volume.restrict (Set.Ioc α β)).prod volume) := by
  have h := (integrable_prod_kernIntegrand_S02 m (β := β) hα).ofReal (𝕜 := ℂ)
  exact Integrable.bdd_mul (c := M) h (ha.comp measurable_snd).aestronglyMeasurable
    (Eventually.of_forall fun z => hM z.2)

lemma intervalIntegrable_scaleAvgS02 (m : ℕ) (ha : Measurable a) (hM : ∀ t, ‖a t‖ ≤ M)
    {α β : ℝ} (hα : 0 < α) (hβ : 0 < β) : IntervalIntegrable (scaleAvgS02 m a) volume α β := by
  have key : ∀ {α β : ℝ}, 0 < α → α ≤ β → IntervalIntegrable (scaleAvgS02 m a) volume α β := by
    intro α β hα hab
    rw [intervalIntegrable_iff_integrableOn_Ioc_of_le hab]
    exact (integrable_prod_scaleAvgS02 m ha hM (β := β) hα).integral_prod_left
  rcases le_total α β with h | h
  · exact key hα h
  · exact (key hβ h).symm

lemma integral_scaleAvgS02 (m : ℕ) (ha : Measurable a) (hM : ∀ t, ‖a t‖ ≤ M)
    {α β : ℝ} (hα : 0 < α) (hβ : 0 < β) :
    ∫ u in α..β, scaleAvgS02 m a u = ∫ t, a t * KernC m α β t := by
  have key : ∀ {α β : ℝ}, 0 < α → α ≤ β →
      ∫ u in α..β, scaleAvgS02 m a u = ∫ t, a t * KernC m α β t := by
    intro α β hα hab
    rw [intervalIntegral.integral_of_le hab]
    unfold scaleAvgS02
    rw [integral_integral_swap (integrable_prod_scaleAvgS02 m ha hM (β := β) hα)]
    refine integral_congr_ae (Eventually.of_forall fun t => ?_)
    simp only
    rw [integral_const_mul, KernC, Kern_eq, intervalIntegral.integral_of_le hab, integral_complex_ofReal]
  rcases le_total α β with h | h
  · exact key hα h
  · rw [intervalIntegral.integral_symm, key hβ h, ← integral_neg]
    refine integral_congr_ae (Eventually.of_forall fun t => ?_)
    simp only [KernC, Kern_eq]
    rw [intervalIntegral.integral_symm β α]
    push_cast
    ring

/-- The primitive `H_m(s) = ∫_1^s ∫ a(t) u^{m/2} g_{cu}^{(m)}(t) dt du/u` (as in node S01). -/
def flowPrimS02 (m : ℕ) (a : ℝ → ℂ) (s : ℝ) : ℂ :=
  ∫ u in (1 : ℝ)..s, (∫ t, a t * ((√u ^ m * gaussianD m (63 / 20 * u) t : ℝ) : ℂ)) / u

lemma flowPrimS02_eq (m : ℕ) (a : ℝ → ℂ) (s : ℝ) :
    flowPrimS02 m a s = ∫ u in (1 : ℝ)..s, scaleAvgS02 m a u := by
  unfold flowPrimS02 scaleAvgS02
  refine intervalIntegral.integral_congr fun u _ => ?_
  rw [← integral_div]
  congr 1
  funext t
  simp only [kernIntegrand]
  push_cast
  ring

lemma flowPrimS02_sub (m : ℕ) (ha : Measurable a) (hM : ∀ t, ‖a t‖ ≤ M) {u v : ℝ}
    (hu : 0 < u) (hv : 0 < v) :
    flowPrimS02 m a v - flowPrimS02 m a u = ∫ t, a t * KernC m u v t := by
  rw [flowPrimS02_eq, flowPrimS02_eq, intervalIntegral.integral_interval_sub_left
    (intervalIntegrable_scaleAvgS02 m ha hM one_pos hv)
    (intervalIntegrable_scaleAvgS02 m ha hM one_pos hu), integral_scaleAvgS02 m ha hM hu hv]

lemma continuousOn_flowPrimS02 (m : ℕ) (ha : Measurable a) (hM : ∀ t, ‖a t‖ ≤ M) :
    ContinuousOn (flowPrimS02 m a) (Set.Ioi 0) := by
  intro s hs
  have hs : 0 < s := hs
  set b₁ := min s 1 / 2
  set b₂ := max s 1 + 1
  have hb₁ : 0 < b₁ := by positivity
  have h1s : b₁ < s := by
    have := min_le_left s 1; simp only [b₁]; linarith
  have h2s : s < b₂ := by have := le_max_left s 1; simp only [b₂]; linarith
  have hb12 : b₁ ≤ b₂ := h1s.le.trans h2s.le
  have hcont : ContinuousOn (fun b => ∫ u in (1 : ℝ)..b, scaleAvgS02 m a u) (Set.uIcc b₁ b₂) := by
    refine intervalIntegral.continuousOn_primitive_interval'
      (intervalIntegrable_scaleAvgS02 m ha hM hb₁ (hb₁.trans_le hb12)) ?_
    rw [Set.uIcc_of_le hb12]
    constructor
    · have := min_le_right s 1; simp only [b₁]; linarith
    · have := le_max_right s 1; simp only [b₂]; linarith
  have e : flowPrimS02 m a = fun b => ∫ u in (1 : ℝ)..b, scaleAvgS02 m a u :=
    funext (flowPrimS02_eq m a)
  rw [e]
  refine (hcont.continuousAt ?_).continuousWithinAt
  rw [Set.uIcc_of_le hb12]
  exact Icc_mem_nhds h1s h2s

end S02Scalar

/-! ### Node S02: the flow primitives -/

section S02Flow

/-- Counting functions only depend on the increments over positive intervals. -/
lemma countingSup_congr_pos {n : ℕ} {Δ Δ' : ℝ → ℝ → ℝ≥0∞}
    (h : ∀ u v : ℝ, 0 < u → u < v → Δ u v = Δ' u v) : countingSup n Δ = countingSup n Δ' := by
  unfold countingSup
  refine iSup_congr fun I => ?_
  congr 1
  refine List.map_congr_left fun p hp => ?_
  exact h _ _ (by exact_mod_cast I.pos p hp) (by exact_mod_cast I.lt p hp)

lemma measurable_Kern_one_S02 (m : ℕ) {s : ℝ} (hs : 0 < s) : Measurable (Kern m 1 s) := by
  rcases le_total 1 s with h | h
  · exact (continuous_Kern m one_pos h).measurable
  · have e : Kern m 1 s = fun t => -Kern m s 1 t := funext fun t => by
      simp only [Kern_eq]; exact intervalIntegral.integral_symm _ _
    rw [e]
    exact (continuous_Kern m hs h).measurable.neg

variable {Ω : Type} [MeasurableSpace Ω] {ν : Measure Ω} {U V : ℝ → Ω → Ω}

/-- The orbit product `t ↦ f(U^t ω) g(V^t ω)`. -/
def orbitProdS02 (U V : ℝ → Ω → Ω) (f g : Ω → ℂ) (ω : Ω) (t : ℝ) : ℂ := f (U t ω) * g (V t ω)

lemma measurable_orbitProdS02_uncurry (hUV : CommutingFlows ν U V) {f g : Ω → ℂ}
    (hf : Measurable f) (hg : Measurable g) :
    Measurable (fun p : Ω × ℝ => orbitProdS02 U V f g p.1 p.2) :=
  (hf.comp (hUV.measU.comp measurable_swap)).mul (hg.comp (hUV.measV.comp measurable_swap))

lemma measurable_orbitProdS02 (hUV : CommutingFlows ν U V) {f g : Ω → ℂ}
    (hf : Measurable f) (hg : Measurable g) (ω : Ω) : Measurable (orbitProdS02 U V f g ω) :=
  (measurable_orbitProdS02_uncurry hUV hf hg).comp measurable_prodMk_left

omit [MeasurableSpace Ω] in
lemma norm_orbitProdS02_le {f g : Ω → ℂ} {Bf Bg : ℝ} (hBf : ∀ ω, ‖f ω‖ ≤ Bf)
    (hBg : ∀ ω, ‖g ω‖ ≤ Bg) (ω : Ω) (t : ℝ) : ‖orbitProdS02 U V f g ω t‖ ≤ Bf * Bg := by
  unfold orbitProdS02
  rw [norm_mul]
  exact mul_le_mul (hBf _) (hBg _) (norm_nonneg _) ((norm_nonneg _).trans (hBf (U t ω)))

/-- The increments of the flow primitive are the interval-kernel outputs. -/
lemma flowPrimS02_orbit_sub (hUV : CommutingFlows ν U V) (m : ℕ) {f g : Ω → ℂ}
    (hf : Measurable f) (hg : Measurable g) {Bf Bg : ℝ} (hBf : ∀ ω, ‖f ω‖ ≤ Bf)
    (hBg : ∀ ω, ‖g ω‖ ≤ Bg) (ω : Ω) {u v : ℝ} (hu : 0 < u) (hv : 0 < v) :
    flowPrimS02 m (orbitProdS02 U V f g ω) v - flowPrimS02 m (orbitProdS02 U V f g ω) u =
      flowBilin U V (KernC m u v) f g ω :=
  flowPrimS02_sub m (measurable_orbitProdS02 hUV hf hg ω) (norm_orbitProdS02_le hBf hBg ω) hu hv

lemma measurable_flowPrimS02 (hUV : CommutingFlows ν U V) (m : ℕ) {f g : Ω → ℂ}
    (hf : Measurable f) (hg : Measurable g) {Bf Bg : ℝ} (hBf : ∀ ω, ‖f ω‖ ≤ Bf)
    (hBg : ∀ ω, ‖g ω‖ ≤ Bg) {s : ℝ} (hs : 0 < s) :
    Measurable fun ω => flowPrimS02 m (orbitProdS02 U V f g ω) s := by
  have e : ∀ ω, flowPrimS02 m (orbitProdS02 U V f g ω) s = flowBilin U V (KernC m 1 s) f g ω := by
    intro ω
    have h := flowPrimS02_orbit_sub hUV m hf hg hBf hBg ω one_pos hs
    have h1 : flowPrimS02 m (orbitProdS02 U V f g ω) 1 = 0 := intervalIntegral.integral_same
    rw [h1, sub_zero] at h
    exact h
  simp_rw [e]
  have hK : Measurable (KernC m 1 s) :=
    Complex.measurable_ofReal.comp (measurable_Kern_one_S02 m hs)
  have hj : StronglyMeasurable (fun p : Ω × ℝ => orbitProdS02 U V f g p.1 p.2 * KernC m 1 s p.2) :=
    ((measurable_orbitProdS02_uncurry hUV hf hg).mul (hK.comp measurable_snd)).stronglyMeasurable
  exact (hj.integral_prod_right' (ν := volume)).measurable

end S02Flow

/-- **Theorem 8.2 (node S02, convergence for commuting flows).** For commuting jointly measurable
measure-preserving real flows `U, V` on a probability space and bounded measurable `f, g`, the
averages `R⁻¹ ∫_0^R f(U^t ω) g(V^t ω) dt` converge for almost every `ω` as `R → ∞` through
real values. Derived from the flow counting estimate (node F01), the counting-to-limit lemma
(node E02) and the scalar Tauberian implication (node S01). -/
theorem commuting_flow_averages_converge (hF : F01Statement) (hE02 : E02Statement)
    (hS01 : S01Statement) : S02Statement := by
  intro Ω _ ν _ U V hUV f g hf hg hfB hgB
  obtain ⟨Bf, hBf⟩ := hfB
  obtain ⟨Bg, hBg⟩ := hgB
  obtain ⟨C, hC0, hFC⟩ := hF
  have hfin_f : eLpNorm f 3 ν ≠ ∞ :=
    (MemLp.of_bound (p := 3) hf.aestronglyMeasurable Bf (ae_of_all _ hBf)).eLpNorm_ne_top
  have hfin_g : eLpNorm g 3 ν ≠ ∞ :=
    (MemLp.of_bound (p := 3) hg.aestronglyMeasurable Bg (ae_of_all _ hBg)).eLpNorm_ne_top
  have hconv : ∀ m : ℕ, (m = 3 ∨ m = 4) → ∀ᵐ ω ∂ν, ∃ L,
      Tendsto (flowPrimS02 m (orbitProdS02 U V f g ω)) atTop (𝓝 L) := by
    intro m hm
    refine hE02 Ω ν (fun ω => flowPrimS02 m (orbitProdS02 U V f g ω))
      (fun ω => continuousOn_flowPrimS02 m (measurable_orbitProdS02 hUV hf hg ω)
        (norm_orbitProdS02_le hBf hBg ω))
      (fun s hs => measurable_flowPrimS02 hUV m hf hg hBf hBg (by exact_mod_cast hs))
      (C * ((eLpNorm f 3 ν).toReal * (eLpNorm g 3 ν).toReal)) ?_
    intro n hn
    have hcs : ∀ ω, countingSup n (fun u v => ‖flowPrimS02 m (orbitProdS02 U V f g ω) v -
        flowPrimS02 m (orbitProdS02 U V f g ω) u‖ₑ) =
        countingSup n (fun u v => ‖flowBilin U V (KernC m u v) f g ω‖ₑ) := fun ω =>
      countingSup_congr_pos fun u v hu huv => by
        rw [flowPrimS02_orbit_sub hUV m hf hg hBf hBg ω hu (hu.trans huv)]
    simp_rw [hcs]
    refine (hFC Ω ν U V hUV m hm n hn f g hf hg ⟨Bf, hBf⟩ ⟨Bg, hBg⟩).trans (le_of_eq ?_)
    rw [← ENNReal.ofReal_toReal hfin_f, ← ENNReal.ofReal_toReal hfin_g,
      ← ENNReal.ofReal_mul (by positivity), ← ENNReal.ofReal_mul (by positivity),
      ENNReal.toReal_ofReal ENNReal.toReal_nonneg, ENNReal.toReal_ofReal ENNReal.toReal_nonneg]
    congr 1
    ring
  filter_upwards [hconv 3 (Or.inl rfl), hconv 4 (Or.inr rfl)] with ω h3 h4
  obtain ⟨L, -, hL⟩ := hS01 (orbitProdS02 U V f g ω) (measurable_orbitProdS02 hUV hf hg ω)
    (Bf * Bg) (norm_orbitProdS02_le hBf hBg ω) h3 h4
  exact ⟨L, hL⟩


/-- Lemma 6.2 (node E02) in the packaged form `E02Statement`. -/
theorem E02_holds : E02Statement := fun _ _ _ _ H hc hm _ hB =>
  square_root_counting_implies_ae_Cauchy H hc hm hB

/-- Lemma 8.1 (node S01) in the packaged form `S01Statement`. -/
theorem S01_holds : S01Statement := fun _ ha _ hM h3 h4 =>
  Gaussian_primitives_to_all_L1_kernels ha hM h3 h4

/-- **Theorem 8.2 (node S02), convergence for commuting flows**, unconditionally. -/
theorem S02_holds : S02Statement :=
  commuting_flow_averages_converge flow_counting_bound E02_holds S01_holds

end

end Auto
