/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib
public import TwoCommuting.Auto.Sec8GaussianPrimitives

/-!
# Discrete transformations and arbitrary probability spaces

This file was automatically generated by Claude.

Formalization of §9 ("Discrete transformations and arbitrary probability spaces", nodes
T01–T05) of `blueprint/commuting_ergodic_blueprint.tex`.

## Contents

* T01 (`two_coordinate_suspension_flows`): the explicit two-coordinate suspension flows.
* T02 (`invertible_commuting_averages_ae`): bounded inputs for invertible maps, from S02.
* T03 (`bounded_observable_compact_coding`): compact coding of the two observables.
* T04 (`commuting_compact_natural_extension`): an explicit simultaneous invertible extension.
* T05 (`bounded_commuting_averages_ae`): bounded inputs on arbitrary probability spaces.
-/

@[expose] public section

open scoped ENNReal NNReal
open MeasureTheory Filter Topology

universe u

namespace Auto

noncomputable section

/-- The bilinear ergodic averages `A_N(f,g)(x) = N⁻¹ ∑_{n<N} f(Tⁿx) g(Sⁿx)`. -/
def bilinAvg {X : Type*} (T S : X → X) (f g : X → ℂ) (N : ℕ) (x : X) : ℂ :=
  (N : ℂ)⁻¹ * ∑ n ∈ Finset.range N, f (T^[n] x) * g (S^[n] x)

/-- The statement of Theorem 9.2 (node T02): for commuting invertible probability-preserving
maps with measurable inverses and bounded measurable `f, g`, the averages `A_N(f,g)` converge
almost everywhere. Stated for spaces in `Type`. -/
def InvertibleBoundedConvergence : Prop :=
  ∀ (Y : Type) [MeasurableSpace Y] (ν : Measure Y) [IsProbabilityMeasure ν]
    (T S Tinv Sinv : Y → Y), MeasurePreserving T ν ν → MeasurePreserving S ν ν →
    Measurable Tinv → Measurable Sinv →
    Function.LeftInverse Tinv T → Function.RightInverse Tinv T →
    Function.LeftInverse Sinv S → Function.RightInverse Sinv S →
    T ∘ S = S ∘ T →
    ∀ f g : Y → ℂ, Measurable f → Measurable g → (∃ C, ∀ y, ‖f y‖ ≤ C) → (∃ C, ∀ y, ‖g y‖ ≤ C) →
      ∀ᵐ y ∂ν, ∃ L, Tendsto (fun N => bilinAvg T S f g N y) atTop (𝓝 L)

/-! ### T01: suspension flows -/

section TSec

open Set

section T01

variable {X : Type*}

/-- Integer powers of an invertible map `T` with inverse `Tinv`: `T^k` for `k ≥ 0` and
`Tinv^(-k)` for `k < 0`. -/
def zpowMap (T Tinv : X → X) : ℤ → X → X
  | Int.ofNat n => T^[n]
  | Int.negSucc n => Tinv^[n + 1]

/-- The permutation built from `T` and its two-sided inverse. -/
def permOfInv (T Tinv : X → X) (hl : Function.LeftInverse Tinv T)
    (hr : Function.RightInverse Tinv T) : Equiv.Perm X := ⟨T, Tinv, hl, hr⟩

theorem zpowMap_eq_perm (T Tinv : X → X) (hl : Function.LeftInverse Tinv T)
    (hr : Function.RightInverse Tinv T) (k : ℤ) :
    zpowMap T Tinv k = ⇑(permOfInv T Tinv hl hr ^ k) := by
  cases k with
  | ofNat n =>
    simp [zpowMap, Equiv.Perm.coe_pow, permOfInv]
  | negSucc n =>
    rw [zpow_negSucc, ← inv_pow, Equiv.Perm.coe_pow]
    simp [zpowMap, permOfInv, Equiv.Perm.inv_def]

theorem zpowMap_add (T Tinv : X → X) (hl : Function.LeftInverse Tinv T)
    (hr : Function.RightInverse Tinv T) (a b : ℤ) (x : X) :
    zpowMap T Tinv (a + b) x = zpowMap T Tinv a (zpowMap T Tinv b x) := by
  simp only [zpowMap_eq_perm T Tinv hl hr, zpow_add, Equiv.Perm.mul_apply]

theorem zpowMap_zero (T Tinv : X → X) (x : X) : zpowMap T Tinv 0 x = x := rfl

theorem zpowMap_comm (T Tinv S Sinv : X → X) (hlT : Function.LeftInverse Tinv T)
    (hrT : Function.RightInverse Tinv T) (hlS : Function.LeftInverse Sinv S)
    (hrS : Function.RightInverse Sinv S) (hTS : T ∘ S = S ∘ T) (a b : ℤ) (x : X) :
    zpowMap T Tinv a (zpowMap S Sinv b x) = zpowMap S Sinv b (zpowMap T Tinv a x) := by
  have hc : Commute (permOfInv T Tinv hlT hrT) (permOfInv S Sinv hlS hrS) := by
    ext y
    exact congrFun hTS y
  have := (hc.zpow_zpow a b).eq
  rw [zpowMap_eq_perm T Tinv hlT hrT, zpowMap_eq_perm S Sinv hlS hrS]
  exact congrArg (fun e : Equiv.Perm X => e x) this

variable [MeasurableSpace X]

theorem measurable_zpowMap {T Tinv : X → X} (hT : Measurable T) (hTinv : Measurable Tinv)
    (k : ℤ) : Measurable (zpowMap T Tinv k) := by
  cases k with
  | ofNat n => exact hT.iterate n
  | negSucc n => exact hTinv.iterate (n + 1)

theorem measurePreserving_inv_of_measurePreserving {μ : Measure X} {T Tinv : X → X}
    (hT : MeasurePreserving T μ μ) (hTinv : Measurable Tinv)
    (hl : Function.LeftInverse Tinv T) : MeasurePreserving Tinv μ μ := by
  refine ⟨hTinv, ?_⟩
  conv_lhs => rw [← hT.map_eq]
  rw [Measure.map_map hTinv hT.measurable]
  have : Tinv ∘ T = id := funext hl
  rw [this, Measure.map_id]

theorem measurePreserving_zpowMap {μ : Measure X} {T Tinv : X → X}
    (hT : MeasurePreserving T μ μ) (hTinv : Measurable Tinv)
    (hl : Function.LeftInverse Tinv T) (k : ℤ) :
    MeasurePreserving (zpowMap T Tinv k) μ μ := by
  cases k with
  | ofNat n => exact hT.iterate n
  | negSucc n => exact (measurePreserving_inv_of_measurePreserving hT hTinv hl).iterate (n + 1)

/-- Rotation by `t` modulo one preserves Lebesgue measure on `[0,1)`, in integrated form. -/
theorem lintegral_Ico_fract_add (g : ℝ → ℝ≥0∞) (t : ℝ) :
    ∫⁻ u in Ico (0:ℝ) 1, g (Int.fract (u + t)) = ∫⁻ u in Ico (0:ℝ) 1, g u := by
  have hIco : ∀ a : ℝ, volume.restrict (Ico a (a + 1)) = volume.restrict (Ioc a (a + 1)) :=
    fun a => Measure.restrict_congr_set Ico_ae_eq_Ioc
  have h1 : ∫⁻ u in Ioc (0:ℝ) (0 + 1), g (Int.fract (u + t)) =
      ∫⁻ w in Ioc t (t + 1), g (Int.fract w) := by
    have hpre : (fun x : ℝ => x + t) ⁻¹' Ioc t (t + 1) = Ioc (0:ℝ) (0 + 1) := by
      rw [preimage_add_const_Ioc]; congr 1 <;> ring
    rw [← hpre]
    exact (measurePreserving_add_right volume t).setLIntegral_comp_preimage_emb
      (measurableEmbedding_addRight t) (fun w => g (Int.fract w)) _
  have h2 : ∫⁻ w in Ioc t (t + 1), g (Int.fract w) =
      ∫⁻ w in Ioc (0:ℝ) (0 + 1), g (Int.fract w) := by
    refine (isAddFundamentalDomain_Ioc one_pos t).setLIntegral_eq
      (isAddFundamentalDomain_Ioc one_pos 0) _ ?_
    rintro ⟨n, hn⟩ x
    obtain ⟨k, rfl⟩ := AddSubgroup.mem_zmultiples_iff.1 hn
    show g (Int.fract ((k • (1:ℝ)) + x)) = g (Int.fract x)
    simp
  have h3 : ∫⁻ w in Ico (0:ℝ) 1, g (Int.fract w) = ∫⁻ w in Ico (0:ℝ) 1, g w :=
    setLIntegral_congr_fun measurableSet_Ico (fun w hw => by rw [Int.fract_eq_self.2 hw])
  have e0 := hIco 0
  rw [zero_add] at e0
  rw [← h3, e0, ← zero_add (1:ℝ), h1, h2]

/-- The rotation `u ↦ {u + t}` preserves Lebesgue measure restricted to `[0,1)`. -/
theorem measurePreserving_fract_add (t : ℝ) :
    MeasurePreserving (fun u : ℝ => Int.fract (u + t)) (volume.restrict (Ico (0:ℝ) 1))
      (volume.restrict (Ico (0:ℝ) 1)) := by
  have hm : Measurable (fun u : ℝ => Int.fract (u + t)) := (measurable_add_const t).fract
  refine ⟨hm, ?_⟩
  ext B hB
  rw [Measure.map_apply hm hB, ← lintegral_indicator_one (hm hB), ← lintegral_indicator_one hB]
  have := lintegral_Ico_fract_add (B.indicator 1) t
  exact this

/-- A fibrewise map `(x, y) ↦ (φ_y x, ψ y)` preserves a product measure when every fibre map
`φ_y` preserves the first factor and `ψ` preserves the second. -/
theorem measurePreserving_fiberwise {Y : Type*} [MeasurableSpace Y] {μ : Measure X}
    {ρ : Measure Y} [SFinite μ] [SFinite ρ] (φ : Y → X → X) (ψ : Y → Y)
    (hφm : Measurable (Function.uncurry φ)) (hφ : ∀ y, MeasurePreserving (φ y) μ μ)
    (hψ : MeasurePreserving ψ ρ ρ) :
    MeasurePreserving (fun ω : X × Y => (φ ω.2 ω.1, ψ ω.2)) (μ.prod ρ) (μ.prod ρ) := by
  have h := hψ.skew_product (μc := μ) (μd := μ) hφm (ae_of_all _ fun y => (hφ y).map_eq)
  exact (Measure.measurePreserving_swap).comp (h.comp Measure.measurePreserving_swap)

/-- Lebesgue measure restricted to `[0,1)`. -/
abbrev unitIcoMeasure : Measure ℝ := volume.restrict (Ico (0:ℝ) 1)

instance : IsProbabilityMeasure unitIcoMeasure := ⟨by simp⟩

/-- The product probability measure `μ ⊗ Leb[0,1) ⊗ Leb[0,1)` on the suspension
`X × ℝ × ℝ` (points with a coordinate outside `[0,1)` form a null set). -/
def suspensionMeasure (μ : Measure X) : Measure (X × ℝ × ℝ) :=
  μ.prod (unitIcoMeasure.prod unitIcoMeasure)

instance (μ : Measure X) [IsProbabilityMeasure μ] :
    IsProbabilityMeasure (suspensionMeasure μ) := by
  unfold suspensionMeasure; infer_instance

/-- The suspension flow of `T` in the first real coordinate:
`U^t(x,u,v) = (T^{⌊u+t⌋} x, {u+t}, v)`. -/
def suspFlowFirst (T Tinv : X → X) (t : ℝ) (ω : X × ℝ × ℝ) : X × ℝ × ℝ :=
  (zpowMap T Tinv ⌊ω.2.1 + t⌋ ω.1, Int.fract (ω.2.1 + t), ω.2.2)

/-- The suspension flow of `S` in the second real coordinate:
`V^t(x,u,v) = (S^{⌊v+t⌋} x, u, {v+t})`. -/
def suspFlowSecond (S Sinv : X → X) (t : ℝ) (ω : X × ℝ × ℝ) : X × ℝ × ℝ :=
  (zpowMap S Sinv ⌊ω.2.2 + t⌋ ω.1, ω.2.1, Int.fract (ω.2.2 + t))

theorem floor_fract_add_add_floor (a t : ℝ) : ⌊Int.fract a + t⌋ + ⌊a⌋ = ⌊a + t⌋ := by
  have : Int.fract a + t = (a + t) - (⌊a⌋ : ℝ) := by rw [Int.fract]; ring
  rw [this, Int.floor_sub_intCast]; ring

theorem fract_fract_add (a t : ℝ) : Int.fract (Int.fract a + t) = Int.fract (a + t) := by
  have : Int.fract a + t = (a + t) - (⌊a⌋ : ℝ) := by rw [Int.fract]; ring
  rw [this, Int.fract_sub_intCast]

omit [MeasurableSpace X] in
theorem suspFlowFirst_add (T Tinv : X → X) (hl : Function.LeftInverse Tinv T)
    (hr : Function.RightInverse Tinv T) (t s : ℝ) (ω : X × ℝ × ℝ) :
    suspFlowFirst T Tinv (t + s) ω = suspFlowFirst T Tinv t (suspFlowFirst T Tinv s ω) := by
  obtain ⟨x, u, v⟩ := ω
  simp only [suspFlowFirst]
  have e : u + (t + s) = (u + s) + t := by ring
  rw [← zpowMap_add T Tinv hl hr, floor_fract_add_add_floor, fract_fract_add, e]

omit [MeasurableSpace X] in
theorem suspFlowSecond_add (S Sinv : X → X) (hl : Function.LeftInverse Sinv S)
    (hr : Function.RightInverse Sinv S) (t s : ℝ) (ω : X × ℝ × ℝ) :
    suspFlowSecond S Sinv (t + s) ω = suspFlowSecond S Sinv t (suspFlowSecond S Sinv s ω) := by
  obtain ⟨x, u, v⟩ := ω
  simp only [suspFlowSecond]
  have e : v + (t + s) = (v + s) + t := by ring
  rw [← zpowMap_add S Sinv hl hr, floor_fract_add_add_floor, fract_fract_add, e]

omit [MeasurableSpace X] in
theorem suspFlowFirst_zero (T Tinv : X → X) (ω : X × ℝ × ℝ) (hu : ω.2.1 ∈ Ico (0:ℝ) 1) :
    suspFlowFirst T Tinv 0 ω = ω := by
  obtain ⟨x, u, v⟩ := ω
  simp only [suspFlowFirst, add_zero, Int.floor_eq_zero_iff.2 hu, Int.fract_eq_self.2 hu]
  rfl

omit [MeasurableSpace X] in
theorem suspFlowSecond_zero (S Sinv : X → X) (ω : X × ℝ × ℝ) (hv : ω.2.2 ∈ Ico (0:ℝ) 1) :
    suspFlowSecond S Sinv 0 ω = ω := by
  obtain ⟨x, u, v⟩ := ω
  simp only [suspFlowSecond, add_zero, Int.floor_eq_zero_iff.2 hv, Int.fract_eq_self.2 hv]
  rfl

omit [MeasurableSpace X] in
theorem suspFlow_comm (T Tinv S Sinv : X → X) (hlT : Function.LeftInverse Tinv T)
    (hrT : Function.RightInverse Tinv T) (hlS : Function.LeftInverse Sinv S)
    (hrS : Function.RightInverse Sinv S) (hTS : T ∘ S = S ∘ T) (t s : ℝ) (ω : X × ℝ × ℝ) :
    suspFlowFirst T Tinv t (suspFlowSecond S Sinv s ω) =
      suspFlowSecond S Sinv s (suspFlowFirst T Tinv t ω) := by
  obtain ⟨x, u, v⟩ := ω
  simp only [suspFlowFirst, suspFlowSecond]
  rw [zpowMap_comm T Tinv S Sinv hlT hrT hlS hrS hTS]

theorem measurable_zpowMap_uncurry {T Tinv : X → X} (hT : Measurable T)
    (hTinv : Measurable Tinv) : Measurable (fun p : ℤ × X => zpowMap T Tinv p.1 p.2) :=
  measurable_from_prod_countable_right (fun k => measurable_zpowMap hT hTinv k)

theorem measurable_suspFlowFirst_uncurry {T Tinv : X → X} (hT : Measurable T)
    (hTinv : Measurable Tinv) :
    Measurable (fun p : ℝ × (X × ℝ × ℝ) => suspFlowFirst T Tinv p.1 p.2) := by
  unfold suspFlowFirst
  have h1 : Measurable (fun p : ℝ × (X × ℝ × ℝ) => p.2.2.1 + p.1) := by fun_prop
  refine Measurable.prodMk ?_ (Measurable.prodMk h1.fract (by fun_prop))
  exact (measurable_zpowMap_uncurry hT hTinv).comp (h1.floor.prodMk (by fun_prop))

theorem measurable_suspFlowSecond_uncurry {S Sinv : X → X} (hS : Measurable S)
    (hSinv : Measurable Sinv) :
    Measurable (fun p : ℝ × (X × ℝ × ℝ) => suspFlowSecond S Sinv p.1 p.2) := by
  unfold suspFlowSecond
  have h1 : Measurable (fun p : ℝ × (X × ℝ × ℝ) => p.2.2.2 + p.1) := by fun_prop
  refine Measurable.prodMk ?_ (Measurable.prodMk (by fun_prop) h1.fract)
  exact (measurable_zpowMap_uncurry hS hSinv).comp (h1.floor.prodMk (by fun_prop))

theorem measurePreserving_suspFlowFirst {μ : Measure X} [SFinite μ] {T Tinv : X → X}
    (hT : MeasurePreserving T μ μ) (hTinv : Measurable Tinv)
    (hl : Function.LeftInverse Tinv T) (t : ℝ) :
    MeasurePreserving (suspFlowFirst T Tinv t) (suspensionMeasure μ) (suspensionMeasure μ) := by
  have hψ : MeasurePreserving (Prod.map (fun u : ℝ => Int.fract (u + t)) id)
      (unitIcoMeasure.prod unitIcoMeasure) (unitIcoMeasure.prod unitIcoMeasure) :=
    (measurePreserving_fract_add t).prod (MeasurePreserving.id _)
  have hφm : Measurable (Function.uncurry
      (fun (p : ℝ × ℝ) (x : X) => zpowMap T Tinv ⌊p.1 + t⌋ x)) :=
    (measurable_zpowMap_uncurry hT.measurable hTinv).comp
      (((measurable_fst.comp measurable_fst).add_const t).floor.prodMk measurable_snd)
  exact measurePreserving_fiberwise (μ := μ) (fun (p : ℝ × ℝ) (x : X) => zpowMap T Tinv ⌊p.1 + t⌋ x)
    _ hφm (fun p => measurePreserving_zpowMap hT hTinv hl _) hψ

theorem measurePreserving_suspFlowSecond {μ : Measure X} [SFinite μ] {S Sinv : X → X}
    (hS : MeasurePreserving S μ μ) (hSinv : Measurable Sinv)
    (hl : Function.LeftInverse Sinv S) (t : ℝ) :
    MeasurePreserving (suspFlowSecond S Sinv t) (suspensionMeasure μ) (suspensionMeasure μ) := by
  have hψ : MeasurePreserving (Prod.map id (fun v : ℝ => Int.fract (v + t)))
      (unitIcoMeasure.prod unitIcoMeasure) (unitIcoMeasure.prod unitIcoMeasure) :=
    (MeasurePreserving.id _).prod (measurePreserving_fract_add t)
  have hφm : Measurable (Function.uncurry
      (fun (p : ℝ × ℝ) (x : X) => zpowMap S Sinv ⌊p.2 + t⌋ x)) :=
    (measurable_zpowMap_uncurry hS.measurable hSinv).comp
      (((measurable_snd.comp measurable_fst).add_const t).floor.prodMk measurable_snd)
  exact measurePreserving_fiberwise (μ := μ) (fun (p : ℝ × ℝ) (x : X) => zpowMap S Sinv ⌊p.2 + t⌋ x)
    _ hφm (fun p => measurePreserving_zpowMap hS hSinv hl _) hψ

theorem ae_suspension_mem_Ico (μ : Measure X) [SFinite μ] :
    ∀ᵐ ω ∂suspensionMeasure μ, ω.2.1 ∈ Ico (0:ℝ) 1 ∧ ω.2.2 ∈ Ico (0:ℝ) 1 := by
  have h0 : ∀ᵐ u ∂unitIcoMeasure, u ∈ Ico (0:ℝ) 1 := ae_restrict_mem measurableSet_Ico
  have h1 : ∀ᵐ p ∂(unitIcoMeasure.prod unitIcoMeasure),
      p.1 ∈ Ico (0:ℝ) 1 ∧ p.2 ∈ Ico (0:ℝ) 1 :=
    (Measure.quasiMeasurePreserving_fst.ae h0).and (Measure.quasiMeasurePreserving_snd.ae h0)
  exact Measure.quasiMeasurePreserving_snd.ae h1

/-- **Lemma 9.1 (node T01, suspension flows).** Let `T, S` be commuting invertible
probability-preserving transformations of `(X, μ)` with measurable inverses `Tinv, Sinv`.
On `Ω = X × ℝ × ℝ` with the product probability measure `μ ⊗ Leb[0,1) ⊗ Leb[0,1)`
(which is carried by `X × [0,1)²`), the formulas
`U^t(x,u,v) = (T^{⌊u+t⌋} x, {u+t}, v)` and `V^t(x,u,v) = (S^{⌊v+t⌋} x, u, {v+t})`
define commuting, jointly measurable, measure-preserving real flows: the group laws hold at
every point, `U^0` and `V^0` are the identity on `X × [0,1)²` (a set of full measure), the
two flows commute at every point, `(t, ω) ↦ U^t ω` and `(t, ω) ↦ V^t ω` are measurable, and each
`U^t`, `V^t` preserves the measure. -/
theorem two_coordinate_suspension_flows (μ : Measure X) [IsProbabilityMeasure μ]
    (T S Tinv Sinv : X → X) (hT : MeasurePreserving T μ μ) (hS : MeasurePreserving S μ μ)
    (hTinv : Measurable Tinv) (hSinv : Measurable Sinv)
    (hlT : Function.LeftInverse Tinv T) (hrT : Function.RightInverse Tinv T)
    (hlS : Function.LeftInverse Sinv S) (hrS : Function.RightInverse Sinv S)
    (hTS : T ∘ S = S ∘ T) :
    IsProbabilityMeasure (suspensionMeasure μ) ∧
    (∀ᵐ ω ∂suspensionMeasure μ, ω.2.1 ∈ Ico (0:ℝ) 1 ∧ ω.2.2 ∈ Ico (0:ℝ) 1) ∧
    (∀ (t s : ℝ) (ω : X × ℝ × ℝ),
      suspFlowFirst T Tinv (t + s) ω = suspFlowFirst T Tinv t (suspFlowFirst T Tinv s ω)) ∧
    (∀ (t s : ℝ) (ω : X × ℝ × ℝ),
      suspFlowSecond S Sinv (t + s) ω = suspFlowSecond S Sinv t (suspFlowSecond S Sinv s ω)) ∧
    (∀ ω : X × ℝ × ℝ, ω.2.1 ∈ Ico (0:ℝ) 1 → suspFlowFirst T Tinv 0 ω = ω) ∧
    (∀ ω : X × ℝ × ℝ, ω.2.2 ∈ Ico (0:ℝ) 1 → suspFlowSecond S Sinv 0 ω = ω) ∧
    (∀ (t s : ℝ) (ω : X × ℝ × ℝ),
      suspFlowFirst T Tinv t (suspFlowSecond S Sinv s ω) =
        suspFlowSecond S Sinv s (suspFlowFirst T Tinv t ω)) ∧
    Measurable (fun p : ℝ × (X × ℝ × ℝ) => suspFlowFirst T Tinv p.1 p.2) ∧
    Measurable (fun p : ℝ × (X × ℝ × ℝ) => suspFlowSecond S Sinv p.1 p.2) ∧
    (∀ t : ℝ, MeasurePreserving (suspFlowFirst T Tinv t)
      (suspensionMeasure μ) (suspensionMeasure μ)) ∧
    (∀ t : ℝ, MeasurePreserving (suspFlowSecond S Sinv t)
      (suspensionMeasure μ) (suspensionMeasure μ)) :=
  ⟨inferInstance, ae_suspension_mem_Ico μ, suspFlowFirst_add T Tinv hlT hrT,
    suspFlowSecond_add S Sinv hlS hrS, suspFlowFirst_zero T Tinv, suspFlowSecond_zero S Sinv,
    suspFlow_comm T Tinv S Sinv hlT hrT hlS hrS hTS,
    measurable_suspFlowFirst_uncurry hT.measurable hTinv,
    measurable_suspFlowSecond_uncurry hS.measurable hSinv,
    measurePreserving_suspFlowFirst hT hTinv hlT, measurePreserving_suspFlowSecond hS hSinv hlS⟩

end T01

/-! ### T03: compact coding of two bounded observables -/

section T03

/-- The code space `E = (D × D)^(ℕ × ℕ)`, where `D` is the closed disk of radius `C` in `ℂ`.
It carries the product topology (compact, metrizable) and its Borel σ-algebra. -/
abbrev codeSpace (C : ℝ) : Type :=
  ℕ × ℕ → (Metric.closedBall (0:ℂ) C × Metric.closedBall (0:ℂ) C)

/-- The shift `(m,n) ↦ (m+1,n)` on the code space. -/
def codeShiftFirst {C : ℝ} (e : codeSpace C) : codeSpace C := fun k => e (k.1 + 1, k.2)

/-- The shift `(m,n) ↦ (m,n+1)` on the code space. -/
def codeShiftSecond {C : ℝ} (e : codeSpace C) : codeSpace C := fun k => e (k.1, k.2 + 1)

/-- First component of the `(0,0)` coordinate. -/
def codeObsFirst {C : ℝ} (e : codeSpace C) : ℂ := ((e (0, 0)).1 : ℂ)

/-- Second component of the `(0,0)` coordinate. -/
def codeObsSecond {C : ℝ} (e : codeSpace C) : ℂ := ((e (0, 0)).2 : ℂ)

variable {X : Type*}

/-- The coding map `π(x)_{m,n} = (f(T^m S^n x), g(T^m S^n x))`. -/
def codeMap (T S : X → X) (f g : X → ℂ) (C : ℝ) (hfC : ∀ x, ‖f x‖ ≤ C)
    (hgC : ∀ x, ‖g x‖ ≤ C) (x : X) : codeSpace C := fun k =>
  (⟨f (T^[k.1] (S^[k.2] x)), mem_closedBall_zero_iff.2 (hfC _)⟩,
    ⟨g (T^[k.1] (S^[k.2] x)), mem_closedBall_zero_iff.2 (hgC _)⟩)

theorem continuous_codeShiftFirst (C : ℝ) : Continuous (codeShiftFirst (C := C)) :=
  continuous_pi fun _ => continuous_apply _

theorem continuous_codeShiftSecond (C : ℝ) : Continuous (codeShiftSecond (C := C)) :=
  continuous_pi fun _ => continuous_apply _

theorem continuous_codeObsFirst (C : ℝ) : Continuous (codeObsFirst (C := C)) :=
  continuous_subtype_val.comp (continuous_fst.comp (continuous_apply _))

theorem continuous_codeObsSecond (C : ℝ) : Continuous (codeObsSecond (C := C)) :=
  continuous_subtype_val.comp (continuous_snd.comp (continuous_apply _))

theorem codeShift_comm (C : ℝ) :
    codeShiftFirst (C := C) ∘ codeShiftSecond = codeShiftSecond ∘ codeShiftFirst := rfl

theorem norm_codeObsFirst_le {C : ℝ} (e : codeSpace C) : ‖codeObsFirst e‖ ≤ C :=
  mem_closedBall_zero_iff.1 (e (0, 0)).1.2

theorem norm_codeObsSecond_le {C : ℝ} (e : codeSpace C) : ‖codeObsSecond e‖ ≤ C :=
  mem_closedBall_zero_iff.1 (e (0, 0)).2.2

theorem codeObsFirst_codeMap (T S : X → X) (f g : X → ℂ) (C : ℝ) (hfC : ∀ x, ‖f x‖ ≤ C)
    (hgC : ∀ x, ‖g x‖ ≤ C) : codeObsFirst ∘ codeMap T S f g C hfC hgC = f := rfl

theorem codeObsSecond_codeMap (T S : X → X) (f g : X → ℂ) (C : ℝ) (hfC : ∀ x, ‖f x‖ ≤ C)
    (hgC : ∀ x, ‖g x‖ ≤ C) : codeObsSecond ∘ codeMap T S f g C hfC hgC = g := rfl

theorem codeMap_comp_first (T S : X → X) (hTS : T ∘ S = S ∘ T) (f g : X → ℂ) (C : ℝ)
    (hfC : ∀ x, ‖f x‖ ≤ C) (hgC : ∀ x, ‖g x‖ ≤ C) :
    codeMap T S f g C hfC hgC ∘ T = codeShiftFirst ∘ codeMap T S f g C hfC hgC := by
  have hc : Function.Commute S T := fun x => (congrFun hTS x).symm
  funext x k
  have e : T^[k.1] (S^[k.2] (T x)) = T^[k.1 + 1] (S^[k.2] x) := by
    rw [(hc.iterate_left k.2).eq, Function.iterate_succ_apply]
  simp only [Function.comp_apply, codeMap, codeShiftFirst, e]

theorem codeMap_comp_second (T S : X → X) (f g : X → ℂ) (C : ℝ)
    (hfC : ∀ x, ‖f x‖ ≤ C) (hgC : ∀ x, ‖g x‖ ≤ C) :
    codeMap T S f g C hfC hgC ∘ S = codeShiftSecond ∘ codeMap T S f g C hfC hgC := by
  funext x k
  have e : S^[k.2] (S x) = S^[k.2 + 1] x := (Function.iterate_succ_apply S k.2 x).symm
  simp only [Function.comp_apply, codeMap, codeShiftSecond, e]

variable [MeasurableSpace X]

theorem measurable_codeMap {T S : X → X} (hT : Measurable T) (hS : Measurable S) {f g : X → ℂ}
    (hf : Measurable f) (hg : Measurable g) (C : ℝ) (hfC : ∀ x, ‖f x‖ ≤ C)
    (hgC : ∀ x, ‖g x‖ ≤ C) : Measurable (codeMap T S f g C hfC hgC) := by
  refine Measurable.of_eval fun k => ?_
  have hk : Measurable (fun x => T^[k.1] (S^[k.2] x)) :=
    (hT.iterate k.1).comp (hS.iterate k.2)
  exact ((hf.comp hk).subtype_mk).prodMk ((hg.comp hk).subtype_mk)

theorem measurePreserving_of_semiconj {Y : Type*} [MeasurableSpace Y] {μ : Measure X}
    {π : X → Y} (hπ : Measurable π) {T : X → X} {τ : Y → Y} (hT : MeasurePreserving T μ μ)
    (hτ : Measurable τ) (h : π ∘ T = τ ∘ π) :
    MeasurePreserving τ (μ.map π) (μ.map π) := by
  refine ⟨hτ, ?_⟩
  rw [Measure.map_map hτ hπ, ← h, ← Measure.map_map hπ hT.measurable, hT.map_eq]

/-- **Lemma 9.3 (node T03, compact coding of the two observables).** For commuting
measure-preserving maps `T, S` on an arbitrary probability space and bounded measurable
`f, g : X → ℂ`, there are a compact metrizable space `E` with its Borel σ-algebra, a Borel
probability measure `ν`, commuting continuous `ν`-preserving maps `τ, σ`, bounded continuous
`f_E, g_E : E → ℂ`, and a measurable measure-preserving `π : X → E` with
`π ∘ T = τ ∘ π`, `π ∘ S = σ ∘ π`, `f = f_E ∘ π`, `g = g_E ∘ π`. -/
theorem bounded_observable_compact_coding (μ : Measure X) [IsProbabilityMeasure μ]
    (T S : X → X) (hT : MeasurePreserving T μ μ) (hS : MeasurePreserving S μ μ)
    (hTS : T ∘ S = S ∘ T) (f g : X → ℂ) (hf : Measurable f) (hg : Measurable g)
    (hfb : ∃ C, ∀ x, ‖f x‖ ≤ C) (hgb : ∃ C, ∀ x, ‖g x‖ ≤ C) :
    ∃ (E : Type) (_ : TopologicalSpace E) (_ : MeasurableSpace E),
      CompactSpace E ∧ TopologicalSpace.MetrizableSpace E ∧ BorelSpace E ∧
      ∃ (ν : Measure E) (τ σ : E → E) (fE gE : E → ℂ) (π : X → E),
        IsProbabilityMeasure ν ∧ Continuous τ ∧ Continuous σ ∧ τ ∘ σ = σ ∘ τ ∧
        MeasurePreserving τ ν ν ∧ MeasurePreserving σ ν ν ∧
        Continuous fE ∧ Continuous gE ∧ (∃ C, ∀ e, ‖fE e‖ ≤ C) ∧ (∃ C, ∀ e, ‖gE e‖ ≤ C) ∧
        MeasurePreserving π μ ν ∧ π ∘ T = τ ∘ π ∧ π ∘ S = σ ∘ π ∧
        f = fE ∘ π ∧ g = gE ∘ π := by
  obtain ⟨Cf, hCf⟩ := hfb
  obtain ⟨Cg, hCg⟩ := hgb
  set C := max Cf Cg
  have hfC : ∀ x, ‖f x‖ ≤ C := fun x => (hCf x).trans (le_max_left _ _)
  have hgC : ∀ x, ‖g x‖ ≤ C := fun x => (hCg x).trans (le_max_right _ _)
  have hπ := measurable_codeMap hT.measurable hS.measurable hf hg C hfC hgC
  refine ⟨codeSpace C, inferInstance, inferInstance, inferInstance, inferInstance, inferInstance,
    μ.map (codeMap T S f g C hfC hgC), codeShiftFirst, codeShiftSecond, codeObsFirst,
    codeObsSecond, codeMap T S f g C hfC hgC, inferInstance,
    continuous_codeShiftFirst C, continuous_codeShiftSecond C, codeShift_comm C,
    measurePreserving_of_semiconj hπ hT (continuous_codeShiftFirst C).measurable
      (codeMap_comp_first T S hTS f g C hfC hgC),
    measurePreserving_of_semiconj hπ hS (continuous_codeShiftSecond C).measurable
      (codeMap_comp_second T S f g C hfC hgC),
    continuous_codeObsFirst C, continuous_codeObsSecond C, ⟨C, norm_codeObsFirst_le⟩,
    ⟨C, norm_codeObsSecond_le⟩, ⟨hπ, rfl⟩, codeMap_comp_first T S hTS f g C hfC hgC,
    codeMap_comp_second T S f g C hfC hgC, rfl, rfl⟩

end T03

/-! ### T04: an explicit invertible extension -/

section T04

variable {E : Type*} [TopologicalSpace E]

/-- The finite history `w_k(z) = (R^k z, R^{k-1} z, …, R z, z, z, …)`. -/
def histEmbed (R : E → E) (k : ℕ) (z : E) : ℕ → E := fun j => R^[k - j] z

/-- Coordinatewise application of a map to a sequence. -/
def coordMap (a : E → E) (x : ℕ → E) : ℕ → E := fun j => a (x j)

/-- The pair of consecutive coordinates `(x_{j+1}, x_j)`. -/
def pairMap (j : ℕ) (x : ℕ → E) : E × E := (x (j + 1), x j)

theorem continuous_histEmbed {R : E → E} (hR : Continuous R) (k : ℕ) :
    Continuous (histEmbed R k) :=
  continuous_pi fun j => hR.iterate (k - j)

theorem continuous_coordMap {a : E → E} (ha : Continuous a) : Continuous (coordMap a) :=
  continuous_pi fun j => ha.comp (continuous_apply j)

theorem continuous_pairMap (j : ℕ) : Continuous (pairMap (E := E) j) :=
  (continuous_apply _).prodMk (continuous_apply _)

omit [TopologicalSpace E] in
theorem coordMap_comp_histEmbed {a R : E → E} (h : Function.Commute a R) (k : ℕ) :
    coordMap a ∘ histEmbed R k = histEmbed R k ∘ a := by
  funext z j
  simp only [Function.comp_apply, coordMap, histEmbed, (h.iterate_right (k - j)).eq]

omit [TopologicalSpace E] in
theorem eval_zero_comp_histEmbed (R : E → E) (k : ℕ) :
    (fun x : ℕ → E => x 0) ∘ histEmbed R k = R^[k] := by
  funext z; simp [histEmbed]

omit [TopologicalSpace E] in
theorem pairMap_comp_histEmbed (R : E → E) {j k : ℕ} (hjk : j < k) :
    pairMap j ∘ histEmbed R k = (fun y => (y, R y)) ∘ R^[k - (j + 1)] := by
  funext z
  have e : k - j = (k - (j + 1)) + 1 := by omega
  simp only [Function.comp_apply, pairMap, histEmbed, e, Function.iterate_succ_apply']

/-- The closed set of backward `R`-orbits `{x | R x_{k+1} = x_k for all k}`. -/
def natExtSet (R : E → E) : Set (ℕ → E) := {x | ∀ k, R (x (k + 1)) = x k}

theorem isClosed_natExtSet [T2Space E] {R : E → E} (hR : Continuous R) :
    IsClosed (natExtSet R) := by
  have : natExtSet R = ⋂ k, {x : ℕ → E | R (x (k + 1)) = x k} := by
    ext x; simp [natExtSet]
  rw [this]
  exact isClosed_iInter fun k => isClosed_eq (hR.comp (continuous_apply _)) (continuous_apply _)

/-- Lift of a map `a` with `a ∘ b = b ∘ a = R` to backward orbits: apply `a` coordinatewise. -/
def natExtLift {R : E → E} (a b : E → E) (hab : ∀ y, a (b y) = R y)
    (hba : ∀ y, b (a y) = R y) (x : natExtSet R) : natExtSet R :=
  ⟨coordMap a x.1, fun k => by
    have h1 : R (a (x.1 (k + 1))) = a (R (x.1 (k + 1))) := by rw [← hab, hba]
    simp only [coordMap, h1, x.2 k]⟩

/-- Its inverse: drop the first coordinate and apply `b`. -/
def natExtInvLift {R : E → E} (a b : E → E) (hab : ∀ y, a (b y) = R y)
    (hba : ∀ y, b (a y) = R y) (x : natExtSet R) : natExtSet R :=
  ⟨fun k => b (x.1 (k + 1)), fun k => by
    have h1 : R (b (x.1 (k + 1 + 1))) = b (R (x.1 (k + 1 + 1))) := by rw [← hba, hab]
    simp only [h1, x.2 (k + 1)]⟩

/-- The lifted homeomorphism of the space of backward orbits. -/
def natExtHomeomorph {R : E → E} (a b : E → E) (ha : Continuous a) (hb : Continuous b)
    (hab : ∀ y, a (b y) = R y) (hba : ∀ y, b (a y) = R y) : natExtSet R ≃ₜ natExtSet R where
  toFun := natExtLift a b hab hba
  invFun := natExtInvLift a b hab hba
  left_inv x := by
    apply Subtype.ext; funext k
    simp only [natExtLift, natExtInvLift, coordMap, hba, x.2 k]
  right_inv x := by
    apply Subtype.ext; funext k
    simp only [natExtLift, natExtInvLift, coordMap, hab, x.2 k]
  continuous_toFun :=
    ((continuous_coordMap ha).comp continuous_subtype_val).subtype_mk _
  continuous_invFun :=
    (continuous_pi fun k => hb.comp ((continuous_apply (k + 1)).comp continuous_subtype_val)).subtype_mk _

theorem natExtHomeomorph_val {R : E → E} (a b : E → E) (ha : Continuous a) (hb : Continuous b)
    (hab : ∀ y, a (b y) = R y) (hba : ∀ y, b (a y) = R y) :
    Subtype.val ∘ natExtHomeomorph a b ha hb hab hba = coordMap a ∘ Subtype.val := rfl

variable [CompactSpace E] [TopologicalSpace.MetrizableSpace E] [MeasurableSpace E] [BorelSpace E]

/-- The invariant Borel probability measure on sequences, obtained as a cluster point of the
laws of the finite histories `w_k(z)`, `z ∼ ν`. -/
theorem exists_natExt_measure (ν : Measure E) [IsProbabilityMeasure ν] (τ σ : E → E)
    (hτc : Continuous τ) (hσc : Continuous σ) (hτ : MeasurePreserving τ ν ν)
    (hσ : MeasurePreserving σ ν ν) (hc : τ ∘ σ = σ ∘ τ) :
    ∃ P : Measure (ℕ → E), IsProbabilityMeasure P ∧ P.map (coordMap τ) = P ∧
      P.map (coordMap σ) = P ∧ P.map (fun x => x 0) = ν ∧
      ∀ j, P.map (pairMap j) = ν.map (fun z => (z, τ (σ z))) := by
  set R : E → E := τ ∘ σ with hRdef
  have hRc : Continuous R := hτc.comp hσc
  have hR : MeasurePreserving R ν ν := hτ.comp hσ
  have hτR : Function.Commute τ R := fun y => by
    simp only [hRdef, Function.comp_apply]; rw [← Function.comp_apply (f := σ) (g := τ), ← hc]
    rfl
  have hσR : Function.Commute σ R := fun y => by
    simp only [hRdef, Function.comp_apply]; rw [← Function.comp_apply (f := σ) (g := τ), ← hc]
    rfl
  let ν' : ProbabilityMeasure E := ⟨ν, inferInstance⟩
  let s : ℕ → ProbabilityMeasure (ℕ → E) := fun k => ν'.map (histEmbed R k)
  have hsm : ∀ k, Measurable (histEmbed R k) := fun k => (continuous_histEmbed hRc k).measurable
  obtain ⟨P, -, hP⟩ := isCompact_univ.exists_clusterPt (f := Filter.map s atTop)
    (le_principal_iff.2 univ_mem)
  have key : ∀ A : Set (ProbabilityMeasure (ℕ → E)), IsClosed A →
      (∀ᶠ k in atTop, s k ∈ A) → P ∈ A :=
    fun A hA h => hA.closure_subset (hP.mem_closure_of_mem A h)
  have hinv : ∀ (a : E → E), Continuous a → MeasurePreserving a ν ν → Function.Commute a R →
      P.map (coordMap a) = P := by
    intro a hac ha haR
    refine key {Q | Q.map (coordMap a) = Q}
      (isClosed_eq (ProbabilityMeasure.continuous_map (continuous_coordMap hac)) continuous_id)
      (Eventually.of_forall fun k => ?_)
    apply Subtype.ext
    show Measure.map (coordMap a) (Measure.map (histEmbed R k) ν) = Measure.map (histEmbed R k) ν
    rw [Measure.map_map (continuous_coordMap hac).measurable (hsm k),
      coordMap_comp_histEmbed haR, ← Measure.map_map (hsm k) ha.measurable, ha.map_eq]
  have h0 : P.map (fun x => x 0) = ν' := by
    refine key {Q | Q.map (fun x => x 0) = ν'}
      (isClosed_eq (ProbabilityMeasure.continuous_map (continuous_apply 0)) continuous_const)
      (Eventually.of_forall fun k => ?_)
    apply Subtype.ext
    show Measure.map (fun x : ℕ → E => x 0) (Measure.map (histEmbed R k) ν) = ν
    rw [Measure.map_map (continuous_apply 0).measurable (hsm k), eval_zero_comp_histEmbed,
      (hR.iterate k).map_eq]
  have hpair : ∀ j, P.map (pairMap j) = ν'.map (fun z => (z, R z)) := by
    intro j
    refine key {Q | Q.map (pairMap j) = ν'.map (fun z => (z, R z))}
      (isClosed_eq (ProbabilityMeasure.continuous_map (continuous_pairMap j)) continuous_const)
      ((eventually_gt_atTop j).mono fun k hk => ?_)
    apply Subtype.ext
    show Measure.map (pairMap j) (Measure.map (histEmbed R k) ν) =
      Measure.map (fun z => (z, R z)) ν
    rw [Measure.map_map (continuous_pairMap j).measurable (hsm k), pairMap_comp_histEmbed R hk,
      ← Measure.map_map (show Measurable (fun y : E => (y, R y)) from
        measurable_id.prodMk hRc.measurable) (hR.iterate _).measurable,
      (hR.iterate _).map_eq]
  refine ⟨P, inferInstance, congrArg Subtype.val (hinv τ hτc hτ hτR),
    congrArg Subtype.val (hinv σ hσc hσ hσR), congrArg Subtype.val h0,
    fun j => congrArg Subtype.val (hpair j)⟩

theorem measure_compl_natExtSet (P : Measure (ℕ → E)) (ν : Measure E) {R : E → E}
    (hRc : Continuous R) (hpair : ∀ j, P.map (pairMap j) = ν.map (fun z => (z, R z))) :
    P (natExtSet R)ᶜ = 0 := by
  have : (natExtSet R)ᶜ = ⋃ k, pairMap k ⁻¹' {p : E × E | R p.1 ≠ p.2} := by
    ext x; simp [natExtSet, pairMap]
  rw [this]
  refine measure_iUnion_null fun k => ?_
  have hD : MeasurableSet {p : E × E | R p.1 ≠ p.2} :=
    (isClosed_eq (hRc.comp continuous_fst) continuous_snd).isOpen_compl.measurableSet
  rw [← Measure.map_apply (continuous_pairMap k).measurable hD, hpair,
    Measure.map_apply (show Measurable (fun z : E => (z, R z)) from
      measurable_id.prodMk hRc.measurable) hD]
  simp

/-- **Lemma 9.4 (node T04, an explicit invertible extension).** Let `E` be a compact metrizable
space with its Borel σ-algebra, `ν` a Borel probability measure and `τ, σ` commuting continuous
`ν`-preserving maps. There are a compact metrizable space `Ê` (with its Borel σ-algebra), a
probability measure `νhat`, commuting `νhat`-preserving homeomorphisms `τhat, σhat` of `Ê`, and a
continuous measure-preserving `π₀ : Ê → E` with `π₀ ∘ τhat = τ ∘ π₀` and `π₀ ∘ σhat = σ ∘ π₀`.

Here `Ê` is the space of backward orbits `{x ∈ E^ℕ | (τσ) x_{k+1} = x_k}`; the measure is a
cluster point (in the compact space of probability measures) of the laws of the finite
histories `(R^k z, …, z, z, …)`, `z ∼ ν`, instead of the Riesz–Markov construction. -/
theorem commuting_compact_natural_extension {E : Type u} [TopologicalSpace E] [CompactSpace E]
    [TopologicalSpace.MetrizableSpace E] [MeasurableSpace E] [BorelSpace E]
    (ν : Measure E) [IsProbabilityMeasure ν] (τ σ : E → E) (hτc : Continuous τ)
    (hσc : Continuous σ) (hτ : MeasurePreserving τ ν ν) (hσ : MeasurePreserving σ ν ν)
    (hc : τ ∘ σ = σ ∘ τ) :
    ∃ (Ehat : Type u) (_ : TopologicalSpace Ehat) (_ : MeasurableSpace Ehat),
      CompactSpace Ehat ∧ TopologicalSpace.MetrizableSpace Ehat ∧ BorelSpace Ehat ∧
      ∃ (νhat : Measure Ehat) (τhat σhat : Ehat ≃ₜ Ehat) (π₀ : Ehat → E),
        IsProbabilityMeasure νhat ∧ MeasurePreserving τhat νhat νhat ∧ MeasurePreserving σhat νhat νhat ∧
        ⇑τhat ∘ ⇑σhat = ⇑σhat ∘ ⇑τhat ∧ Continuous π₀ ∧ MeasurePreserving π₀ νhat ν ∧
        π₀ ∘ τhat = τ ∘ π₀ ∧ π₀ ∘ σhat = σ ∘ π₀ := by
  obtain ⟨P, hPprob, hPτ, hPσ, hP0, hPpair⟩ := exists_natExt_measure ν τ σ hτc hσc hτ hσ hc
  set R : E → E := fun z => τ (σ z) with hRdef
  have hRc : Continuous R := hτc.comp hσc
  have hτσ : ∀ y, τ (σ y) = R y := fun _ => rfl
  have hστ : ∀ y, σ (τ y) = R y := fun y => (congrFun hc y).symm
  have hclosed : IsClosed (natExtSet R) := isClosed_natExtSet hRc
  have hmeas : MeasurableSet (natExtSet R) := hclosed.measurableSet
  have hemb : MeasurableEmbedding (Subtype.val : natExtSet R → ℕ → E) :=
    MeasurableEmbedding.subtype_coe hmeas
  have hcompact : CompactSpace (natExtSet R) := isCompact_iff_compactSpace.1 hclosed.isCompact
  set νh : Measure (natExtSet R) := Measure.comap Subtype.val P
  have hmapval : νh.map Subtype.val = P := by
    rw [map_comap_subtype_coe hmeas, Measure.restrict_eq_self_of_ae_mem]
    exact measure_compl_natExtSet P ν hRc hPpair
  have hprob : IsProbabilityMeasure νh := by
    have : IsProbabilityMeasure (νh.map Subtype.val) := by rw [hmapval]; exact hPprob
    exact Measure.isProbabilityMeasure_of_map hemb.measurable.aemeasurable
  let τh := natExtHomeomorph τ σ hτc hσc hτσ hστ
  let σh := natExtHomeomorph σ τ hσc hτc hστ hτσ
  have hpres : ∀ (a b : E → E) (ha : Continuous a) (hb : Continuous b)
      (hab : ∀ y, a (b y) = R y) (hba : ∀ y, b (a y) = R y), P.map (coordMap a) = P →
      MeasurePreserving (natExtHomeomorph a b ha hb hab hba) νh νh := by
    intro a b ha hb hab hba hPa
    refine ⟨(natExtHomeomorph a b ha hb hab hba).continuous.measurable, ?_⟩
    rw [← hemb.comap_map (Measure.map _ νh), Measure.map_map hemb.measurable
      (natExtHomeomorph a b ha hb hab hba).continuous.measurable, natExtHomeomorph_val,
      ← Measure.map_map (continuous_coordMap ha).measurable hemb.measurable, hmapval, hPa]
  have hπ₀c : Continuous (fun x : natExtSet R => x.1 0) :=
    (continuous_apply 0).comp continuous_subtype_val
  refine ⟨natExtSet R, inferInstance, inferInstance, hcompact, inferInstance, inferInstance,
    νh, τh, σh, fun x => x.1 0, hprob, hpres τ σ hτc hσc hτσ hστ hPτ,
    hpres σ τ hσc hτc hστ hτσ hPσ, ?_, hπ₀c, ⟨hπ₀c.measurable, ?_⟩, rfl, rfl⟩
  · funext x
    apply Subtype.ext; funext k
    show τ (σ (x.1 k)) = σ (τ (x.1 k))
    exact congrFun hc _
  · have : (fun x : natExtSet R => x.1 0) = (fun x : ℕ → E => x 0) ∘ Subtype.val := rfl
    rw [this, ← Measure.map_map (continuous_apply 0).measurable hemb.measurable, hmapval, hP0]

end T04

/-! ### T05: bounded inputs on arbitrary probability spaces -/

section T05

variable {X : Type*}

/-- Averages commute with factor maps. -/
theorem bilinAvg_factor {Y : Type*} (T S : X → X) (τ σ : Y → Y) (π : X → Y)
    (hT : π ∘ T = τ ∘ π) (hS : π ∘ S = σ ∘ π) (fY gY : Y → ℂ) (N : ℕ) (x : X) :
    bilinAvg τ σ fY gY N (π x) = bilinAvg T S (fY ∘ π) (gY ∘ π) N x := by
  have hT' : Function.Semiconj π T τ := fun y => congrFun hT y
  have hS' : Function.Semiconj π S σ := fun y => congrFun hS y
  simp only [bilinAvg, Function.comp_apply, (hT'.iterate_right _).eq, (hS'.iterate_right _).eq]

theorem norm_bilinAvg_le (T S : X → X) {f g : X → ℂ} {Cf Cg : ℝ} (hf : ∀ x, ‖f x‖ ≤ Cf)
    (hg : ∀ x, ‖g x‖ ≤ Cg) (N : ℕ) (x : X) : ‖bilinAvg T S f g N x‖ ≤ Cf * Cg := by
  have hCf : 0 ≤ Cf := (norm_nonneg _).trans (hf x)
  have hCg : 0 ≤ Cg := (norm_nonneg _).trans (hg x)
  rcases Nat.eq_zero_or_pos N with rfl | hN
  · simp [bilinAvg]; positivity
  have hsum : ‖∑ n ∈ Finset.range N, f (T^[n] x) * g (S^[n] x)‖ ≤ N * (Cf * Cg) := by
    calc ‖∑ n ∈ Finset.range N, f (T^[n] x) * g (S^[n] x)‖
        ≤ ∑ n ∈ Finset.range N, ‖f (T^[n] x) * g (S^[n] x)‖ := norm_sum_le _ _
      _ ≤ ∑ _n ∈ Finset.range N, Cf * Cg := Finset.sum_le_sum fun n _ => by
          rw [norm_mul]; exact mul_le_mul (hf _) (hg _) (norm_nonneg _) hCf
      _ = N * (Cf * Cg) := by simp
  have hN' : (0 : ℝ) < N := by exact_mod_cast hN
  calc ‖bilinAvg T S f g N x‖ = (N : ℝ)⁻¹ * ‖∑ n ∈ Finset.range N, f (T^[n] x) * g (S^[n] x)‖ := by
        simp [bilinAvg]
    _ ≤ (N : ℝ)⁻¹ * (N * (Cf * Cg)) := by gcongr
    _ = Cf * Cg := by field_simp

variable [MeasurableSpace X]

theorem measurable_bilinAvg {T S : X → X} (hT : Measurable T) (hS : Measurable S) {f g : X → ℂ}
    (hf : Measurable f) (hg : Measurable g) (N : ℕ) : Measurable (bilinAvg T S f g N) := by
  unfold bilinAvg
  refine Measurable.const_mul ?_ _
  exact Finset.measurable_sum _ fun n _ =>
    (hf.comp (hT.iterate n)).mul (hg.comp (hS.iterate n))

theorem measurableSet_bilinAvg_converges {T S : X → X} (hT : Measurable T) (hS : Measurable S)
    {f g : X → ℂ} (hf : Measurable f) (hg : Measurable g) :
    MeasurableSet {x | ∃ L, Tendsto (fun N => bilinAvg T S f g N x) atTop (𝓝 L)} :=
  StronglyMeasurable.measurableSet_exists_tendsto
    (fun N => (measurable_bilinAvg hT hS hf hg N).stronglyMeasurable)

/-- Almost-everywhere convergence of uniformly bounded measurable functions upgrades to an
a.e. limit `F` and convergence in every `L^r`, `1 ≤ r < ∞`. -/
theorem exists_limit_Lp_of_ae_converges {μ : Measure X} [IsFiniteMeasure μ] {A : ℕ → X → ℂ}
    (hA : ∀ N, Measurable (A N)) {C : ℝ} (hC : ∀ N x, ‖A N x‖ ≤ C)
    (hconv : ∀ᵐ x ∂μ, ∃ L, Tendsto (fun N => A N x) atTop (𝓝 L)) :
    ∃ F : X → ℂ, (∀ᵐ x ∂μ, Tendsto (fun N => A N x) atTop (𝓝 (F x))) ∧
      ∀ r : ℝ, 1 ≤ r → MemLp F (ENNReal.ofReal r) μ ∧
        Tendsto (fun N => eLpNorm (A N - F) (ENNReal.ofReal r) μ) atTop (𝓝 0) := by
  set F : X → ℂ := fun x => limUnder atTop (fun N => A N x)
  have hFt : ∀ᵐ x ∂μ, Tendsto (fun N => A N x) atTop (𝓝 (F x)) :=
    hconv.mono fun x hx => tendsto_nhds_limUnder hx
  have hFm : AEStronglyMeasurable F μ :=
    aestronglyMeasurable_of_tendsto_ae atTop (fun N => (hA N).aestronglyMeasurable) hFt
  have hFb : ∀ᵐ x ∂μ, ‖F x‖ ≤ C :=
    hFt.mono fun x hx => le_of_tendsto' hx.norm fun N => hC N x
  refine ⟨F, hFt, fun r hr => ?_⟩
  have hp : (1 : ℝ≥0∞) ≤ ENNReal.ofReal r := by simpa using ENNReal.ofReal_le_ofReal hr
  have hp' : ENNReal.ofReal r ≠ ∞ := ENNReal.ofReal_ne_top
  have hFL : MemLp F (ENNReal.ofReal r) μ := MemLp.of_bound hFm C hFb
  refine ⟨hFL, tendsto_Lp_finite_of_tendsto_ae hp hp' (fun N => (hA N).aestronglyMeasurable)
    hFL ?_ hFt⟩
  refine (unifIntegrable_const hp hp' (memLp_const ((C : ℝ) : ℂ))).ae_mono
    (fun N => (hA N).aestronglyMeasurable) fun N => ae_of_all _ fun x => ?_
  rw [enorm_le_iff_norm_le, Complex.norm_real, Real.norm_eq_abs]
  exact (hC N x).trans (le_abs_self C)

/-- **Theorem 9.5 (node T05, bounded inputs on arbitrary probability spaces).** Assume the
conclusion of node T02 (`InvertibleBoundedConvergence`, for invertible systems on spaces in
`Type`). Let `T, S` be commuting measurable measure-preserving maps of an arbitrary probability
space `(X, μ)` and `f, g : X → ℂ` bounded measurable. Then the averages `A_N(f,g)` converge
almost everywhere, and there is a function `F` (their a.e. limit) with `F ∈ L^r` and
`A_N(f,g) → F` in `L^r` for every `1 ≤ r < ∞`.
The proof codes the system into a compact one (T03), lifts it to an invertible one (T04),
applies T02 there and pulls the convergence set back. -/
theorem bounded_commuting_averages_ae_of_invertible (H : InvertibleBoundedConvergence)
    {X : Type u} [MeasurableSpace X] (μ : Measure X) [IsProbabilityMeasure μ] (T S : X → X)
    (hT : MeasurePreserving T μ μ) (hS : MeasurePreserving S μ μ) (hTS : T ∘ S = S ∘ T)
    (f g : X → ℂ) (hf : Measurable f) (hg : Measurable g) (hfb : ∃ C, ∀ x, ‖f x‖ ≤ C)
    (hgb : ∃ C, ∀ x, ‖g x‖ ≤ C) :
    (∀ᵐ x ∂μ, ∃ L, Tendsto (fun N => bilinAvg T S f g N x) atTop (𝓝 L)) ∧
    ∃ F : X → ℂ, (∀ᵐ x ∂μ, Tendsto (fun N => bilinAvg T S f g N x) atTop (𝓝 (F x))) ∧
      ∀ r : ℝ, 1 ≤ r → MemLp F (ENNReal.ofReal r) μ ∧
        Tendsto (fun N => eLpNorm (bilinAvg T S f g N - F) (ENNReal.ofReal r) μ) atTop (𝓝 0) := by
  have hae : ∀ᵐ x ∂μ, ∃ L, Tendsto (fun N => bilinAvg T S f g N x) atTop (𝓝 L) := by
    obtain ⟨E, tE, mE, hEc, hEm, hEb, ν, τ, σ, fE, gE, π, hνp, hτc, hσc, hτσ, hτ, hσ, hfEc, hgEc,
      hfEb, hgEb, hπ, hπT, hπS, hfπ, hgπ⟩ :=
      bounded_observable_compact_coding μ T S hT hS hTS f g hf hg hfb hgb
    obtain ⟨Eh, tEh, mEh, hEhc, hEhm, hEhb, νh, τh, σh, π₀, hνhp, hτh, hσh, hτσh, hπ₀c, hπ₀,
      hπ₀τ, hπ₀σ⟩ := commuting_compact_natural_extension ν τ σ hτc hσc hτ hσ hτσ
    have hup := H Eh νh τh σh τh.symm σh.symm hτh hσh τh.symm.continuous.measurable
      σh.symm.continuous.measurable τh.symm_apply_apply τh.apply_symm_apply
      σh.symm_apply_apply σh.apply_symm_apply hτσh (fE ∘ π₀) (gE ∘ π₀)
      (hfEc.measurable.comp hπ₀c.measurable) (hgEc.measurable.comp hπ₀c.measurable)
      (let ⟨C, hC⟩ := hfEb; ⟨C, fun y => hC _⟩) (let ⟨C, hC⟩ := hgEb; ⟨C, fun y => hC _⟩)
    have hG := measurableSet_bilinAvg_converges hτc.measurable hσc.measurable
      hfEc.measurable hgEc.measurable
    have hE : ∀ᵐ e ∂ν, ∃ L, Tendsto (fun N => bilinAvg τ σ fE gE N e) atTop (𝓝 L) := by
      rw [← hπ₀.map_eq, ae_map_iff hπ₀.measurable.aemeasurable hG]
      refine hup.mono fun y hy => ?_
      simpa only [bilinAvg_factor τh σh τ σ π₀ hπ₀τ hπ₀σ] using hy
    rw [← hπ.map_eq] at hE
    refine (ae_of_ae_map hπ.measurable.aemeasurable hE).mono fun x hx => ?_
    simpa only [bilinAvg_factor T S τ σ π hπT hπS, ← hfπ, ← hgπ] using hx
  refine ⟨hae, ?_⟩
  obtain ⟨Cf, hCf⟩ := hfb
  obtain ⟨Cg, hCg⟩ := hgb
  exact exists_limit_Lp_of_ae_converges
    (measurable_bilinAvg hT.measurable hS.measurable hf hg) (norm_bilinAvg_le T S hCf hCg) hae

end T05

end TSec

/-! ### Node T02: bounded inputs, invertible maps -/

section T02

open Set

/-- On the unit time interval `[n, n+1]`, for a starting phase `0 ≤ u < 1/8`, the phase
`{u + t}` lies in `I = (1/4, 1/2)` exactly when `u + t - n` does, and then `⌊u + t⌋ = n`. -/
lemma fract_mem_window_T02 {u t : ℝ} (n : ℕ) (hu0 : 0 ≤ u) (hu : u < 1 / 8)
    (ht : t ∈ Icc (n : ℝ) (n + 1)) :
    (Int.fract (u + t) ∈ Ioo (1 / 4 : ℝ) (1 / 2) ↔ u + t - n ∈ Ioo (1 / 4 : ℝ) (1 / 2)) ∧
      (u + t - n ∈ Ioo (1 / 4 : ℝ) (1 / 2) → ⌊u + t⌋ = n) := by
  obtain ⟨ht1, ht2⟩ := ht
  by_cases hlt : u + t < n + 1
  · have hfl : ⌊u + t⌋ = (n : ℤ) := by
      rw [Int.floor_eq_iff]; push_cast; constructor <;> linarith
    have hfr : Int.fract (u + t) = u + t - n := by
      rw [Int.fract, hfl]; push_cast; ring
    exact ⟨by rw [hfr], fun _ => hfl⟩
  · push Not at hlt
    have hfl : ⌊u + t⌋ = (n : ℤ) + 1 := by
      rw [Int.floor_eq_iff]; push_cast; constructor <;> linarith
    have hfr : Int.fract (u + t) = u + t - n - 1 := by
      rw [Int.fract, hfl]; push_cast; ring
    refine ⟨⟨fun h => ?_, fun h => ?_⟩, fun h => ?_⟩
    · rw [hfr] at h; exact absurd h.1 (by linarith)
    · exact absurd h.2 (by linarith)
    · exact absurd h.2 (by linarith)

variable {X : Type*}

/-- The auxiliary input `f̃(x,u,v) = f(x) 1_I(u)`, `I = (1/4,1/2)`. -/
def liftFirstT02 (f : X → ℂ) (ω : X × ℝ × ℝ) : ℂ :=
  if ω.2.1 ∈ Ioo (1 / 4 : ℝ) (1 / 2) then f ω.1 else 0

/-- The auxiliary input `g̃(x,u,v) = g(x) 1_I(v)`, `I = (1/4,1/2)`. -/
def liftSecondT02 (g : X → ℂ) (ω : X × ℝ × ℝ) : ℂ :=
  if ω.2.2 ∈ Ioo (1 / 4 : ℝ) (1 / 2) then g ω.1 else 0

/-- On `[n, n+1]` the suspended integrand is `f(Tⁿx) g(Sⁿx)` times the indicator of
`n + J(u,v)`, `J(u,v) = (1/4 - min(u,v), 1/2 - max(u,v))`. -/
lemma susp_integrand_eq_T02 (T Tinv S Sinv : X → X) (f g : X → ℂ) (x : X) {u v : ℝ}
    (hu0 : 0 ≤ u) (hu : u < 1 / 8) (hv0 : 0 ≤ v) (hv : v < 1 / 8) (n : ℕ) {t : ℝ}
    (ht : t ∈ Icc (n : ℝ) (n + 1)) :
    liftFirstT02 f (suspFlowFirst T Tinv t (x, u, v)) *
        liftSecondT02 g (suspFlowSecond S Sinv t (x, u, v)) =
      (Ioo ((n : ℝ) + 1 / 4 - min u v) (n + 1 / 2 - max u v)).indicator
        (fun _ => f (T^[n] x) * g (S^[n] x)) t := by
  obtain ⟨hU1, hU2⟩ := fract_mem_window_T02 n hu0 hu ht
  obtain ⟨hV1, hV2⟩ := fract_mem_window_T02 n hv0 hv ht
  have hJ : t ∈ Ioo ((n : ℝ) + 1 / 4 - min u v) (n + 1 / 2 - max u v) ↔
      u + t - n ∈ Ioo (1 / 4 : ℝ) (1 / 2) ∧ v + t - n ∈ Ioo (1 / 4 : ℝ) (1 / 2) := by
    simp only [mem_Ioo]
    constructor
    · rintro ⟨h1, h2⟩
      have := min_le_left u v; have := min_le_right u v
      have := le_max_left u v; have := le_max_right u v
      refine ⟨⟨?_, ?_⟩, ?_, ?_⟩ <;> linarith
    · rintro ⟨⟨h1, h2⟩, h3, h4⟩
      refine ⟨?_, ?_⟩
      · rcases min_choice u v with h | h <;> rw [h] <;> linarith
      · rcases max_choice u v with h | h <;> rw [h] <;> linarith
  have eU : liftFirstT02 f (suspFlowFirst T Tinv t (x, u, v)) =
      if Int.fract (u + t) ∈ Ioo (1 / 4 : ℝ) (1 / 2) then f (zpowMap T Tinv ⌊u + t⌋ x) else 0 :=
    rfl
  have eV : liftSecondT02 g (suspFlowSecond S Sinv t (x, u, v)) =
      if Int.fract (v + t) ∈ Ioo (1 / 4 : ℝ) (1 / 2) then g (zpowMap S Sinv ⌊v + t⌋ x) else 0 :=
    rfl
  rw [eU, eV]
  by_cases hin : t ∈ Ioo ((n : ℝ) + 1 / 4 - min u v) (n + 1 / 2 - max u v)
  · rw [indicator_of_mem hin]
    obtain ⟨h1, h2⟩ := hJ.1 hin
    rw [ite_eq_left (hU1.2 h1), ite_eq_left (hV1.2 h2), hU2 h1, hV2 h2]
    rfl
  · rw [indicator_of_notMem hin]
    rw [hJ, not_and_or] at hin
    rcases hin with h | h
    · rw [ite_eq_right (fun h' => h (hU1.1 h')), zero_mul]
    · rw [ite_eq_right (fun h' => h (hV1.1 h')), mul_zero]

/-- The integral of the suspended integrand over one unit time interval. -/
lemma integral_unit_T02 (T Tinv S Sinv : X → X) (f g : X → ℂ) (x : X) {u v : ℝ}
    (hu0 : 0 ≤ u) (hu : u < 1 / 8) (hv0 : 0 ≤ v) (hv : v < 1 / 8) (n : ℕ) :
    IntervalIntegrable (fun t => liftFirstT02 f (suspFlowFirst T Tinv t (x, u, v)) *
        liftSecondT02 g (suspFlowSecond S Sinv t (x, u, v))) volume n (n + 1) ∧
    ∫ t in (n : ℝ)..(n + 1), liftFirstT02 f (suspFlowFirst T Tinv t (x, u, v)) *
        liftSecondT02 g (suspFlowSecond S Sinv t (x, u, v)) =
      ((1 / 4 - |u - v| : ℝ) : ℂ) * (f (T^[n] x) * g (S^[n] x)) := by
  have hle : (n : ℝ) ≤ n + 1 := by linarith
  have heq : EqOn (fun t => liftFirstT02 f (suspFlowFirst T Tinv t (x, u, v)) *
        liftSecondT02 g (suspFlowSecond S Sinv t (x, u, v)))
      ((Ioo ((n : ℝ) + 1 / 4 - min u v) (n + 1 / 2 - max u v)).indicator
        (fun _ => f (T^[n] x) * g (S^[n] x))) (uIcc (n : ℝ) (n + 1)) := by
    intro t ht
    rw [uIcc_of_le hle] at ht
    exact susp_integrand_eq_T02 T Tinv S Sinv f g x hu0 hu hv0 hv n ht
  have hsub : Ioo ((n : ℝ) + 1 / 4 - min u v) (n + 1 / 2 - max u v) ⊆ Ioc (n : ℝ) (n + 1) := by
    intro t ht
    have := min_le_left u v; have := le_max_left u v
    have := le_min hu0 hv0
    obtain ⟨h1, h2⟩ := ht
    constructor <;> linarith
  refine ⟨?_, ?_⟩
  · rw [intervalIntegrable_congr (heq.mono uIoc_subset_uIcc)]
    exact ((integrableOn_const (C := f (T^[n] x) * g (S^[n] x))
      (s := Ioo ((n : ℝ) + 1 / 4 - min u v) (n + 1 / 2 - max u v)) (μ := volume)
      (by simp)).integrable_indicator₀ measurableSet_Ioo.nullMeasurableSet).intervalIntegrable
  · rw [intervalIntegral.integral_congr heq, intervalIntegral.integral_of_le hle,
      setIntegral_indicator measurableSet_Ioo, inter_eq_right.2 hsub, setIntegral_const,
      Real.volume_real_Ioo_of_le, Complex.real_smul]
    · congr 2
      rcases le_total u v with h | h
      · rw [max_eq_right h, min_eq_left h, abs_of_nonpos (by linarith)]; ring
      · rw [max_eq_left h, min_eq_right h, abs_of_nonneg (by linarith)]; ring
    · have := min_le_left u v; have := le_max_left u v
      have := le_min hu0 hv0; have := max_lt hu hv
      linarith

/-- **The exact suspension identity.** For `0 ≤ u, v < 1/8`,
`∫_0^N f̃(U^t(x,u,v)) g̃(V^t(x,u,v)) dt = b(u,v) ∑_{n<N} f(Tⁿx) g(Sⁿx)`,
with `b(u,v) = 1/4 - |u - v|`. -/
lemma integral_susp_T02 (T Tinv S Sinv : X → X) (f g : X → ℂ) (x : X) {u v : ℝ}
    (hu0 : 0 ≤ u) (hu : u < 1 / 8) (hv0 : 0 ≤ v) (hv : v < 1 / 8) (N : ℕ) :
    ∫ t in (0 : ℝ)..N, liftFirstT02 f (suspFlowFirst T Tinv t (x, u, v)) *
        liftSecondT02 g (suspFlowSecond S Sinv t (x, u, v)) =
      ((1 / 4 - |u - v| : ℝ) : ℂ) * ∑ n ∈ Finset.range N, f (T^[n] x) * g (S^[n] x) := by
  have h := intervalIntegral.sum_integral_adjacent_intervals (μ := volume) (a := fun k : ℕ => (k : ℝ))
    (n := N) (f := fun t => liftFirstT02 f (suspFlowFirst T Tinv t (x, u, v)) *
        liftSecondT02 g (suspFlowSecond S Sinv t (x, u, v)))
    (fun k _ => by
      have := (integral_unit_T02 T Tinv S Sinv f g x hu0 hu hv0 hv k).1
      simpa using this)
  simp only [Nat.cast_zero, Nat.cast_add, Nat.cast_one] at h
  rw [← h, Finset.mul_sum]
  refine Finset.sum_congr rfl fun k _ => ?_
  exact (integral_unit_T02 T Tinv S Sinv f g x hu0 hu hv0 hv k).2

/-- Transfer of convergence from the suspension: at a point `(x,u,v)` with `0 ≤ u, v < 1/8`,
convergence of the continuous-time averages of `f̃, g̃` forces convergence of `A_N(f,g)(x)`. -/
lemma bilinAvg_converges_of_susp_T02 (T Tinv S Sinv : X → X) (f g : X → ℂ) (x : X) {u v : ℝ}
    (hu0 : 0 ≤ u) (hu : u < 1 / 8) (hv0 : 0 ≤ v) (hv : v < 1 / 8)
    (h : ∃ L : ℂ, Tendsto (fun R : ℝ => (R⁻¹ : ℂ) * ∫ t in (0 : ℝ)..R,
      liftFirstT02 f (suspFlowFirst T Tinv t (x, u, v)) *
        liftSecondT02 g (suspFlowSecond S Sinv t (x, u, v))) atTop (𝓝 L)) :
    ∃ L, Tendsto (fun N => bilinAvg T S f g N x) atTop (𝓝 L) := by
  obtain ⟨L, hL⟩ := h
  set b : ℂ := ((1 / 4 - |u - v| : ℝ) : ℂ)
  have hb : b ≠ 0 := by
    have : 0 < 1 / 4 - |u - v| := by
      have : |u - v| < 1 / 8 := abs_sub_lt_iff.2 ⟨by linarith, by linarith⟩
      linarith
    exact Complex.ofReal_ne_zero.2 this.ne'
  have hN := hL.comp tendsto_natCast_atTop_atTop
  have e : ∀ N : ℕ, ((fun R : ℝ => (R⁻¹ : ℂ) * ∫ t in (0 : ℝ)..R,
      liftFirstT02 f (suspFlowFirst T Tinv t (x, u, v)) *
        liftSecondT02 g (suspFlowSecond S Sinv t (x, u, v))) ∘ (fun N : ℕ => (N : ℝ))) N =
      b * bilinAvg T S f g N x := by
    intro N
    simp only [Function.comp_apply]
    rw [integral_susp_T02 T Tinv S Sinv f g x hu0 hu hv0 hv N, bilinAvg, Complex.ofReal_natCast]
    ring
  rw [funext e] at hN
  refine ⟨b⁻¹ * L, ?_⟩
  have := hN.const_mul b⁻¹
  simpa [← mul_assoc, inv_mul_cancel₀ hb] using this

end T02

/-- **Theorem 9.2 (node T02, bounded inputs, invertible maps).** Assuming the flow theorem
(node S02), for commuting invertible probability-preserving maps `T, S` with measurable
inverses and bounded measurable complex `f, g`, the averages `A_N(f,g)` converge almost
everywhere. The proof uses the suspension flows of node T01 with the inputs
`f̃(x,u,v) = f(x) 1_I(u)`, `g̃(x,u,v) = g(x) 1_I(v)`, `I = (1/4,1/2)`, the exact identity
`N⁻¹ ∫_0^N f̃(U^t ω) g̃(V^t ω) dt = b(u,v) A_N(f,g)(x)` for `0 ≤ u, v < 1/8`, and Fubini. -/
theorem invertible_commuting_averages_ae (hS02 : S02Statement) : InvertibleBoundedConvergence := by
  intro Y _ ν _ T S Tinv Sinv hT hS hTinv hSinv hlT hrT hlS hrS hTS f g hf hg hfB hgB
  obtain ⟨Bf, hBf⟩ := hfB
  obtain ⟨Bg, hBg⟩ := hgB
  obtain ⟨-, -, hUadd, hVadd, -, -, hcomm, hUm, hVm, hUmp, hVmp⟩ :=
    two_coordinate_suspension_flows ν T S Tinv Sinv hT hS hTinv hSinv hlT hrT hlS hrS hTS
  have hUV : CommutingFlows (suspensionMeasure ν) (suspFlowFirst T Tinv)
      (suspFlowSecond S Sinv) :=
    { measU := hUm, measV := hVm, mpU := hUmp, mpV := hVmp, addU := hUadd, addV := hVadd,
      comm := hcomm }
  have hmeasI1 : MeasurableSet {ω : Y × ℝ × ℝ | ω.2.1 ∈ Set.Ioo (1 / 4 : ℝ) (1 / 2)} :=
    measurableSet_Ioo.preimage (measurable_fst.comp measurable_snd)
  have hmeasI2 : MeasurableSet {ω : Y × ℝ × ℝ | ω.2.2 ∈ Set.Ioo (1 / 4 : ℝ) (1 / 2)} :=
    measurableSet_Ioo.preimage (measurable_snd.comp measurable_snd)
  have hft : Measurable (liftFirstT02 f) :=
    Measurable.ite hmeasI1 (hf.comp measurable_fst) measurable_const
  have hgt : Measurable (liftSecondT02 g) :=
    Measurable.ite hmeasI2 (hg.comp measurable_fst) measurable_const
  have hftB : ∀ ω, ‖liftFirstT02 f ω‖ ≤ max Bf 0 := fun ω => by
    unfold liftFirstT02
    split_ifs
    · exact le_max_of_le_left (hBf _)
    · simp
  have hgtB : ∀ ω, ‖liftSecondT02 g ω‖ ≤ max Bg 0 := fun ω => by
    unfold liftSecondT02
    split_ifs
    · exact le_max_of_le_left (hBg _)
    · simp
  have hae := hS02 (Y × ℝ × ℝ) (suspensionMeasure ν) _ _ hUV (liftFirstT02 f)
    (liftSecondT02 g) hft hgt ⟨_, hftB⟩ ⟨_, hgtB⟩
  set P : Y → Prop := fun x => ∃ L, Tendsto (fun N => bilinAvg T S f g N x) atTop (𝓝 L)
  set box : Set (ℝ × ℝ) := Set.Ioo (0 : ℝ) (1 / 8) ×ˢ Set.Ioo (0 : ℝ) (1 / 8)
  have hsub : {x | ¬ P x} ×ˢ box ⊆ {ω | ¬ ∃ L : ℂ, Tendsto (fun R : ℝ => (R⁻¹ : ℂ) *
      ∫ t in (0 : ℝ)..R, liftFirstT02 f (suspFlowFirst T Tinv t ω) *
        liftSecondT02 g (suspFlowSecond S Sinv t ω)) atTop (𝓝 L)} := by
    rintro ⟨x, u, v⟩ ⟨hx, hu, hv⟩ hconv
    exact hx (bilinAvg_converges_of_susp_T02 T Tinv S Sinv f g x hu.1.le hu.2 hv.1.le hv.2 hconv)
  have h0 : suspensionMeasure ν ({x | ¬ P x} ×ˢ box) = 0 :=
    measure_mono_null hsub (ae_iff.1 hae)
  have hI : unitIcoMeasure (Set.Ioo (0 : ℝ) (1 / 8)) ≠ 0 := by
    rw [Measure.restrict_apply measurableSet_Ioo,
      Set.inter_eq_left.2 (Set.Ioo_subset_Ico_self.trans (Set.Ico_subset_Ico_right (by norm_num)))]
    simp
  rw [suspensionMeasure, Measure.prod_prod, Measure.prod_prod] at h0
  rw [ae_iff]
  rcases mul_eq_zero.1 h0 with h | h
  · exact h
  · exact absurd h (mul_ne_zero hI hI)


/-- **Theorem 9.4 (node T05), bounded inputs on arbitrary probability spaces**, unconditionally:
for commuting measurable measure-preserving `T, S` and bounded measurable `f, g`, the averages
`A_N(f,g)` converge almost everywhere and in every `L^r`, `1 ≤ r < ∞`. -/
theorem bounded_commuting_averages_ae {X : Type u} [MeasurableSpace X] (μ : Measure X)
    [IsProbabilityMeasure μ] (T S : X → X) (hT : MeasurePreserving T μ μ)
    (hS : MeasurePreserving S μ μ) (hTS : T ∘ S = S ∘ T) (f g : X → ℂ) (hf : Measurable f)
    (hg : Measurable g) (hfb : ∃ C, ∀ x, ‖f x‖ ≤ C) (hgb : ∃ C, ∀ x, ‖g x‖ ≤ C) :
    (∀ᵐ x ∂μ, ∃ L, Tendsto (fun N => bilinAvg T S f g N x) atTop (𝓝 L)) ∧
    ∃ F : X → ℂ, (∀ᵐ x ∂μ, Tendsto (fun N => bilinAvg T S f g N x) atTop (𝓝 (F x))) ∧
      ∀ r : ℝ, 1 ≤ r → MemLp F (ENNReal.ofReal r) μ ∧
        Tendsto (fun N => eLpNorm (bilinAvg T S f g N - F) (ENNReal.ofReal r) μ) atTop (𝓝 0) :=
  bounded_commuting_averages_ae_of_invertible (invertible_commuting_averages_ae S02_holds) μ T S
    hT hS hTS f g hf hg hfb hgb

end

end Auto
